Repository akka/akka, pull requests merged in 2018-08, with the labels that each got.

#25415 Upgrade to SBT 1.2.0
  project/build.properties
Labels: tested

#25417 Add jaxb to camel test classpath
  akka-docs/src/main/paradox/camel.md
  project/Dependencies.scala
Labels: tested

#25430 Docs depend on camel test deps to pick up removed camel deps
  build.sbt
Labels: tested

#25357 Separate out Effects and ChainedEffects in typed persistence
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/SideEffect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EffectImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedRunning.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/Effect.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/ManyRecoveriesSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/OptionalSnapshotStoreSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/AccountExample1.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/AccountExample2.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorsCompileOnly.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/InDepthPersistentBehaviorSpec.scala
Labels: tested

#25438 Log exception for association failure
  akka-remote/src/main/scala/akka/remote/transport/netty/NettyTransport.scala
Labels: tested

#25419 Add ClusterSingleton supervision documentation
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/test/java/jdocs/cluster/singleton/ClusterSingletonSupervision.java
  akka-docs/src/test/java/jdocs/cluster/singleton/SupervisorActor.java
  akka-docs/src/test/scala/docs/cluster/singleton/ClusterSingletonSupervision.scala
Labels: validating

#25450 Log more details for TCP connection errors
  akka-actor/src/main/scala/akka/io/Tcp.scala
Labels: tested

#25445 Support discovering jdk-11
  project/CrossJava.scala
Labels: tested

#25457 Discover JDK in $JAVA_HOME
  project/CrossJava.scala
Labels: tested

#25462 Minor documentation fixes
  akka-docs/src/main/paradox/stream/stream-customize.md
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
Labels: tested

#25422 =doc Fix Config links in testing (#25421)
  akka-docs/src/main/paradox/general/configuration.md
  akka-docs/src/main/paradox/testing.md
Labels: tested

#25465 Add direction & throttler mode accessors to improve Java interop
  akka-remote/src/main/scala/akka/remote/transport/ThrottlerTransportAdapter.scala
  akka-remote/src/test/java/akka/remote/transport/ThrottlerTransportAdapterTest.java
Labels: tested

#25471 Fix README scladex badge
  README.md
Labels: tested

#25474 explicit return type in ThrottlerTransportAdapter Java API
  akka-remote/src/main/scala/akka/remote/transport/ThrottlerTransportAdapter.scala
Labels: tested

#25488 Enforce valid seqnr for deletes, #25487
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/main/scala/akka/persistence/JournalProtocol.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorDeleteFailureSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
Labels: 2 - pick next, tested

#25464 Docs: IDE tip wrt to javadsl / scaladsl #25312
  akka-docs/src/main/paradox/additional/ide.md
  akka-docs/src/main/paradox/additional/index.md
  akka-docs/src/main/paradox/images/idetip-auto-importer-solution.png
  akka-docs/src/main/paradox/stream/stream-quickstart.md
Labels: tested

#25404 Harden BindCanonicalAddressSpec
  akka-remote/src/main/scala/akka/remote/BoundAddressesExtension.scala
  akka-remote/src/test/scala/akka/remote/artery/BindCanonicalAddressSpec.scala
Labels: tested

#25494 Various documentation fixes of "Basics and working with Flows"
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
Labels: tested

#25439 Correct parameter order in FSM transition-syntax snippet
  akka-docs/src/test/java/jdocs/actor/fsm/FSMDocTest.java
Labels: tested

#25456 =stream Avoid boxing Attributes in java Optional
  akka-stream/src/main/scala/akka/stream/impl/ActorRefBackpressureSinkStage.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSources.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala
Labels: tested

#25492 Additional records support for async dns
  akka-actor-tests/src/test/scala/akka/io/dns/AsyncDnsResolverIntegrationSpec.scala
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsResolverSpec.scala
  akka-actor/src/main/scala/akka/io/dns/DnsProtocol.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsCache.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsManager.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala
  akka-actor/src/main/scala/akka/io/dns/internal/DnsClient.scala
Labels: 2 - pick next, tested

#25405 Break up cluster sharding docs into sections
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested

#25396 Split up persistence documentation
  akka-docs/src/main/paradox/index-actors.md
  akka-docs/src/main/paradox/persistence-fsm.md
  akka-docs/src/main/paradox/persistence-journals.md
  akka-docs/src/main/paradox/persistence.md
Labels: tested

#25390 Document inclusivity of delete events
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala
Labels: tested

#25389 Remove use of deprecated methods in java docs
  akka-docs/src/test/java/jdocs/actor/InitializationDocTest.java
  akka-docs/src/test/java/jdocs/actor/SampleActorTest.java
  akka-docs/src/test/java/jdocs/actor/fsm/BuncherTest.java
  akka-docs/src/test/java/jdocs/circuitbreaker/TellPatternJavaActor.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeHold.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeManualTrigger.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeMissedTicks.java
  akka-docs/src/test/java/jdocs/tutorial_4/DeviceGroupTest.java
  akka-docs/src/test/java/jdocs/tutorial_4/DeviceTest.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceGroupTest.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceTest.java
Labels: tested

#25353 Harden StreamTestKitSpec
  akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala
Labels: tested

#25416 Remove various compiler warnings
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StopSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/SupervisorStrategy.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-remote/src/main/scala/akka/remote/artery/ImmutableLongMap.scala
  akka-remote/src/main/scala/akka/remote/transport/netty/SSLEngineProvider.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Graph.scala
Labels: tested

#25511 add java.time.Duration support for javadsl #24646
  akka-actor-tests/src/test/java/akka/event/LoggingAdapterTest.java
  akka-actor-tests/src/test/java/akka/pattern/PatternsTest.java
  akka-actor/src/main/scala/akka/pattern/Patterns.scala
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeGlobalRateLimit.java
  akka-testkit/src/main/scala/akka/testkit/javadsl/TestKit.scala
Labels: 2 - pick next, tested

#25431 +doc Improved scalafiddle integration
  akka-docs/src/main/paradox/_template/projectSpecificFooter.st
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/assets/js/scalafiddle.js
  akka-docs/src/main/paradox/stream/stream-quickstart.md
  akka-docs/src/test/scala/docs/actor/ActorDocSpec.scala
  akka-docs/src/test/scala/docs/stream/TwitterStreamQuickstartDocSpec.scala
  project/plugins.sbt
Labels: tested

#25501 Support joining 2.5.9 or earlier, compat InitJoinAck, #25491
  akka-cluster/src/main/scala/akka/cluster/Cluster.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/JoinConfigCompatChecker.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
Labels: 2 - pick next, tested

#25035 Handle a negative value returned by Math.abs()
  akka-actor/src/main/scala/akka/dispatch/affinity/AffinityPool.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-docs/src/test/java/jdocs/stream/HubDocTest.java
  akka-docs/src/test/scala/docs/stream/HubsDocSpec.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Hub.scala
Labels: tested

#25521 increase outbound-control-queue-size
  akka-remote/src/main/resources/reference.conf
Labels: tested

#25517 Add grpc samples to RELEASING.md
  RELEASING.md
Labels: tested

#25551 add missing mima filters, current version was not updated
  akka-actor/src/main/mima-filters/2.5.14.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.14.backwards.excludes
  project/MiMa.scala
Labels: tested
