Repository akka/akka, pull requests merged in 2018-02, with the labels that each got.

#24438 Cancel GroupBy when all substreams cancel
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
Labels: tested

#24524 paradox javadoc and scaladoc directives for cluster-client.md
  akka-docs/src/main/paradox/cluster-client.md
Labels: tested

#24449 Make MetricsBasedResizerSpec a bit slower but less GC sensitive
  akka-actor-tests/src/test/scala/akka/routing/MetricsBasedResizerSpec.scala
  akka-actor/src/main/scala/akka/routing/OptimalSizeExploringResizer.scala
Labels: tested

#24528 RecipeAdhocSource: Less fragile way of waiting for stream completion
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeAdhocSourceTest.java
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeAdhocSource.scala
Labels: tested

#24530 StreamTcpDocSpec: Less race, better error if client fails
  akka-docs/src/test/java/jdocs/stream/io/StreamTcpDocTest.java
  akka-docs/src/test/scala/docs/stream/io/StreamTcpDocSpec.scala
Labels: reviewed, tested

#24522 Add log() in stream-error.md
  akka-docs/src/main/paradox/stream/stream-cookbook.md
  akka-docs/src/main/paradox/stream/stream-error.md
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeLoggingElements.java
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeLoggingElements.scala
Labels: tested

#24534 =pro fix osgi plugin muting AutomaticModuleName
  project/plugins.sbt
  project/scripts/validate-automatic-module-names
Labels: tested

#24537 Too many Tocks in typed TimerSpec
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/TestKit.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/TestProbe.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/TestProbe.scala
  akka-testkit-typed/src/test/scala/akka/testkit/typed/scaladsl/TestProbeSpec.scala
Labels: tested

#24539 Add example of testing actors with subclassing
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/test/java/jdocs/testkit/TestKitDocTest.java
  akka-docs/src/test/scala/docs/testkit/TestkitDocSpec.scala
Labels: tested

#23824 Add wireTap combinator (#15077)
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-stream-tests/src/test/scala/akka/stream/DslConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphUnzipSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphWireTapSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: tested

#24538 Generate file to use instead of assuming class loader type
  akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala
  akka-actor/src/main/mima-filters/2.5.10.backwards.excludes
  akka-actor/src/main/scala/akka/io/Tcp.scala
  akka-actor/src/main/scala/akka/io/TcpConnection.scala
  project/Dependencies.scala
Labels: tested

#24019 Chunker should only pull if buffer is empty
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeByteStrings.java
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeByteStrings.scala
Labels: tested

#24547 Document that a scheduler is needed for standalone typed ask
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
Labels: tested

#24549 Typed: Renaming deferred
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorContextAskTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/FaultToleranceDocTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StashDocTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/coexistence/TypedWatchingUntypedTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/DeferredSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/StepWise.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/GracefulStopSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/OnSignalSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashBufferSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/FaultToleranceDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/MutableIntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StashDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/coexistence/TypedWatchingUntypedSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/internal/ReplicatorBehavior.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterImpl.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExampleTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/RemoteContextAskSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/RemoteDeployNotAllowedSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExampleSpec.scala
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorSpec.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/BehaviorTestkit.scala
Labels: tested

#24343 [#24294] Fix DistributedPubSubMediator not unsubscribing actors from …
  akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/pubsub/DistributedPubSubMediatorSpec.scala
Labels: validating

#24531 Add warning about AsyncRecovery assumptions c* plugin makes
  akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala
Labels: tested

#24487 +tkt Provide run method that doesn't canonicalize behavior #24486
  akka-testkit-typed/src/main/scala/akka/testkit/typed/BehaviorTestkit.scala
  akka-testkit-typed/src/test/scala/akka/testkit/typed/BehaviorTestkitSpec.scala
Labels: tested

#24423 alsoTo eager cancellation #24291
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-docs/src/main/paradox/stream/stream-error.md
  akka-stream-tests/src/test/scala/akka/stream/ActorMaterializerSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefBackpressureSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBroadcastSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/QueueSinkSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#24545 #24411 Give a bit more time to the consumers
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala
Labels: tested

#24562 Deprecated method used in docs
  akka-docs/src/test/java/jdocs/circuitbreaker/DangerousJavaActor.java
Labels: tested

#24521 =doc cleaning up documentation on deprecated actorSubscriber and actorPublisher
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-docs/src/main/paradox/stream/stream-integrations.md
Labels: tested

#24564 A bit more generous timeouts in RateTransformationDocSpec
  akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala
Labels: tested

#24565 Make stashing timer messages work
  akka-actor-tests/src/test/scala/akka/actor/TimerSpec.scala
  akka-actor/src/main/scala/akka/actor/Timers.scala
Labels: tested

#24569 fix java documentation snippet by being explicit
  akka-docs/src/test/java/jdocs/actor/FaultHandlingTest.java
Labels: tested

#24573 Cut the detail level in half
  akka-docs/src/main/paradox/actors.md
Labels: needs-attention

#24555 fail fast if Typed Cluster.sharding.spawn is called several times wit…
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
Labels: tested

#24120 Rolling update config checker
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/JoinConfigCompatCheckSharding.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/JoinConfigCompatCheckShardingSpec.scala
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/mima-filters/2.5.9.backwards.excludes
  akka-cluster/src/main/protobuf/ClusterMessages.proto
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/Cluster.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterSettings.scala
  akka-cluster/src/main/scala/akka/cluster/JoinConfigCompatCheckCluster.scala
  akka-cluster/src/main/scala/akka/cluster/JoinConfigCompatChecker.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterTestKit.scala
  akka-cluster/src/test/scala/akka/cluster/JoinConfigCompatCheckerSpec.scala
  akka-cluster/src/test/scala/akka/cluster/JoinConfigCompatPreDefinedChecksSpec.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
  akka-docs/src/main/paradox/cluster-usage.md
Labels: tested

#23828 Artery with TCP/TLS, #24390
  akka-bench-jmh/src/main/scala/akka/remote/artery/CodecBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/remote/artery/SendQueueBenchmark.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/SharedMediaDriverSupport.scala
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemotingMultiNodeSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamConcistencySpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamLatencySpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamMaxThroughputSpec.scala
  akka-remote-tests/src/test/scala/akka/remote/artery/ArteryFailedToBindSpec.scala
  akka-remote/src/main/java/akka/remote/artery/aeron/AeronErrorLog.java
  akka-remote/src/main/mima-filters/2.5.9.backwards.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-remote/src/main/scala/akka/remote/artery/EnvelopeBufferPool.scala
  akka-remote/src/main/scala/akka/remote/artery/FlightRecorder.scala
  akka-remote/src/main/scala/akka/remote/artery/FlightRecorderEvents.scala
  akka-remote/src/main/scala/akka/remote/artery/Handshake.scala
  akka-remote/src/main/scala/akka/remote/artery/SendQueue.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/AeronSink.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/AeronSource.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/TaskRunner.scala
  akka-remote/src/main/scala/akka/remote/artery/compress/InboundCompressions.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/TcpFraming.scala
  akka-remote/src/test/java/akka/remote/artery/aeron/AeronStat.java
  akka-remote/src/test/scala/akka/remote/Ticket1978CommunicationSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/ArterySpecSupport.scala
  akka-remote/src/test/scala/akka/remote/artery/EnvelopeBufferSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/HandshakeDenySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/LargeMessagesStreamSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteFailureSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteSendConsistencySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/SendQueueSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/aeron/AeronSinkSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TcpFramingSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala
  akka-testkit/src/main/scala/akka/testkit/TestKit.scala
Labels: tested

#24567 +add collectType by @hepin1989
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/scala/akka/stream/DslConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowCollectTypeSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSpec.scala
  akka-stream/src/main/mima-filters/2.5.9.backwards.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#24497 Adding preMaterialize operator for Source #23895
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
  akka-docs/src/test/java/jdocs/stream/FlowDocTest.java
  akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#24550 Separate Java and Scala typed TestProbes
  akka-actor-typed-tests/src/test/java/akka/actor/typed/ManualTimerTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorContextAskTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/testing/async/BasicAsyncTestingTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-cluster-typed/src/test/java/akka/cluster/typed/ClusterApiTest.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/BasicClusterExampleTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorTest.java
  akka-testkit-typed/src/main/scala/akka/testkit/typed/FishingOutcome.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/StubbedActorContext.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/TestKit.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/TestProbeImpl.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/ExplicitlyTriggeredScheduler.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/TestProbe.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ExplicitlyTriggeredScheduler.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/ManualTime.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/TestProbe.scala
  akka-testkit-typed/src/test/scala/akka/testkit/typed/javadsl/TestProbeTest.java
  akka-testkit-typed/src/test/scala/akka/testkit/typed/scaladsl/TestProbeSpec.scala
Labels: tested

#24023 Stop unused Artery outbound streams, #23967
  akka-bench-jmh/src/main/scala/akka/remote/artery/SendQueueBenchmark.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/LargeMessageClusterSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamLatencySpec.scala
  akka-remote/src/main/mima-filters/2.5.9.backwards.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-remote/src/main/scala/akka/remote/artery/Control.scala
  akka-remote/src/main/scala/akka/remote/artery/FlightRecorderEvents.scala
  akka-remote/src/main/scala/akka/remote/artery/Handshake.scala
  akka-remote/src/main/scala/akka/remote/artery/SendQueue.scala
  akka-remote/src/main/scala/akka/remote/artery/SystemMessageDelivery.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/compress/InboundCompressions.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/test/scala/akka/remote/artery/EnvelopeBufferSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/InboundControlJunctionSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/OutboundIdleShutdownSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/SendQueueSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/SystemMessageDeliverySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/TestContext.scala
Labels: tested

#24577 #23951 Fail materialized future of IO stages when stream fails
  akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSinkSpec.scala
  akka-stream/src/main/scala/akka/stream/IOResult.scala
  akka-stream/src/main/scala/akka/stream/impl/io/FileSubscriber.scala
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSubscriber.scala
Labels: tested

#24340 Exception from receiveRecover should stop the PersistentActor #24192
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
Labels: 2 - pick next, tested

#24586 fix TlsTcpWithHostnameVerificationSpec when run without tls
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
Labels: tested

#24568 Issue 24519: Created method lazilyAsync for both DSLs and adds section in docs
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazilyAsyncSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#24527 +str Add Flow.lazyInit (#24427)
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: 2 - pick next, tested

#24591 Fix error message when LinearTraversalBuilder module has more than one outlet
  akka-stream/src/main/scala/akka/stream/impl/TraversalBuilder.scala
Labels: 2 - pick next, tested

#24593 ambiguous method byteBuffer.limit with jdk9
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TcpFramingSpec.scala
Labels: 2 - pick next, tested

#24590 use Flow.lazyInit in Artery TCP
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
Labels: 2 - pick next, tested

#24484 =act Experiment with LineNumbers for Lambda's #24480
  akka-actor-tests/src/test/scala/akka/util/LineNumberSpec.scala
  akka-actor-tests/src/test/scala/akka/util/LineNumberSpecCodeForScala.scala
  akka-actor/src/main/scala/akka/util/LineNumbers.scala
Labels: 2 - pick next, tested

#24589 prune entries in ClusterReceptionist from nodes that have been removed, #23683
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistImpl.scala
  akka-cluster-typed/src/main/resources/reference.conf
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
Labels: 2 - pick next, tested

#24601 Fix dead link in cluster.md
  akka-docs/src/main/paradox/common/cluster.md
Labels: tested

#24603 Receptionist message improvements, #24511 and #24492
  akka-actor-typed-tests/src/test/java/akka/actor/typed/receptionist/ReceptionistApiTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/receptionist/LocalReceptionistSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/receptionist/ReceptionistApiSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExampleTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/typed/RemoteContextAskSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExampleSpec.scala
Labels: 2 - pick next, tested

#24440 Actually use the relative blocking io dispatcher setting
  akka-actor/src/main/mima-filters/2.5.10.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.9.backwards.excludes
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/AttributesSpec.scala
  akka-stream/src/main/mima-filters/2.5.9.backwards.excludes
  akka-stream/src/main/resources/reference.conf
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/Materializer.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSinks.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSources.scala
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala
  akka-testkit/src/main/mima-filters/2.5.9.backwards.excludes
Labels: 2 - pick next, tested

#24606 fix blocking-io-dispatcher setting, #24357
  akka-stream/src/main/resources/reference.conf
  project/scripts/release
Labels: tested

#24608 Avoid infinite recursion in AbstractPersistentFSM, #24448
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSMBase.scala
  akka-persistence/src/test/java/akka/persistence/fsm/AbstractPersistentFSMTest.java
Labels: tested

#24611 small adjustment of the aeron vs tcp documentation
  akka-docs/src/main/paradox/remoting-artery.md
  akka-remote/src/main/resources/reference.conf
Labels: tested

#24625 2.5.10 wire protocol regression
  akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/mima-filters/2.5.10.backwards.excludes
  akka-cluster/src/main/protobuf/ClusterMessages.proto
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
  project/MiMa.scala
Labels: tested
