Repository akka/akka, pull requests merged in 2018-03, with the labels that each got.

#24634 =doc fix the wrong position of a sentence
  akka-docs/src/main/paradox/persistence.md
Labels: tested

#24632 Fixes broken test for Scala 2.12 #24617
  akka-actor-tests/src/test/scala/akka/util/LineNumberSpec.scala
Labels: tested

#24638 MiMa latest release updated
  project/MiMa.scala
Labels: tested

#24618 Adds test and caps the timeout check period to 1s
  akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/Timers.scala
Labels: tested

#24563 Add unidoc directive for markdowns
  akka-docs/src/main/paradox/cluster-client.md
  build.sbt
  project/ParadoxSupport.scala
  project/plugins.sbt
Labels: tested

#24628 +ben add DirectBufferPoolBenchmark, just for reference
  akka-bench-jmh/src/main/scala/akka/actor/DirectByteBufferPoolBenchmark.scala
Labels: tested

#24655 Add log() method to typed Logging API #24648
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Logger.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala
Labels: tested

#24592 slowdown LargeMessageClusterSpec for tcp transport, #24576
  akka-cluster/src/multi-jvm/scala/akka/cluster/LargeMessageClusterSpec.scala
Labels: tested

#24645 Add java duration support for Source.tick (Java DSL) #24339
  akka-actor/src/main/mima-filters/2.5.11.backwards.excludes
  akka-actor/src/main/scala/akka/util/JavaDurationConverters.scala
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
Labels: tested

#24552 #24544 Add dispatcher name to names of threads created by AffinityPool
  akka-actor/src/main/scala/akka/dispatch/affinity/AffinityPool.scala
Labels: tested

#24653 fix Trigger references in the stream cookbook example for digest #24317
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeDigest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeTest.java
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeAdhocSource.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeDecompress.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeDigest.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeDroppyBroadcast.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeFlattenSeq.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeHold.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeKeepAlive.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeManualTrigger.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeParseLines.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeReduceByKey.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeSeq.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeSpec.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeWorkerPool.scala
Labels: tested

#24600 Add serializer for `akka.NotUsed` (#24599)
  akka-docs/src/main/paradox/serialization.md
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/serialization/MiscMessageSerializer.scala
  akka-remote/src/test/scala/akka/remote/serialization/MiscMessageSerializerSpec.scala
Labels: tested

#24659 = all bye-bye semicolon
  akka-actor-tests/src/test/scala/akka/AkkaExceptionSpec.scala
  akka-actor/src/main/scala/akka/actor/AbstractFSM.scala
  akka-actor/src/main/scala/akka/routing/MurmurHash.scala
  akka-bench-jmh/src/main/scala/akka/remote/artery/compress/CountMinSketchBenchmark.scala
  akka-camel/src/test/scala/akka/camel/DefaultCamelTest.scala
  akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala
  akka-osgi/src/test/scala/akka/osgi/test/TestActivators.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSMBase.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/BenchmarkFileReporter.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamMaxThroughputSpec.scala
  akka-remote/src/test/scala/akka/remote/RemotingSpec.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/TestSource.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala
Labels: tested

#24612 Fix a few leftover Behaviors.deferred mentions
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorSpec.scala
Labels: tested

#24582 TCK: Empty Flow[Int]: onSubscribe should be called prior to onComplete always
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/EmptyProcessorTest.scala
Labels: tested

#24669 ClusterSharding: automatically choose start or startProxy by a node role (#23934)
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/mima-filters/2.5.11.backwards.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested

#24619 deduplicate logic for IODispatcher #24604
  akka-docs/src/main/paradox/stream/stream-io.md
  akka-docs/src/test/scala/docs/stream/io/StreamFileDocSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/FlightRecorderSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/AttributesSpec.scala
  akka-stream/src/main/mima-filters/2.5.11.backwards.excludes
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSinks.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSources.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FileIO.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/StreamConverters.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FileIO.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
Labels: tested

#24657 parity for Sink, for preMaterialize operation
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/SinkTest.java
  akka-stream-tests/src/test/scala/akka/stream/DslConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
Labels: tested

#24667 lazy init of SerializationExtension in Artery, #24620
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterSingletonApiSpec.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
Labels: tested

#24689 Unidoc directives for cluster md files
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-dc.md
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-singleton.md
  project/ParadoxSupport.scala
Labels: tested

#24661 = util add Throwables helper to help fatal checking of Throwable for …
  akka-actor-tests/src/test/java/akka/japi/ThrowablesTest.java
  akka-actor/src/main/scala/akka/japi/Throwables.scala
Labels: tested

#24515 Add serialization with transport information method in public API #24321
  akka-actor/src/main/scala/akka/serialization/Serialization.scala
  akka-docs/src/main/paradox/serialization.md
Labels: tested

#24651 Add duration to Scheduler ,AbstractFSM ,ActorSelection and AbstractScheduler
  akka-actor/src/main/java/akka/actor/AbstractScheduler.java
  akka-actor/src/main/mima-filters/2.5.11.backwards.excludes
  akka-actor/src/main/scala/akka/actor/AbstractFSM.scala
  akka-actor/src/main/scala/akka/actor/ActorSelection.scala
  akka-actor/src/main/scala/akka/actor/Scheduler.scala
  akka-actor/src/main/scala/akka/util/JavaDurationConverters.scala
Labels: tested

#24405 Update PersistenceQueryDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/query/PersistenceQueryDocSpec.scala
Labels: tested

#24642 Do not drop messages when delaying with EmitEarly strategy and the buffer overflows
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDelaySpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: tested

#24705 Subscription timeouts should not hit after stream ref subscribe
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SinkRefImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala
Labels: tested

#24693 =doc #24688 link to akka cluster bootstrap in docs
  akka-docs/src/main/paradox/cluster-usage.md
Labels: tested

#24704 Remove default parameters in doc journal
  akka-docs/src/test/scala/docs/persistence/query/PersistenceQueryDocSpec.scala
Labels: tested

#24707 Execute tasks from Actors constructor on creation of BehaviorTestKit
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/BehaviorTestKitImpl.scala
Labels: tested

#24644 Issue 24490: Refactoring of ActorContextSpec
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/StepWise.scala
Labels: 2 - pick next, tested

#24702 Make use of the fact that identity is eliminated
  akka-remote/src/main/mima-filters/2.5.11.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/TestStage.scala
Labels: tested

#24624 Split up receptionist implementations
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/receptionist/LocalReceptionistSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/receptionist/ServiceKeySerializationSpec.scala
  akka-actor-typed/src/main/resources/reference.conf
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistMessages.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ServiceKey.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ServiceKeySerializer.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSettings.scala
  akka-docs/src/main/paradox/cluster-client.md
Labels: tested

#24721 Subscribing twice should cancel second subscriber
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/FlatMapConcatDoubleSubscriberTest.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/ActorGraphInterpreterSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
Labels: tested

#24575 Java flow dsl lower bounds
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeAdhocSourceTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream/src/main/scala/akka/stream/javadsl/BidiFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/BidiFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#24730 Expect effect type/class for BehaviorTestKit
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/BehaviorTestKit.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/BehaviorTestKit.scala
  akka-testkit-typed/src/test/scala/akka/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: reviewed, tested

#24737 Adding explanation for Java DSL TestKit#awaitAssert return value
  akka-docs/src/main/paradox/testing.md
  akka-testkit/src/main/scala/akka/testkit/javadsl/TestKit.scala
Labels: tested

#24743 Remove the duplicated class Coroner.scala
  akka-stream-testkit/src/test/scala/akka/stream/testkit/Coroner.scala
Labels: tested

#24747 Capture the Success companion object as well as its class
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefSourceSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#24712 + str Add java.time.Duration to TimerGraphStageLogic
  akka-docs/src/test/java/jdocs/stream/GraphStageDocTest.java
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#24706 + str Add java.time.Duration to akka-stream's javadsl.*
  akka-stream/src/main/scala/akka/stream/javadsl/BidiFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Restart.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/StreamConverters.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
Labels: tested

#24749 Small TCK fix in cancelled sink
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/CancelledSinkSubscriberTest.scala
  akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala
Labels: tested

#24748 Typed persistence tests: RecoveryPermitterSpec
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
Labels: tested

#24746 =doc Note Source.queue backpressure behavior on stream integration page
  akka-docs/src/main/paradox/stream/stream-integrations.md
Labels: tested

#24745 less aggressive resend of Artery sys msg after nack, #24744
  akka-remote/src/main/scala/akka/remote/artery/InboundEnvelope.scala
  akka-remote/src/main/scala/akka/remote/artery/OutboundEnvelope.scala
  akka-remote/src/main/scala/akka/remote/artery/SystemMessageDelivery.scala
  akka-remote/src/test/scala/akka/remote/artery/SystemMessageDeliverySpec.scala
Labels: tested

#24739 minor improvement of ClusterReceptionist loading
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentBehaviorSpec.scala
Labels: tested

#24722 Bugfix in VirtualProcessor
  akka-stream/src/main/mima-filters/2.5.11.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala
Labels: tested

#24685 materialized value of Flow.lazyInit must be a Future #24670
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySinkSpec.scala
  akka-stream/src/main/mima-filters/2.5.11.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
Labels: reviewed, tested

#24754 improve docs and test style of lazyInitAsync
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySinkSpec.scala
Labels: validating

#24762 ! deps upgrade to scala 2.12.5
  project/Dependencies.scala
Labels: tested

#24759 + testkit Add java.time.Duration to testkit's javadsl
  akka-actor/src/main/scala/akka/util/Timeout.scala
  akka-docs/src/test/java/jdocs/actor/ActorDocTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeGlobalRateLimit.java
  akka-docs/src/test/java/jdocs/testkit/TestKitDocTest.java
  akka-docs/src/test/java/jdocs/testkit/TestKitSampleTest.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceGroupQueryTest.java
  akka-docs/src/test/java/jdocs/tutorial_6/DeviceGroupQueryTest.java
  akka-testkit/src/main/scala/akka/testkit/javadsl/EventFilter.scala
  akka-testkit/src/main/scala/akka/testkit/javadsl/TestKit.scala
Labels: tested

#24755 =doc using java.time.Duration for stream's javadsl
  akka-docs/src/test/java/jdocs/stream/FlowDocTest.java
  akka-docs/src/test/java/jdocs/stream/GraphStageDocTest.java
  akka-docs/src/test/java/jdocs/stream/HubDocTest.java
  akka-docs/src/test/java/jdocs/stream/KillSwitchDocTest.java
  akka-docs/src/test/java/jdocs/stream/QuickStartDocTest.java
  akka-docs/src/test/java/jdocs/stream/RestartDocTest.java
  akka-docs/src/test/java/jdocs/stream/StreamBuffersRateDocTest.java
  akka-docs/src/test/java/jdocs/stream/StreamTestKitDocTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeAdhocSourceTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeKeepAlive.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowThrottleTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
Labels: tested

#24508 Adding defer method to PersistentActor
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/test/java/jdocs/persistence/LambdaPersistenceDocTest.java
  akka-docs/src/test/scala/docs/persistence/PersistenceDocSpec.scala
  akka-persistence/src/main/mima-filters/2.5.10.backwards.excludes
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
Labels: tested

#24505 =pro add log timestamps to all sbt output and enable sbt debug logging for multi-jvm for ssh debugging
  project/AddLogTimestamps.scala
  project/MultiNode.scala
Labels: tested

#24757 [docs] added notes where the code was unclear for beginners
  akka-docs/src/main/paradox/stream/stream-graphs.md
  akka-docs/src/test/scala/docs/testkit/TestkitDocSpec.scala
Labels: reviewed, tested

#24767 Many recoveries spec: Transferred
  akka-persistence-typed/src/test/scala/akka/persistence/typed/ManyRecoveriesSpec.scala
Labels: tested

#24777 Add delivery semantics notes to stream refs
  akka-docs/src/main/paradox/stream/stream-refs.md
Labels: tested

#24780 Use genjavadoc 0.11 which is needed for Scala 2.12.5
  akka-persistence/src/main/mima-filters/2.5.11.backwards.excludes
  project/Doc.scala
Labels: tested

#23841 fix #23618 : Support for persistence dynamic configuration at runtime
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/test/java/jdocs/persistence/PersistenceMultiDocTest.java
  akka-docs/src/test/java/jdocs/persistence/PersistenceQueryDocTest.java
  akka-docs/src/test/scala/docs/persistence/PersistenceMultiDocSpec.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/PersistenceQuery.scala
  akka-persistence-query/src/test/java/akka/persistence/query/PersistenceQueryTest.java
  akka-persistence-query/src/test/scala/akka/persistence/query/DummyReadJournal.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/PersistenceQuerySpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdSpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByTagSpec.scala
  akka-persistence/src/main/mima-filters/2.5.11.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.8.backwards.excludes
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/main/scala/akka/persistence/Persistence.scala
  akka-persistence/src/test/scala/akka/persistence/PersistenceSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
Labels: tested

#24102 GraphDSL create with Seq[Graph] added
  akka-docs/src/main/paradox/stream/stream-graphs.md
  akka-docs/src/test/java/jdocs/stream/GraphDSLDocTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/GraphDslTest.java
  akka-stream-tests/src/test/scala/akka/stream/DslFactoriesConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphOpsIntegrationSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: tested

#24790 Consolidate docs on disabling Java serialization
  akka-docs/src/main/paradox/project/migration-guide-2.4.x-2.5.x.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/serialization.md
Labels: tested

#24791 = build bump to sbt 1.1.2
  project/build.properties
Labels: tested

#24729 Typed logging MDC improvements
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorLoggingTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Logger.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/LoggingBehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedRequestingRecoveryPermit.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/StubbedActorContext.scala
Labels: tested

#24640 Allow nested typed timers
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
Labels: 2 - pick next, tested

#24786 Log sent/receive message log level check
  akka-remote/src/main/scala/akka/remote/Endpoint.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-remote/src/main/scala/akka/remote/artery/MessageDispatcher.scala
  akka-remote/src/test/scala/akka/remote/MessageLoggingSpec.scala
Labels: tested

#24785 log warning if heartbeat sender ticks are delayed
  akka-cluster/src/main/scala/akka/cluster/ClusterHeartbeat.scala
Labels: tested

#24682 better Typed HelloWorld, #24491
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/TimerScheduler.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/TimerScheduler.scala
  akka-docs/src/main/paradox/typed/actors.md
Labels: tested

#24799 Update ssl-config
  project/Dependencies.scala
Labels: tested

#24800 BehaviorTestKit - hasEffects and expectEffectPF
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/BehaviorTestKit.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/BehaviorTestKit.scala
  akka-testkit-typed/src/test/scala/akka/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: tested
