Repository akka/akka, pull requests merged in 2018-04, with the labels that each got.

#24804 use java.time.Duration in Typed javadsl, #24646
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed/src/main/scala/akka/actor/typed/SupervisorStrategy.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/TimerScheduler.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/internal/ReplicatorBehavior.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/Replicator.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/ClusterSingleton.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorTest.java
  akka-testkit-typed/src/main/scala/akka/testkit/typed/TestKitSettings.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/TestProbeImpl.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/ActorTestKit.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/Effects.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/ManualTime.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/TestProbe.scala
  akka-testkit-typed/src/test/java/akka/testkit/typed/javadsl/ManualTimerExampleTest.java
  akka-testkit-typed/src/test/java/akka/testkit/typed/javadsl/TestProbeTest.java
Labels: tested

#24802 use new Typed persistence impl in javadsl, #24753
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/PersistentBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentBehaviorSpec.scala
Labels: tested

#24784 automatic throttle burst size, #24699
  akka-docs/src/main/paradox/project/migration-guide-2.4.x-2.5.x.md
  akka-docs/src/main/paradox/stream/stream-quickstart.md
  akka-docs/src/test/java/jdocs/stream/HubDocTest.java
  akka-docs/src/test/java/jdocs/stream/QuickStartDocTest.java
  akka-docs/src/test/scala/docs/stream/HubsDocSpec.scala
  akka-docs/src/test/scala/docs/stream/QuickStartDocSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowThrottleSpec.scala
  akka-stream/src/main/mima-filters/2.5.11.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/Throttle.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#24828 override watchWith in EffectfulActorContext, fixes #24924
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/EffectfulActorContext.scala
  akka-testkit-typed/src/test/scala/akka/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: tested

#24843 Update to the latest mima 0.2.0
  akka-persistence/src/main/mima-filters/2.4.1.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.4.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.6.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.7.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.11.backwards.excludes
  project/plugins.sbt
Labels: tested

#24830 Akka event logging unnecessary ' started' while shutdown - fix #24803
  akka-actor/src/main/scala/akka/event/Logging.scala
Labels: tested

#24845 #24752 Fix timestamped versions
  project/AkkaBuild.scala
  project/TimeStampede.scala
Labels: validating

#24849 add weakly up to leader actions list
  akka-docs/src/main/paradox/common/cluster.md
Labels: 2 - pick next, tested

#24852 Remove explicit outlet selector from graph docs
  akka-docs/src/test/scala/docs/stream/GraphDSLDocSpec.scala
Labels: tested

#24815 ActorBenchmark ported to typed
  akka-bench-jmh/src/main/scala/akka/actor/typed/TypedActorBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/actor/typed/TypedBenchmarkActors.scala
Labels: tested

#24837 ArteryMessageLoggingSpec pick up command line overrides for akka settings
  akka-remote/src/test/scala/akka/remote/MessageLoggingSpec.scala
Labels: tested

#24842 Make sure to close resource in UnfoldResourceAsync
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceAsyncSourceSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala
Labels: tested

#24858 clarify the resolve debug logging
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
Labels: tested

#22339 add eagerCancel to Partition and Balance stage
  akka-docs/src/main/paradox/stream/stages-overview.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBalanceSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: tested

#24857 Clear system messages sequence number for restarted node, #24847
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-cluster/src/test/scala/akka/cluster/ResetSystemMessageSeqNrSpec.scala
  akka-remote/src/main/mima-filters/2.5.11.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/SystemMessageDelivery.scala
Labels: tested

#24827 remove dependencies of provided scope
  build.sbt
  project/Dependencies.scala
Labels: tested

#24836 Harden TcpSpec: wait for port to be bound
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
Labels: tested

#24829 DSL ActorContext extends typed ActorContext #24823
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
Labels: tested

#24820 Fixed an empty ByteStrings problem in InputStreamSinkStage
  akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSinkSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala
Labels: 2 - pick next, tested

#24844 Add some cross linking with Play and Lagom
  akka-docs/src/main/paradox/cluster-dc.md
  akka-docs/src/main/paradox/common/cluster.md
  akka-docs/src/main/paradox/common/other-modules.md
  akka-docs/src/main/paradox/guide/tutorial_5.md
  akka-docs/src/main/paradox/howto.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
Labels: 2 - pick next, tested

#24768 Optional snapshot store spec
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedRunning.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/OptionalSnapshotStoreSpec.scala
Labels: 2 - pick next, tested

#24883 Add java.time.Duration support in the JavaDSL in akka-actor module #24646
  akka-actor-tests/src/test/java/akka/actor/ActorSelectionTest.java
  akka-actor-tests/src/test/java/akka/actor/InboxJavaAPITest.java
  akka-actor-tests/src/test/java/akka/pattern/CircuitBreakerTest.java
  akka-actor/src/main/scala/akka/actor/AbstractFSM.scala
  akka-actor/src/main/scala/akka/actor/ActorDSL.scala
  akka-actor/src/main/scala/akka/actor/Scheduler.scala
  akka-actor/src/main/scala/akka/actor/Timers.scala
  akka-actor/src/main/scala/akka/io/Tcp.scala
  akka-actor/src/main/scala/akka/pattern/BackoffOptions.scala
  akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
  akka-actor/src/main/scala/akka/pattern/Patterns.scala
  akka-actor/src/main/scala/akka/routing/ScatterGatherFirstCompleted.scala
  akka-actor/src/main/scala/akka/routing/TailChopping.scala
  akka-docs/src/test/java/jdocs/actor/ActorDocTest.java
  akka-docs/src/test/java/jdocs/actor/FaultHandlingDocSample.java
  akka-docs/src/test/java/jdocs/actor/InboxDocTest.java
  akka-docs/src/test/java/jdocs/actor/SchedulerDocTest.java
  akka-docs/src/test/java/jdocs/actor/TimerDocTest.java
  akka-docs/src/test/java/jdocs/actor/fsm/Buncher.java
  akka-docs/src/test/java/jdocs/actor/fsm/FSMDocTest.java
  akka-docs/src/test/java/jdocs/circuitbreaker/DangerousJavaActor.java
  akka-docs/src/test/java/jdocs/circuitbreaker/EvenNoFailureJavaExample.java
  akka-docs/src/test/java/jdocs/circuitbreaker/TellPatternJavaActor.java
  akka-docs/src/test/java/jdocs/cluster/StatsSampleClient.java
  akka-docs/src/test/java/jdocs/ddata/DataBot.java
  akka-docs/src/test/java/jdocs/future/FutureDocTest.java
  akka-docs/src/test/java/jdocs/io/IODocTest.java
  akka-docs/src/test/java/jdocs/io/JavaReadBackPressure.java
  akka-docs/src/test/java/jdocs/pattern/BackoffSupervisorDocTest.java
  akka-docs/src/test/java/jdocs/persistence/LambdaPersistenceDocTest.java
  akka-docs/src/test/java/jdocs/persistence/query/MyEventsByTagJavaPublisher.java
  akka-docs/src/test/java/jdocs/routing/RouterDocTest.java
  akka-docs/src/test/java/jdocs/stream/StreamTestKitDocTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeGlobalRateLimit.java
Labels: 2 - pick next, tested

#24886 Link to forum instead of mailing list from readme
  README.md
Labels: tested

#24854 +doc Add examples to Sink.actorRefWithAck
  akka-docs/src/main/paradox/stream/stream-integrations.md
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
Labels: 2 - pick next, tested

#24851 Fix serialization in TypedActor
  akka-actor-tests/src/test/scala/akka/actor/TypedActorSpec.scala
  akka-actor/src/main/scala/akka/actor/TypedActor.scala
  akka-actor/src/main/scala/akka/actor/dungeon/Children.scala
  akka-actor/src/main/scala/akka/actor/dungeon/Dispatch.scala
  akka-actor/src/main/scala/akka/serialization/Serializer.scala
  akka-cluster-metrics/src/main/scala/akka/cluster/metrics/protobuf/MessageSerializer.scala
  akka-cluster-tools/src/main/scala/akka/cluster/pubsub/protobuf/DistributedPubSubMessageSerializer.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/SerializationSupport.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/MessageSerializer.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/SnapshotSerializer.scala
  akka-remote/src/main/scala/akka/remote/MessageSerializer.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-remote/src/main/scala/akka/remote/serialization/DaemonMsgCreateSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/MessageContainerSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/MiscMessageSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/WrappedPayloadSupport.scala
  akka-stream/src/main/scala/akka/stream/serialization/StreamRefSerializer.scala
Labels: 2 - pick next, tested

#24742 Cluster receptionist and new reincarnation of node
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ClusterMessages.java
  akka-cluster-typed/src/main/protobuf/ClusterMessages.proto
  akka-cluster-typed/src/main/resources/reference.conf
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AkkaClusterTypedSerializer.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/AkkaClusterTypedSerializerSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/TestKitUtils.scala
  build.sbt
Labels: 2 - pick next, tested

#24882 #24609 continued johanandren
  akka-actor-tests/src/test/java/akka/pattern/PatternsTest.java
  akka-actor/src/main/mima-filters/2.5.10.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.11.backwards.excludes
  akka-actor/src/main/scala/akka/pattern/Patterns.scala
Labels: 2 - pick next, tested

#24907 doc Remove duplicated ask section subject
  akka-docs/src/main/paradox/stream/stream-integrations.md
Labels: tested

#24920 Update actors.md
  akka-docs/src/main/paradox/typed/actors.md
Labels: tested

#24921 Adds support for the signature directive to the paradox configuration
  akka-docs/src/main/paradox/stream/reference/fromIterator.md
  build.sbt
  project/ParadoxSupport.scala
Labels: tested

#24925 Link to multi-dc persistence
  akka-docs/src/main/paradox/cluster-dc.md
Labels: tested

#24930 Bind map operation to value
  akka-actor/src/main/scala/akka/serialization/Serialization.scala
Labels: tested

#24923 Update circuit breaker docs to only show one language's examples
  akka-docs/src/main/paradox/common/circuitbreaker.md
Labels: tested

#24916 Minor updates to stream ref docs
  akka-docs/src/main/paradox/stream/stream-refs.md
Labels: tested

#24945 fix trailing space, fixes pr validation
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
Labels: tested

#24947 =doc fix duplicate "."
  akka-docs/src/main/paradox/actors.md
Labels: tested

#24937 Support Typed ActorSystem with Setup
  akka-actor-typed-tests/src/test/java/akka/actor/typed/ExtensionsTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ExtensionsSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
Labels: tested

#24950 fix contramap documentation typo
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
Labels: tested

#24961 Add classtag to tap/monitor for interception
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentBehaviorSpec.scala
Labels: tested

#24949 Fix snippets in typed cluster docs
  akka-cluster-sharding-typed/src/test/scala/doc/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/BasicClusterExampleTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterSingletonPersistenceSpec.scala
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#24967 Harden StreamTestKitSpec
  akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala
Labels: tested

#24966 Harden ClusterClientHandoverSpec
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/client/ClusterClientHandoverSpec.scala
  akka-testkit-typed/src/test/scala/akka/testkit/typed/scaladsl/ManualTimerExampleSpec.scala
Labels: tested

#24850 Add tests for BoundedBlockingQueue
  akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala
  akka-actor/src/main/scala/akka/util/BoundedBlockingQueue.scala
Labels: tested

#24968 use travis for mima and whitesource, remain no jenkins for tests (in parallel)
  .travis.yml
  CONTRIBUTING.md
  akka-testkit/src/main/mima-filters/2.4.16.backwards.excludes
  akka-testkit/src/main/mima-filters/2.5.3.backwards.excludes
  akka-testkit/src/main/mima-filters/2.5.4.backwards.excludes
  project/MiMa.scala
Labels: tested

#24913 make akka.paterns,PatternCS imports explicit in gracefulStop docs #24912
  akka-docs/src/main/paradox/actors.md
Labels: tested

#24978 =str javadoc rewording on new wireTap method
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#24981 Async serializer market trait
  akka-actor-tests/src/test/scala/akka/serialization/AsyncSerializeSpec.scala
  akka-actor/src/main/scala/akka/serialization/AsyncSerializer.scala
  akka-actor/src/main/scala/akka/serialization/Serializer.scala
Labels: tested

#24990 Allow reuse of journal loading logic
  CONTRIBUTING.md
  akka-persistence-query/src/main/mima-filters/2.5.12.backwards.excludes
  akka-persistence-query/src/main/scala/akka/persistence/query/PersistenceQuery.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/PersistenceQuerySpec.scala
  akka-persistence/src/main/scala/akka/persistence/PersistencePlugin.scala
Labels: tested

#24980 =str clarify invocation semantics of wireTap, make test less flaky
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWireTapSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#24795 RestartWithBackOff delay cancel to wait for failure
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RestartSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Restart.scala
Labels: tested

#24936 Fix typed cluster singleton cross dc proxies
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/MultiDcClusterShardingSpec.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiDcClusterShardingSpec.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonProxy.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerSpec.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/ClusterSingleton.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterSingletonImpl.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiDcClusterActors.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiDcClusterSingletonSpec.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiNodeTypedClusterSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiNodeClusterSpec.scala
  build.sbt
Labels: tested

#24890 Clarify in Scaladoc that failed sinks are removed (#21693)
  akka-stream/src/main/scala/akka/stream/javadsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Hub.scala
Labels: tested

#24911 Use 'same thread' execution context in UnfoldResourceSourceAsync
  akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala
Labels: tested

#25013 add BehaviorTestKit.runOne and .ref
  akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/javadsl/BehaviorTestKit.scala
  akka-testkit-typed/src/main/scala/akka/testkit/typed/scaladsl/BehaviorTestKit.scala
Labels: tested

#25001 Upgrade to Scala 2.12.6
  .travis.yml
  project/Dependencies.scala
Labels: tested

#24999 Remove erroneous character in distributed data doc
  akka-docs/src/main/paradox/distributed-data.md
Labels: tested

#25002 =doc fix the dead link for Failure Detector
  akka-docs/src/main/paradox/common/cluster.md
Labels: tested

#25015 Remove application.conf from typed test projects
  akka-cluster-sharding-typed/src/test/resources/application.conf
  akka-cluster-typed/src/test/resources/application.conf
  akka-persistence-typed/src/test/resources/application.conf
Labels: tested

#25003 Look for perf-java-flames on path in MultiJVM perf support
  akka-multi-node-testkit/src/main/mima-filters/2.5.12.backwards.excludes
  akka-multi-node-testkit/src/main/scala/akka/remote/testkit/PerfFlamesSupport.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/FanInThrougputSpec.scala
Labels: tested

#24997 =doc missing ACK reply in doc example
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
Labels: tested
