Repository akka/akka, pull requests merged in 2018-09, with the labels that each got.

#25555 Adding the CVE ID to RNG advisory
  akka-docs/src/main/paradox/security/2018-08-29-aes-rng.md
Labels: tested

#25552 QueueSource now drops after completion (#25349)
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/QueueSourceSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
Labels: tested

#25548 Fix SelectionHandler sequenceNumber overflow, #25546
  akka-actor/src/main/scala/akka/io/SelectionHandler.scala
Labels: tested

#25544 Link to sample projects
  akka-docs/src/main/paradox/additional/deploy.md
  akka-docs/src/main/paradox/additional/osgi.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/fsm.md
  akka-docs/src/main/paradox/general/supervision.md
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/index-network.md
  akka-docs/src/main/paradox/multi-node-testing.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  build.sbt
Labels: tested

#25401 Add the pipe pattern section
  akka-docs/src/main/paradox/futures.md
  akka-docs/src/main/paradox/images/futures-pipeto1.png
  akka-docs/src/main/paradox/images/futures-pipeto2.png
  akka-docs/src/test/java/jdocs/future/FutureDocTest.java
  akka-docs/src/test/scala/docs/future/FutureDocSpec.scala
Labels: tested

#25329 the highestSequenceNr is not predictable (https://github.com/akka/akka/i…
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala
Labels: tested

#25542 fix negative math.abs in Sharding Typed, #25034
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingMessageExtractor.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#25388 Fix bug in Balance stage when a downstream wait a response indefinitely
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBalanceSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: tested

#25515 Build with 2.12 as default
  project/Dependencies.scala
Labels: tested

#25585 Fix bad link to Immutability Changes Everything
  akka-docs/src/main/paradox/persistence-schema-evolution.md
Labels: tested

#25589 Docs: use the latest name to refer to Alpakka Kafka Connector
  akka-docs/src/main/paradox/common/other-modules.md
Labels: tested

#25554 Mima latest version 2.5.16
  akka-distributed-data/src/main/mima-filters/2.5.16.backwards.excludes
  project/MiMa.scala
Labels: tested

#25591 =doc Explain cgroup memory limit flags for docker
  akka-docs/src/main/paradox/additional/deploy.md
Labels: tested

#25575 Explicit intercept API for nesting, #25557
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/DeferredSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/MonitorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WidenSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StopSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WrappingBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/PersistentBehaviorImpl.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentBehaviorSpec.scala
Labels: tested

#25603 Upgrade to akka-paradox 0.12
  project/plugins.sbt
Labels: tested

#25588 Logging docs: show akka-slf4j dependency
  akka-docs/src/main/paradox/logging.md
Labels: tested

#25562 +doc Adding a fiddle example for Akka Typed
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-docs/src/main/paradox/assets/js/scalafiddle.js
  akka-docs/src/main/paradox/typed/actors.md
  build.sbt
Labels: tested

#25576 Allow restarting a named child in StubbedActorContext
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: tested

#25621 fix fiddle snippet path
  akka-docs/src/main/paradox/typed/actors.md
Labels: tested

#25606 cleanup some systemActor stuff
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorRef.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/adapter/package.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterImpl.scala
Labels: tested

#25152 Add method foreachAsync to Sink object
  akka-docs/src/main/paradox/stream/operators/Sink/foreachAsync.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/SinkRecipeDocTest.java
  akka-docs/src/test/scala/docs/stream/SinkRecipeDocSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachAsyncSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
Labels: tested

#25414 Document async and inetaddress DNS
  akka-actor/src/main/mima-filters/2.5.16.backwards.excludes
  akka-actor/src/main/scala/akka/io/Dns.scala
  akka-actor/src/main/scala/akka/io/dns/DnsProtocol.scala
  akka-docs/src/main/paradox/index-network.md
  akka-docs/src/main/paradox/io-dns.md
  akka-docs/src/test/java/jdocs/actor/io/dns/DnsCompileOnlyDocTest.java
  akka-docs/src/test/scala/docs/actor/io/dns/DnsCompileOnlyDocSpec.scala
Labels: tested

#25626 update to sbt 1.2.3
  project/build.properties
Labels: tested

#25633 Some more BehaviorIntercept tests
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WidenSpec.scala
Labels: tested

#25572 Remove Scheduler param in EntityRef.ask, #25481
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
Labels: tested

#25563 Utility to check that same version of all modules is used
  akka-actor-tests/src/test/scala/akka/util/ManifestInfoVersionSpec.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/util/ManifestInfo.scala
  build.sbt
Labels: tested

#25400 Add deprecation documentation to bin-compat docs
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
Labels: needs-attention

#25601 Use supervision in all places of Source.fromIterator, #25574
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowIteratorSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: tested

#25478 Add TODO and link to issue for stream ops with no description section
  akka-docs/src/main/paradox/stream/operators/FileIO/toPath.md
  akka-docs/src/main/paradox/stream/operators/Sink/asPublisher.md
  akka-docs/src/main/paradox/stream/operators/Sink/fromSubscriber.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/collectType.md
  akka-docs/src/main/paradox/stream/operators/Source/asSubscriber.md
  akka-docs/src/main/paradox/stream/operators/Source/fromPublisher.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/fromInputStream.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/fromJavaStream.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/fromOutputStream.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/javaCollector.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/javaCollectorParallelUnordered.md
Labels: needs-attention

#24286 =doc #24283 include rationale for Sink Source not extending RS
  akka-docs/src/main/paradox/general/stream/stream-design.md
Labels: discuss, tested

#25565 Undeprecate the config, add a note in cluster singleton
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster/src/main/resources/reference.conf
Labels: tested

#25225 WIP: Passivate for Typed Sharding, #24478
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/MultiDcClusterShardingSpec.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/SingletonCompileOnlyTest.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/SingletonCompileOnlySpec.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
Labels: tested

#25654 Remove the ActorContext parameter from the scaladsl command handler
  akka-actor/src/main/scala/akka/util/ConstantFun.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterSingletonPersistenceSpec.scala
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedRunning.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/PersistentBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/PersistentBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/PersistentBehaviors.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/AccountExample1.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/AccountExample2.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorsCompileOnly.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/InDepthPersistentBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/MovieWatchList.scala
Labels: tested

#25610 Introduce RecipientRef interface for ActorRef and EntityRef, #24463
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/DebugRef.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorRef.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorRefImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InternalRecipientRef.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorRefAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/adapter/package.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
Labels: tested

#25666 Warning for truncated DNS messages
  akka-actor/src/main/scala/akka/io/dns/internal/DnsClient.scala
  akka-docs/src/main/paradox/io-dns.md
Labels: tested

#25665 Deduplicate is specific to interception so belongs where it is
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
Labels: tested

#25505 AccountExample in javadsl, #25485
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/AccountExample.java
Labels: tested

#25653 Supervision with a BehaviorInterceptor
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/SupervisorStrategy.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Restarter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-testkit/src/test/scala/akka/testkit/TestActorRefSpec.scala
Labels: tested

#25636 Only treat nameservers as a StringList in config if getting as String…
  akka-actor-tests/src/test/scala/akka/io/dns/DnsSettingsSpec.scala
  akka-actor/src/main/scala/akka/io/dns/DnsSettings.scala
Labels: tested

#25590 Provide minSequenceNr for snapshot deletion
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RemoveInternalClusterShardingDataSpec.scala
  akka-docs/src/main/paradox/persistence.md
Labels: 2 - pick next, tested

#25645 Improve AskTimeoutException message, #25644
  akka-actor-tests/src/test/scala/akka/pattern/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
  akka-actor/src/main/scala/akka/pattern/Patterns.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
Labels: 2 - pick next, tested

#25678 Don't automatically down quarantined node, #25632
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/SurviveNetworkInstabilitySpec.scala
Labels: 2 - pick next, tested

#25684 Revert "Avoid ask to sharding guardian if region already cached", #25683
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ConcurrentStartupShardingSpec.scala
Labels: 2 - pick next, tested

#25595 Revert Support for rolling upgrade of ORSet[ActorRef], #25336
  akka-distributed-data/src/main/mima-filters/2.5.16.backwards.excludes
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala
  akka-docs/src/main/paradox/project/index.md
  akka-docs/src/main/paradox/project/migration-guide-2.4.x-2.5.x.md
  akka-docs/src/main/paradox/project/rolling-update.md
Labels: 2 - pick next, tested

#25689 AccountExample6 - command and event handlers as methods
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/PersistentBehaviors6.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/AccountExample6.scala
Labels: needs-attention

#25687 Support IPv6 in async-dns
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsManagerSpec.scala
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsResolverSpec.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsManager.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala
Labels: tested

#25685 Document MutableBehavior
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/MutableIntroTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/MutableIntroSpec.scala
  akka-docs/src/main/paradox/typed/actors.md
Labels: tested

#25693 Upgrade to scala 2.12.7
  .travis.yml
  project/Dependencies.scala
Labels: tested
