Repository akka/akka, pull requests merged in 2019-03, with the labels that each got.

#26441 Don't apply 'discipline' flags to compilation run for documentation
  project/AkkaBuild.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26450 Fixing minor wrapping.
  akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotSpec.scala
Labels: tested

#26440 Add issue reference field to ApiMayChange annotation (#26409)
  akka-actor/src/main/java/akka/annotation/ApiMayChange.java
  akka-actor/src/main/mima-filters/2.5.21.backwards.excludes
Labels: tested

#26437 Document snapshot releases
  RELEASING.md
Labels: tested

#26401 remove ccompat import in CollectionSinkSpec, #26305
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/CollectionSinkSpec.scala
Labels: tested

#26431 Doc changes on supervising example on Tutorial guide # 26429
  akka-docs/src/test/scala/tutorial_1/ActorHierarchyExperiments.scala
Labels: tested

#26353 Rename start/endContextPropagation functions to asFlow/Source..
  akka-docs/src/main/paradox/stream/operators/Source/asSourceWithContext.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextLogSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/WithContextUsageSpec.scala
  akka-stream/src/main/mima-filters/2.5.21.backwards.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SourceWithContext.scala
Labels: 2 - pick next, tested

#26372 Adds Flow.asFlowWithContext
  akka-docs/src/main/paradox/stream/operators/Flow/asFlowWithContext.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: 2 - pick next, tested

#26461 Fixing compilation error regarding to and from context propagated source
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextSpec.scala
Labels: 2 - pick next, tested

#26462 Sets correct return type for withAttributes on Source/FlowWithContext
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextLogSpec.scala
  akka-stream/src/main/mima-filters/2.5.21.backwards.excludes
  akka-stream/src/main/scala/akka/stream/Graph.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SourceWithContext.scala
Labels: 2 - pick next, tested

#26464 Adds to and toMap to SourceWithContext
  akka-docs/src/main/paradox/persistence-query.md
  akka-persistence-query/src/main/scala/akka/persistence/query/ReadJournalProvider.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SourceWithContext.scala
Labels: tested

#26465 Adds fromPairs to SourceWithContent object
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream/src/main/mima-filters/2.5.21.backwards.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SourceWithContext.scala
Labels: tested

#26452 Consolidate duplicate persistence sharding function #26451
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-persistence/src/main/mima-filters/2.5.21.backwards.excludes
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
Labels: tested

#26422 act Avoid deadletter access if not needed
  akka-actor/src/main/scala/akka/dispatch/Mailbox.scala
Labels: tested

#26457 Use AsyncDnsCache directly in DnsServiceDiscovery, #25948
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsManagerSpec.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsCache.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsManager.scala
  akka-discovery/src/main/scala/akka/discovery/dns/DnsServiceDiscovery.scala
  akka-discovery/src/test/scala/akka/discovery/dns/DnsDiscoverySpec.scala
Labels: tested

#26469 Fix dead links in the docs
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/stream/operators/RestartSink/withBackoff.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: t:docs, tested

#26447 Fix typos of OutgoingConnectionStage's port names
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
Labels: tested

#26261 Access latestSeqNr in typed persistence
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
Labels: tested

#26474 !str remove {Source,Flow}WithContext.statefulMapConcat, fixes #26330
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream/src/main/mima-filters/2.5.21.backwards.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
Labels: tested

#26475 Remove outdated comment from build.properties
  project/build.properties
Labels: tested

#26456 Add marker support in logging filters #26544
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Logger.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/event/Logging.scala
  akka-remote/src/main/scala/akka/remote/artery/MessageDispatcher.scala
  akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala
Labels: tested

#26135 Simplify backoff supervision API #26156
  akka-actor/src/main/mima-filters/2.5.21.backwards.excludes
  akka-actor/src/main/scala/akka/pattern/Backoff.scala
  akka-actor/src/main/scala/akka/pattern/BackoffOptions.scala
  akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/HandleBackoff.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnRestartSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnStopSupervisor.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/SupervisionSpec.scala
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/general/supervision.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/test/java/jdocs/pattern/BackoffSupervisorDocTest.java
  akka-docs/src/test/java/jdocs/persistence/LambdaPersistenceDocTest.java
  akka-docs/src/test/scala/docs/pattern/BackoffSupervisorDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/PersistenceDocSpec.scala
Labels: tested

#26479 fix login the bind address when remoting starts
  .java-version
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
Labels: tested

#26483 Use only https links to doc.akka.io by now (canonical link in our docs HTML)
  build.sbt
Labels: tested

#26485 Adds docs for actorRef stream integration #24595
  akka-docs/src/main/paradox/stream/stream-integrations.md
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
Labels: tested

#26460 Document publishing branch snapshots
  RELEASING.md
Labels: tested

#26323 Typed actor routers
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/RoutersTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/routing/RoutingLogicSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/MessageAndSignals.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/RoutingLogic.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-docs/src/main/paradox/typed/index.md
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#26347 Typed persistence stash improvements
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedSettings.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/StashManagement.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/StashStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
Labels: tested

#26478 Use configuration property for timeout for assertAllStagesStopped (#26410)
  akka-stream-testkit/src/main/resources/reference.conf
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/StreamTestKit.scala
Labels: tested

#26396 Wrap exception from unstash, #26148
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
Labels: tested

#26497 Check all recipients and msgs are done rather than specific order
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
Labels: tested

#26400 Validate compile in multi-jvm
  .travis.yml
  build.sbt
  project/MultiNode.scala
Labels: 2 - pick next, tested

#26484 signals for EventSourcedBehavior
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/EventSourcedSignal.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/SignalHandler.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/EventSourcedActorFailureTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/NullEmptyStateTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PrimitiveStateTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotMutableStateSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: t:persistence, t:typed, tested

#26516 clarifies backoff's "restart" #23406
  akka-docs/src/main/paradox/general/supervision.md
Labels: tested

#26331 Intercept poststop
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/GracefulStopDocTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/GracefulStopSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StopSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/GracefulStopDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/PoisonPill.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
Labels: tested

#26522 Paradox: latest 0.5.3, latest theme 0.16, more https
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/futures.md
  akka-docs/src/main/paradox/guide/tutorial_1.md
  akka-docs/src/main/paradox/typed/guide/tutorial_1.md
  build.sbt
  project/AkkaBuild.scala
  project/GitHub.scala
  project/Publish.scala
  project/plugins.sbt
Labels: t:docs, tested

#26528 Remove Lightbend Enterprise Suite from deploy.md
  akka-docs/src/main/paradox/additional/deploy.md
Labels: tested

#26513 Issue references to FIXMEs in Typed
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/DeferredSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WrappingBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/internal/ReplicatorBehavior.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/BasicClusterExampleTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
Labels: tested

#26509 Fix typo in QueueSource's error message.
  akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
Labels: tested

#26301 =act #26300 try not to get stopped by death pact before Unregistration is complete
  akka-actor/src/main/scala/akka/io/TcpConnection.scala
Labels: 2 - pick next, tested

#26534 Correctly throw when akka.discovery.SimpleServiceDiscovery is found
  akka-discovery/src/main/scala/akka/discovery/Discovery.scala
Labels: tested

#26506 Expect java11 for releasing
  project/scripts/release
Labels: tested

#25817 Deprecated the after pattern supporting methods which accept a v…
  akka-actor-tests/src/test/java/akka/pattern/PatternsTest.java
  akka-actor/src/main/scala/akka/pattern/Patterns.scala
  akka-docs/src/test/java/jdocs/future/FutureDocTest.java
  akka-docs/src/test/java/jdocs/stream/StreamTestKitDocTest.java
Labels: tested

#26524 Expected behavior on Terminated with orElse signal handling
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
Labels: tested

#26547 Wrong filename for some 2.5.20 mima excludes
  akka-stream/src/main/mima-filters/2.5.20.backward.excludes
  akka-stream/src/main/mima-filters/2.5.20.backwards.excludes
Labels: tested

#26533 Typed Persistence: Implement deleting snapshots / events #24698
  akka-persistence-typed/src/main/scala/akka/persistence/typed/EventSourcedSignal.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/Retention.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/JournalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence/src/main/scala/akka/persistence/JournalProtocol.scala
  akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
Labels: tested

#25413 Race condition in lazy sink on immediate failure
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySinkSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
Labels: tested

#26546 Include 'reproducible builds' sbt plugin
  build.sbt
  project/OSGi.scala
  project/plugins.sbt
Labels: tested

#26332 Fix pattern for matching SRV service names
  akka-discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
  akka-discovery/src/test/scala/akka/discovery/LookupSpec.scala
Labels: 2 - pick next, tested

#26553 Typed Persistence: Rename internal.JournalInteractions for clarity #26551
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RequestingRecoveryPermit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested

#26476 give cached value back
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
Labels: tested

#26542 akka-distributed-data compiler warnings
  akka-cluster/src/main/scala/akka/cluster/Member.scala
  akka-distributed-data/src/main/mima-filters/2.5.21.backwards.excludes
  akka-distributed-data/src/main/scala/akka/cluster/ddata/ORMap.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/ORMultiMap.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/ORSet.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/PruningState.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializer.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/FlagSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/GCounterSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/GSetSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/LWWMapSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/LWWRegisterSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/ORMapSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/ORMultiMapSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/ORSetSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/PNCounterMapSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/PNCounterSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/VersionVectorSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/WriteAggregatorSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializerSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializerSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26548 Notice too long quarantine-after-silence config value, #26512
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/Endpoint.scala
  akka-remote/src/main/scala/akka/remote/RemoteSettings.scala
Labels: tested

#26515 Explicitly require jdk9+ for javadoc generation
  project/Doc.scala
Labels: tested

#26555 Make sure actor started timer before we change time
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/ManualTimerExampleSpec.scala
Labels: tested

#26569 enable serializer for ShardRegionStats, #25348
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializerSpec.scala
  akka-docs/src/main/paradox/project/rolling-update.md
Labels: 2 - pick next, tested

#26571 Update genjavadoc
  project/Doc.scala
Labels: tested

#26552 Strict compiler settings for discovery
  akka-discovery/src/test/scala/akka/discovery/DiscoveryConfigurationSpec.scala
  akka-discovery/src/test/scala/akka/discovery/aggregate/AggregateServiceDiscoverySpec.scala
  akka-discovery/src/test/scala/akka/discovery/dns/DnsDiscoverySpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26557 Clarified the failure conditions for Read/WriteLocal
  akka-docs/src/main/paradox/distributed-data.md
Labels: tested

#26519 add missing API in javadsl.EventSourcedBehavior, #26273
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
Labels: 2 - pick next, tested

#26521 a few more persistence tests from PersistentActorSpec, #24687
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PersistenceId.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
Labels: 2 - pick next, tested

#26540 Typed version of the ForkJoinActorBenchmark
  akka-bench-jmh-typed/src/main/scala/akka/actor/typed/TypedActorBenchmark.scala
  akka-bench-jmh-typed/src/main/scala/akka/actor/typed/TypedBenchmarkActors.scala
  akka-bench-jmh-typed/src/main/scala/akka/actor/typed/TypedForkJoinActorBenchmark.scala
Labels: tested

#26539 add EventSourcedBehaviorTimersSpec, #24687
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorTimersSpec.scala
Labels: 2 - pick next, tested

#26576 Update Akka Management version to 1.0.0
  akka-docs/src/main/paradox/discovery/index.md
Labels: tested

#26575 Small typos
  akka-docs/src/main/paradox/discovery/index.md
Labels: tested

#26595 Typed Persistence: fix snapshot deletion algorithm, #26584
  akka-persistence-typed/src/main/scala/akka/persistence/typed/EventSourcedSignal.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/Retention.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
Labels: tested

#26596 Replace SnapshotSelectionCriteria and SnapshotMetadata, #26536
  akka-persistence-typed/src/main/scala/akka/persistence/typed/EventSourcedSignal.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/SnapshotSelectionCriteria.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotMutableStateSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: tested

#26604 Fix of the new javadoc search functionality
  project/Doc.scala
Labels: tested

#26583 fix NPE in SnapshotStore, #26580
  akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala
  akka-persistence/src/main/scala/akka/persistence/snapshot/SnapshotStore.scala
Labels: tested

#26578 test when event handler throws during replay, #24687
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
Labels: 2 - pick next, tested

#26538 add tests for missing journal and snapshot plugin config, #24687
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedSettings.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence/src/main/scala/akka/persistence/Persistence.scala
Labels: 2 - pick next, tested

#26585 remove ??? in SnapshotMutableStateSpec, #26581
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotMutableStateSpec.scala
Labels: tested

#26605 fix race condition in Running.storingSnapshot, #26601
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: 2 - pick next, tested

#26520 Make typed persistence side effect internal
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EffectImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/SideEffect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/Effect.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
Labels: 2 - pick next, tested

#26603 Typed Persistence: docs / sample for deleting snapshots and events
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: tested

#26607 Add DeleteEventsCompleted in signal handler for logging consistency #26606
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
Labels: tested

#26590 Typed guardian startup and actor adapter simplification
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ExtensionsSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/GuardianStartupSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/GuardianStartupBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/PropsAdapter.scala
Labels: 2 - pick next, tested

#26613 Docs: latest Akka Paradox template
  project/plugins.sbt
Labels: t:docs, tested

#26588 Introduce warning silencer plugin
  akka-actor/src/main/mima-filters/2.5.21.backwards.excludes
  akka-actor/src/main/scala-2.13+/akka/util/ccompat/ccompatUsedUntil213.scala
  akka-actor/src/main/scala-2.13+/akka/util/ccompat/imm/package.scala
  akka-actor/src/main/scala-2.13-/akka/util/ccompat/ccompatUsedUntil213.scala
  akka-actor/src/main/scala-2.13-/akka/util/ccompat/imm/package.scala
  akka-actor/src/main/scala-2.13-/akka/util/ccompat/package.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingMinMembersSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiDcClusterShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/CoordinatedShutdownShardingSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerDownedSpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonLeavingSpeedSpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonRestart2Spec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonRestartSpec.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MinMembersBeforeUpSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcHeartbeatTakingOverSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiNodeClusterSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/NodeMembershipSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RestartFirstSeedNodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RestartNode2Spec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RestartNode3Spec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RestartNodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/UnreachableNodeJoinsAgainSpec.scala
  akka-discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/DeltaPropagationSelector.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/ORMap.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/ORMultiMap.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/ORSet.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/VersionVector.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializer.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/SerializationSupport.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/DurablePruningSpec.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorMapDeltaSpec.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorPruningSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/LotsOfDataBot.scala
  project/AkkaDisciplinePlugin.scala
  project/MultiNode.scala
Labels: tested

#26570 Extends collection of shutdown Reasons (e.g. ClusterJoinUnsuccessfulReason)
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala
  akka-cluster/src/main/mima-filters/2.5.21.backwards.excludes
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested

#26567 Try harder to get a good log source class in EventSourcedBehavior
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/LoggerClass.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
Labels: tested

#26599 Typed unstash improvements
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/EffectfulActorContext.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashBufferSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/StashBuffer.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/StashBuffer.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
Labels: tested

#26615 fix compilation error in LoggerSourceTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
Labels: needs-attention

#26616 fix ActorSystemSpec, #26614
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorSystemSpec.scala
Labels: tested

#25796 FanoutPublisherSink leaking actors on upstream failure
  akka-stream-tests/src/test/scala/akka/stream/impl/FanoutProcessorSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala
Labels: tested

#26054 GrapheStage implementation for actorRef source (#25324)
  akka-docs/src/main/paradox/stream/stream-integrations.md
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-docs/src/test/java/jdocs/stream/operators/SourceDocExamples.java
  akka-docs/src/test/scala/docs/stream/StreamTestKitDocSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefSourceSpec.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorSource.scala
  akka-stream/src/main/mima-filters/2.5.21.backwards.excludes
  akka-stream/src/main/scala/akka/stream/CompletionStrategy.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSourceActor.scala
  akka-stream/src/main/scala/akka/stream/impl/Modules.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#26529 test PoisonPill and stash of EventSourcedBehavior, #24687
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
Labels: 2 - pick next, tested

#26621 Disable genjavadoc during scaladoc compilation #26617
  project/Doc.scala
Labels: tested

#26541 Typed perf improvements
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
Labels: tested

#26623 Minor ClusterSharding scaladoc suggestions.
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#26577 add more tests for receiving PoisonPill in various states, #24687
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RequestingRecoveryPermit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
Labels: 2 - pick next, tested

#26619 contribution guidelines about wire compatibility
  CONTRIBUTING.md
Labels: tested

#26554 Represent closed in either end as closed in ADT
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
Labels: 2 - pick next, tested

#26579 cleanup logging in persistence tests, #24687
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/EventSourcedActorFailureTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/ManyRecoveriesSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/OptionalSnapshotStoreSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala
Labels: 2 - pick next, tested

#26635 Typo in Akka Typed Persistence Docs
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#26638 revert rename gotoOldest
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
Labels: 2 - pick next, tested

#26610 cleanup Receptionist example
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExample.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExampleTest.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExample.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExampleSpec.scala
  akka-docs/src/main/paradox/typed/actor-discovery.md
Labels: tested

#26611 print typeName in ShardRegion logs
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#26639 Add "-no-link-warnings" for 2.11 scaladoc
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26626 Fix memory leak in watchWith (#26625)
  akka-actor/src/main/mima-filters/2.5.21.backwards.excludes
  akka-actor/src/main/scala/akka/actor/Stash.scala
  akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala
Labels: 2 - pick next, tested
