Repository akka/akka, pull requests merged in 2019-07, with the labels that each got.

#27229 update modules list for akka enhancements
  akka-docs/src/main/paradox/guide/modules.md
  akka-docs/src/main/paradox/typed/guide/modules.md
Labels: tested

#26811 Re-write InputStreamSource as GraphStage
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/FileSourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSinkSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/IOResult.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSources.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamPublisher.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
Labels: 2 - pick next, tested

#27209 better logger class for typed.ActorSystem
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
Labels: tested

#27005 Merge Source.apply and Source.from docs
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/apply.md
  akka-docs/src/main/paradox/stream/operators/Source/from.md
  akka-docs/src/main/paradox/stream/operators/index.md
  project/StreamOperatorsIndexGenerator.scala
Labels: tested

#27167 Log rebalance progress at INFO per rebalance info
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: 2 - pick next, tested

#26703 Move a couple of Akka Streams examples to their own files
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/conflate.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/conflateWithSeed.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/log.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/scan.md
  akka-docs/src/test/scala/docs/stream/operators/SourceOrFlow.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Conflate.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Log.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Scan.scala
Labels: tested

#27148 ClassTag in BehaviorInterceptor, #25887
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/AsyncTestingExampleTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/InterceptTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/LogMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StopSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/PoisonPill.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/GuardianStartupBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorInterceptorSpec.scala
Labels: 2 - pick next, tested

#27252 Remove Behavior.orElse, #26867
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#27251 Allow widen to be used with EventSourcedBehavior, #25887
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorInterceptorSpec.scala
Labels: 2 - pick next, tested

#27097 Remove API may change for flow with context
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: 2 - pick next, tested

#27127 Support same dispatcher as parent in Typed, #27123
  akka-actor-typed-tests/src/test/java/akka/actor/typed/DispatcherSelectorTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/DispatchersDocTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/PropsSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/DispatcherSelectorSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/DispatchersDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Props.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/PropsImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorRefFactoryAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/PropsAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Adapter.scala
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-actor/src/main/scala/akka/actor/Deployer.scala
  akka-actor/src/main/scala/akka/dispatch/Mailboxes.scala
  akka-docs/src/main/paradox/typed/dispatchers.md
Labels: 2 - pick next, tested

#27178 move synchronous behavior testing docs
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/AsyncTestingExampleTest.java
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/JunitIntegrationExampleTest.java
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/ScalaTestIntegrationExampleSpec.scala
  akka-docs/src/main/paradox/typed/testing.md
Labels: 2 - pick next, tested

#27096 Remove ApiMayChange from typed testkit
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/BehaviorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/TestInbox.scala
  build.sbt
Labels: 2 - pick next, tested

#27170 FlowDelay with EmitEarly caused a NPE
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDelaySpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: 2 - pick next, tested, to-be-backported

#27264 FlowDelay with EmitEarly caused a NPE (#27170)
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDelaySpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: backport, tested

#27246 Add expectNoMessage to subscriber probe
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeGlobalRateLimit.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeMissedTicks.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeSimpleDrop.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowAskSpec.scala
Labels: t:stream, t:testing, tested

#27160 Log Dropped from DeadLetterListener, #26432
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/DeadLetterSuspensionSpec.scala
  akka-actor-tests/src/test/scala/akka/dispatch/MailboxConfigSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/MessageAndSignals.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/event/DeadLetterListener.scala
  akka-bench-jmh/src/main/scala/akka/remote/artery/CodecBenchmark.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/StashManagement.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/Handshake.scala
  akka-remote/src/test/scala/akka/remote/artery/TestContext.scala
  akka-testkit/src/main/scala/akka/testkit/TestEventListener.scala
Labels: 2 - pick next, tested

#26757 Cluster heartbeat timings
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster/src/main/protobuf/ClusterMessages.proto
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterHeartbeat.scala
  akka-cluster/src/main/scala/akka/cluster/CrossDcClusterHeartbeat.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterHeartbeatReceiverSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterHeartbeatSenderSpec.scala
  akka-cluster/src/test/scala/akka/cluster/CrossDcHeartbeatSenderSpec.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
Labels: 2 - pick next, tested, to-be-backported

#27245 Replace ActorPublishers in leveldb with stages
  akka-persistence-query/src/main/mima-filters/2.5.x.backwards.excludes
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/AllPersistenceIdsPublisher.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/AllPersistenceIdsStage.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/Buffer.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/DeliveryBuffer.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdPublisher.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdStage.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagPublisher.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagStage.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/scaladsl/LeveldbReadJournal.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByTagSpec.scala
Labels: 2 - pick next, tested

#25205 Subscription timeouts not working
  akka-stream-tests/src/test/scala/akka/stream/impl/TimeoutsSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/ActorProcessor.scala
  akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala
Labels: 2 - pick next, tested

#27257 Add sender to the exception message when the message sent is null.
  akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala
Labels: tested

#27081 Make EntityRef & EntityTypeKey contravariant
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleSpec.scala
Labels: tested

#26471 Fix an issue of prolonged delay in the Delay stage [#26470].
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDelaySpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: tested

#27241 fix two log messages related to unsafe-remote-features
  akka-cluster/src/main/scala/akka/cluster/ClusterActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
Labels: 2 - pick next, tested

#26946 Akka Persistence instrumentation improvements
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
Labels: tested

#27130 EventSeq in Typed EventAdapter, #26909
  akka-actor/src/main/scala/akka/util/OptionVal.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/EventAdapter.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedEventAdapterSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
  akka-persistence/src/main/scala/akka/persistence/Persistent.scala
Labels: 2 - pick next, tested

#27200 Typed Stash: Create via factory method on Behaviors
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StashDocTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashBufferSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/GuardianStartupSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StashDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/GuardianStartupBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/StashBuffer.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/StashBuffer.scala
  akka-actor/src/main/scala-2.13/akka/compat/Future.scala
  akka-actor/src/main/scala/akka/actor/Stash.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/StashManagement.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/StashStateSpec.scala
Labels: 2 - pick next, tested

#27077 Pattern for responding to a sharded actor
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingReplyCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: 2 - pick next, tested

#27280 Akka Persistence instrumentation improvements (#26946)
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
Labels: 2 - pick next, tested

#27279 Fix an issue of prolonged delay in the Delay stage #26470
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDelaySpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: backport, tested

#27250 Deprecation removal hunt
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/scala/akka/actor/AbstractActor.scala
  akka-actor/src/main/scala/akka/actor/Actor.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
  akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#27282 use Scala 2.13 for last step in release script
  project/scripts/release
Labels: 2 - pick next, tested

#27267 Rewrite actor ref sink as a graph stage
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefSinkSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSinkActor.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSinkStage.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
Labels: 2 - pick next, tested

#27284 Serialization of case object with Jackson, #27283
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
Labels: tested

#27188 Akka 27103/streams zip all [#27103]
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zipAll.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/scala/akka/stream/DslConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowZipAllSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#27289 Don't WARN when the user explicitly enabled unsafe features
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
Labels: tested

#27281 Cluster heartbeat timings (#26757)
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/mima-filters/2.5.23.backwards.excludes
  akka-cluster/src/main/protobuf/ClusterMessages.proto
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterHeartbeat.scala
  akka-cluster/src/main/scala/akka/cluster/CrossDcClusterHeartbeat.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterHeartbeatReceiverSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterHeartbeatSenderSpec.scala
  akka-cluster/src/test/scala/akka/cluster/CrossDcHeartbeatSenderSpec.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
Labels: backport, tested

#27247 Re-write file sink as a graph stage
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/io/FileOutputStage.scala
  akka-stream/src/main/scala/akka/stream/impl/io/FileSubscriber.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSinks.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FileIO.scala
Labels: 2 - pick next, tested

#27222 cluster.joinSeedNodes(...) does not throw warnings when seed hostname contains underscores #25287
  akka-actor-tests/src/test/scala/akka/actor/ActorPathSpec.scala
  akka-actor/src/main/scala/akka/actor/Address.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/Cluster.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterApiSpec.scala
  akka-cluster/src/main/scala/akka/cluster/Cluster.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
Labels: 2 - pick next, tested

#27274 Cluster Sharding: make askAllShards not a hard coded timeout #27273
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
Labels: tested

#27297 Minor spelling fix in doc
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-routing.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/distributed-pub-sub.md
  akka-docs/src/main/paradox/fault-tolerance.md
  akka-docs/src/main/paradox/fsm.md
  akka-docs/src/main/paradox/index-actors.md
  akka-docs/src/main/paradox/index-classic.md
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/index-network.md
  akka-docs/src/main/paradox/mailboxes.md
  akka-docs/src/main/paradox/persistence-fsm.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/routing.md
  akka-docs/src/main/paradox/scheduler.md
  akka-docs/src/main/paradox/testing.md
Labels: tested

#27277 Use SPDX short identifier for license
  project/AkkaBuild.scala
Labels: tested

#27305 Fix stack overflow in stream converters
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamConvertersSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
Labels: tested, to-be-backported

#27260 Make shard homes retry request warning message less spammy
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#27286 Remove warnings in persistence-tck
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalPerfSpec.scala
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala
  akka-persistence-tck/src/main/scala/akka/persistence/scalatest/OptionalTests.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#27296 Small fix and test coverage for unfoldResourceAsync
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceAsyncSourceSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala
Labels: tested

#27306 Serialization for more Cluster Sharding query messages
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-sharding/src/main/protobuf/ClusterShardingMessages.proto
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializerSpec.scala
Labels: tested, to-be-backported

#27271 Style Guide: Functional vs object-oriented style, #22805
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StyleGuideDocExamples.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/index.md
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27307 Fix stack overflow in stream converters (#27305)
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamConvertersSpec.scala
  akka-stream/src/main/mima-filters/2.5.23.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
Labels: backport, tested

#27270 Update paradox-apidoc
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/testing.md
  project/plugins.sbt
Labels: tested

#27313 Make the router doc test actually verify that it works
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
Labels: tested

#27256 Remove additional-serialization-bindings, #26684
  akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/serialization/Serialization.scala
  akka-cluster-metrics/src/test/scala/akka/cluster/metrics/protobuf/MessageSerializerSpec.scala
  akka-cluster-tools/src/main/resources/reference.conf
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
  akka-docs/src/main/paradox/serialization.md
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/test/scala/akka/remote/serialization/AllowJavaSerializationOffSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/DaemonMsgCreateSerializerSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/MiscMessageSerializerSpec.scala
Labels: tested

#27320 Fix Scaladoc typo
  akka-stream/src/main/scala/akka/stream/CompletionStrategy.scala
Labels: tested

#27311 Rename widen to transformMessages, #27253
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/DeferredSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TransformMessagesSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorInterceptorSpec.scala
Labels: tested

#27314 One more deprecation for IOResult(n, ex)
  akka-stream/src/main/scala/akka/stream/IOResult.scala
Labels: tested

#27237 Deprecate classic remoting classes
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/Member.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/SurviveNetworkInstabilitySpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-remote-tests/src/multi-jvm/scala/akka/remote/TransportFailSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/RemoteRestartedQuarantinedSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/SurviveNetworkPartitionSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/classic/RemoteGatePiercingSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/classic/RemoteNodeRestartGateSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/classic/Ticket15109Spec.scala
  akka-remote/src/main/scala/akka/remote/AckedDelivery.scala
  akka-remote/src/main/scala/akka/remote/Endpoint.scala
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteMetricsExtension.scala
  akka-remote/src/main/scala/akka/remote/RemoteSettings.scala
  akka-remote/src/main/scala/akka/remote/Remoting.scala
  akka-remote/src/main/scala/akka/remote/RemotingLifecycleEvent.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/QuarantinedEvent.scala
  akka-remote/src/main/scala/akka/remote/transport/AbstractTransportAdapter.scala
  akka-remote/src/main/scala/akka/remote/transport/AkkaPduCodec.scala
  akka-remote/src/main/scala/akka/remote/transport/AkkaProtocolTransport.scala
  akka-remote/src/main/scala/akka/remote/transport/FailureInjectorTransportAdapter.scala
  akka-remote/src/main/scala/akka/remote/transport/TestTransport.scala
  akka-remote/src/main/scala/akka/remote/transport/ThrottlerTransportAdapter.scala
  akka-remote/src/main/scala/akka/remote/transport/Transport.scala
  akka-remote/src/main/scala/akka/remote/transport/netty/NettySSLSupport.scala
  akka-remote/src/main/scala/akka/remote/transport/netty/NettyTransport.scala
  akka-remote/src/main/scala/akka/remote/transport/netty/SSLEngineProvider.scala
  akka-remote/src/main/scala/akka/remote/transport/netty/TcpSupport.scala
  akka-remote/src/test/scala/akka/remote/AckedDeliverySpec.scala
  akka-remote/src/test/scala/akka/remote/RemoteConfigSpec.scala
  akka-remote/src/test/scala/akka/remote/RemoteFeaturesSpec.scala
  akka-remote/src/test/scala/akka/remote/Ticket1978CommunicationSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteWatcherSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteDeploymentWhitelistSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteSettingsSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteWatcherSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/transport/AkkaProtocolSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/transport/GenericTransportSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/transport/SystemMessageDeliveryStressTest.scala
  akka-remote/src/test/scala/akka/remote/classic/transport/TestTransportSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/transport/ThrottlerTransportAdapterSpec.scala
Labels: tested

#27308 Java 9+ compilation compat nitpicks
  akka-actor/src/main/scala/akka/io/Dns.scala
  akka-actor/src/main/scala/akka/util/Reflect.scala
Labels: tested

#27319 Snapshot adapter for typed persistence
  akka-persistence-typed/src/main/scala/akka/persistence/typed/SnapshotAdapter.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/NoOpSnapshotAdapter.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSnapshotAdapterSpec.scala
Labels: tested

#27323 adjust Cluster in docs ToC
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/index-cluster.md
Labels: tested

#27244 Doc trait+object (enum) serialization for Jackson
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/CustomAdtSerializer.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
Labels: tested

#27341 Remove infinite redirect from docs
  akka-docs/src/main/paradox/.htaccess
Labels: tested

#27344 fix serialization failure in ClusterShardingSpec
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
Labels: tested

#27326 Style Guide: Passing around too many parameters, #22805
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StyleGuideDocExamples.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27343 Improve "Typed Actors" intro
  akka-docs/src/main/paradox/typed-actors.md
Labels: tested

#27316 fix FIXMEs in Jackson serializer and docs
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v1/OrderAdded.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/CustomerMigration.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/ItemAdded.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/OrderPlaced.java
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v1/Customer.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v1/ItemAdded.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v1/OrderAdded.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2a/Address.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2a/Customer.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2a/CustomerMigration.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2a/ItemAdded.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2a/OrderPlaced.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2a/OrderPlacedMigration.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2b/ItemAdded.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2b/ItemAddedMigration.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2c/ItemAdded.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2c/ItemAddedMigration.scala
Labels: tested

#27310 Move event stream messages to EventStream.*, #27211
  akka-actor-typed-tests/src/test/java/akka/actor/typed/eventstream/EventStreamTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/eventstream/EventStreamSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/eventstream/EventStream.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/EventStreamExtension.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/EventStreamAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
Labels: tested

#27322 Use application-test.conf for typed testkit, #25708
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestKitJunitResource.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ScalaTestWithActorTestKit.scala
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/TestConfigExample.java
  akka-actor-testkit-typed/src/test/resources/application-test.conf
  akka-actor-testkit-typed/src/test/resources/application.conf
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitSpec.scala
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/TestConfigExample.scala
  akka-docs/src/main/paradox/general/configuration.md
  akka-docs/src/main/paradox/typed/testing.md
Labels: tested

#27272 Style: Update HelloWorld sample to OO style for Java, #22805
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/SpawnProtocolDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/SpawnProtocolDocSpec.scala
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actors.md
Labels: 2 - pick next, tested

#27332 Update to Jackson databind 2.9.9.1 to fix CVE-2019-12384 and CVE-2019-12814
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27331 Backport new serializers from 2.6
  akka-actor-tests/src/test/scala/akka/serialization/PrimitivesSerializationSpec.scala
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/serialization/PrimitiveSerializers.scala
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-sharding/src/main/protobuf/ClusterShardingMessages.proto
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializerSpec.scala
  akka-remote/src/main/java/akka/remote/ArteryControlFormats.java
  akka-remote/src/main/java/akka/remote/ContainerFormats.java
  akka-remote/src/main/java/akka/remote/SystemMessageFormats.java
  akka-remote/src/main/java/akka/remote/WireFormats.java
  akka-remote/src/main/protobuf/ContainerFormats.proto
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/serialization/MiscMessageSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/ThrowableNotSerializableException.scala
  akka-remote/src/test/java/akka/remote/ProtobufProtocol.java
  akka-remote/src/test/scala/akka/remote/serialization/MiscMessageSerializerSpec.scala
Labels: backport, tested

#27329 Style Guide: factory method and messages, #22805
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StyleGuideDocExamples.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AbstractBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AbstractBehavior.scala
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27302 Harden copyUSAciiBytesToStr, so that it works on Raspberry Pi, #27301
  akka-actor-tests/src/test/scala/akka/util/AsciiStringCopySpec.scala
  akka-actor/src/main/scala/akka/util/Unsafe.java
Labels: tested, to-be-backported

#27346 Harden copyUSAciiBytesToStr, so that it works on Raspberry Pi, #27301
  akka-actor-tests/src/test/scala/akka/util/AsciiStringCopySpec.scala
  akka-actor/src/main/scala/akka/util/Unsafe.java
Labels: backport, tested

#27337 Style Guide: enum msg, ask, tot fun, naming, meth ref, intro, #22805
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StyleGuideDocExamples.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AbstractBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AbstractBehavior.scala
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27334 Fix intercept of Watch in use of safe remote features #27333
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterWatcherNoClusterWatcheeSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/AttemptSysMsgRedeliverySpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteFeaturesSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/SurviveNetworkPartitionSpec.scala
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/test/scala/akka/remote/artery/SystemMessageDeliverySpec.scala
  akka-remote/src/test/scala/akka/remote/classic/ActorsLeakSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
Labels: tested

#26906 Hostname verification should be done by the client only
  akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala
Labels: tested

#27354 Allow java serialization for TypedActorRemoteDeploySpec
  akka-actor-tests/src/test/scala/akka/util/IgnoreForScala212.scala
  akka-remote/src/test/scala/akka/remote/TypedActorRemoteDeploySpec.scala
Labels: tested

#27315 Cluster aware routers for typed
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/receptionist/ReceptionistApiSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistMessages.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/Registry.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/internal/ClusterReceptionistUnreachabilitySpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
  akka-docs/src/main/paradox/typed/actor-discovery.md
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#27359 Fix race in ActorModelSpec
  akka-actor-tests/src/test/scala/akka/actor/dispatch/ActorModelSpec.scala
Labels: backport, tested

#27020 Add fluent API for 2-stream 'mergeLatest'
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mergeLatest.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mergePreferred.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/scala/akka/stream/DslConsistencySpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#27093 Added actor termination coordinated shutdown task
  akka-actor-tests/src/test/scala/akka/actor/CoordinatedShutdownSpec.scala
  akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/test/java/jdocs/actor/ActorDocTest.java
  akka-docs/src/test/scala/docs/actor/ActorDocSpec.scala
Labels: tested

#27357 Align SpawnProtocol with style guide
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/SpawnProtocolDocTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SpawnProtocolSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/DispatcherSelectorSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/DispatchersDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/SpawnProtocolDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/SpawnProtocol.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/internal/ClusterReceptionistUnreachabilitySpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27183 Mailbox selection for Akka Typed actors
  akka-actor-typed-tests/src/test/java/akka/actor/typed/MailboxSelectorTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/MailboxDocTest.java
  akka-actor-typed-tests/src/test/resources/mailbox-config-sample.conf
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/MailboxSelectorSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/MailboxDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Props.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/PropsImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/PropsAdapter.scala
  akka-actor/src/main/scala/akka/dispatch/Mailboxes.scala
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/typed/index.md
  akka-docs/src/main/paradox/typed/mailboxes.md
Labels: tested

#27176 reduce message sizes for Gossip and DeltaPropagation in ddata, #27175
  akka-distributed-data/src/main/resources/reference.conf
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27355 Test hostname verification
  .gitignore
  akka-remote/src/test/resources/Makefile
  akka-remote/src/test/resources/keystore
  akka-remote/src/test/resources/truststore
  akka-remote/src/test/scala/akka/remote/artery/ArterySpecSupport.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
Labels: tested

#27293 Don't use pattern matching to generate less bytecode.
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
Labels: tested

#27353 Serialization support for wrapped stream refs
  akka-actor-tests/src/test/scala/akka/actor/DynamicAccessSpec.scala
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/scala/akka/actor/DynamicAccess.scala
  akka-actor/src/main/scala/akka/actor/ReflectiveDynamicAccess.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
  akka-docs/src/main/paradox/stream/stream-refs.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/AkkaJacksonModule.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/StreamRefModule.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
  akka-stream/src/main/scala/akka/stream/StreamRefs.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/StreamRefResolverImpl.scala
  build.sbt
Labels: tested

#27383 Fix SurviveNetworkInstabilitySpec
  akka-cluster/src/multi-jvm/scala/akka/cluster/SurviveNetworkInstabilitySpec.scala
Labels: tested

#27388 Fix some grammar in the typed style guide
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27390 Reword the "ask versus ?" typed style docs
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27292 Use a dedicated mismatching indicator instead of null for WidenInterc…
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
Labels: tested

#27362 User serializer for protobuf3
  akka-docs/src/main/paradox/serialization.md
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/test/java/akka/remote/protobuf/v3/ProtobufProtocolV3.java
  akka-remote/src/test/protobuf/ProtobufProtocolV3.proto
  akka-remote/src/test/scala/akka/remote/serialization/ProtobufSerializerSpec.scala
  project/Dependencies.scala
Labels: tested

#27325 streams: clarify how to complete a Source.actorRef in Scaladocs and docs
  akka-docs/src/main/paradox/stream/operators/Source/actorRef.md
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#27404 Persistence typed context
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: 2 - pick next, tested

#27365 Include version error in the docs
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
Labels: tested

#27396 Loosen expectation of TlsTcpWithHostnameVerificationSpec
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
Labels: tested

#27402 Instructions for generating protobuf
  CONTRIBUTING.md
Labels: tested

#27398 Use min of numberOfMessages and buffer size when unstash.
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashBufferSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
Labels: tested

#27393 Reword the "Where to define messages" style docs
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: 2 - pick next, tested

#27407 update mima url
  CONTRIBUTING.md
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
Labels: validating

#27408 Change the onWriteRejected and onWriteFailed signature to pass PersistentRepr for context propagation.
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: 2 - pick next, tested

#27382 Expand on rolling update recommendations, best practices
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/additional/deploy.md
  akka-docs/src/main/paradox/additional/rolling-deploys.md
  akka-docs/src/main/paradox/additional/rolling-updates.md
Labels: 2 - pick next, tested

#27288 Remove source/sink fromPublisher/fromSubscriber
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream-tests/src/test/scala/akka/stream/ActorMaterializerSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: 2 - pick next, tested

#26827 Re-write output stream subscriber as graph stage
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream-tests/src/test/java/akka/stream/io/OutputStreamSinkTest.java
  akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSinkSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/io/IOSinks.scala
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamGraphStage.scala
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSubscriber.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
Labels: 2 - pick next, tested

#27385 Add clarification to doc on cluster cross boundary use of DeathWatch
  akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterWatcherNoClusterWatcheeSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/scala/docs/remoting/RemoteDeploymentDocSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/AttemptSysMsgRedeliverySpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/NewRemoteActorSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteDeploymentDeathWatchSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteFeaturesSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteNodeDeathWatchSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteNodeRestartDeathWatchSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteReDeploymentSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/TransportFailSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/SurviveNetworkPartitionSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/classic/RemoteNodeShutdownAndComesBackSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/routing/RemoteRandomSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/routing/RemoteRoundRobinSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/routing/RemoteScatterGatherSpec.scala
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteSettings.scala
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/test/scala/akka/remote/RemoteFeaturesSpec.scala
  akka-remote/src/test/scala/akka/remote/RemoteRouterSpec.scala
  akka-remote/src/test/scala/akka/remote/TypedActorRemoteDeploySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeploymentSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteRouterSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteWatcherSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/SystemMessageDeliverySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/ActorsLeakSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteDeploymentWhitelistSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteWatcherSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemotingSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
Labels: 2 - pick next, tested

#27401 Deemphasize CallingThreadDispatcher in the docs
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/testing.md
Labels: tested

#27412 OutputStreamGraphStage follow-up fixes
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamGraphStage.scala
Labels: 2 - pick next, tested

#27389 Fix stashing of commands when snapshot is in progress
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/StashingWhenSnapshottingSpec.scala
Labels: 2 - pick next, tested, to-be-backported

#27414 Provide more helpful message when synchronous testing ActorRef is used for asking
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
Labels: tested

#27395 Productionize: GetShardRegionStats returns empty shard set on ask timeout
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-sharding/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster-sharding/src/main/protobuf/ClusterShardingMessages.proto
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardingQueries.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGetStatsSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingQueriesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardingQueriesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializerSpec.scala
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#27415 Fix stashing of commands when snapshot is in progress (#27389)
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/StashingWhenSnapshottingSpec.scala
Labels: backport, tested

#27336 Migration guide for Persistent FSM to typed persistence
  akka-docs/src/main/paradox/persistence-fsm.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/PersistentFSMMigration.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/PersistentFSMMigration.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/PersistentFsmToTypedMigrationCompileOnlyTest.java
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/PersistentFsmToTypedMigrationSpec.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala
  akka-persistence/src/test/java/akka/persistence/fsm/AbstractPersistentFSMTest.java
  akka-persistence/src/test/scala/akka/persistence/fsm/PersistentFSMSpec.scala
Labels: 2 - pick next, tested

#27403 Update example documentation of retry.
  akka-actor/src/main/scala/akka/pattern/RetrySupport.scala
Labels: tested

#27392 Reword the "private messages" typed style docs
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StyleGuideDocExamples.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27424 Fix warnings in akka-actor-typed-tests
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/MonitorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TerminatedSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TransformMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/coexistence/TypedSupervisingUntypedSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/eventstream/EventStreamSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StopSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/DispatchersDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/FaultToleranceDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/SpawnProtocolDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/coexistence/TypedWatchingUntypedSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#27423 Add 'core' and 'dumps' to gitignore
  .gitignore
Labels: tested

#27427 Cleaned up ShardsQueryResult and added region shards query timeout for failure context in logging
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardingQueries.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardingQueriesSpec.scala
Labels: t:cluster-sharding, tested

#27433 Add patterns to @silenced for #27424
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/FaultToleranceDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/SpawnProtocolDocSpec.scala
Labels: tested

#27417 Added GPG and release script prerequisite setup steps explicitly to release doc
  RELEASING.md
Labels: 1 - triaged, 2 - pick next, t:docs, tested

#27436 Fixed akka-stream-tests-tck warnings
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/FilePublisherTest.scala
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/GroupByTest.scala
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/SplitWhenTest.scala
  project/AkkaDisciplinePlugin.scala
Labels: 1 - triaged, tested

#27431 Fix race in AkkaProtocolSpec
  akka-remote/src/test/scala/akka/remote/classic/transport/AkkaProtocolSpec.scala
Labels: tested
