Repository akka/akka, pull requests merged in 2019-09, with the labels that each got.

#27600 Update to Lightbend Community Code of Conduct
  CODE_OF_CONDUCT.md
Labels: tested

#27597 doc: stylish interaction-patterns.md, #24717
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/MailboxDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingReplyCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#27386 Use dilated timeout in enterBarrier
  akka-multi-node-testkit/src/main/scala/akka/remote/testkit/MultiNodeSpec.scala
Labels: tested

#27612 doc: stylish cluster.md, #24717
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/BasicClusterExampleTest.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#27518 Remove Future from typed.ActorSystem.systemActorOf, #27437
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: reviewed, tested

#27523 Use one param list for first two arguments of ActorContext.ask
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/receptionist/ReceptionistApiSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/ReplicatorMessageAdapter.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorMessageAdapter.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/RemoteContextAskSpec.scala
Labels: reviewed, tested

#27596 doc: stylish getting started tutuorial, #24717
  akka-docs/src/main/paradox/typed/guide/tutorial_3.md
  akka-docs/src/main/paradox/typed/guide/tutorial_4.md
  akka-docs/src/main/paradox/typed/guide/tutorial_5.md
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
  akka-docs/src/test/java/jdocs/typed/tutorial_2/IotMain.java
  akka-docs/src/test/java/jdocs/typed/tutorial_2/IotSupervisor.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/DeviceProtocol.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/DeviceTest.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/inprogress1/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/inprogress2/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/inprogress2/DeviceProtocol.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/inprogress3/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceGroup.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceGroupTest.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceManager.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceManagerProtocol.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceManagerTest.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceProtocol.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceTest.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceGroup.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceGroupQuery.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceGroupQueryTest.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceGroupTest.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceManager.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceManagerProtocol.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceManagerTest.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceProtocol.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceTest.java
  akka-docs/src/test/scala/typed/tutorial_3/Device.scala
  akka-docs/src/test/scala/typed/tutorial_3/DeviceInProgress.scala
  akka-docs/src/test/scala/typed/tutorial_4/Device.scala
  akka-docs/src/test/scala/typed/tutorial_4/DeviceGroup.scala
  akka-docs/src/test/scala/typed/tutorial_4/DeviceManager.scala
  akka-docs/src/test/scala/typed/tutorial_5/Device.scala
  akka-docs/src/test/scala/typed/tutorial_5/DeviceGroup.scala
  akka-docs/src/test/scala/typed/tutorial_5/DeviceGroupQuery.scala
  akka-docs/src/test/scala/typed/tutorial_5/DeviceGroupQuerySpec.scala
  akka-docs/src/test/scala/typed/tutorial_5/DeviceManager.scala
Labels: tested

#27613 doc: stylish cluster-sharding.md, #24717
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/HelloWorldPersistentEntityExample.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingReplyCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#27599 restore getting started guide images
  akka-docs/src/main/paradox/typed/guide/actors-intro.md
  akka-docs/src/main/paradox/typed/guide/actors-motivation.md
  akka-docs/src/main/paradox/typed/guide/diagrams/actor_graph.png
  akka-docs/src/main/paradox/typed/guide/diagrams/actor_graph.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/actor_tree_supervision.png
  akka-docs/src/main/paradox/typed/guide/diagrams/actor_tree_supervision.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/arch_boxes_diagram.png
  akka-docs/src/main/paradox/typed/guide/diagrams/arch_boxes_diagram.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/device_manager_tree.png
  akka-docs/src/main/paradox/typed/guide/diagrams/device_manager_tree.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/exception_prop.png
  akka-docs/src/main/paradox/typed/guide/diagrams/exception_prop.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/object_graph.png
  akka-docs/src/main/paradox/typed/guide/diagrams/object_graph.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/object_graph_snakes.png
  akka-docs/src/main/paradox/typed/guide/diagrams/object_graph_snakes.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/seq_chart.png
  akka-docs/src/main/paradox/typed/guide/diagrams/seq_chart.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/seq_chart_multi_thread.png
  akka-docs/src/main/paradox/typed/guide/diagrams/seq_chart_multi_thread.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/seq_chart_thread.png
  akka-docs/src/main/paradox/typed/guide/diagrams/seq_chart_thread.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/serialized_timeline_invariants.png
  akka-docs/src/main/paradox/typed/guide/diagrams/serialized_timeline_invariants.svg
  akka-docs/src/main/paradox/typed/guide/tutorial.md
  akka-docs/src/main/paradox/typed/guide/tutorial_4.md
Labels: tested

#27615 doc: stylish cluster-singleton.md, #24717
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/SingletonCompileOnlyTest.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/SingletonCompileOnlySpec.scala
Labels: reviewed, tested

#27617 Remove mentions of Typed - replaces @@@note of classic/typed with an includes
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-routing.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/distributed-pub-sub.md
  akka-docs/src/main/paradox/fault-tolerance.md
  akka-docs/src/main/paradox/fsm.md
  akka-docs/src/main/paradox/includes.md
  akka-docs/src/main/paradox/index-actors.md
  akka-docs/src/main/paradox/index-classic.md
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/index-network.md
  akka-docs/src/main/paradox/mailboxes.md
  akka-docs/src/main/paradox/persistence-fsm.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/routing.md
  akka-docs/src/main/paradox/scheduler.md
  akka-docs/src/main/paradox/testing.md
  build.sbt
Labels: t:docs, tested

#27537 Learning Akka Typed from Classic, #25624
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/fromclassic/ClassicSample.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/fromclassic/TypedSample.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/fromclassic/ClassicSample.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/fromclassic/TypedSample.scala
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/from-classic.md
  akka-docs/src/main/paradox/typed/index.md
Labels: tested

#27616 doc: stylish actor-discovery.md, #24717
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExample.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/PingSerializer.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExample.scala
  akka-docs/src/main/paradox/typed/actor-discovery.md
Labels: tested

#27619 doc: stylish stash.md, #24717
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StashDocSample.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StashDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StashDocSpec.scala
  akka-docs/src/main/paradox/typed/stash.md
Labels: tested

#27583 Automatically enable eventStream Slf4jLogger for Typed, #26537
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-tests/src/test/scala/akka/config/ConfigSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/DeferredSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/MailboxSelectorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TransformMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed/src/main/resources/reference.conf
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/ManyRecoveriesSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorInterceptorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRecoveryTimeoutSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRetentionSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorTimersSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedEventAdapterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/OptionalSnapshotStoreSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala
Labels: tested

#27587 Include actor path as akkaSource in MDC
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/LoggingEventFilter.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/LoggingEventFilterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/LogMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorMdc.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
Labels: tested

#27610 Optimization of MDC interceptor, #26537
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
Labels: reviewed, tested

#27605 Extension methods to Logger as workaround for overload and varargs problem, #26537
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/LoggerOpsSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/OOIntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/SpawnProtocolDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/package.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-docs/src/test/scala/typed/tutorial_3/Device.scala
  akka-docs/src/test/scala/typed/tutorial_3/DeviceInProgress.scala
  akka-docs/src/test/scala/typed/tutorial_4/Device.scala
  akka-docs/src/test/scala/typed/tutorial_4/DeviceGroup.scala
  akka-docs/src/test/scala/typed/tutorial_5/Device.scala
  akka-docs/src/test/scala/typed/tutorial_5/DeviceGroup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/StashManagement.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: validating

#27622 Scaladoc, comments and test: Change untyped to classic - General Typed docs cleanup
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/GuardianStartupSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/adapter/package.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AkkaClusterTypedSerializer.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/DistributedData.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorFlow.scala
  akka-stream/src/main/scala/akka/stream/Shape.scala
Labels: tested

#27609 Deprecate Cluster Client #27242
  akka-cluster-tools/src/main/scala/akka/cluster/client/ClusterClient.scala
  akka-cluster-tools/src/main/scala/akka/cluster/client/protobuf/ClusterClientMessageSerializer.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/client/ClusterClientHandoverSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/client/ClusterClientSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/client/ClusterClientStopSpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/client/protobuf/ClusterClientMessageSerializerSpec.scala
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27626 Try out Config lib 1.3.5-RC1
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27623 doc: stylish routers.md, #24717
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-docs/src/main/paradox/typed/routers.md
Labels: reviewed, tested

#27591 Remove the Artery flight recorder
  akka-bench-jmh/src/main/scala/akka/remote/artery/FlightRecorderBench.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiNodeTypedClusterSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiNodeClusterSpec.scala
  akka-docs/src/main/paradox/remoting-artery.md
  akka-multi-node-testkit/src/main/mima-filters/2.5.x.backwards.excludes
  akka-multi-node-testkit/src/main/scala/akka/remote/testkit/FlightRecordingSupport.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemotingMultiNodeSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/FanInThrougputSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/FanOutThrougputSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/MaxThroughputSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/TaskRunnerMetrics.scala
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/EventSink.scala
  akka-remote/src/main/scala/akka/remote/artery/FlightRecorder.scala
  akka-remote/src/main/scala/akka/remote/artery/FlightRecorderReader.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/TcpFraming.scala
  akka-remote/src/test/scala/akka/remote/artery/ArteryMultiNodeSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/ArterySpecSupport.scala
  akka-remote/src/test/scala/akka/remote/artery/FlightRecorderSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeployerSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteRouterSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TcpFramingSpec.scala
Labels: reviewed, tested

#27628 Fixed incorrect routing sample comment
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
Labels: tested

#27624 doc: stylish fault-tolerance.md, #24717
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/BubblingSample.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/BubblingSampleTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/supervision/SupervisionCompileOnlyTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/FaultToleranceDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/supervision/SupervisionCompileOnly.scala
  akka-docs/src/main/paradox/typed/fault-tolerance.md
Labels: reviewed, tested

#27637 fix deprecation warning for protobuf enum
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
Labels: 2 - pick next, tested

#27547 Propagate downstream cancellation failures
  akka-bench-jmh/src/main/scala/akka/stream/InterpreterBenchmark.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/ActorGraphInterpreterSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/GraphInterpreterFailureModesSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/GraphInterpreterPortsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/GraphInterpreterSpecKit.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterStressSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterSupervisionSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/LifecycleInterpreterSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/FileSourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphStageTimersSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphUnzipWithSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/MaybeSourceSpec.scala
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/UnzipWithApply.scala.template
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/IOResult.scala
  akka-stream/src/main/scala/akka/stream/SubscriptionWithCancelException.scala
  akka-stream/src/main/scala/akka/stream/impl/LazySource.scala
  akka-stream/src/main/scala/akka/stream/impl/MaybeSource.scala
  akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
  akka-stream/src/main/scala/akka/stream/impl/SetupStage.scala
  akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSource.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphStages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSources.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSource.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FileIO.scala
  akka-stream/src/main/scala/akka/stream/javadsl/StreamConverters.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/CoupledTerminationFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FileIO.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: 2 - pick next, tested

#27641 unmoored doc comment in PhasedFusingActorMaterializer
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
Labels: 2 - pick next, tested

#27644 rename the new Materializer.create to createMaterializer, #27642
  akka-docs/src/test/java/jdocs/stream/FlowDocTest.java
  akka-docs/src/test/java/jdocs/stream/HubDocTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkAsJavaStreamSpec.scala
  akka-stream-typed/src/test/java/akka/stream/typed/javadsl/CustomGuardianAndMaterializerTest.java
  akka-stream/src/main/scala/akka/stream/Materializer.scala
Labels: 2 - pick next, tested

#27643 StreamRefs cancellation behavior
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#27645 watchTermination now fails the future on downstream failure
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeAdhocSource.scala
Labels: 2 - pick next, tested

#27646 Remove left over mention of using materializer for settings
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
Labels: 2 - pick next, tested

#27653 assemblyMergeStrategy first for logback-test.xml, #27652
  project/MultiNode.scala
Labels: tested

#27655 Fix ByteStringSpec for Scala 2.13.1
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
Labels: tested

#27657 Consolidate Paradox settings, add includes workaround #27656
  build.sbt
  project/Paradox.scala
Labels: t:docs, tested

#27586 Bump up dependencies.
  akka-docs/src/test/java/jdocs/stream/TwitterStreamQuickstartDocTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeGlobalRateLimit.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeMultiGroupByTest.java
  akka-remote/src/test/java/akka/remote/protobuf/v3/ProtobufProtocolV3.java
  project/Dependencies.scala
  project/JavaFormatter.scala
  project/plugins.sbt
Labels: tested

#27391 ActorRefResolver: use ref's system if available
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorRefResolverSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorRefResolver.scala
Labels: tested

#27668 Multi-jvm assembly: deduplicate: META-INF default file #27667
  project/MultiNode.scala
Labels: tested

#27666 Failed: MultiDcClusterSharding #27663
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/MultiDcClusterShardingSpec.scala
Labels: tested

#27669 Improve tiny readability in mailboxes doc
  akka-docs/src/main/paradox/typed/mailboxes.md
Labels: tested

#27658 Fix typo in CoupledTerminationFlow docs
  akka-stream/src/main/scala/akka/stream/javadsl/CoupledTerminationFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/CoupledTerminationFlow.scala
Labels: tested

#27654 Akka Stream log operator documentation fix
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Log.scala
Labels: tested

#27674 remove todo in Behavior.start
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
Labels: tested

#27664 Update to paradox 0.6.5
  project/ParadoxSupport.scala
  project/plugins.sbt
Labels: tested

#27558 Update to MiMa 0.6.0
  akka-actor/src/main/mima-filters/2.5.12.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.17.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.24.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.25.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster-metrics/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster-metrics/src/main/mima-filters/2.5.24.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.5.24.backwards.excludes
  akka-cluster-tools/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster-tools/src/main/mima-filters/2.5.24.backwards.excludes
  akka-cluster/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster/src/main/mima-filters/2.5.24.backwards.excludes
  akka-coordination/src/main/mima-filters/2.5.24.backwards.excludes
  akka-discovery/src/main/mima-filters/2.5.19.backwards.excludes
  akka-discovery/src/main/mima-filters/2.5.24.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.5.17.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.5.21.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.5.24.backwards.excludes
  akka-multi-node-testkit/src/main/mima-filters/2.5.17.backwards.excludes
  akka-multi-node-testkit/src/main/mima-filters/2.5.24.backwards.excludes
  akka-persistence-query/src/main/mima-filters/2.5.17.backwards.excludes
  akka-persistence-query/src/main/mima-filters/2.5.24.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.17.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.24.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.25.backwards.excludes
  akka-remote/src/main/mima-filters/2.5.17.backwards.excludes
  akka-remote/src/main/mima-filters/2.5.24.backwards.excludes
  akka-remote/src/main/mima-filters/2.5.25.backwards.excludes
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.17.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.24.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.4.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-testkit/src/main/mima-filters/2.5.17.backwards.excludes
  akka-testkit/src/main/mima-filters/2.5.24.backwards.excludes
  akka-testkit/src/main/mima-filters/2.5.x.backwards.excludes
  project/MiMa.scala
  project/plugins.sbt
Labels: tested

#27511 API changes related to DataDeleted, #27371
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/internal/ReplicatorBehavior.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/Replicator.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/ReplicatorMessageAdapter.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/Replicator.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorMessageAdapter.scala
  akka-cluster-typed/src/test/java/akka/cluster/ddata/typed/javadsl/ReplicatorTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorChaosSpec.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27684 [backport] Update to paradox 0.6.5
  project/ParadoxSupport.scala
  project/plugins.sbt
Labels: backport, tested

#27695 Forward port: Added ttl configs for AsynchDnsResolve #27578
  akka-actor-tests/src/test/scala/akka/io/dns/AsyncDnsResolverIntegrationSpec.scala
  akka-actor-tests/src/test/scala/akka/io/dns/DnsSettingsSpec.scala
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsResolverSpec.scala
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/io/dns/DnsSettings.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala
  akka-actor/src/main/scala/akka/io/dns/internal/package.scala
Labels: tested

#27686 Upgrade to akka-paradox 0.24 with search box transparency fix
  project/plugins.sbt
Labels: tested

#27682 Update scalafmt-core to 2.0.1
  .scalafmt.conf
Labels: tested

#27711 Rename stream detached exception naming
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#27675 Fixes to one of the tests in FlowGroupBySpec
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala
Labels: tested

#27670 Avoid publication of duplicate UnreachableDataCenter, #24955
  akka-cluster/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDomainEventSpec.scala
Labels: 2 - pick next, tested

#27692 Cluster sharding with remember entities (persistence) must setup shared journal
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesSpec.scala
Labels: 2 - pick next, tested

#27665 Use ActorSystem's ThreadFactory for the Aeron threads, #27603
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/test/scala/akka/remote/DaemonicSpec.scala
Labels: 2 - pick next, tested

#27718 Fix Java snippet (was partially showing on scala)
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#27719 withinTimeRange not working correctly in BackoffOnRestart
  akka-actor-tests/src/test/scala/akka/pattern/BackoffOnRestartSupervisorSpec.scala
  akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/HandleBackoff.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnRestartSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnStopSupervisor.scala
Labels: 2 - pick next, tested, to-be-backported

#27727 withinTimeRange in BackoffOnRestart fixed
  akka-actor-tests/src/test/scala/akka/pattern/BackoffOnRestartSupervisorSpec.scala
  akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/HandleBackoff.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnRestartSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnStopSupervisor.scala
Labels: backport, tested

#27721 Update sbt-scalafmt to 2.0.5
  project/plugins.sbt
Labels: tested

#27722 Align passivation method names
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
Labels: tested

#27717 doc: stylish persistence.md and persistence-snapshot.md, #24717
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithMutableState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithNullState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithOptionState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BlogPostEntity.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BlogPostExample.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/StashingExample.java
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BlogPostEntity.scala
Labels: tested

#27708 WIP cluster usage - Swap content from Classic pages to Typed #24717
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/additional/deploy.md
  akka-docs/src/main/paradox/additional/observability.md
  akka-docs/src/main/paradox/additional/operations.md
  akka-docs/src/main/paradox/additional/osgi.md
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/cluster-dc.md
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/common/cluster.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/distributed-pub-sub.md
  akka-docs/src/main/paradox/includes/cluster.md
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/stream/stream-refs.md
  akka-docs/src/main/paradox/typed/choosing-cluster.md
  akka-docs/src/main/paradox/typed/cluster-membership.md
  akka-docs/src/main/paradox/typed/cluster-specification.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/failure-detector.md
  akka-docs/src/main/paradox/typed/index-cluster.md
  project/Paradox.scala
Labels: 2 - pick next, tested

#27744 Code example for collect and collectType
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/collect.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/collectType.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Collect.scala
Labels: tested

#27733 Eliminate race in multi node StreamRefSpec
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala
Labels: tested

#27704 Minimal docs for rolling migration from classic sharding to typed
  akka-docs/src/main/paradox/additional/rolling-updates.md
Labels: tested

#27706 Extra caveat around state in Java EventSourcedBehavior
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#27214 Examples of response aggregator and latency tail chopping
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/Aggregator.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/AggregatorTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/TailChopping.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/Aggregator.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/AggregatorSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/TailChopping.scala
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/auction/AuctionEntity.java
Labels: tested

#27738 Consolidated passivation check on settings used in region and shard
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingSettingsSpec.scala
Labels: t:cluster-sharding, tested

#27755 Upgrade scalafix plugin
  project/plugins.sbt
Labels: tested

#27756 Use git from the path instead of jgit/sbt-git
  project/Whitesource.scala
  project/plugins.sbt
Labels: tested

#27752 Split async and sync testing into separate pages, #24717
  akka-docs/src/main/paradox/typed/from-classic.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-docs/src/main/paradox/typed/testing-async.md
  akka-docs/src/main/paradox/typed/testing-sync.md
  akka-docs/src/main/paradox/typed/testing.md
Labels: tested

#27747 Add PreRestart to typed docs
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/supervision/SupervisionCompileOnlyTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/supervision/SupervisionCompileOnly.scala
  akka-docs/src/main/paradox/typed/fault-tolerance.md
Labels: tested

#27748 doc: stylish dispatchers.md, #24717
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/test/java/jdocs/actor/typed/BlockingActor.java
  akka-docs/src/test/java/jdocs/actor/typed/PrintActor.java
  akka-docs/src/test/java/jdocs/actor/typed/SeparateDispatcherCompletionStageActor.java
  akka-docs/src/test/scala/docs/actor/typed/BlockingActor.scala
  akka-docs/src/test/scala/docs/actor/typed/BlockingDispatcherSample.scala
  akka-docs/src/test/scala/docs/actor/typed/DispatcherDocSpec.scala
  akka-docs/src/test/scala/docs/actor/typed/PrintActor.scala
Labels: tested

#27746 doc: stylish fsm.md, #24717
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/FSMDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/FSMDocSpec.scala
  akka-docs/src/main/paradox/typed/fsm.md
Labels: tested

#27659 doc: stylish distributed-data.md, #24717
  akka-cluster-typed/src/test/java/akka/cluster/ddata/typed/javadsl/ReplicatorTest.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/ddata/typed/javadsl/ReplicatorDocSample.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/ddata/typed/javadsl/ReplicatorDocTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorCompileOnlyTest.scala
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/ddata/typed/scaladsl/ReplicatorDocSpec.scala
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: tested

#27759 Migration guide entry for new config resolution
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27672 remove deprecated actorRefWithAck in akka-stream-typed
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorSink.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorSink.scala
Labels: 2 - pick next, tested

#27740 New base cluster sharding multi-node/jvm test to cleanup and tighten testing
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingConfig.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
Labels: tested

#27764 Cluster Sharding: General Typed docs cleanup after all API changes
  akka-docs/src/main/paradox/additional/osgi.md
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/cluster-dc.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/includes/cluster.md
  akka-docs/src/main/paradox/stream/stream-refs.md
  akka-docs/src/main/paradox/typed/cluster-concepts.md
  akka-docs/src/main/paradox/typed/cluster-membership.md
  akka-docs/src/main/paradox/typed/cluster-sharding-concepts.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/index-cluster.md
Labels: tested

#27676 Update sbt-whitesource to 0.1.17
  project/plugins.sbt
Labels: tested

#27707 Final removal of ActorPublisher and ActorSubscriber, #26187
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowTakeSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/actor/ActorPublisher.scala
  akka-stream/src/main/scala/akka/stream/actor/ActorSubscriber.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorProcessor.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorPublisher.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorSubscriberMessage.scala
  akka-stream/src/main/scala/akka/stream/impl/FanIn.scala
  akka-stream/src/main/scala/akka/stream/impl/Modules.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#27781 Remove ExpectingReply
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/EventSourcedEntity.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ClusterShardingPersistenceTest.java
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ShardingEventSourcedEntityWithEnforcedRepliesCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithMutableState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithNullState.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithOptionState.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/ExpectingReply.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EffectImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/auction/AuctionCommand.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/auction/AuctionEntity.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorReplySpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
Labels: 2 - pick next, tested

#27778 Update protobuf-java to 3.9.2
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27790 Use japi lambdas where it makes sense
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/EffectfulActorContext.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/BehaviorTestKitTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ReceiveBuilderTest.java
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorRefResolver.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Extensions.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AskPattern.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/BehaviorBuilder.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/StashBuffer.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/ReplicatorMessageAdapter.scala
Labels: 2 - pick next, tested

#27780 fix JsonFraming to accept multiple top-level arrays
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/JsonFramingSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/JsonObjectParser.scala
Labels: tested

#27701 wait for async excess events when occurrences 0
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/LoggingEventFilterImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/LoggingEventFilter.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/LoggingEventFilter.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/TestAppenderSpec.scala
Labels: 2 - pick next, tested

#27762 doc: Cleanup serialization.md, #24717
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/serialization-classic.md
  akka-docs/src/main/paradox/serialization.md
  akka-docs/src/main/paradox/typed/actor-discovery.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/test/java/jdocs/serialization/SerializationDocTest.java
  akka-docs/src/test/scala/docs/serialization/SerializationDocSpec.scala
Labels: 2 - pick next, tested

#27771 Typed actorsystem clarifications
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/coexisting.md
  akka-docs/src/main/paradox/typed/from-classic.md
  akka-docs/src/main/paradox/typed/guide/diagrams/actor_top_tree.png
  akka-docs/src/main/paradox/typed/guide/diagrams/actor_top_tree.svg
  akka-docs/src/main/paradox/typed/guide/diagrams/actor_tree_supervision.png
  akka-docs/src/main/paradox/typed/guide/diagrams/actor_tree_supervision.svg
  akka-docs/src/main/paradox/typed/guide/tutorial_1.md
  akka-docs/src/main/paradox/typed/testing-async.md
Labels: 2 - pick next, tested

#27796 update to Jackson 2.9.10
  project/Dependencies.scala
Labels: tested

#27784 Cross link also from Typed doc pages to Classic
  akka-docs/src/main/paradox/cluster-routing.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/fault-tolerance.md
  akka-docs/src/main/paradox/fsm.md
  akka-docs/src/main/paradox/mailboxes.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/routing.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/fault-tolerance.md
  akka-docs/src/main/paradox/typed/fsm.md
  akka-docs/src/main/paradox/typed/mailboxes.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/testing.md
Labels: 2 - pick next, t:docs, tested

#27660 LogCapture in more tests
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/coexistence/ClassicSupervisingTypedSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/JoinConfigCompatCheckerClusterShardingSpec.scala
Labels: tested

#27797 Some follow up on the japi lambda changes
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/BehaviorBuilder.scala
Labels: tested

#27725 Remove EventSourcedEntity, #27724
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/EventSourcedEntity.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/EventSourcedEntity.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/MultiDcClusterShardingSpec.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ClusterShardingPersistenceTest.java
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ShardingEventSourcedEntityWithEnforcedRepliesCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithMutableState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithNullState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/HelloWorldEventSourcedEntityExampleTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/HelloWorldPersistentEntityExample.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingStateSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/EntityTypeKeySpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithOptionState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/HelloWorldEventSourcedEntityExampleSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/HelloWorldPersistentEntityExample.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/from-classic.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PersistenceId.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BlogPostEntity.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/PersistenceIdSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BlogPostEntity.scala
  build.sbt
Labels: 2 - pick next, tested

#27635 BlockingIODispatcher actually not needed
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
Labels: 2 - pick next, tested

#27787 Adding select scala steward ignores to not receive auto-PR updates on a few dependencies
  .scala-steward.conf
Labels: t:build, tested

#27783 Distributed Data: General Typed docs cleanup after all API changes
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/ddata/typed/javadsl/ReplicatorDocSample.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/ddata/typed/scaladsl/ReplicatorDocSpec.scala
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: 2 - pick next, t:cluster-ddata, t:docs, tested

#27779 Cleanup persistence docs, #24717
  akka-docs/src/main/paradox/general/message-delivery-reliability.md
  akka-docs/src/main/paradox/persistence-journals.md
  akka-docs/src/main/paradox/persistence-plugins.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/test/java/jdocs/persistence/PersistenceQueryDocTest.java
  akka-docs/src/test/java/jdocs/persistence/ResumableProjectionExample.java
  akka-docs/src/test/scala/docs/persistence/query/PersistenceQueryDocSpec.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: 2 - pick next, tested

#27723 System materializer guardian
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-stream-tests/src/test/scala/akka/stream/SystemMaterializerSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/TraversalBuilderSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/resources/reference.conf
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/Materializer.scala
  akka-stream/src/main/scala/akka/stream/SystemMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/MaterializerGuardian.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: 2 - pick next, tested

#27801 Cluster Singleton - General Typed docs cleanup after all API changes …
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
Labels: 2 - pick next, tested

#27765 General concepts to typed
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/fault-tolerance.md
  akka-docs/src/main/paradox/general/actor-systems.md
  akka-docs/src/main/paradox/general/actors.md
  akka-docs/src/main/paradox/general/addressing.md
  akka-docs/src/main/paradox/general/configuration.md
  akka-docs/src/main/paradox/general/jmm.md
  akka-docs/src/main/paradox/general/message-delivery-reliability.md
  akka-docs/src/main/paradox/general/remoting.md
  akka-docs/src/main/paradox/general/supervision.md
  akka-docs/src/main/paradox/images/actor-paths-overview.png
  akka-docs/src/main/paradox/index-actors.md
  akka-docs/src/main/paradox/index-classic.md
  akka-docs/src/main/paradox/index-utilities-classic.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/routing.md
  akka-docs/src/main/paradox/stream/stream-error.md
  akka-docs/src/main/paradox/supervision-classic.md
  akka-docs/src/main/paradox/typed/fault-tolerance.md
  akka-docs/src/test/java/jdocs/actor/typed/SharedMutableStateDocTest.java
  akka-docs/src/test/java/jdocs/config/ConfigDoc.java
  akka-docs/src/test/java/jdocs/config/ConfigDocTest.java
  akka-docs/src/test/scala/docs/actor/typed/SharedMutableStateDocSpec.scala
  akka-docs/src/test/scala/docs/config/ConfigDocSpec.scala
Labels: 2 - pick next, tested

#27820 more cross-links to Classic docs, #24717
  akka-docs/src/main/paradox/typed/actor-discovery.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/fault-tolerance.md
  akka-docs/src/main/paradox/typed/fsm.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-docs/src/main/paradox/typed/mailboxes.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/routers.md
  akka-docs/src/main/paradox/typed/stash.md
  akka-docs/src/main/paradox/typed/testing-async.md
  akka-docs/src/main/paradox/typed/testing-sync.md
  akka-docs/src/main/paradox/typed/testing.md
Labels: tested

#27822 doc: duplicate singleton lease section
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
Labels: tested

#27812 Make running mima in PrValidation optional (default enabled)
  project/ValidatePullRequest.scala
Labels: tested

#27818 Add HTML meta page descriptions for the most important landing pages
  akka-docs/src/main/paradox/additional/deploying.md
  akka-docs/src/main/paradox/additional/operations.md
  akka-docs/src/main/paradox/additional/packaging.md
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
  akka-docs/src/main/paradox/coordination.md
  akka-docs/src/main/paradox/discovery/index.md
  akka-docs/src/main/paradox/extending-akka.md
  akka-docs/src/main/paradox/general/actor-systems.md
  akka-docs/src/main/paradox/general/actors.md
  akka-docs/src/main/paradox/general/addressing.md
  akka-docs/src/main/paradox/general/jmm.md
  akka-docs/src/main/paradox/general/message-delivery-reliability.md
  akka-docs/src/main/paradox/general/supervision.md
  akka-docs/src/main/paradox/io-tcp.md
  akka-docs/src/main/paradox/io-udp.md
  akka-docs/src/main/paradox/multi-jvm-testing.md
  akka-docs/src/main/paradox/multi-node-testing.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/project/migration-guides.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/scheduler.md
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-docs/src/main/paradox/serialization.md
  akka-docs/src/main/paradox/stream/index.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/cluster-membership.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/fsm.md
  akka-docs/src/main/paradox/typed/index-cluster.md
  akka-docs/src/main/paradox/typed/index.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: t:docs, tested

#27734 Update to Scala 2.12.10
  akka-actor/src/main/scala-2.13-/akka/util/ByteString.scala
  project/Dependencies.scala
  project/Doc.scala
Labels: tested

#27826 Fix Travis: Update AdoptOpenJDK
  .travis.yml
Labels: backport, tested
