Repository akka/akka, pull requests merged in 2019-10, with the labels that each got.

#27830 Remove unnecessary dependency
  build.sbt
Labels: tested

#27817 Define ScmInfo
  project/AkkaBuild.scala
Labels: tested

#27530 Same logic for onRecoveryFailure in ReplayingSnapshot as ReplayingEvents, #27526
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
Labels: tested

#27831 Update scalafmt-core to 2.1.0
  .scalafmt.conf
  akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala
  akka-docs/src/test/scala/docs/stream/TwitterStreamQuickstartDocSpec.scala
  akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbStore.scala
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-remote/src/main/scala/akka/remote/artery/Control.scala
  akka-stream/src/main/scala/akka/stream/KillSwitch.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefBackpressureSource.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/impl/StreamSubscriptionTimeout.scala
Labels: tested

#27833 Make scm section consistent with previous releases
  project/AkkaBuild.scala
Labels: tested

#27825 Fix ByteStringSpec for Scala 2.13.1
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
Labels: backport, tested

#27829 Try to get root cause of timeout in ReplicatorPruningSpec
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorPruningSpec.scala
Labels: tested

#26935 Update sbt to 1.3.2
  .sbtopts
  project/build.properties
  project/plugins.sbt
Labels: tested

#27819 A few more removals of use of typed, where makes sense.
  akka-docs/src/main/paradox/extending-akka.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27813 typo
  akka-discovery/src/main/resources/reference.conf
Labels: tested

#27810 Deprecate akka.Main
  akka-actor/src/main/scala/akka/Main.scala
  akka-docs/src/main/paradox/additional/packaging.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27808 Remove LogMarker leftover
  akka-actor-typed/src/main/scala/akka/actor/typed/LogOptions.scala
Labels: tested

#27685 Convert 2.5.x MiMa excludes to subdirectory style
  CONTRIBUTING.md
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-cluster-metrics/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-cluster-sharding/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-cluster-tools/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-cluster/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-coordination/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-distributed-data/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-multi-node-testkit/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-persistence-query/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-persistence/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-testkit/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
Labels: tested

#27731 Only allow deserialization for know classes in ProtobufSerializer, #27730
  akka-actor/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/serialization/ProtobufSerializer.scala
  akka-remote/src/test/scala/akka/remote/serialization/ProtobufSerializerSpec.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
Labels: tested, to-be-backported

#27843 Clarify ORMap docs on replacing entries
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: tested

#27821 doc: improve docs of Cluster joining
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/BasicClusterExampleTest.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/includes/cluster.md
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#27846 doc: use ref links
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/additional/operations.md
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-routing.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
  akka-docs/src/main/paradox/distributed-pub-sub.md
  akka-docs/src/main/paradox/event-bus.md
  akka-docs/src/main/paradox/fsm.md
  akka-docs/src/main/paradox/general/message-delivery-reliability.md
  akka-docs/src/main/paradox/io-tcp.md
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/multi-node-testing.md
  akka-docs/src/main/paradox/persistence-fsm.md
  akka-docs/src/main/paradox/persistence-plugins.md
  akka-docs/src/main/paradox/persistence-schema-evolution.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/routing.md
  akka-docs/src/main/paradox/stream/stream-dynamic.md
  akka-docs/src/main/paradox/stream/stream-graphs.md
  akka-docs/src/main/paradox/stream/stream-quickstart.md
  akka-docs/src/main/paradox/stream/stream-refs.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/cluster-concepts.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/guide/actors-motivation.md
  akka-docs/src/main/paradox/typed/guide/modules.md
  akka-docs/src/main/paradox/typed/guide/tutorial_3.md
Labels: tested

#27814 Jackson 2.10.0
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
  project/Dependencies.scala
Labels: tested

#27842 Don't duplicate CrossJava logic
  project/AkkaBuild.scala
  project/CrossJava.scala
  project/Doc.scala
  project/Jdk9.scala
  project/JdkOptions.scala
Labels: tested

#27865 move AdapterExtension to internal package
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/AdapterExtension.scala
Labels: tested

#27862 supervision in AdapterClusterImpl
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterImpl.scala
Labels: tested

#27832 doc: Source.maybe, #25468
  akka-docs/src/main/paradox/stream/operators/Source/maybe.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/SourceOperators.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#27849 Only allow deserialization for know classes in ProtobufSerializer, #27730 (backport)
  akka-actor/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/serialization/ProtobufSerializer.scala
  akka-remote/src/test/scala/akka/remote/serialization/ProtobufSerializerSpec.scala
Labels: backport, tested

#27872 changing wording in docs. From 'migrating' to 'upgrade'
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27873 Docs: add project info boxes
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/coordination.md
  akka-docs/src/main/paradox/discovery/index.md
  akka-docs/src/main/paradox/distributed-pub-sub.md
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/multi-node-testing.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/stream/index.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/stream.md
  akka-docs/src/main/paradox/typed/testing.md
  project/AkkaBuild.scala
  project/plugins.sbt
  project/project-info.conf
Labels: tested

#27870 doc: improve receptionist docs, #25895
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExample.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExample.scala
  akka-docs/src/main/paradox/typed/actor-discovery.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
Labels: tested

#27864 adapter for Scheduler
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/AdapterTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/SchedulerAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Adapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/adapter/package.scala
Labels: tested

#27874 doc: java Duration in supervision example
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/supervision/SupervisionCompileOnlyTest.java
Labels: tested

#27866 Incorporate some classic actor docs in Actors Typed where applicable
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/general/supervision.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/fault-tolerance.md
Labels: t:docs, t:typed, tested

#27868 doc: describe number-of-shards config, #26920
  akka-cluster-sharding-typed/src/main/resources/reference.conf
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster-sharding-concepts.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#27869 Document how to run typed sharding with roles
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#27876 doc: more links to ide tips
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/guide/tutorial.md
Labels: tested

#27880 Actor discovery: Don't start a page with referencing and describing h…
  akka-docs/src/main/paradox/general/addressing.md
  akka-docs/src/main/paradox/typed/actor-discovery.md
Labels: tested

#27890 Spell BehaviorTestKit correctly
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: tested

#27887 Updates external serialization documentation #27886
  akka-docs/src/main/paradox/serialization.md
Labels: tested

#27894 typo, user guardian instead of guardian
  akka-docs/src/main/paradox/typed/guide/tutorial_1.md
Labels: tested

#27867 doc: separate page for reference.conf listing, #27798
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/cluster-routing.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/general/configuration-reference.md
  akka-docs/src/main/paradox/general/configuration.md
  akka-docs/src/main/paradox/general/index.md
  akka-docs/src/main/paradox/multi-node-testing.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#27878 Add system creation with config and props
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
Labels: tested

#27896 Updates external serialization documentation #27886
  akka-docs/src/main/paradox/serialization.md
Labels: backport, tested

#27841 Update mockito-core to 3.1.0
  project/Dependencies.scala
Labels: tested

#27809 Remove deprecated secure cookie
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes/_existing.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/transport/AkkaPduCodec.scala
  akka-remote/src/main/scala/akka/remote/transport/AkkaProtocolTransport.scala
  akka-remote/src/test/scala/akka/remote/RemoteConfigSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemotingSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/transport/AkkaProtocolSpec.scala
Labels: tested

#27901 Migrate streams doc under typed to operators
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRef.md
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRef.md
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/main/paradox/stream/stream-integrations.md
  akka-docs/src/main/paradox/typed/index.md
  akka-docs/src/main/paradox/typed/stream.md
  project/StreamOperatorsIndexGenerator.scala
Labels: tested

#27823 Add a sample for Source.unfoldResource
  akka-docs/src/main/paradox/stream/operators/Source/unfoldResource.md
  akka-docs/src/test/java/jdocs/stream/operators/source/UnfoldResource.java
  akka-docs/src/test/scala/docs/stream/operators/source/UnfoldResource.scala
Labels: tested

#27885 Update sbt-paradox-project-info to 1.1.3
  project/plugins.sbt
Labels: tested

#27895 doc: some more docs for PreRestart signal
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/fault-tolerance.md
  akka-docs/src/main/paradox/typed/from-classic.md
Labels: tested

#27891 doc: move Coordinated Shutdown to a separate page
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/coordinated-shutdown.md
  akka-docs/src/main/paradox/general/actor-systems.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/stream/operators/Source/unfoldResource.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/index.md
Labels: tested

#27871 Note sharding persistent mode deprecation in migration guide
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27892 Add Intro section to actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
Labels: tested

#27898 doc: Watching Actors, #27897
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/GracefulStopDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/GracefulStopDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/MessageAndSignals.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/fault-tolerance.md
  akka-docs/src/main/paradox/typed/from-classic.md
Labels: tested

#27916 doc: format attributes table in migration-guide, #27858
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27902 doc: Add page for testing of EventSourcedBehavior, #27899
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleDocTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleDocSpec.scala
  akka-docs/src/main/paradox/typed/persistence-testing.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/testing.md
Labels: tested

#27691 Update sbt-paradox-apidoc to 0.3
  project/plugins.sbt
Labels: tested

#27900 Added mapError to SourceWithContext and FlowWithContext.
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
Labels: tested

#27893 crossPaths back to default
  project/Publish.scala
  project/Release.scala
Labels: 2 - pick next, tested

#27920 Standardized log level highlighting
  akka-docs/src/main/paradox/logging.md
Labels: tested

#27889 Prepare for other compression algorithms in JacksonSerializer, #27066
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
Labels: tested

#27928 Fix broken persistent fsm link
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27911 Harden DowningProviderSpec, and detect terminated before initialized, #27840
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-cluster/src/test/scala/akka/cluster/DowningProviderSpec.scala
Labels: 2 - pick next, tested

#27828 Update sbt-scalafmt to 2.0.6
  project/plugins.sbt
Labels: tested

#27827 Update scalacheck to 1.14.2
  project/Dependencies.scala
Labels: tested

#27927 doc: ReceiveBuilder is optional, #25755
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27930 Travis: cache coursier library directory
  .travis.yml
Labels: tested

#27926 doc: clarify side effect in event handler, #25720
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#27907 doc: Diagrams for intro and interaction examples
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/images/adapted-response.png
  akka-docs/src/main/paradox/typed/images/aggregator.png
  akka-docs/src/main/paradox/typed/images/ask-from-actor.png
  akka-docs/src/main/paradox/typed/images/ask-from-outside.png
  akka-docs/src/main/paradox/typed/images/chat-room.png
  akka-docs/src/main/paradox/typed/images/fire-forget.png
  akka-docs/src/main/paradox/typed/images/hello-world1.png
  akka-docs/src/main/paradox/typed/images/hello-world2.png
  akka-docs/src/main/paradox/typed/images/per-session-child.png
  akka-docs/src/main/paradox/typed/images/request-response.png
  akka-docs/src/main/paradox/typed/images/sharded-response.png
  akka-docs/src/main/paradox/typed/images/tail-chopping.png
  akka-docs/src/main/paradox/typed/images/timer.png
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#27879 Justify why pool/group routers have different defaults
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#27917 make getContext and createReceive protocted in javadsl.AbstractBehavior
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AbstractBehavior.scala
Labels: tested

#27915 doc: minor cleanup of mailboxes.md
  akka-docs/src/main/paradox/mailboxes.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/mailboxes.md
Labels: tested

#27912 doc: Add pipeToSelf in interaction-patterns.md, #27877
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-docs/src/main/paradox/typed/images/pipe-to-self.png
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#27936 Revert: Harden DowningProviderSpec, and detect terminated before initialized, #27840
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-cluster/src/test/scala/akka/cluster/DowningProviderSpec.scala
Labels: tested

#27925 don't crossPaths for akka-protobuf-v3, #27921
  build.sbt
Labels: 2 - pick next, tested

#27910 Some tweaks to the Cluster Client to gRPC migration notes
  akka-docs/src/main/paradox/cluster-client.md
Labels: tested

#27860 Bugfix/akka 27647
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested, to-be-backported

#27939 doc: small improvements of core cluster pages
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/BasicClusterExampleTest.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
  akka-docs/src/main/paradox/includes/cluster.md
  akka-docs/src/main/paradox/typed/cluster-concepts.md
  akka-docs/src/main/paradox/typed/cluster-membership.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/failure-detector.md
  akka-docs/src/main/paradox/typed/index-cluster.md
  project/Paradox.scala
Labels: tested

#27857 Make SingleConsumerMultiProducer the default mail box for typed
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/adpater/PropsAdapterSpec.scala
  akka-actor-typed/src/main/resources/reference.conf
  akka-actor-typed/src/main/scala/akka/actor/typed/Props.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/PropsAdapter.scala
  akka-bench-jmh-typed/README.md
  akka-bench-jmh-typed/src/main/scala/akka/BenchRunner.scala
  akka-bench-jmh/README.md
  akka-bench-jmh/src/main/resources/logback-test.xml
  akka-bench-jmh/src/main/scala/akka/actor/typed/TypedActorBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/actor/typed/TypedBenchmarkActors.scala
  akka-bench-jmh/src/main/scala/akka/actor/typed/TypedForkJoinActorBenchmark.scala
  akka-docs/src/main/paradox/mailboxes.md
  akka-docs/src/main/paradox/typed/mailboxes.md
  build.sbt
Labels: 2 - pick next, tested

#27940 Fix state.nonEmpty check when starting HandOffStopper#27647 (#27860)
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: backport, tested

#27913 doc: fix Persistence ToC
  akka-docs/src/main/paradox/index.md
  akka-docs/src/main/paradox/typed/index-persistence.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#27938 Ignore length field value when provided computeFrameSize (#27884)
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FramingSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Framing.scala
Labels: tested, to-be-backported

#27882 use CBOR in some tests instead of custom serializers
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/PingSerializerExampleTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorSystemSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterSingletonApiSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/RemoteContextAskSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/RemoteMessageSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/PingSerializer.scala
Labels: tested

#27834 harden access to outboundControlIngress, #27732
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
Labels: 2 - pick next, tested, to-be-backported

#27943 harden access to outboundControlIngress
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
Labels: backport, tested

#27941 Ignore length field value when provided computeFrameSize
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FramingSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Framing.scala
Labels: backport, tested

#27909 adjust dependencies to akka-protobuf-v3, #27661
  build.sbt
Labels: tested

#27942 Go back to taking a Behavior to typed pool routers
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/RoutersTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#27848 More tolerance in GraphMergePrioritizedSpec
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergePrioritizedSpec.scala
Labels: tested

#27919 Typed docs: some spelling and language fixes
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-docs/src/main/paradox/typed/actor-discovery.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-docs/src/main/paradox/typed/routers.md
  akka-docs/src/main/paradox/typed/stash.md
  project/Paradox.scala
Labels: t:docs, tested

#27945 Akka Paradox theme 0.25 (with transitive Paradox, apidoc, project-info)
  project/plugins.sbt
Labels: tested

#27962 Eliminate race in multi node StreamRefSpec, #27957
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
Labels: backport, tested

#27953 rename PersistenceId.apply to PersistenceId.ofUniqueId, #27924
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterSingletonPersistenceSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PersistenceId.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/ManyRecoveriesSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/PersistenceIdSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/StashingWhenSnapshottingSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorInterceptorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRecoveryTimeoutSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorReplySpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRetentionSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorTimersSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedEventAdapterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSnapshotAdapterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/OptionalSnapshotStoreSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotMutableStateSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/MovieWatchList.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/PersistentFsmToTypedMigrationSpec.scala
Labels: tested

#27905 Update agrona to 1.0.8
  project/Dependencies.scala
Labels: tested

#27952 Update aeron-client, aeron-driver to 1.22.0
  project/Dependencies.scala
Labels: tested

#27963 missing barrier in RemoteFeaturesSpec, #27838
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteFeaturesSpec.scala
Labels: tested

#27845 Avoid using mockito in akka-cluster-sharding
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/fold.md
  project/Dependencies.scala
Labels: tested

#27811 Deprecate JavaLogger (java.utl.logging)
  akka-actor-tests/src/test/scala/akka/event/jul/JavaLoggerSpec.scala
  akka-actor/src/main/scala/akka/event/jul/JavaLogger.scala
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27966 Fail startup if mixed versions are used, #27965
  akka-actor-tests/src/test/scala/akka/config/ConfigSpec.scala
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/util/ManifestInfo.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27946 Document typed extensions
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/extensions/ExtensionDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/extensions/ExtensionDocSpec.scala
  akka-docs/src/main/paradox/index-utilities.md
  akka-docs/src/main/paradox/typed/extending.md
Labels: tested

#27967 doc: minor changes to sharding docs
  akka-docs/src/main/paradox/typed/cluster-sharding-concepts.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#27888 Rename LoggingEventFilter to LoggingTestKit
  akka-actor-testkit-typed/src/main/resources/reference.conf
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/LoggingEvent.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/LoggingTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestAppender.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/LoggingTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/LoggingTestKit.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/LoggingTestKitTest.java
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/LoggingEventFilterSpec.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/TestAppenderSpec.scala
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/LoggingDocExamples.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/DeferredSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/LogMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/MailboxSelectorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TransformMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/LoggerOpsSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/LoggingDocExamples.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/testing-async.md
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRecoveryTimeoutSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/OptionalSnapshotStoreSpec.scala
Labels: tested

#27958 Fix wording
  akka-docs/src/main/paradox/stream/stream-parallelism.md
Labels: tested

#27961 fix TlsSpec on JDK 11, #27956
  akka-stream-tests/src/test/scala/akka/stream/io/DeprecatedTlsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
Labels: tested

#27964 Last sequence number fix
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SlowInMemorySnapshotStore.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotMutableStateSpec.scala
Labels: 2 - pick next, tested, to-be-backported

#27947 API compile coverage for Java DSL runWith
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceRunWithTest.java
Labels: tested

#27959 doc: minor improvements to cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
Labels: tested

#27977 Two new test cases missed the PersistenceId.ofUniqueId
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
Labels: 2 - pick next, tested

#27983 Remove ActorSubscriber
  akka-stream/src/main/scala/akka/stream/actor/ActorSubscriber.scala
Labels: tested

#27979 Update aeron-client, aeron-driver to 1.22.1
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27985 Upgrade to Config 1.4.0
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27971 doc: improvements to Distributed Data docs
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/internal/ReplicatorBehavior.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/Replicator.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/Replicator.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/ddata/typed/javadsl/ReplicatorDocSample.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/ddata/typed/scaladsl/ReplicatorDocSpec.scala
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/test/java/jdocs/ddata/DistributedDataDocTest.java
Labels: tested

#27496 lastSequenceNr should reflect the snapshot sequence and not start with 0 when journal is empty
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotRecoveryWithEmptyJournalSpec.scala
Labels: tested

#27986 Provide Scheduler implicitly from implicit typed actorsystem
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitBase.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/receptionist/ReceptionistApiSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/SpawnProtocolDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-bench-jmh/src/main/scala/akka/actor/typed/TypedActorBenchmark.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/internal/ClusterReceptionistUnreachabilitySpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/scala/docs/persistence/query/PersistenceQueryDocSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
Labels: 2 - pick next, tested

#27993 lastSequenceNr should reflect the snapshot sequence
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotRecoveryWithEmptyJournalSpec.scala
Labels: backport, tested

#27856 Tags from actor props goes into MDC
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/LoggingDocExamples.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/LoggingDocExamples.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Props.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorMdc.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/PropsImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/PropsAdapter.scala
  akka-actor/src/main/scala/akka/actor/Deployer.scala
  akka-actor/src/main/scala/akka/actor/Props.scala
  akka-docs/src/main/paradox/typed/logging.md
  akka-remote/src/main/java/akka/remote/WireFormats.java
  akka-remote/src/main/protobuf/WireFormats.proto
  akka-remote/src/main/scala/akka/remote/serialization/DaemonMsgCreateSerializer.scala
  akka-remote/src/test/scala/akka/remote/serialization/MessageContainerSerializerSpec.scala
Labels: 2 - pick next, tested

#27991 Handle ActorInitializationException from Classic child in Typed parent, #27970
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
Labels: 2 - pick next, tested

#27998 add missing apply for consistency types, #27997
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/Replicator.scala
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorCompileOnlyTest.scala
Labels: 2 - pick next, tested

#27995 inmem journal must not reset highestSequenceNr after journal cleanup, #27994
  akka-persistence-tck/src/test/scala/akka/persistence/journal/inmem/InmemJournalSpec.scala
  akka-persistence/src/main/mima-filters/2.5.x.backwards.excludes/issue-27994-inmem-journal.excludes
  akka-persistence/src/main/scala/akka/persistence/journal/inmem/InmemJournal.scala
Labels: 2 - pick next, tested

#27982 -5 pads out the max level of a logger, remove when using []
  akka-actor-typed-tests/src/test/resources/logback-doc-dev.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-prod.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-test.xml
Labels: tested

#27988 Update protobuf-java and protoc to 3.10.0
  akka-cluster-metrics/src/main/java/akka/cluster/metrics/protobuf/msg/ClusterMetricsMessages.java
  akka-cluster-sharding-typed/src/main/java/akka/cluster/sharding/typed/internal/protobuf/ShardingMessages.java
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-tools/src/main/java/akka/cluster/client/protobuf/msg/ClusterClientMessages.java
  akka-cluster-tools/src/main/java/akka/cluster/pubsub/protobuf/msg/DistributedPubSubMessages.java
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ClusterMessages.java
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatedDataMessages.java
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatorMessages.java
  akka-docs/src/main/java/docs/ddata/protobuf/msg/TwoPhaseSetMessages.java
  akka-docs/src/main/java/docs/persistence/proto/FlightAppModels.java
  akka-multi-node-testkit/src/main/java/akka/remote/testconductor/TestConductorProtocol.java
  akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java
  akka-remote-tests/src/test/java/akka/remote/artery/protobuf/TestMessages.java
  akka-remote/src/main/java/akka/remote/ArteryControlFormats.java
  akka-remote/src/main/java/akka/remote/ContainerFormats.java
  akka-remote/src/main/java/akka/remote/SystemMessageFormats.java
  akka-remote/src/main/java/akka/remote/WireFormats.java
  akka-remote/src/test/java/akka/remote/ProtobufProtocol.java
  akka-remote/src/test/java/akka/remote/protobuf/v3/ProtobufProtocolV3.java
  akka-stream/src/main/java/akka/stream/StreamRefMessages.java
  project/Dependencies.scala
  project/Protobuf.scala
Labels: 2 - pick next, tested

#27978 small simplification since Scala 2.11 isn't supported
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/Cluster.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/ClusterSingleton.scala
Labels: tested

#27974 Add API for multi-dc Sharding/Singleton in Typed, #27705
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/MultiDcClusterShardingSpec.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerSpec.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiDcClusterSingletonSpec.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiDcPinger.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/BasicClusterExampleTest.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/SingletonCompileOnlyTest.java
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/SingletonCompileOnlySpec.scala
  akka-docs/src/main/paradox/cluster-dc.md
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/typed/cluster-dc.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/index-cluster.md
Labels: 2 - pick next, tested

#27931 Document using an EventSourcedBehavior as a PersistentFSM
  akka-docs/src/main/paradox/typed/index-persistence.md
  akka-docs/src/main/paradox/typed/persistence-fsm.md
Labels: 2 - pick next, tested

#27378 Provide cancellation for CoordinatedShutdown tasks (#27335)
  akka-actor-tests/src/test/scala/akka/actor/CoordinatedShutdownSpec.scala
  akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala
  akka-docs/src/main/paradox/coordinated-shutdown.md
  akka-docs/src/test/java/jdocs/actor/ActorDocTest.java
  akka-docs/src/test/scala/docs/actor/ActorDocSpec.scala
Labels: tested

#28002 use max seqNr in RecoverySuccess
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotRecoveryWithEmptyJournalSpec.scala
Labels: tested

#28005 doc: minor clarification of ActorRef.toTyped
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/coexistence/ClassicWatchingTypedSpec.scala
  akka-docs/src/main/paradox/typed/coexisting.md
Labels: 2 - pick next, tested

#28006 remove FIXME for Quickstart link
  akka-docs/src/main/paradox/typed/guide/introduction.md
  akka-docs/src/main/paradox/typed/guide/tutorial.md
  akka-docs/src/main/paradox/typed/guide/tutorial_1.md
Labels: 2 - pick next, tested

#28007 cleanup OSGi build properties
  project/OSGi.scala
Labels: 2 - pick next, tested

#27594 Stream cancellation modes
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/GraphInterpreterSpecKit.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/CancellationStrategySpec.scala
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: 2 - pick next, tested

#27742 RetryFlow: retries of individual stream elements with backouff
  akka-docs/src/main/paradox/stream/operators/RetryFlow/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RetryFlow/withBackoffAndContext.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/RetryFlowTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RetryFlowSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/RetryFlowCoordinator.scala
  akka-stream/src/main/scala/akka/stream/javadsl/RetryFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RetryFlow.scala
  project/StreamOperatorsIndexGenerator.scala
Labels: t:stream, tested

#27989 Update sbt to 1.3.3
  project/build.properties
Labels: tested

#28009 Expose new DNS protocol via the DNS extension
  akka-actor-tests/src/test/scala/akka/io/SimpleDnsCacheSpec.scala
  akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala
  akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsManagerSpec.scala
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsResolverSpec.scala
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes/issue-27219-new-dns.excludes
  akka-actor/src/main/scala/akka/io/Dns.scala
  akka-actor/src/main/scala/akka/io/DnsProvider.scala
  akka-actor/src/main/scala/akka/io/InetAddressDnsProvider.scala
  akka-actor/src/main/scala/akka/io/InetAddressDnsResolver.scala
  akka-actor/src/main/scala/akka/io/SimpleDnsCache.scala
  akka-actor/src/main/scala/akka/io/SimpleDnsManager.scala
  akka-actor/src/main/scala/akka/io/TcpOutgoingConnection.scala
  akka-actor/src/main/scala/akka/io/UdpConnection.scala
  akka-actor/src/main/scala/akka/io/WithUdpSend.scala
  akka-actor/src/main/scala/akka/io/dns/CachePolicy.scala
  akka-actor/src/main/scala/akka/io/dns/DnsProtocol.scala
  akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsCache.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsManager.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsProvider.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala
  akka-discovery/src/main/scala/akka/discovery/dns/DnsServiceDiscovery.scala
  akka-docs/src/main/paradox/io-dns.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-remote-tests/src/multi-jvm/scala/akka/io/DnsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
Labels: tested

#28008 [2.5 backport] stream: add CancellationStrategy attribute to c…
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/CancellationStrategySpec.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/SubscriptionWithCancelException.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: backport, tested

#28014 doc: adjustments of migration guide
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#28018 StreamRefs spec fail
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SinkRefImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala
Labels: 2 - pick next, tested

#28020 StreamRefs spec fail, #27957
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
Labels: 2 - pick next, backport, tested

#28021 Add names for input and output boundaries
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
Labels: 2 - pick next, tested, to-be-backported

#28017 doc: Show how to fail future of external ask
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: 2 - pick next, tested

#28022 Add names for input and output boundaries
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
Labels: backport, tested

#25822 Add external predicate to matchEquals and matchAny in ReceiverBu…
  akka-actor/src/main/java/akka/japi/pf/ReceiveBuilder.java
Labels: tested

#28023 Removed unnecessary comment in test.
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
Labels: tested

#28013 Add grouped example to akka-docs (#25468)
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/grouped.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Grouped.scala
Labels: tested

#28030 Changing mima latestPatchOf
  project/MiMa.scala
Labels: tested

#28031 latestPatchOf 2.5.26
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes/2.5.26-vs-2.6.0-RC1.excludes
  akka-actor/src/main/scala/akka/actor/TypedActor.scala
  akka-persistence/src/main/mima-filters/2.5.x.backwards.excludes/2.5.26-vs-2.6.0-RC1.excludes
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes/2.5.26-vs-2.6.0-RC1.excludes
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes/2.5.26-vs-2.6.0-RC1.excludes
  akka-stream/src/main/scala/akka/stream/SubscriptionWithCancelException.scala
  project/MiMa.scala
Labels: tested

#28012 Add a page for Typed Distributed PubSub
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/DistributedPubSubExample.scala
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/distributed-pub-sub.md
  akka-docs/src/main/paradox/typed/index-cluster.md
Labels: tested

#28039 Wrong scminfo in 2.5
  RELEASING.md
Labels: tested

#28025 Cluster doc cleanup.
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#28036 Fix incorrect exception names in fault tolerance doc
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/BubblingSample.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/FaultToleranceDocSpec.scala
Labels: tested

#28026 fix typo on persistence-schema-evolution.md
  akka-docs/src/main/paradox/persistence-schema-evolution.md
Labels: tested

#28042 Remoting docs config snippet should have provider = remote
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
Labels: t:docs, tested, to-be-backported

#28055 Failed: Could not create directory, file exists and is not a director…
  project/plugins.sbt
Labels: tested

#28051 Discovered that RC comparison was problematic in Akka HTTP
  akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala
  akka-actor/src/main/scala/akka/AkkaVersion.scala
Labels: tested

#28056 Fixes intermittent "Could not create directory" issue
  project/AkkaBuild.scala
Labels: tested

#28053 Adding bullet point in doc.
  akka-docs/src/main/paradox/remoting-artery.md
Labels: tested
