Repository akka/akka, pull requests merged in 2019-11, with the labels that each got.

#28088 doc: fix link to persistence style guide
  akka-docs/src/main/paradox/typed/persistence-testing.md
Labels: tested

#28087 Use PersistenceId.ofUnique instead of the private constructor
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/EventSourcedActorFailureTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/NullEmptyStateTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PrimitiveStateTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/MovieWatchList.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/auction/AuctionEntity.java
Labels: tested

#28122 doc: update faq.md
  akka-docs/src/main/paradox/additional/faq.md
Labels: 2 - pick next, tested

#28098 Watch in the wrong place in sample
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/fromclassic/TypedSample.scala
Labels: tested

#28062 Clarify snapshop every n events
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/RetentionCriteria.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/RetentionCriteria.scala
Labels: tested

#28125 Docs polish for 2.6.0
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/coordination.md
  akka-docs/src/main/paradox/discovery/index.md
  akka-docs/src/main/paradox/distributed-pub-sub.md
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/multi-node-testing.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/stream/index.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/actor-discovery.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/cluster-dc.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/distributed-pub-sub.md
  akka-docs/src/main/paradox/typed/fault-tolerance.md
  akka-docs/src/main/paradox/typed/fsm.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-docs/src/main/paradox/typed/mailboxes.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/routers.md
  akka-docs/src/main/paradox/typed/stash.md
  akka-docs/src/main/paradox/typed/testing-async.md
  akka-docs/src/main/paradox/typed/testing-sync.md
  akka-docs/src/main/paradox/typed/testing.md
  project/plugins.sbt
Labels: 2 - pick next, tested

#28121 Update links to samples, #28106
  akka-docs/src/main/paradox/additional/osgi.md
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-docs/src/main/paradox/cluster-routing.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/fsm.md
  akka-docs/src/main/paradox/multi-jvm-testing.md
  akka-docs/src/main/paradox/multi-node-testing.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/project/examples.md
  akka-docs/src/main/paradox/project/index.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/supervision-classic.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/fsm.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: 2 - pick next, tested

#28130 add dependency to akka-slf4j from akka-actor-typed
  build.sbt
Labels: 2 - pick next, tested

#28131 Link to Tour of Akka Typed
  akka-docs/src/main/paradox/typed/from-classic.md
Labels: 2 - pick next, tested

#28132 move Coordinated Shutdown down in ToC
  akka-docs/src/main/paradox/typed/index.md
Labels: 2 - pick next, tested

#28129 Docs: set 2.6 release date in project info
  project/project-info.conf
Labels: 2 - pick next, tested

#28127 Need akka-slf4j on classpath for internal logging
  akka-docs/src/main/paradox/typed/logging.md
Labels: 2 - pick next, tested

#27904 Update sbt-updates to 0.4.3
  project/plugins.sbt
Labels: tested

#28136 Fix typo in Response type
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#28110 Exclude agrona from scala-steward
  .scala-steward.conf
Labels: tested

#28033 Improved docs for some queries
  akka-persistence-query/src/main/scala/akka/persistence/query/javadsl/CurrentEventsByTagQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/javadsl/EventsByPersistenceIdQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/javadsl/EventsByTagQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/CurrentEventsByTagQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/EventsByPersistenceIdQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/EventsByTagQuery.scala
Labels: tested

#28116 Avoid falling back to IterableOnceOps.copyToArray
  akka-actor/src/main/scala-2.13+/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
  akka-bench-jmh/src/main/scala/akka/util/ByteString_toArray_Benchmark.scala
Labels: Merge After 2.6.0 Release, tested, to-be-backported

#28135 update mima latestPatch 2.6.0
  build.sbt
  project/MiMa.scala
Labels: tested

#28101 Update sbt-scalafix to 0.9.8
  project/plugins.sbt
Labels: tested

#28139 Remove trailing div from fold.md
  akka-docs/src/main/paradox/stream/operators/Sink/fold.md
Labels: tested

#28150 Update sbt-header to 5.3.0
  project/plugins.sbt
Labels: tested

#28151 doc: fix the word spell error in actor-lifecycle
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
Labels: tested

#28146 Fix the URL Holly reported
  akka-docs/src/main/paradox/.htaccess
Labels: tested

#28134 Run whitesource for tags
  .travis.yml
Labels: tested

#28107 sbt option to explicitly specify the jdk8 jdk to use
  project/AkkaBuild.scala
  project/JdkOptions.scala
Labels: tested

#28100 doc: improve doc example of javadsl Extension
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/extensions/ExtensionDocTest.java
  akka-docs/src/main/paradox/typed/extending.md
Labels: tested

#28028 Update sbt-whitesource to 0.1.18
  project/plugins.sbt
Labels: tested

#28160 Fix fire and forget wording
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#28157 Modified the existing Effect directive in sample code of docs
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: tested

#28047 Only deliver buffered RestartShard to the local ShardRegion #27782
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardRegionSpec.scala
Labels: 2 - pick next, Merge After 2.6.0 Release, tested

#28179 Disable JavaUdpMulticastTest
  akka-docs/src/test/java/jdocs/io/JavaUdpMulticastTest.java
Labels: tested

#28145 fix links to samples
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/multi-jvm-testing.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/project/examples.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/fsm.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#28118 Remove classgraph dependency from sbt plugin scope
  project/plugins.sbt
Labels: tested

#27850 doc: Flow.fold
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/fold.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Fold.scala
Labels: tested

#28188 fixed the bug that messageAdapter can not work for primitive types
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
Labels: tested

#28183 Update ssl-config to 0.4.1
  project/Dependencies.scala
Labels: tested

#28185 doc: reword routing link to new API
  akka-docs/src/main/paradox/fsm.md
  akka-docs/src/main/paradox/routing.md
Labels: tested

#28103 Update jul-to-slf4j, log4j-over-slf4j, ... to 1.7.29
  project/Dependencies.scala
Labels: tested

#28163 Update jackson-annotations, jackson-core, ... to 2.10.1
  project/Dependencies.scala
Labels: tested

#28190 Update silencer to 1.4.4, to support scala 2.13.1
  project/AkkaDisciplinePlugin.scala
Labels: tested

#27713 Update sbt-pgp to 2.0.0
  project/Release.scala
  project/plugins.sbt
Labels: tested

#28189 Remove native packager plugin
  project/plugins.sbt
Labels: tested

#28181 Keep custom logger name in EventSourcedBehavior
  akka-actor-typed/src/main/mima-filters/2.6.0.backwards.excludes/issue-28161-logger-name.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
Labels: tested

#28199 rename scaladsl.LoggingTestKit.intercept to expect, #28194
  akka-actor-testkit-typed/src/main/mima-filters/2.6.0.backwards.excludes/issue-28194-LoggingTestKit.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/LoggingTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/LoggingTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/LoggingTestKit.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/TestAppenderSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/DeferredSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/LogMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/MailboxSelectorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TransformMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/LoggerOpsSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/LoggingDocExamples.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRecoveryTimeoutSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/OptionalSnapshotStoreSpec.scala
Labels: tested

#27903 Update gson to 2.8.6
  project/Dependencies.scala
Labels: tested

#28043 Update metrics-core, metrics-jvm to 4.1.1
  project/Dependencies.scala
Labels: tested

#28202 Replace 'intercept' with 'expect'
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
Labels: tested

#28197 preserve order of ask replies, #28196
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
Labels: tested

#28193 Backport disable udpmulticasttest
  akka-docs/src/test/java/jdocs/io/JavaUdpMulticastTest.java
Labels: tested

#28162 Fix method name in the description of Source 'lazilyAsync' operator
  akka-docs/src/main/paradox/stream/operators/Source/lazilyAsync.md
  akka-docs/src/main/paradox/stream/operators/index.md
Labels: tested

#28097 Docs: Remove extra type params in RetryFlow signature
  akka-docs/src/main/paradox/stream/operators/RetryFlow/withBackoff.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/RetryFlowTest.java
Labels: t:docs, tested

#28173 Mention no implicit sender in coexistence.md #28074
  akka-docs/src/main/paradox/typed/coexisting.md
Labels: tested

#28152 Use specific exception for discovery timeout
  akka-discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
  akka-discovery/src/main/scala/akka/discovery/dns/DnsServiceDiscovery.scala
  akka-discovery/src/test/scala/akka/discovery/dns/DnsServiceDiscoverySpec.scala
Labels: tested

#28120 Don't log AskTimeout strack trace for dns resolve timeout
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala
  akka-actor/src/main/scala/akka/io/dns/internal/DnsClient.scala
Labels: tested

#28091 doc: Broadcast Stream operator, #25468
  akka-docs/src/main/paradox/stream/operators/Broadcast.md
  akka-docs/src/test/java/jdocs/stream/operators/BroadcastDocExample.java
  akka-docs/src/test/scala/docs/stream/operators/BroadcastDocExample.scala
Labels: tested

#28203 Reconsider cluster.role.<role-name>.min-nr-of-members fallback #28177
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRolePartitioningSpec.scala
Labels: tested

#28191 Fix race condition in print tree
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: tested

#28192 Dump name server logs if resolve fails
  akka-actor-tests/src/test/scala/akka/io/dns/AsyncDnsResolverIntegrationSpec.scala
  akka-actor-tests/src/test/scala/akka/io/dns/DockerBindDnsService.scala
Labels: needs-attention

#28141 27729 consistent hashing routing
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/routing/RoutingLogicSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.x.backwards.excludes/issue-27729-consistent-hashing.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/RoutingLogic.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#28214 move mima filter to 2.6.0
  CONTRIBUTING.md
  akka-actor-typed/src/main/mima-filters/2.6.0.backwards.excludes/issue-27729-consistent-hashing.excludes
  akka-actor-typed/src/main/mima-filters/2.6.x.backwards.excludes/issue-27729-consistent-hashing.excludes
Labels: tested

#28216 Don't update scalafmt from scala-steward
  .scala-steward.conf
Labels: tested

#28210 Add docs for stream operator Sink.collection
  akka-docs/src/main/paradox/stream/operators/Sink/collection.md
  akka-docs/src/main/paradox/stream/operators/index.md
  project/StreamOperatorsIndexGenerator.scala
Labels: tested

#28220 Remove scoverage since we don't really use it
  project/AkkaDisciplinePlugin.scala
  project/plugins.sbt
Labels: tested

#28223 [doc] typo remove superfluous `the`
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#28222 [doc] typo add missing you
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#28187 Add interceptors for interpretUnstashedMessage and onReplayingSnapshot.
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RequestingRecoveryPermit.scala
Labels: tested

#28200 add Java API for DistributedPubSubMediator.Count, #27728
  akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala
Labels: tested

#28168 Add omitted `logPrefixSkipList` in getting logger class in `EventSourcedBehavior`
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
Labels: tested

#28201 Document and fix getAsyncCallback thread safety issues
  akka-remote/src/main/scala/akka/remote/artery/Handshake.scala
  akka-remote/src/main/scala/akka/remote/artery/SystemMessageDelivery.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#28195 Operator docs for Source.combine
  akka-docs/src/main/paradox/stream/operators/Source/combine.md
  akka-docs/src/test/java/jdocs/stream/operators/source/Combine.java
  akka-docs/src/test/scala/docs/stream/operators/source/Combine.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#28205 Change uninitialized throw to reflect state vs arg issue
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
Labels: tested

#28234 [doc] typo, add missing `
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#28221 [doc] fix listing, add newline beforehand
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#28218 Small interpreter metadata fixes
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/StreamTestKit.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
Labels: tested, to-be-backported

#28078 =doc: take and takeWhile
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/take.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/takeWhile.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Take.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/TakeWhile.scala
Labels: tested

#28237 Fix type on cluster-usage page
  akka-docs/src/main/paradox/cluster-usage.md
Labels: tested

#28224 [doc] typo actors `need` instead of `needs`
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#28182 Use stop supervision for PropsAdapter, #28035
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/coexistence/ClassicSupervisingTypedSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/adpater/PropsAdapterSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.0.backwards.excludes/issue-28035-supervision.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/PropsAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Adapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/adapter/PropsAdapter.scala
Labels: tested

#28230 Update sbt to 1.3.4
  project/build.properties
Labels: tested

#28225 Operator docs for Source.tick
  akka-docs/src/main/paradox/stream/operators/Source/tick.md
  akka-docs/src/test/java/jdocs/stream/operators/source/Tick.java
  akka-docs/src/test/scala/docs/stream/operators/source/Tick.scala
Labels: tested

#28217 Update only jackson-core-databind from scala-steward
  .scala-steward.conf
  project/Dependencies.scala
Labels: tested

#28236 Don't include protobuf settings for all projects
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/extensions/ExtensionDocSpec.scala
  project/AkkaBuild.scala
Labels: tested

#27037 Use embedded media driver for StressSpec
  akka-cluster/src/multi-jvm/scala/akka/cluster/SharedMediaDriverSupport.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala
Labels: tested

#28241 clarify async appender
  akka-actor-typed-tests/src/test/resources/logback-doc-dev.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-prod.xml
  akka-docs/src/main/paradox/typed/logging.md
Labels: tested

#28242 fix race condition in WriteAggregatorSpec, #25581
  akka-distributed-data/src/test/scala/akka/cluster/ddata/WriteAggregatorSpec.scala
Labels: tested

#28240 backport StreamRefResolver, #28215
  akka-docs/src/main/paradox/stream/stream-refs.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
  akka-stream/src/main/scala/akka/stream/StreamRefs.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/StreamRefResolverImpl.scala
Labels: backport, tested

#28104 Use dedicated message for PersistentShardCoodinator termination instead of PoisonPill
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
Labels: tested

#28245 [doc] typo remove superfluous `a`
  akka-docs/src/main/paradox/general/actors.md
Labels: tested

#28246 [doc] typo `actor` instead of `cator`
  akka-docs/src/main/paradox/general/supervision.md
Labels: tested

#28004 Add recover example to akka-docs (#25468)
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/recover.md
  akka-docs/src/main/paradox/stream/stream-error.md
  akka-docs/src/test/java/jdocs/stream/FlowErrorDocTest.java
  akka-docs/src/test/scala/docs/stream/FlowErrorDocSpec.scala
Labels: tested

#27990 Add scanAsync examples to akka-docs (#25468)
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/scan.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/scanAsync.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/ScanAsync.scala
Labels: tested

#28108 Make akka-protobuf-v3.jar reproducible
  build.sbt
Labels: Merge After 2.6.0 Release, tested

#28244 Use dedicated message for PersistentShardCoodinator termination
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
Labels: backport, tested

#28248 Don't loadExtensions at startup if already terminated, #27840
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-cluster/src/test/scala/akka/cluster/DowningProviderSpec.scala
Labels: tested

#28239 Document scanAsync
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/scan.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/scanAsync.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/ScanAsync.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#28251 Missing creation of second actor
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
Labels: tested

#28219 Split akka-streams interop pages
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/stream/actor-interop.md
  akka-docs/src/main/paradox/stream/futures-interop.md
  akka-docs/src/main/paradox/stream/index.md
  akka-docs/src/main/paradox/stream/reactive-streams-interop.md
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
  akka-docs/src/main/paradox/stream/stream-integrations.md
Labels: tested

#28156 Remove scalac javabootclasspath hack
  project/JdkOptions.scala
Labels: tested

#28094 more efficient and correct clear in Slf4jLogger
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorMdc.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala
Labels: tested

#28111 Example for Source.unfoldAsync
  akka-docs/src/main/paradox/stream/operators/Source/unfoldAsync.md
  akka-docs/src/test/java/jdocs/stream/operators/source/UnfoldAsync.java
  akka-docs/src/test/scala/docs/stream/operators/source/UnfoldAsync.scala
Labels: tested

#28090 doc: Partition Streams operator, #25468
  akka-docs/src/main/paradox/stream/operators/Partition.md
  akka-docs/src/test/java/jdocs/stream/operators/PartitionDocExample.java
  akka-docs/src/test/scala/docs/stream/operators/PartitionDocExample.scala
Labels: tested

#27875 Add convenience method to start timer without key
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/ManualTimerExampleTest.java
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/TestProbeSpec.scala
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/ManualTimerExampleSpec.scala
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StyleGuideDocExamples.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TransformMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/FSMDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/TailChopping.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/TimerScheduler.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/TimerScheduler.scala
  akka-actor/src/main/scala/akka/actor/AbstractFSM.scala
  akka-actor/src/main/scala/akka/actor/FSM.scala
  akka-actor/src/main/scala/akka/actor/Timers.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceGroupQuery.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSMBase.scala
Labels: tested

#28238 doc: filter and filterNot streams operator, #25468
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/filter.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/filterNot.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Filter.scala
Labels: tested

#28080 Example for unfoldResourceAsync
  akka-docs/src/main/paradox/stream/operators/Source/unfoldResourceAsync.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/source/UnfoldResourceAsync.java
  akka-docs/src/test/scala/docs/stream/operators/source/UnfoldResourceAsync.scala
Labels: tested

#28252 Re-enable multicast tests
  akka-docs/src/test/java/jdocs/io/JavaUdpMulticastTest.java
  akka-docs/src/test/scala/docs/io/ScalaUdpMulticastSpec.scala
Labels: tested

#28243 Example for mapConcat
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapConcat.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/MapConcat.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/MapConcat.scala
Labels: tested

#27984 Include host and port in BindException message (#27785)
  akka-actor/src/main/scala/akka/io/TcpListener.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
Labels: tested

#28232 28206 adding address typed
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorRefResolverSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/routing/RoutingLogicSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.0.backwards.excludes/issue-28206-address.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorRefResolver.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
Labels: tested

#28256 Revert to old extension load failure handling logic
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: tested

#25000 Flow.delayWith allows custom delay for each element.
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/delayWith.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDelaySpec.scala
  akka-stream/src/main/mima-filters/2.6.0.backwards.excludes/pr-25000-delaywith.excludes
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/javadsl/DelayStrategy.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/DelayStrategy.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#28258 Docs: link pages with TLS
  akka-docs/src/main/paradox/distributed-pub-sub.md
  akka-docs/src/main/paradox/general/remoting.md
  akka-docs/src/main/paradox/persistence-journals.md
  akka-docs/src/main/paradox/persistence-plugins.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/persistence-schema-evolution.md
  akka-docs/src/main/paradox/stream/stream-io.md
  akka-docs/src/main/paradox/typed/distributed-pub-sub.md
  akka-docs/src/main/paradox/typed/guide/tutorial_5.md
  project/project-info.conf
Labels: t:docs, tested

#28259 Update sbt-header to 5.3.1
  project/plugins.sbt
Labels: tested

#28148 Include host and port in mdc if clustered or remote
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.0.backwards.excludes/issue-28073-host-port-in-mdc.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorMdc.scala
  akka-actor/src/main/mima-filters/2.6.0.backwards.excludes/issue-28073-host-port-in-mdc.excludes
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterActorLoggingSpec.scala
  akka-docs/src/main/paradox/typed/logging.md
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala
  akka-slf4j/src/test/resources/logback-test.xml
  akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala
Labels: 2 - pick next, tested

#28262 Use timer key for tests that require it
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
Labels: 2 - pick next, validating

#28247 Update aeron-client, aeron-driver to 1.24.0
  project/Dependencies.scala
Labels: tested

#28253 Better deadLetter logging of wrapped messages, #28109
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.0.backwards.excludes/issue-28109-wrapped-message.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InternalMessage.scala
  akka-actor/src/main/scala/akka/actor/Actor.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/actor/ActorSelection.scala
  akka-actor/src/main/scala/akka/event/DeadLetterListener.scala
  akka-actor/src/main/scala/akka/routing/ConsistentHashing.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingMessageExtractor.scala
  akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala
Labels: tested

#28267 Use CrossVersion.patch for Silencer plugin
  project/AkkaDisciplinePlugin.scala
Labels: tested, to-be-backported

#28140 Scala 2.13.0 -> Scala 2.13.1
  .travis.yml
  akka-actor-typed/src/main/mima-filters/2.6.0.backwards.excludes/28140-scala-2.13.1.backwards.excludes
  akka-actor/src/main/scala/akka/util/TypedMultiMap.scala
  akka-cluster-typed/src/main/mima-filters/2.6.0.backwards.excludes/28140-scala-2.13.1.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/SubFlowImpl.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SubFlow.scala
  project/AkkaBuild.scala
  project/Dependencies.scala
  project/Doc.scala
Labels: tested

#28268 Revert "Remove scalac javabootclasspath hack (#28156)"
  project/JdkOptions.scala
Labels: 2 - pick next, tested

#28271 Delay operator emit early fix
  akka-stream/src/main/scala/akka/stream/OverflowStrategy.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: 2 - pick next, tested

#28277 [doc] rephrase ask system to SpawnProtocol.spawn
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
Labels: tested
