Repository akka/akka, pull requests merged in 2019-06, with the labels that each got.

#27059 Set useful description in sbt setting
  project/AkkaBuild.scala
Labels: tested

#27051 Improve logging in DistributedData extension
  akka-cluster-typed/src/main/resources/reference.conf
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/DistributedData.scala
Labels: tested

#27069 Set useful description in sbt setting (#27059) [backport]
  project/AkkaBuild.scala
Labels: tested

#27065 Minor typo is fixed
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
Labels: tested

#27063 fix typo
  akka-docs/src/main/paradox/discovery/index.md
Labels: tested, to-be-backported

#27057 Internal stable markers
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala
  akka-actor/src/main/scala/akka/dispatch/Mailbox.scala
  akka-actor/src/main/scala/akka/dispatch/sysmsg/SystemMessage.scala
  akka-remote/src/main/scala/akka/remote/Remoting.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
Labels: tested

#27055 Removed overly-enthusiastic-about-scala-sample exclamation point in doc
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested

#27018 Add common/io-layer to the ToC
  akka-docs/src/main/paradox/io.md
Labels: tested

#27075 fix typeo
  akka-docs/src/main/paradox/discovery/index.md
Labels: backport, tested

#27070 Update links of moved modules to doc.akka.io (#27058) [backport]
  akka-docs/src/main/paradox/additional/deploy.md
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-dc.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/common/other-modules.md
  akka-docs/src/main/paradox/coordination.md
  akka-docs/src/main/paradox/discovery/index.md
  akka-docs/src/main/paradox/guide/modules.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/typed/guide/modules.md
Labels: backport, tested

#26789 Adding improved warning when jdk8 is not found #26222
  build.sbt
Labels: tested

#27087 support akka.build.version=file
  project/AkkaBuild.scala
Labels: tested

#27088 Minor jackson doc tweaks
  akka-docs/src/main/paradox/serialization-jackson.md
Labels: tested

#27084 Note about lease timeout and JVM pauses
  akka-docs/src/main/paradox/coordination.md
Labels: tested

#27074 Remove too verbose debug logging for timers, #26932
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor/src/main/scala/akka/actor/dungeon/TimerSchedulerImpl.scala
Labels: tested

#27072 Netty is not optional for multi jvm test kit
  project/Dependencies.scala
Labels: tested

#27025 Decrease waiting-for-state-timeout to 2s
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27090 Clarify what to do instead of sending a PoisonPill for ActorRef source
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#27099 Remove removed modules from AkkaDiscipline plugin
  project/AkkaDisciplinePlugin.scala
Labels: tested

#27101 Remove duplicate copyright
  akka-actor-typed-tests/src/test/java/akka/actor/typed/ActorSystemTest.java
Labels: tested

#27054 Jackson serializer typed.ActorRef, #24155
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/ActorRefModule.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/AkkaJacksonModule.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/TypedActorRefModule.scala
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestMessages.java
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  build.sbt
Labels: tested

#27091 Doc Jackson annotation gotchas, #24155
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestMessages.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/SerializationDocTest.java
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
Labels: tested

#27068 Support separate conf per JacksonSerializer binding, #24155
  akka-actor/src/main/scala/akka/serialization/Serialization.scala
  akka-actor/src/main/scala/akka/serialization/Serializer.scala
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
Labels: tested

#27067 try Jackson compression impact, #24155
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
Labels: tested

#27056 use ISO-8601 date/time format in Jackson serializer, #24155
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
Labels: tested

#27085 re-enable dead letter logging after specified duration, #24874
  akka-actor-tests/src/test/scala/akka/actor/DeadLetterSuspensionSpec.scala
  akka-actor-tests/src/test/scala/akka/config/ConfigSpec.scala
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/event/DeadLetterListener.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27108 Being explicit about how to disable artery
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27092 Jackson whitelist for deserialization of unbound class, #26910
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
Labels: tested

#27119 Remove Behavior.same/empty/etc, #26730
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/BehaviorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKit.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
  akka-actor-typed-tests/src/test/java/akka/actor/typed/ActorSystemTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/ExtensionsTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/eventstream/EventStreamTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ExtensionsSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/receptionist/LocalReceptionistSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/PoisonPill.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/BehaviorBuilder.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AbstractBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardingState.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/AkkaClusterTypedSerializerSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
Labels: tested

#27117 Remove request parameter in Typed Replicator messages, #27115
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/internal/ReplicatorBehavior.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/Replicator.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/Replicator.scala
  akka-cluster-typed/src/test/java/akka/cluster/ddata/typed/javadsl/ReplicatorTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: 2 - pick next, tested

#27129 Trying this out as the other PR isn't running in travis
  .travis.yml
  project/AkkaDisciplinePlugin.scala
  project/Dependencies.scala
Labels: tested

#27134 Remove typed from api may change
  akka-docs/src/main/paradox/common/may-change.md
Labels: tested

#27128 Widen and timers can be used together, #25318
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WidenSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
Labels: 2 - pick next, tested

#27121 Remove ActorContext parameter from javadsl.ReceiveBuilder, #27120
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/BehaviorTestKitTest.java
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/SyncTestingExampleTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorLoggingTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/BehaviorBuilderTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/WatchTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/receptionist/ReceptionistApiTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/BubblingSample.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/FSMDocTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/GracefulStopDocTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/OOIntroTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StashDocTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/coexistence/TypedWatchingUntypedTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/coexistence/UntypedWatchingTypedTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/supervision/SupervisionCompileOnlyTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/OOIntroSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/BehaviorBuilder.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExample.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/SingletonCompileOnlyTest.java
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/actors.md
Labels: 2 - pick next, tested

#27136 Enable Jackson for 2.13
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  build.sbt
Labels: 2 - pick next, tested

#27105 Remove Jackson Smile format, #24155
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27043 Upgrade to Aeron 1.19.1
  akka-cluster/src/multi-jvm/scala/akka/cluster/SharedMediaDriverSupport.scala
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/test/java/akka/remote/artery/aeron/AeronStat.java
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27064 remove Jackson afterburner, since no visible improvement #24155
  akka-bench-jmh/src/main/java/akka/serialization/jackson/JavaMessages.java
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestMessages.java
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  build.sbt
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27098 Use Duration in javadsl.EntityRef.ask
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ClusterShardingPersistenceTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/HelloWorldPersistentEntityExample.java
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#27140 cross release again
  project/scripts/release
Labels: 2 - pick next, tested

#27141 Fix entity ref link in migration guide
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#27102 Make Behaviors.intercept a factory () => BehaviorInterceptor
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/InterceptTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StopSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/GuardianStartupBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterSingletonImpl.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
Labels: 2 - pick next, tested

#27073 Make Artery connect failure logging less verbose, #26865
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartSink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartSource.scala
Labels: 2 - pick next, tested

#26813 Type inference for EntityRef.ask, #26709
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/AsyncTestingExampleTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AskPattern.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithMutableState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithNullState.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithOptionState.scala
  akka-docs/src/main/paradox/typed/persistence-style.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: 2 - pick next, tested

#27138 changing logging error as previous wasn't proper english
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
Labels: tested

#26526 Add a create method with context and namePrefix to ActorMaterialize‘s Java API.
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
Labels: tested

#27144 Consolidate 'fat jar' docs
  akka-docs/src/main/paradox/additional/deploy.md
  akka-docs/src/main/paradox/general/configuration.md
Labels: tested

#27083 Option to target system JDK instead of JDK8
  build.sbt
  project/AkkaBuild.scala
  project/CrossJava.scala
Labels: tested

#27146 Revise modules listing
  akka-docs/src/main/paradox/common/other-modules.md
Labels: t:docs, tested, to-be-backported

#27159 Some old netty config paths in tests fixed
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/UntrustedSpec.scala
Labels: tested

#27161 Fix error in sharding message flow description
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested

#27147 Allow specifying a log level when logging exceptions being seen the SupervisorStrategy
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/SupervisorStrategy.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
Labels: tested

#27162 Revise modules listing
  akka-docs/src/main/paradox/common/other-modules.md
Labels: backport, tested

#27154 upgrade to ScalaTest 3.0.8
  akka-actor-tests/src/test/java/akka/actor/JavaAPI.java
  akka-actor-tests/src/test/java/akka/actor/JavaExtension.java
  akka-actor-tests/src/test/java/akka/actor/StashJavaAPI.java
  akka-actor-tests/src/test/java/akka/japi/JavaAPITestBase.java
  akka-actor-tests/src/test/java/akka/util/JavaDuration.java
  project/Dependencies.scala
Labels: tested

#27080 Simplify the definition of ActorRef#narrow
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorRefImpl.scala
Labels: tested

#27152 Revert 0.4.* of ssl config for 2.13
  project/Dependencies.scala
Labels: tested, to-be-backported

#27171 Handle InitJoin messages correctly, #27169
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
Labels: tested

#27145 Fix authors script to run with 2.13
  scripts/authors.scala
Labels: tested

#27180 Handle InitJoin messages correctly, #27169
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
Labels: backport, tested

#27173 increase monitored-by-nr-of-members config, #27172
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/test/scala/akka/cluster/ClusterConfigSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27174 Mention Artery port 25520 in migration guide
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27177 Don't passivate idle for remembering entities
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#27126 Disable remote watch and remote deployment outside Cluster
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/Deployer.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster/src/main/scala/akka/cluster/ClusterActorRefProvider.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterDeathWatchSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/DeterministicOldestWhenJoiningSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RemoteFeaturesWithClusterSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ResetSystemMessageSeqNrSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/scala/docs/remoting/RemoteDeploymentDocSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/NewRemoteActorSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteDeploymentDeathWatchSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteFeaturesSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteNodeDeathWatchSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteNodeRestartDeathWatchSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteReDeploymentSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/TransportFailSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/classic/RemoteNodeShutdownAndComesBackSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/routing/RemoteRandomSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/routing/RemoteRoundRobinSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/routing/RemoteScatterGatherSpec.scala
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteSettings.scala
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/test/scala/akka/remote/RemoteFeaturesSpec.scala
  akka-remote/src/test/scala/akka/remote/RemoteRouterSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeploymentSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteRouterSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteWatcherSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteDeploymentWhitelistSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteWatcherSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemotingSpec.scala
Labels: tested

#27196 Akka Typed Add example of how to java `getSelf` for persistence typed #27061
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
Labels: tested

#27186 Docs: make rolling restarts/upgrades/updates more prominent, easier to find #27039
  akka-docs/src/main/paradox/additional/deploy.md
  akka-docs/src/main/paradox/additional/deploying.md
  akka-docs/src/main/paradox/additional/index.md
  akka-docs/src/main/paradox/additional/packaging.md
  akka-docs/src/main/paradox/additional/rolling-deploys.md
  akka-docs/src/main/paradox/cluster-dc.md
  akka-docs/src/main/paradox/index.md
  akka-docs/src/main/paradox/project/rolling-update.md
Labels: tested

#27195 Adding WatchedWith effect in akka actor typed testkit #27190
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/Effect.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/EffectfulActorContext.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/Effects.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/Effects.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/BehaviorTestKitTest.java
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
  akka-docs/src/main/paradox/typed/testing.md
Labels: tested

#27202 Remoting test tagged as IgnoreForScala212 failed in Jenkins nightly, needs one line of config
  akka-remote/src/test/scala/akka/remote/TypedActorRemoteDeploySpec.scala
Labels: tested

#27199 Update deploy.md to avoid Maven generating erroneous tags
  akka-docs/src/main/paradox/additional/packaging.md
Labels: tested

#27201 Add mapMaterializedValue for Source/Flow withContext master
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SourceWithContext.scala
Labels: tested, to-be-backported

#27139 Add mapMaterializedValue for Source/Flow withContext akka 2.5
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SourceWithContext.scala
Labels: backport, t:stream, tested

#27217 Add missing @InternalStableApi for Akka Persistence instrumentation
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
Labels: tested

#27213 Use short configurable timeout for expectNoMessage #27212
  CONTRIBUTING.md
  akka-actor-tests/src/test/scala/akka/actor/ActorLifeCycleSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ActorSelectionSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemDispatcherSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/CoordinatedShutdownSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/DeadLetterSupressionSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/FunctionRefSpec.scala
  akka-actor-tests/src/test/scala/akka/event/EventBusSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/coexistence/UntypedSupervisingTypedSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDomainEventPublisherSpec.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorMapDeltaSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/scala/tutorial_4/DeviceGroupSpec.scala
  akka-docs/src/test/scala/tutorial_4/DeviceSpec.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-testkit/src/main/resources/reference.conf
  akka-testkit/src/main/scala/akka/testkit/TestKit.scala
  akka-testkit/src/main/scala/akka/testkit/TestKitExtension.scala
  akka-testkit/src/main/scala/akka/testkit/javadsl/TestKit.scala
Labels: tested

#27210 Rolling update when adding akka-cluster-typed dependency, #27191
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistConfigCompatChecker.scala
Labels: tested

#27225 Upgrade sbt-scoverage, sbt-scalafix and sbt-header
  project/plugins.sbt
Labels: tested

#27204 ActorHierarchyExperiments: Send a `start` message to the first actor
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
  akka-docs/src/test/scala/typed/tutorial_1/ActorHierarchyExperiments.scala
Labels: tested

#27226 Fix paradox anchor references
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/additional/deploying.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/discovery/index.md
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/event-bus.md
  akka-docs/src/main/paradox/general/stream/stream-design.md
  akka-docs/src/main/paradox/general/supervision.md
  akka-docs/src/main/paradox/io.md
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/persistence-fsm.md
  akka-docs/src/main/paradox/persistence-journals.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/project/rolling-update.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/routing.md
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-docs/src/main/paradox/stream/operators/UnzipWith.md
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
  akka-docs/src/main/paradox/stream/stream-graphs.md
  akka-docs/src/main/paradox/stream/stream-introduction.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#27221 Clarify remembered entities limit is for active entities
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested

#27118 Reduce boilerplate for interaction with Typed Replicator #27116
  akka-cluster-typed/src/main/resources/reference.conf
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/ReplicatorMessageAdapter.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorMessageAdapter.scala
  akka-cluster-typed/src/test/java/akka/cluster/ddata/typed/javadsl/ReplicatorTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: tested

#27234 Send a `start` message to the first actor …
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
  akka-docs/src/test/scala/typed/tutorial_1/ActorHierarchyExperiments.scala
Labels: tested

#27233 ActorHierarchyExperiments: Send a `start` message to the first actor …
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
  akka-docs/src/test/scala/typed/tutorial_1/ActorHierarchyExperiments.scala
Labels: tested

#27236 Fixes same wording multiple times
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested
