Repository akka/akka, pull requests merged in 2019-12, with the labels that each got.

#28282 +sbt Add rewriteTokens
  .scalafmt.conf
Labels: tested

#28283 Update mockito-core to 3.2.0
  project/Dependencies.scala
Labels: tested

#28279 Use CrossVersion.patch for Silencer plugin
  .travis.yml
  project/AkkaDisciplinePlugin.scala
Labels: backport, tested

#28288 Docs: use ref-links to pages
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/project/rolling-update.md
  akka-docs/src/main/paradox/typed/distributed-pub-sub.md
Labels: t:docs, tested

#28285 Update sbt-scalafix to 0.9.11
  project/plugins.sbt
Labels: tested

#28292 [2.5 backport] Backport of #27848 to fix #24580 for release-2.5
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergePrioritizedSpec.scala
Labels: backport, tested

#28180 Docs: add some API links to stream operator docs
  CONTRIBUTING.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/filter.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/filterNot.md
  project/Doc.scala
  project/Paradox.scala
  project/plugins.sbt
Labels: t:docs, t:stream, tested

#28284 Update link to akka vavr sample project
  akka-docs/src/main/paradox/actors.md
Labels: 2 - pick next, tested

#28250 add local affinity support for group router
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.0.backwards.excludes/issue-28174-prefer-local-routees.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/GroupRouterSpec.scala
  akka-docs/src/main/paradox/typed/routers.md
Labels: 2 - pick next, tested

#28293 New cluster node state diagram and other small improvements
  akka-docs/src/main/paradox/images/member-state-diagram.png
  akka-docs/src/main/paradox/images/member-states-weakly-up.png
  akka-docs/src/main/paradox/images/member-states.drawing
  akka-docs/src/main/paradox/images/member-states.png
  akka-docs/src/main/paradox/images/member-states.svg
  akka-docs/src/main/paradox/typed/cluster-membership.md
Labels: 2 - pick next, tested

#28300 build: fix mima checking for Akka 2.6.0
  akka-actor/src/main/mima-filters/2.6.0.backwards.excludes/28300-fix-2.6.0-mima.excludes
  akka-remote/src/main/mima-filters/2.6.0.backwards.excludes/28300-fix-2.6.0-mima.excludes
  akka-stream/src/main/mima-filters/2.6.0.backwards.excludes/28300-fix-2.6.0-mima.excludes
  project/MiMa.scala
Labels: 2 - pick next, tested

#28302 Downgrade sbt-osgi
  .scala-steward.conf
  project/plugins.sbt
Labels: 2 - pick next, tested

#28029 Add external predicate to matchEquals and matchAny in ReceiverBuilder, #25774
  akka-actor/src/main/java/akka/japi/pf/ReceiveBuilder.java
Labels: 2 - pick next, tested

#28209 Structured log events, #28207
  akka-actor/src/main/scala/akka/actor/ActorLogMarker.scala
  akka-actor/src/main/scala/akka/event/DeadLetterListener.scala
  akka-actor/src/main/scala/akka/event/Logging.scala
  akka-cluster-sharding/src/main/mima-filters/2.6.0.backwards.excludes/issue-28207-struct-log.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardingLogMarker.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster/src/main/scala/akka/cluster/Cluster.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterHeartbeat.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterLogMarker.scala
  akka-cluster/src/main/scala/akka/cluster/CrossDcClusterHeartbeat.scala
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-remote/src/main/scala/akka/remote/PhiAccrualFailureDetector.scala
  akka-remote/src/main/scala/akka/remote/RemoteLogMarker.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala
  akka-slf4j/src/test/resources/logback-test.xml
  akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala
Labels: 2 - pick next, tested

#28299 Manifest-less Jackson serializers
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
Labels: 2 - pick next, tested

#28312 mima filter for ClusterLogger, #28207
  akka-cluster/src/main/mima-filters/2.6.0.backwards.excludes/issue-28207-struct-logging.excludes
Labels: 2 - pick next, tested

#28303 Update sbt-paradox-akka to 0.28
  project/plugins.sbt
Labels: tested

#28274 Avoid dead letter for rebalance timeout msg
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested

#28308 use %mdc logback config to output all MDC entries
  akka-actor-testkit-typed/src/test/resources/logback-test.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-dev.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-prod.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-test.xml
  akka-actor-typed-tests/src/test/resources/logback-test.xml
  akka-bench-jmh/src/main/resources/logback-test.xml
  akka-cluster-metrics/src/test/resources/logback-test.xml
  akka-cluster-sharding-typed/src/multi-jvm/resources/logback-test.xml
  akka-cluster-sharding-typed/src/test/resources/logback-test.xml
  akka-cluster-typed/src/multi-jvm/resources/logback-test.xml
  akka-cluster-typed/src/test/resources/logback-test.xml
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-docs/src/test/resources/logback-test.xml
  akka-osgi/src/test/resources/logback-test.xml
  akka-persistence-typed/src/test/resources/logback-test.xml
  akka-slf4j/src/test/resources/logback-test.xml
  akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala
Labels: 2 - pick next, tested

#28311 Backport of LogMarker.properties
  akka-actor/src/main/scala/akka/event/Logging.scala
  akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala
  akka-slf4j/src/test/resources/logback-test.xml
  akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala
Labels: backport, tested

#28313 add whitelist in serialization rolling update instruction
  akka-docs/src/main/paradox/additional/rolling-updates.md
Labels: 2 - pick next, tested

#28315 Document JavaFlowSupport
  akka-docs/src/main/paradox/stream/reactive-streams-interop.md
  akka-docs/src/test/scala/docs/stream/ReactiveStreamsDocSpec.scala
Labels: tested

#28319 [doc] add `the` for a better flow
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#28322 [doc] add `a` for a better flow
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#28320 [doc] improve blog post actor text
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#28309 attempt to fix v1.class does not exist
  akka-docs/src/test/java/jdocs/persistence/PersistenceSchemaEvolutionDocTest.java
  akka-docs/src/test/scala/docs/persistence/PersistenceSchemaEvolutionDocSpec.scala
Labels: tested

#28326 Fix typos
  CONTRIBUTING.md
  akka-actor-tests/src/test/scala/akka/routing/ResizerSpec.scala
  akka-actor/src/main/scala/akka/io/SimpleDnsCache.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-docs/src/main/paradox/persistence-journals.md
  akka-docs/src/main/paradox/stream/actor-interop.md
  akka-docs/src/test/java/jdocs/actor/typed/BlockingActor.java
  akka-docs/src/test/scala/docs/actor/typed/BlockingActor.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/SignalHandler.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#28325 [doc] add `to` for a better flow
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#28081 Source.unfold examples
  akka-docs/src/main/paradox/stream/operators/Source/unfold.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/source/Unfold.java
  akka-docs/src/test/scala/docs/stream/operators/source/Unfold.scala
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceUnfoldTest.java
Labels: tested

#26310 Add Java DSL Flow#mapError version without PartialFunction (#24992)
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
Labels: tested

#28341 Suppress ActorSelectionMessage with DeadLetterSuppression, #28226
  akka-actor-tests/src/test/scala/akka/actor/DeadLetterSupressionSpec.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/event/DeadLetterListener.scala
Labels: tested

#28345 Remove wrong import from hello world doc sample, #28169
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-docs/src/main/paradox/typed/actors.md
Labels: tested

#28354 Clarify typed timeout is not for akka typed
  akka-actor/src/main/resources/reference.conf
Labels: tested

#28314 remove logging of full config in ConfigDocSpec
  akka-docs/src/test/scala/docs/config/ConfigDocSpec.scala
Labels: tested

#28330 Remove allocation of Some from CompressionTable
  akka-remote/src/main/mima-filters/2.6.1.backwards.excludes/CompressionTable.excludes
  akka-remote/src/main/scala/akka/remote/artery/compress/CompressionTable.scala
  akka-remote/src/main/scala/akka/remote/serialization/ArteryMessageSerializer.scala
  akka-remote/src/test/scala/akka/remote/artery/compress/OutboundCompressionSpec.scala
Labels: tested

#28342 typo in reference.conf comment
  akka-remote/src/main/resources/reference.conf
Labels: tested

#28343 Example for intersperse
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/grouped.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/intersperse.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/Intersperse.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Intersperse.scala
Labels: tested

#28335 Log non-completed rebalance at warning level
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested

#28352 Fix a single grammar error in Getting Started Guide
  akka-docs/src/main/paradox/typed/guide/actors-motivation.md
Labels: tested

#28363 fix concurrent access to CompressionTable Object2IntHashMap
  akka-remote/src/main/scala/akka/remote/artery/compress/CompressionTable.scala
Labels: tested

#28360 Adding a clarification to the Akka Classic stash documentation about what happens when an actor is restarted.
  akka-docs/src/main/paradox/actors.md
Labels: tested

#28357 stream operator docs: example above RS semantics
  akka-docs/src/main/paradox/stream/operators/Sink/last.md
  akka-docs/src/main/paradox/stream/operators/Sink/lastOption.md
  akka-docs/src/main/paradox/stream/operators/Sink/reduce.md
  akka-docs/src/main/paradox/stream/operators/Sink/takeLast.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/concat.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/interleave.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/map.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/merge.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mergeSorted.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/orElse.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/prepend.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zip.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zipAll.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zipWith.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zipWithIndex.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRef.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/Source/cycle.md
  akka-docs/src/main/paradox/stream/operators/Source/from.md
  akka-docs/src/main/paradox/stream/operators/Source/fromFuture.md
  akka-docs/src/main/paradox/stream/operators/Source/future.md
  akka-docs/src/main/paradox/stream/operators/Source/lazySource.md
  akka-docs/src/main/paradox/stream/operators/Source/range.md
  akka-docs/src/main/paradox/stream/operators/Source/single.md
Labels: tested

#28361 [doc] adjust link text to next section
  akka-docs/src/main/paradox/typed/persistence-style.md
Labels: tested

#28348 Partition must not pull from closed in, #27189
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphPartitionSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: tested

#28365 Partition must not pull from closed in, #27189
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphPartitionSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: backport, tested

#28350 Add checkTestsHaveRun task to check tests have run
  akka-stream-tests/src/test/java-jdk9-only/akka/stream/javadsl/JavaFlowSupportCompileTest.java
  project/TestExtras.scala
Labels: tested

#28324 Perform MiMa checks against 2.6.1
  akka-stream/src/main/mima-filters/2.6.1.backwards.excludes/28324-jdk9-specific-classes.backwards.excludes
  project/MiMa.scala
Labels: tested

#28368 Minor scaladoc fix and cleanup.
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
Labels: tested

#28377 Update sbt to 1.3.5
  project/build.properties
Labels: tested

#28374 #28373 Include akka-testkit into version match
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: tested

#28305 JFR-based remoting flight recorder
  akka-actor/src/main/resources/reference.conf
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamConcistencySpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamLatencySpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamMaxThroughputSpec.scala
  akka-remote/src/main/mima-filters/2.6.1.backwards.excludes/pr-28305-JFR-based-flight-recording.excludes
  akka-remote/src/main/scala-jdk-9/akka/remote/artery/jfr/Events.scala
  akka-remote/src/main/scala-jdk-9/akka/remote/artery/jfr/JFRRemotingFlightRecorder.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/EventSink.scala
  akka-remote/src/main/scala/akka/remote/artery/FlightRecorderEvents.scala
  akka-remote/src/main/scala/akka/remote/artery/RemotingFlightRecorder.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/AeronSink.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/AeronSource.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/compress/InboundCompressions.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/TcpFraming.scala
  akka-remote/src/test/scala-jdk9-only/akka/remote/artery/jfr/JFRRemotingFlightRecorderSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemotingFlightRecorderSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/aeron/AeronSinkSpec.scala
  build.sbt
  project/Jdk9.scala
Labels: tested

#28355 Remove use of getClass in secondary constructors
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingConfig.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
  akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamSpec.scala
  akka-testkit/src/test/scala/akka/testkit/AkkaSpec.scala
Labels: tested

#28369 [doc] document TypeKey in persistence
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithOptionState.scala
Labels: tested

#27042 use sbt-dynver
  RELEASING.md
  project/AkkaBuild.scala
  project/plugins.sbt
  project/scripts/release
Labels: tested

#28349 Docs on fromSinkAndSource
  akka-docs/src/main/paradox/images/fromSinkAndSource.png
  akka-docs/src/main/paradox/stream/operators/Flow/fromSinkAndSource.md
  akka-docs/src/main/paradox/stream/operators/Flow/fromSinkAndSourceCoupled.md
  akka-docs/src/test/java/jdocs/stream/operators/flow/FromSinkAndSource.java
  akka-docs/src/test/scala/docs/stream/operators/flow/FromSinkAndSource.scala
Labels: tested

#28379 Refactor First and Join seed node processes to shared logic for dry and logic hardening
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/SeedNodeProcess.scala
Labels: t:cluster, tested

#28388 Fixing persistence-typed javadsl test compiler warnings
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/EventSourcedActorFailureTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/NullEmptyStateTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PrimitiveStateTest.java
Labels: t:persistence, t:testing, t:typed, tested

#28391 Enable 'adapted args' warnings globally
  akka-actor/src/main/scala/akka/io/dns/internal/DnsClient.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#28340 Timout await extension initialization, #28301
  akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-docs/src/main/paradox/serialization.md
  akka-docs/src/test/java/jdocs/serialization/SerializationDocTest.java
  akka-docs/src/test/scala/docs/serialization/SerializationDocSpec.scala
Labels: tested

#28358 EventSourcedBehavior not failing with DeathPactException for unhandled Terminated() signals
  akka-persistence-typed/src/main/mima-filters/2.6.1.backwards.excludes/issue-28297-deathpactexception.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RequestingRecoveryPermit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorWatchSpec.scala
Labels: tested

#28371 [doc] unhandled vs empty vs ignore
  akka-docs/src/main/paradox/typed/fsm.md
Labels: tested

#28384 Add .withRouteeProps(props) to pool router builder API (akka typed)
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/routing/PoolRouterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.1.backwards.excludes/pr-28384-pool-routee-props.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#28376 Update HdrHistogram to 2.1.12
  project/Dependencies.scala
Labels: tested

#28385 ReceiveTimeout in preStart lost on restart
  akka-actor-tests/src/test/scala/akka/actor/ReceiveTimeoutSpec.scala
  akka-actor/src/main/scala/akka/actor/dungeon/FaultHandling.scala
Labels: tested

#28387 Added correct ordering for TimeBasedUUID offset
  akka-actor/src/main/scala/akka/util/UUIDComparator.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/Offset.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/OffsetSpec.scala
Labels: tested

#28339 dead scaladoc links to log markers
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/typed/logging.md
Labels: tested

#28336 Better short titles for deprecated operators
  akka-docs/src/main/paradox/stream/operators/Flow/lazyInitAsync.md
  akka-docs/src/main/paradox/stream/operators/Sink/lazyInitAsync.md
  akka-docs/src/main/paradox/stream/operators/Source/fromCompletionStage.md
  akka-docs/src/main/paradox/stream/operators/Source/fromFuture.md
  akka-docs/src/main/paradox/stream/operators/Source/fromFutureSource.md
  akka-docs/src/main/paradox/stream/operators/Source/fromSourceCompletionStage.md
  akka-docs/src/main/paradox/stream/operators/Source/lazily.md
  akka-docs/src/main/paradox/stream/operators/Source/lazilyAsync.md
  akka-docs/src/main/paradox/stream/operators/index.md
Labels: tested

#28397 Update mockito-core to 3.2.4
  project/Dependencies.scala
Labels: tested

#28408 Ignore mockito updates
  .scala-steward.conf
Labels: tested

#28409 Fix typos, via a Levenshtein-style corrector
  .scalafix.conf
  akka-actor-tests/src/test/scala/akka/actor/ActorLifeCycleSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemDispatcherSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ReceiveTimeoutSpec.scala
  akka-actor-tests/src/test/scala/akka/routing/MetricsBasedResizerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/extensions/ExtensionDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor/src/main/resources/reference.conf
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcHeartbeatTakingOverSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSunnyWeatherSpec.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/JepsenInspiredInsertSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializerSpec.scala
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/stream/actor-interop.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/distributed-pub-sub.md
  akka-docs/src/main/paradox/typed/style-guide.md
  akka-docs/src/test/java/jdocs/actor/SchedulerDocTest.java
  akka-docs/src/test/scala/docs/cluster/ClusterDocSpec.scala
  akka-docs/src/test/scala/docs/stream/StreamBuffersRateSpec.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeFlattenSeq.scala
  akka-persistence-tck/src/main/scala/akka/persistence/scalatest/MayVerb.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala
  akka-protobuf/src/main/java/akka/protobuf/Descriptors.java
  akka-remote/src/main/java/akka/remote/artery/compress/CountMinSketch.java
  akka-remote/src/main/scala/akka/remote/artery/compress/TopHeavyHitters.scala
  akka-remote/src/test/scala/akka/remote/RemoteRouterSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteInstrumentsSerializationSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteRouterSpec.scala
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupedWithinSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphStageTimersSpec.scala
  akka-stream/src/main/resources/reference.conf
  akka-stream/src/main/scala-jdk-9/akka/stream/impl/JavaFlowAndRsConverters.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#28401 fix wrong logging of REACHABLE, #28393
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested

#28399 Remove the default reschedule=true arg to internal checkReceiveTimeout
  akka-actor/src/main/mima-filters/2.6.1.backwards.excludes/28399-remove-default-arg.excludes
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-actor/src/main/scala/akka/actor/dungeon/FaultHandling.scala
  akka-actor/src/main/scala/akka/actor/dungeon/ReceiveTimeout.scala
Labels: tested

#28410 Document how to report security issues
  CONTRIBUTING.md
Labels: tested

#28412 only check config relation image-liveness-timeout if aeron-upd transport
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
Labels: tested

#28404 [doc] improve serialization
  akka-docs/src/main/paradox/serialization.md
Labels: tested

#28413 mention 2.6.0 in rolling update change log
  akka-docs/src/main/paradox/project/rolling-update.md
Labels: tested

#28333 Serializer for tck JournalPerfSpec.Cmd, #28291
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalPerfSpec.scala
  akka-persistence-tck/src/test/scala/akka/persistence/journal/leveldb/LeveldbJournalJavaSpec.scala
  akka-persistence-tck/src/test/scala/akka/persistence/journal/leveldb/LeveldbJournalNativePerfSpec.scala
  akka-persistence-tck/src/test/scala/akka/persistence/journal/leveldb/LeveldbJournalNativeSpec.scala
  akka-persistence-tck/src/test/scala/akka/persistence/journal/leveldb/LeveldbJournalNoAtomicPersistMultipleEventsSpec.scala
Labels: tested

#28328 [doc] Fix scala doc in javadsl.FileIO
  akka-stream/src/main/scala/akka/stream/javadsl/FileIO.scala
Labels: tested
