Repository akka/akka, pull requests merged in 2019-01, with the labels that each got.

#26117 Document how to observe mocked behavior with typed ActorTestKit
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/AsyncTestingExampleTest.java
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/AsyncTestingExampleSpec.scala
  akka-docs/src/main/paradox/typed/testing.md
Labels: tested

#26163 added example for cycle operator
  akka-docs/src/main/paradox/stream/operators/Source/cycle.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
Labels: tested

#26169 Don't be too clever with the copyright year
  project/CopyrightHeader.scala
Labels: tested

#26162 added examples for Stream # actorRef operator. As part of #25468
  akka-docs/src/main/paradox/stream/operators/Source/actorRef.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/SourceOperators.scala
Labels: tested

#25966 Add pipeToSelf to typed ActorContext
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorContextPipeToSelfTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextPipeToSelfSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InternalMessage.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AskPattern.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
Labels: tested

#26170 Use Adopt JDK 8 in Travis
  .jvmopts-travis
  .travis.yml
Labels: tested

#26193 add examples for scan operator #25468
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/scan.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/SourceOrFlow.scala
Labels: tested

#26202 stashing and pipeToSelf, #25824
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StashDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StashDocSpec.scala
Labels: tested

#26079 Import `akka.actor` as `untyped` but not `a`.
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/DebugRef.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorRef.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorRefAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/StashManagement.scala
Labels: tested

#26166 26160: added `Source.empty` in Java API
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
Labels: tested

#26154 rename timeout to delay in startSingleTimer
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/TimerScheduler.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/TimerScheduler.scala
Labels: tested

#26205 Run ask/pipe on the actor's thread, in Java
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
Labels: tested

#26210 Updates header for `akka.compat.Future`
  akka-actor/src/main/scala-2.11/akka/compat/Future.scala
Labels: tested

#26211 Artery tests: use config to determine TCP/UDP free port + use the correct host
  akka-remote/src/test/scala/akka/remote/artery/ArteryMultiNodeSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/HandshakeFailureSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/HandshakeRetrySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/LateConnectSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteActorSelectionSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteConnectionSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/compress/HandshakeShouldDropCompressionTableSpec.scala
  akka-testkit/src/test/scala/akka/testkit/WithLogCapturing.scala
Labels: tested

#26204 Remove duplicate code in Cluster Sharding Typed HashCode*MessageExtractor [#26197]
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingMessageExtractor.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#26221 Remove some unused import in akka-stream's boilerplate templates.
  akka-stream/src/main/boilerplate/akka/stream/javadsl/GraphCreate.scala.template
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/GraphApply.scala.template
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/UnzipWithApply.scala.template
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/ZipLatestWithApply.scala.template
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/ZipWithApply.scala.template
Labels: tested

#26219 Add how to check binary compatibility.
  CONTRIBUTING.md
Labels: tested

#26218 Fix debug message Udp.Received Message.parse at DnsClient
  akka-actor/src/main/scala/akka/io/dns/internal/DnsClient.scala
Labels: tested

#26161 Add `getSelf`,`getProps`,`getReceiveTimeout` and `getDispatcher` to `akka.actor.AbstractActor.ActorContext`.
  akka-actor/src/main/mima-filters/2.5.20.backwards.excludes
  akka-actor/src/main/scala/akka/actor/AbstractActor.scala
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/futures.md
  akka-docs/src/main/paradox/guide/tutorial_5.md
  akka-docs/src/test/java/jdocs/actor/BlockingFutureActor.java
  akka-docs/src/test/java/jdocs/actor/FaultHandlingDocSample.java
  akka-docs/src/test/java/jdocs/circuitbreaker/DangerousJavaActor.java
  akka-docs/src/test/java/jdocs/circuitbreaker/EvenNoFailureJavaExample.java
  akka-docs/src/test/java/jdocs/circuitbreaker/TellPatternJavaActor.java
  akka-docs/src/test/java/jdocs/cluster/StatsSampleClient.java
  akka-docs/src/test/java/jdocs/ddata/DataBot.java
  akka-docs/src/test/java/jdocs/pattern/SupervisedAsk.java
  akka-docs/src/test/java/jdocs/persistence/query/MyEventsByTagJavaPublisher.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceGroupQuery.java
Labels: tested

#26201 Hidden protocol and interception
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/InterceptTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
Labels: tested

#26153 Cleanup Typed TestProbe implementation
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestProbe.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/TestProbe.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/package.scala
Labels: tested

#26155 don't show receiveSignal from ExtensibleBehavior in Receive
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
Labels: tested

#26132 adds service name parser (copied from akka-management)
  akka-discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
  akka-discovery/src/test/scala/akka/discovery/LookupSpec.scala
Labels: tested

#26241 Fix compiler warnings in akka-cluster* #26087
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/internal/ReplicatorBehavior.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/DistributedData.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterImpl.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/Registry.scala
  akka-cluster/src/main/mima-filters/2.5.19.backwards.excludes
  akka-cluster/src/main/scala/akka/cluster/Cluster.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/main/scala/akka/cluster/routing/ClusterRouterConfig.scala
Labels: t:build, tested

#26242 Always retry sendGracefulShutdownToCoordinator, #26214
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/CoordinatedShutdownShardingSpec.scala
Labels: tested

#26229 WIP Support rolling update for new JoinConfigCompatChecker #26194
  akka-cluster-sharding-typed/src/main/resources/reference.conf
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/JoinConfigCompatCheckerClusterSharding.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/JoinConfigCompatCheckerClusterShardingSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterTestKit.scala
  akka-cluster/src/test/scala/akka/cluster/JoinConfigCompatCheckerRollingUpdateSpec.scala
  akka-cluster/src/test/scala/akka/cluster/JoinConfigCompatCheckerSpec.scala
Labels: tested

#26225 Include manifest or class in missing serializer
  akka-actor/src/main/scala/akka/serialization/Serialization.scala
Labels: tested

#26247 Silence the sbt-scalafix and sbt-java-formatter's file ignoring.
  project/ProjectFileIgnoreSupport.scala
Labels: tested

#26236 Update headers for jdk9 related code.
  akka-stream-tests-tck/src/test/scala-jdk9-only/akka/stream/tck/IterablePublisherViaJavaFlowPublisherTest.scala
  akka-stream-tests/src/test/java-jdk9-only/akka/stream/javadsl/JavaFlowSupportCompileTest.java
  akka-stream-tests/src/test/scala-jdk9-only/akka/stream/scaladsl/FlowPublisherSinkSpec.scala
  akka-stream/src/main/java-jdk-9/akka/stream/javadsl/JavaFlowSupport.java
  akka-stream/src/main/scala-jdk-9/akka/stream/impl/JavaFlowAndRsConverters.scala
  akka-stream/src/main/scala-jdk-9/akka/stream/scaladsl/JavaFlowSupport.scala
  project/CopyrightHeader.scala
  project/CopyrightHeaderForBoilerplate.scala
  project/CopyrightHeaderForJdk9.scala
  project/CopyrightHeaderForProtobuf.scala
  project/Jdk9.scala
Labels: tested

#26228 Expose nowrap parameter in Compression.inflate, #26227
  akka-stream/src/main/scala/akka/stream/impl/io/compression/DeflateDecompressor.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Compression.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Compression.scala
Labels: tested

#26209 Increase patience for ReceptionistExampleSpec
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExampleSpec.scala
Labels: tested

#26249 Don't log when DNS resolver uses defaults
  akka-actor/src/main/scala/akka/io/InetAddressDnsResolver.scala
Labels: tested

#26159 Corrected documentation
  akka-docs/src/main/paradox/stream/stream-introduction.md
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
Labels: tested

#26251 build: make sure ignore files are searched for in base directory
  project/JavaFormatter.scala
  project/ProjectFileIgnoreSupport.scala
  project/ScalafixSupport.scala
Labels: 2 - pick next, tested

#26248 optimize AtLeastOnceDelivery by not scheduling ticks when not needed, #26216
  akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala
Labels: 2 - pick next, tested

#26208 Suppress no seed-nodes configured logging when Bootstrap is used, #25680
  akka-cluster-metrics/src/main/scala/akka/cluster/metrics/ClusterMetricsCollector.scala
  akka-cluster/src/main/mima-filters/2.5.19.backwards.excludes
  akka-cluster/src/main/scala/akka/cluster/AutoDown.scala
  akka-cluster/src/main/scala/akka/cluster/Cluster.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterJmx.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterLogSpec.scala
Labels: tested

#26137 Support stop or keep of child actors when parent is restarted, #25556
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/TestException.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/TestKitSettings.scala
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorCompile.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/BubblingSample.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/BubblingSampleTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/FaultToleranceDocTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/supervision/SupervisionCompileOnlyTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StopSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/supervision/SupervisionCompileOnly.scala
  akka-actor-typed/src/main/resources/reference.conf
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/MessageAndSignals.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/SupervisorStrategy.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-docs/src/main/paradox/typed/fault-tolerance.md
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/EventSourcedActorFailureTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
Labels: tested

#26052 Fix comment in hashtag example of streams quickstart doc
  akka-docs/src/test/scala/docs/stream/TwitterStreamQuickstartDocSpec.scala
Labels: tested

#26212 Terminate StreamRef on node failure, #25960
  akka-actor-tests/src/test/scala/akka/actor/FunctionRefSpec.scala
  akka-actor/src/main/mima-filters/2.5.19.backwards.excludes
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/actor/dungeon/Children.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
Labels: tested

#25963 Reachability.allObservers wrong after filterRecords, #25950
  akka-cluster/src/main/scala/akka/cluster/Gossip.scala
  akka-cluster/src/main/scala/akka/cluster/Reachability.scala
  akka-cluster/src/test/scala/akka/cluster/ReachabilityPerfSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ReachabilitySpec.scala
Labels: tested

#26011 Stashing in persistent behavior, #25717
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/TestKitSettings.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/SupervisorStrategy.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/EventSourcedEntity.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/SingletonCompileOnlySpec.scala
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/SideEffect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EffectImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedSettings.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/JournalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RequestingRecoveryPermit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/StashManagement.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/CommandHandler.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/StashingExample.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/StashStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorReplySpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/AccountExampleWithEventHandlersInState.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/StashingExample.scala
Labels: tested

#26253 StreamConverters.asInputStream sometimes swallows Source failures and reports them as timeouts
  akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSinkSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala
Labels: tested

#26238 Behaviors.logMessages implementation
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorLoggingTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/LogMessagesSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Logger.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
Labels: tested

#26266 Adding memory settings required to build akka #26265
  .sbtopts
Labels: tested

#26233 Update to sbt 1.2.8 (adding --ignore-source-errors for javadoc)
  project/AkkaBuild.scala
  project/Doc.scala
  project/build.properties
Labels: tested

#26295 increase heap size in .sbtopts
  .sbtopts
Labels: tested

#26294 Make discovery and dns APIs stable
  akka-actor/src/main/scala/akka/io/dns/CachePolicy.scala
  akka-actor/src/main/scala/akka/io/dns/DnsProtocol.scala
  akka-actor/src/main/scala/akka/io/dns/DnsResourceRecords.scala
  akka-actor/src/main/scala/akka/io/dns/RecordType.scala
  akka-discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
  akka-docs/src/main/paradox/discovery/index.md
  build.sbt
Labels: 2 - pick next, tested

#26259 Cluster client caveats
  akka-docs/src/main/paradox/cluster-client.md
Labels: 2 - pick next, tested

#26258 No journal failure for command failure stashed while replaying
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
Labels: 2 - pick next, tested

#26270 Fix dead links to samples
  akka-docs/src/main/paradox/camel.md
  akka-docs/src/main/paradox/multi-node-testing.md
  akka-docs/src/main/paradox/persistence.md
Labels: tested

#26299 Use one naming convention for ShardCoordinator in doc and logging
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/RemoveInternalClusterShardingData.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested

#26303 Only build docs with 2.12 on release
  project/Release.scala
  project/scripts/release
Labels: tested

#26304 Updated the latest patch for mima
  project/MiMa.scala
Labels: tested
