Repository akka/akka, pull requests merged in 2019-08, with the labels that each got.

#27440 [2.5 backport] Ignore more message while TcpConnection is shutting down
  akka-actor/src/main/scala/akka/io/TcpConnection.scala
Labels: backport, tested

#27439 actor: ignore more messages while TcpConnection is shutting down
  akka-actor/src/main/scala/akka/io/TcpConnection.scala
Labels: tested, to-be-backported

#27444 Log changes to the ShardCoordinator ddata state
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested, to-be-backported

#27446 Log changes to the ShardCoordinator ddata state (#27444)
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: backport, tested

#27400 Remove extensions to protobuf config checker messages
  akka-cluster-metrics/src/main/java/akka/cluster/metrics/protobuf/msg/ClusterMetricsMessages.java
  akka-cluster-sharding-typed/src/main/java/akka/cluster/sharding/typed/internal/protobuf/ShardingMessages.java
  akka-cluster-tools/src/main/java/akka/cluster/client/protobuf/msg/ClusterClientMessages.java
  akka-cluster-tools/src/main/java/akka/cluster/pubsub/protobuf/msg/DistributedPubSubMessages.java
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ClusterMessages.java
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster/src/main/protobuf/ClusterMessages.proto
  akka-multi-node-testkit/src/main/java/akka/remote/testconductor/TestConductorProtocol.java
  akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java
  akka-remote-tests/src/test/java/akka/remote/artery/protobuf/TestMessages.java
  akka-stream/src/main/java/akka/stream/StreamRefMessages.java
Labels: 2 - pick next, tested

#27438 Fix akka-bench-jmh warnings.
  akka-bench-jmh/src/main/scala/akka/actor/BenchmarkActors.scala
  akka-bench-jmh/src/main/scala/akka/actor/DirectByteBufferPoolBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/actor/TellOnlyBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/cluster/ddata/ORSetSerializationBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/cluster/ddata/VersionVectorBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/persistence/PersistenceActorDeferBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/persistence/PersistentActorWithAtLeastOnceDeliveryBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/remote/artery/CodecBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-bench-jmh/src/main/scala/akka/stream/AskBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/FlowMapBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/MaterializationBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/NewLayoutBenchmark.template
  akka-bench-jmh/src/main/scala/akka/stream/PartitionHubBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/impl/OutputStreamSourceStageBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/io/FileSourcesScaleBenchmark.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#27435 Fixed warnings in akka-bench-jmh-typed
  akka-bench-jmh-typed/src/main/scala/akka/actor/typed/TypedActorBenchmark.scala
  akka-bench-jmh-typed/src/main/scala/akka/actor/typed/TypedBenchmarkActors.scala
  project/AkkaDisciplinePlugin.scala
Labels: 2 - pick next, tested

#27451 Clean up of persistence and cluster docs
  akka-docs/src/main/paradox/index-actors.md
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/index.md
  akka-docs/src/main/paradox/persistence-schema-evolution.md
  akka-docs/src/main/paradox/typed/index-cluster.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence-style.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#27457 Update paradox
  akka-docs/src/main/paradox/guide/modules.md
  akka-docs/src/main/paradox/typed/actors.md
  build.sbt
  project/plugins.sbt
Labels: tested

#27460 Replace map.filterKeys with map.filter to prevent a memory leak in De…
  akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala
Labels: tested

#27458 Typo alowing -> allowing
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRefWithAck.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRefWithAck.md
Labels: tested

#27456 Fix race conditions in Artery TCP binding to 0
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
Labels: 2 - pick next, tested, to-be-backported

#27462 Fix race conditions in Artery TCP binding to 0
  akka-remote/src/main/mima-filters/2.5.23.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
Labels: backport, tested

#27464 Hook in akka-persistence-typed
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested

#27467 Update sbt-jmh plugin to 0.3.7
  project/plugins.sbt
Labels: tested

#27384 Update to Scala 2.12.9
  project/Dependencies.scala
Labels: tested

#27469 Upgraded sbt-updates plugin
  project/plugins.sbt
Labels: tested

#27470 Upgraded silencer plugin
  project/AkkaDisciplinePlugin.scala
Labels: tested

#27468 Upgraded plugin to 2.0.3, nightly to RC8 (bug fixes)
  .scalafmt.conf
  akka-stream/src/main/scala/akka/stream/impl/SubFlowImpl.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SubFlow.scala
  project/plugins.sbt
Labels: tested

#27478 Latest 2.5 is 2.5.24
  project/MiMa.scala
Labels: tested

#27207 Initial release drafter template
  .github/release-drafter.yml
Labels: tested

#27479 2.5.24
  project/MiMa.scala
Labels: tested

#27477 Update links to the Lightbend Platform docs
  RELEASING.md
Labels: tested

#27476 Update to 2.12.9 for travis as well
  .travis.yml
Labels: tested

#27483 Update links to the Lightbend Platform docs (#27477)
  RELEASING.md
Labels: backport, tested

#27495 follow up on style guide changes for private vs public
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StyleGuideDocExamples.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#27494 Move generic dispatcher docs from Classic
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/dispatchers.md
Labels: tested

#27484 Collapse 'project information' and 'additional information'
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/additional/index.md
  akka-docs/src/main/paradox/index.md
  akka-docs/src/main/paradox/project/index.md
Labels: tested

#27490 Fix assertion in dns tests wrt changed docker json API
  akka-actor-tests/src/test/scala/akka/io/dns/DockerBindDnsService.scala
Labels: tested

#27501 [2.5 backport] Fix assertion in dns tests wrt changed docker json API
  akka-actor-tests/src/test/scala/akka/io/dns/DockerBindDnsService.scala
Labels: 2 - pick next, backport, tested

#27504 Deprecate PersistentFSM (for validation)
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSMBase.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/MessageSerializer.scala
  akka-persistence/src/test/scala/akka/persistence/fsm/PersistentFSMSpec.scala
Labels: 2 - pick next, tested

#27261 RebalanceWorker should watch shard regions
  akka-cluster-sharding/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: 2 - pick next, tested

#27266 Propagate stream cancellation causes
  akka-stream-testkit/src/main/scala/akka/stream/testkit/TestGraphStage.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/GraphStageLogicSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/KillSwitch.scala
  akka-stream/src/main/scala/akka/stream/SubscriptionWithCancelException.scala
  akka-stream/src/main/scala/akka/stream/impl/ReactiveStreamsCompliance.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala
  akka-stream/src/main/scala/akka/stream/impl/Timers.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphStages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartFlow.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: 2 - pick next, tested

#27512 Update to jackson-databind 2.9.9.3
  project/Dependencies.scala
Labels: 2 - pick next, tested

#27485 Remove 'How To' section of the docs
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/howto.md
  akka-docs/src/main/paradox/index.md
Labels: 2 - pick next, tested

#27513 update to reactive-streams-tck 1.0.3-RC1
  project/Dependencies.scala
Labels: tested

#27409 Add configuration for all Jackson Features
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
Labels: 2 - pick next, tested

#27498 Convert 'Blocking needs Careful Management' from classic
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/test/java/jdocs/actor/BlockingActor.java
  akka-docs/src/test/java/jdocs/actor/BlockingDispatcherTest.java
  akka-docs/src/test/java/jdocs/actor/PrintActor.java
  akka-docs/src/test/java/jdocs/actor/SeparateDispatcherFutureActor.java
  akka-docs/src/test/java/jdocs/actor/SeparateDispatcherTest.java
  akka-docs/src/test/java/jdocs/actor/typed/BlockingActor.java
  akka-docs/src/test/java/jdocs/actor/typed/BlockingDispatcherTest.java
  akka-docs/src/test/java/jdocs/actor/typed/BlockingFutureActor.java
  akka-docs/src/test/java/jdocs/actor/typed/PrintActor.java
  akka-docs/src/test/java/jdocs/actor/typed/SeparateDispatcherFutureActor.java
  akka-docs/src/test/scala/docs/actor/BlockingDispatcherSample.scala
  akka-docs/src/test/scala/docs/actor/typed/BlockingDispatcherSample.scala
Labels: 2 - pick next, tested

#27473 Upgrade sbt-paradox-akka 0.18 -> 0.23
  project/plugins.sbt
Labels: 2 - pick next, tested

#27502 Update some SBT plugins
  project/plugins.sbt
Labels: tested

#27488 Fix singleton issue when leaving several nodes, #27487
  akka-cluster-tools/src/main/mima-filters/2.5.24.backwards.excludes
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerLeave2Spec.scala
Labels: tested

#27527 Fix singleton issue when leaving several nodes, #27487
  akka-cluster-tools/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerLeave2Spec.scala
Labels: backport, tested

#27505 Update paradox theme to 0.23
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/balance.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/broadcast.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/partition.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/unzip.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/unzipWith.md
  akka-docs/src/main/paradox/stream/stream-introduction.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/routers.md
  build.sbt
  project/plugins.sbt
Labels: tested

#27524 Give the large source test some more time
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowScanAsyncSpec.scala
Labels: tested

#27533 authors.scala for Scala 2.13
  scripts/authors.scala
Labels: tested

#27534 update latestPatchOf25
  project/MiMa.scala
Labels: tested

#27535 update latestPatchOf25 (master)
  project/MiMa.scala
Labels: tested

#27531 streams: move `lastCancellationCause` helper variable to GraphStageLogic
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#27540 doc: Rewrite general actors page, #24717
  akka-docs/src/main/paradox/general/actors.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actors.md
Labels: tested

#27541 doc: stylish actors.md, #24717
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/OOIntroTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/OOIntroSpec.scala
  akka-docs/src/main/paradox/typed/actors.md
Labels: tested

#27542 doc: stylish coexisting.md, #24717
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/coexistence/TypedWatchingUntypedTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/coexistence/UntypedWatchingTypedSpec.scala
Labels: tested

#27450 Clean up of utilities docs
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/classic/index-utilities.md
  akka-docs/src/main/paradox/common/duration.md
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/event-bus.md
  akka-docs/src/main/paradox/extending-akka.md
  akka-docs/src/main/paradox/futures.md
  akka-docs/src/main/paradox/index-classic.md
  akka-docs/src/main/paradox/index-futures.md
  akka-docs/src/main/paradox/index-utilities.md
  akka-docs/src/main/paradox/java8-compat.md
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/scheduler.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  build.sbt
Labels: 2 - pick next, tested

#27561 Remove explicit scala-xml test dependency
  project/Dependencies.scala
Labels: tested

#27545 Update sbt-reproducible-builds
  project/plugins.sbt
Labels: tested

#27486 Add monitoring section
  akka-docs/src/main/paradox/additional/deploy.md
  akka-docs/src/main/paradox/additional/observability.md
Labels: 2 - pick next, tested

#27525 Fix race when binding to port '0' in artery tcp
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
Labels: 2 - pick next, tested, to-be-backported

#27546 Scaladoc: link to source and canonical
  project/Doc.scala
Labels: t:docs, tested

#27553 Upgrade to reactive streams tck 1.0.3
  project/Dependencies.scala
Labels: tested

#27565 harden ClusterSingletonManagerLeave2Spec, #27555
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerLeave2Spec.scala
Labels: tested

#27567 Fix race when binding to port '0' in artery tcp (#27525)
  akka-remote/src/main/mima-filters/2.5.25.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
Labels: backport, tested

#27543 doc: stylish actor-lifecycle.md, #24717
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/GracefulStopDocTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/SpawnProtocolDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/GracefulStopDocSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/SpawnProtocolDocSpec.scala
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
Labels: tested

#27506 Handle rethrows in `recover` more gracefully
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowRecoverSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: t:stream, tested, to-be-backported

#27575 fix config in ArteryUpdSendConsistencySpec
  akka-remote/src/test/scala/akka/remote/artery/RemoteSendConsistencySpec.scala
Labels: tested

#27576 Handle rethrows in `recover` more gracefully
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowRecoverSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: backport, tested

#27560 Circuitbreaker spec cleanup
  akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerSpec.scala
  project/Dependencies.scala
Labels: tested

#27571 Don't rely on OS DNS lookup failure in spec
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
Labels: tested

#27559 fix JavaDoc of ReceiveBuilder, #27536
  akka-actor/src/main/java/akka/japi/pf/ReceiveBuilder.java
Labels: tested

#27577 Create a new flightrecorder instance per connection
  akka-remote/src/main/mima-filters/2.5.25.backwards.excludes
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/TcpFraming.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TcpFramingSpec.scala
Labels: tested, to-be-backported

#27566 Check MiMa for 2.13 artifacts, too
  project/MiMa.scala
Labels: tested

#27579 remove unused sample for classic getting started guide
  akka-docs/src/test/java/jdocs/tutorial_1/ActorHierarchyExperiments.java
  akka-docs/src/test/java/jdocs/tutorial_2/IotMain.java
  akka-docs/src/test/java/jdocs/tutorial_2/IotSupervisor.java
  akka-docs/src/test/java/jdocs/tutorial_3/Device.java
  akka-docs/src/test/java/jdocs/tutorial_3/DeviceInProgress.java
  akka-docs/src/test/java/jdocs/tutorial_3/DeviceInProgress3.java
  akka-docs/src/test/java/jdocs/tutorial_3/DeviceTest.java
  akka-docs/src/test/java/jdocs/tutorial_3/inprogress2/DeviceInProgress2.java
  akka-docs/src/test/java/jdocs/tutorial_4/Device.java
  akka-docs/src/test/java/jdocs/tutorial_4/DeviceGroup.java
  akka-docs/src/test/java/jdocs/tutorial_4/DeviceGroupTest.java
  akka-docs/src/test/java/jdocs/tutorial_4/DeviceManager.java
  akka-docs/src/test/java/jdocs/tutorial_4/DeviceTest.java
  akka-docs/src/test/java/jdocs/tutorial_5/Device.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceGroup.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceGroupQuery.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceGroupQueryTest.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceGroupTest.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceManager.java
  akka-docs/src/test/java/jdocs/tutorial_5/DeviceTest.java
  akka-docs/src/test/scala/tutorial_1/ActorHierarchyExperiments.scala
  akka-docs/src/test/scala/tutorial_2/IotApp.scala
  akka-docs/src/test/scala/tutorial_2/IotSupervisor.scala
  akka-docs/src/test/scala/tutorial_3/Device.scala
  akka-docs/src/test/scala/tutorial_3/DeviceInProgress.scala
  akka-docs/src/test/scala/tutorial_3/DeviceSpec.scala
  akka-docs/src/test/scala/tutorial_4/Device.scala
  akka-docs/src/test/scala/tutorial_4/DeviceGroup.scala
  akka-docs/src/test/scala/tutorial_4/DeviceGroupSpec.scala
  akka-docs/src/test/scala/tutorial_4/DeviceManager.scala
  akka-docs/src/test/scala/tutorial_4/DeviceSpec.scala
  akka-docs/src/test/scala/tutorial_5/Device.scala
  akka-docs/src/test/scala/tutorial_5/DeviceGroup.scala
  akka-docs/src/test/scala/tutorial_5/DeviceGroupQuery.scala
  akka-docs/src/test/scala/tutorial_5/DeviceGroupQuerySpec.scala
  akka-docs/src/test/scala/tutorial_5/DeviceGroupSpec.scala
  akka-docs/src/test/scala/tutorial_5/DeviceManager.scala
Labels: tested

#27568 harden MultiDcSplitBrainSpec, #24955
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSplitBrainSpec.scala
Labels: tested

#27584 Create a new flightrecorder instance per connection (backport)
  akka-remote/src/main/mima-filters/2.5.25.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/TcpFraming.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TcpFramingSpec.scala
Labels: backport, tested

#27522 Don't run scheduled tasks on shutdown, #16495
  akka-actor-tests/src/test/scala/akka/actor/SchedulerSpec.scala
  akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala
  akka-actor/src/main/scala/akka/actor/Scheduler.scala
  akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#27520 Clarify that akka-protobuf-v3 is not for applications, #26181
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/serialization.md
  akka-protobuf/src/main/java/akka/protobuf/GeneratedMessage.java
Labels: tested

#27563 Java TestKit expect msg all of broken
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/ActorTestKitApiTest.java
  akka-testkit/src/main/mima-filters/2.5.x.backwards.excludes
  akka-testkit/src/main/scala/akka/testkit/javadsl/TestKit.scala
  akka-testkit/src/test/java/akka/testkit/javadsl/TestKitApiTest.java
Labels: tested

#27521 Improve Java perspective dispatcher docs
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/DispatchersDocTest.java
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/test/java/jdocs/actor/BlockingFutureActor.java
  akka-docs/src/test/java/jdocs/actor/typed/BlockingActor.java
  akka-docs/src/test/java/jdocs/actor/typed/BlockingDispatcherTest.java
  akka-docs/src/test/java/jdocs/actor/typed/BlockingFutureActor.java
  akka-docs/src/test/java/jdocs/actor/typed/DispatcherDocTest.java
  akka-docs/src/test/java/jdocs/actor/typed/SeparateDispatcherCompletionStageActor.java
  akka-docs/src/test/java/jdocs/dispatcher/DispatcherDocTest.java
  akka-docs/src/test/scala/docs/actor/typed/BlockingActor.scala
  akka-docs/src/test/scala/docs/actor/typed/BlockingDispatcherSample.scala
  akka-docs/src/test/scala/docs/actor/typed/DispatcherDocSpec.scala
  akka-docs/src/test/scala/docs/actor/typed/PrintActor.scala
Labels: tested

#27493 Move generic mailbox docs from classic to main mailboxes doc
  akka-docs/src/main/paradox/mailboxes.md
  akka-docs/src/main/paradox/typed/mailboxes.md
Labels: 2 - pick next, tested

#27593 Remove CallingThreadDispatcher from main dispatchers doc, #27223
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/DispatchersDocSpec.scala
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/index.md
Labels: tested

#26828 Rename type parameter for join and joinMat in Flow instance
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#27544 Add akka-protobuf-v3 to version check
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: tested

#27585 [Only] Deprecate Persistent mode of Cluster Sharding
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested
