Repository akka/akka, pull requests merged in 2019-05, with the labels that each got.

#26839 Add backport steps to CONTRIBUTING.md #26837
  CONTRIBUTING.md
Labels: tested

#26835 Handle CoordinatedShutdown exiting-completed when not joined, #26832
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested, to-be-backported

#26840 Remove unicode arrow
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#26843 Handle CoordinatedShutdown exiting-completed when not joined, #26832
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: backport, tested

#26769 Remove akka-contrib
  akka-contrib/README.md
  akka-contrib/src/main/resources/reference.conf
  akka-contrib/src/main/scala/akka/contrib/circuitbreaker/CircuitBreakerProxy.scala
  akka-contrib/src/main/scala/akka/contrib/circuitbreaker/askExtensions.scala
  akka-contrib/src/main/scala/akka/contrib/jul/JavaLogger.scala
  akka-contrib/src/main/scala/akka/contrib/mailbox/PeekMailbox.scala
  akka-contrib/src/main/scala/akka/contrib/pattern/Aggregator.scala
  akka-contrib/src/main/scala/akka/contrib/pattern/ReceivePipeline.scala
  akka-contrib/src/main/scala/akka/contrib/pattern/ReliableProxy.scala
  akka-contrib/src/main/scala/akka/contrib/throttle/TimerBasedThrottler.scala
  akka-contrib/src/multi-jvm/scala/akka/contrib/pattern/ReliableProxySpec.scala
  akka-contrib/src/test/java/akka/contrib/pattern/ReliableProxyTest.java
  akka-contrib/src/test/java/akka/contrib/throttle/TimerBasedThrottlerTest.java
  akka-contrib/src/test/resources/reference.conf
  akka-contrib/src/test/scala/akka/contrib/circuitbreaker/sample/CircuitBreaker.scala
  akka-contrib/src/test/scala/akka/contrib/jul/JavaLoggerSpec.scala
  akka-contrib/src/test/scala/akka/contrib/mailbox/PeekMailboxSpec.scala
  akka-contrib/src/test/scala/akka/contrib/pattern/AggregatorSpec.scala
  akka-contrib/src/test/scala/akka/contrib/pattern/ReceivePipelineSpec.scala
  akka-contrib/src/test/scala/akka/contrib/pattern/ReliableProxyDocSpec.scala
  akka-contrib/src/test/scala/akka/contrib/throttle/TimerBasedThrottleTest.scala
  akka-contrib/src/test/scala/akka/contrib/throttle/TimerBasedThrottlerSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  build.sbt
  project/Dependencies.scala
  project/OSGi.scala
Labels: 2 - pick next, tested

#26799 Increase timeout to fix PersistentActorJavaDslTest
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
Labels: tested

#26847 remove Future from StreamRefs mat val, #24372
  akka-bench-jmh/src/main/scala/akka/stream/SourceRefBenchmark.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/stream/stream-refs.md
  akka-docs/src/test/java/jdocs/stream/FlowStreamRefsDocTest.java
  akka-docs/src/test/scala/docs/stream/FlowStreamRefsDocSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SinkRefImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala
  akka-stream/src/main/scala/akka/stream/javadsl/StreamRefs.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamRefs.scala
Labels: 2 - pick next, tested

#26822 Removes the redundant val/final modifier in akka.dispatch/routing
  akka-actor/src/main/scala/akka/actor/ActorSelection.scala
  akka-actor/src/main/scala/akka/actor/Deployer.scala
  akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala
  akka-actor/src/main/scala/akka/dispatch/Dispatchers.scala
  akka-actor/src/main/scala/akka/dispatch/ForkJoinExecutorConfigurator.scala
  akka-actor/src/main/scala/akka/dispatch/Mailbox.scala
  akka-actor/src/main/scala/akka/dispatch/Mailboxes.scala
  akka-actor/src/main/scala/akka/dispatch/ThreadPoolBuilder.scala
  akka-actor/src/main/scala/akka/dispatch/affinity/AffinityPool.scala
  akka-actor/src/main/scala/akka/event/Logging.scala
  akka-actor/src/main/scala/akka/io/Dns.scala
  akka-actor/src/main/scala/akka/routing/Balancing.scala
  akka-actor/src/main/scala/akka/routing/Broadcast.scala
  akka-actor/src/main/scala/akka/routing/ConsistentHashing.scala
  akka-actor/src/main/scala/akka/routing/Listeners.scala
  akka-actor/src/main/scala/akka/routing/Resizer.scala
  akka-actor/src/main/scala/akka/routing/RoundRobin.scala
  akka-actor/src/main/scala/akka/routing/Router.scala
  akka-actor/src/main/scala/akka/routing/ScatterGatherFirstCompleted.scala
  akka-actor/src/main/scala/akka/routing/SmallestMailbox.scala
  akka-actor/src/main/scala/akka/routing/TailChopping.scala
Labels: tested

#26759 Clean up paradox output
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/guide/actors-intro.md
  akka-docs/src/main/paradox/project/migration-guide-2.4.x-2.5.x.md
  akka-docs/src/main/paradox/security/2017-02-10-java-serialization.md
  akka-docs/src/main/paradox/typed/guide/actors-intro.md
  build.sbt
  project/plugins.sbt
Labels: tested

#26845 Remove Timing operator
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream-tests/src/test/scala/akka/stream/extra/FlowTimedSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/extra/Implicits.scala
  akka-stream/src/main/scala/akka/stream/extra/Timed.scala
Labels: tested

#26851 Fix config blocks in classic remoting docs
  akka-cluster-metrics/src/multi-jvm/scala/akka/cluster/metrics/sample/StatsSampleSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGetStatsSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingLeavingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesNewExtractorSpec.scala
  akka-docs/src/main/paradox/remoting.md
Labels: tested

#26831 Remove remainings of actorFor, #26190
  akka-actor-tests/src/test/scala/akka/actor/ActorLookupSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/LocalActorRefProviderSpec.scala
  akka-actor-tests/src/test/scala/akka/pattern/AskSpec.scala
  akka-actor-tests/src/test/scala/akka/routing/ConfiguredLocalRoutingSpec.scala
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-actor/src/main/scala/akka/actor/ActorPath.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-remote/src/main/mima-filters/2.5.x.backwards.excludes
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteActorForSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteMessageSerializationSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteDeathWatchSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemotingSpec.scala
Labels: 2 - pick next, tested

#26816 Internal dispatcher to protect against starvation
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemDispatcherSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala
  akka-actor-tests/src/test/scala/akka/config/ConfigSpec.scala
  akka-actor-tests/src/test/scala/akka/dispatch/DispatcherShutdownSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Dispatchers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala
  akka-actor/src/main/scala/akka/dispatch/Dispatchers.scala
  akka-cluster-metrics/src/main/resources/reference.conf
  akka-cluster-metrics/src/main/scala/akka/cluster/metrics/ClusterMetricsSettings.scala
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-tools/src/main/resources/reference.conf
  akka-cluster-tools/src/main/scala/akka/cluster/client/ClusterClient.scala
  akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonProxy.scala
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/DistributedData.scala
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/ClusterSettings.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterConfigSpec.scala
  akka-coordination/src/main/scala/akka/coordination/lease/javadsl/LeaseProvider.scala
  akka-discovery/src/main/scala/akka/discovery/aggregate/AggregateServiceDiscovery.scala
  akka-discovery/src/main/scala/akka/discovery/dns/DnsServiceDiscovery.scala
  akka-distributed-data/src/main/resources/reference.conf
  akka-distributed-data/src/main/scala/akka/cluster/ddata/DurableStore.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializer.scala
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-remote/src/main/scala/akka/remote/Remoting.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/ArteryAeronUdpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/main/scala/akka/remote/transport/AbstractTransportAdapter.scala
  akka-remote/src/main/scala/akka/remote/transport/FailureInjectorTransportAdapter.scala
  akka-stream-tests/src/test/scala/akka/stream/StreamDispatcherSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/FileSourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/AttributesSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkAsJavaStreamSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceAsyncSourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceSourceSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/resources/reference.conf
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSinks.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSources.scala
  akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala
Labels: 2 - pick next, tested

#26830 Run CoordinatedShutdown from ActorSystem.terminate #25213
  akka-actor-tests/src/test/scala/akka/actor/CoordinatedShutdownSpec.scala
  akka-actor-tests/src/test/scala/akka/config/ConfigSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/GuardianStartupBehavior.scala
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-typed/src/test/java/akka/cluster/typed/ClusterApiTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorSystemSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterApiSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterSingletonPersistenceSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/InitialMembersOfNewDcSpec.scala
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/general/actor-systems.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-multi-node-testkit/src/main/scala/akka/remote/testkit/MultiNodeSpec.scala
Labels: 2 - pick next, tested

#26844 Remove docs for ActorPub/Sub and write persistence query docs as stages
  akka-bench-jmh-typed/src/main/scala/akka/actor/typed/TypedBenchmarkActors.scala
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/stream/stream-integrations.md
  akka-docs/src/test/java/jdocs/persistence/PersistenceQueryDocTest.java
  akka-docs/src/test/java/jdocs/persistence/query/MyEventsByTagJavaPublisher.java
  akka-docs/src/test/java/jdocs/persistence/query/MyEventsByTagSource.java
  akka-docs/src/test/java/jdocs/stream/ActorPublisherDocTest.java
  akka-docs/src/test/java/jdocs/stream/ActorSubscriberDocTest.java
  akka-docs/src/test/scala/docs/persistence/query/MyEventsByTagPublisher.scala
  akka-docs/src/test/scala/docs/persistence/query/MyEventsByTagSource.scala
  akka-docs/src/test/scala/docs/persistence/query/PersistenceQueryDocSpec.scala
  akka-docs/src/test/scala/docs/stream/ActorPublisherDocSpec.scala
  akka-docs/src/test/scala/docs/stream/ActorSubscriberDocSpec.scala
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/ActorPublisherTest.scala
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/ActorSubscriberTest.scala
  akka-stream-tests/src/test/java/akka/stream/actor/ActorPublisherTest.java
  akka-stream-tests/src/test/java/akka/stream/actor/ActorSubscriberTest.java
  akka-stream-tests/src/test/scala/akka/stream/actor/ActorPublisherSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/actor/ActorSubscriberSpec.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/actor/ActorPublisher.scala
  akka-stream/src/main/scala/akka/stream/actor/ActorSubscriber.scala
Labels: 2 - pick next, tested

#26860 cleanup migration guide
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#26861 Be more explicit that a node is shutting down as it was marked as DOWN
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested

#26862 internal-dispatcher in akka.cluster.StartupWithOneThreadSpec
  akka-cluster/src/test/scala/akka/cluster/StartupWithOneThreadSpec.scala
Labels: tested

#26856 ResetSystemMessageSeqNrSpec should not run with classic remoting, #26849
  akka-remote/src/test/scala/akka/remote/artery/ArteryMultiNodeSpec.scala
Labels: tested

#26872 fix changed idle-cpu-level property in LatencySpec
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/aeron/AeronStreamLatencySpec.scala
Labels: tested

#26874 Backport down log improvements
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested

#26868 Use java.lang.StringBuilder to format timestamp
  akka-actor-tests/src/test/scala/akka/event/LoggerSpec.scala
  akka-actor/src/main/scala/akka/util/Helpers.scala
Labels: tested, to-be-backported

#26875 Update typesafe config to 1.3.4
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  project/Dependencies.scala
Labels: tested

#26105 =str defer calling SSLEngine.closeOutbound until after handshake
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
Labels: 2 - pick next, tested, to-be-backported

#26420 act: avoid ReceiveTimeout handling in hot path if no receive timeout is set
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-actor/src/main/scala/akka/actor/dungeon/ReceiveTimeout.scala
Labels: tested

#26883 Backport #26105 to release-2.5
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
Labels: backport, tested

#26879 Use java.lang.StringBuilder to format timestamp, #26842
  akka-actor-tests/src/test/scala/akka/event/LoggerSpec.scala
  akka-actor/src/main/scala/akka/util/Helpers.scala
Labels: backport, tested

#26838 Promote ApiMayChange features #26532
  akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala
  akka-remote/src/main/scala/akka/remote/transport/netty/SSLEngineProvider.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Tcp.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#26885 Update CONTRIBUTING.md to current release branches
  CONTRIBUTING.md
Labels: tested

#26423 actor: Potential systemQueuePut improvement
  akka-actor/src/main/scala/akka/dispatch/Mailbox.scala
Labels: tested

#26864 Adds parentheses to method that has side-effect
  akka-actor/src/main/scala/akka/actor/AbstractProps.scala
  akka-actor/src/main/scala/akka/actor/Actor.scala
  akka-actor/src/main/scala/akka/actor/ActorPath.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/FSM.scala
  akka-actor/src/main/scala/akka/actor/IndirectActorProducer.scala
  akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala
  akka-actor/src/main/scala/akka/actor/RepointableActorRef.scala
  akka-actor/src/main/scala/akka/actor/dungeon/ChildrenContainer.scala
  akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala
  akka-actor/src/main/scala/akka/actor/dungeon/Dispatch.scala
  akka-actor/src/main/scala/akka/actor/dungeon/FaultHandling.scala
  akka-actor/src/main/scala/akka/actor/dungeon/ReceiveTimeout.scala
  akka-actor/src/main/scala/akka/dispatch/ForkJoinExecutorConfigurator.scala
  akka-actor/src/main/scala/akka/dispatch/Mailbox.scala
  akka-actor/src/main/scala/akka/event/Logging.scala
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
  akka-actor/src/main/scala/akka/util/LockUtil.scala
  akka-actor/src/main/scala/akka/util/Reflect.scala
Labels: tested

#26701 Clarify docs for Flow.ask generic parameter
  akka-bench-jmh/src/main/scala/akka/stream/AskBenchmark.scala
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/ask.md
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: tested

#26873 Typed receptionist clashes with the clusterclient receptionist
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/receptionist/LocalReceptionistSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#26891 Include includes in 'behavior' snippets
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: tested

#26904 Disable LargeMessageClusterSpec for classic remoting, #26889
  akka-cluster/src/multi-jvm/scala/akka/cluster/LargeMessageClusterSpec.scala
Labels: tested

#26907 Fix formatting for supervision.md
  akka-docs/src/main/paradox/general/supervision.md
Labels: tested

#26898 Restart hooks ordered list format fix
  akka-docs/src/main/paradox/actors.md
Labels: tested

#26911 Determine temporary ports with SocketUtils
  akka-remote/src/test/scala/akka/remote/Ticket1978CommunicationSpec.scala
Labels: tested

#26916 Fix for UdpConnected actor going away on PortUnreachableException
  akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala
  akka-actor/src/main/scala/akka/io/UdpConnection.scala
Labels: tested

#26892 New ReceiveTimeout not applied if it was set while handling a messag…
  akka-actor-tests/src/test/scala/akka/actor/ReceiveTimeoutSpec.scala
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-actor/src/main/scala/akka/actor/dungeon/ReceiveTimeout.scala
Labels: tested

#26924 Wrong link in doc, also directs to bad URL #26823
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-docs/src/main/paradox/cluster-routing.md
  akka-docs/src/main/paradox/cluster-usage.md
Labels: backport, tested

#26925 Test for WatchWith had a race
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
Labels: tested

#26928 Fix for UdpConnected actor going away on PortUnreachableException
  akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala
  akka-actor/src/main/scala/akka/io/UdpConnection.scala
Labels: backport, tested

#26913 Make Java FlowWithContext deal in Pairs
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowWithContextTest.java
  akka-stream/src/main/mima-filters/2.5.22.backwards.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContext.scala
Labels: tested, to-be-backported

#26917 Some more internal-dispatcher usages, #26915
  akka-actor/src/main/scala/akka/event/EventStreamUnsubscriber.scala
  akka-actor/src/main/scala/akka/io/SelectionHandler.scala
  akka-actor/src/main/scala/akka/io/Udp.scala
  akka-actor/src/main/scala/akka/io/UdpConnected.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/LatencySpec.scala
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
Labels: tested

#26921 persistentId -> persistenceId
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala
Labels: tested

#26914 Move incorrect deprecated annoation in BackoffSupervisor
  akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala
Labels: tested, to-be-backported

#26878 Improve performance of DDataShard stashing, #26877
  akka-cluster-sharding/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesPerfSpec.scala
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested, to-be-backported

#26923 Reduce DDataShardCoordinator memory usage during unreachability (#25444)
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested

#26931 Add ByteString.emptyByteString to Java API
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13-/akka/util/ByteString.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/java/jdocs/io/UdpConnectedDocTest.java
  akka-docs/src/test/java/jdocs/stream/BidiFlowDocTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeByteStrings.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeDecompress.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/TcpTest.java
Labels: 2 - pick next, tested, to-be-backported

#26940 Improve performance of DDataShard stashing, #26877
  akka-cluster-sharding/src/main/mima-filters/2.5.22.backwards.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesPerfSpec.scala
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-stream/src/main/mima-filters/2.5.22.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
Labels: backport, tested

#26938 Move incorrect deprecated annotation in BackoffSupervisor (#26914) for validation
  akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala
Labels: backport, tested

#26941 Add ByteString.emptyByteString to Java API
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13-/akka/util/ByteString.scala
  akka-docs/src/test/java/jdocs/io/UdpConnectedDocTest.java
  akka-docs/src/test/java/jdocs/stream/BidiFlowDocTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeByteStrings.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeDecompress.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/TcpTest.java
Labels: backport, tested

#26477 Add setup operator
  akka-docs/src/main/paradox/stream/operators/Sink/setup.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/setup.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/SetupTest.java
  akka-stream-tests/src/test/scala/akka/stream/DslFactoriesConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SetupSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/SetupStage.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested, to-be-backported

#26692 Adds EventSourcedEntity with EnforcingReplies
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/EventSourcedEntity.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/EventSourcedEntity.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ClusterShardingPersistenceTest.java
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ShardingEventSourcedEntityWithEnforcedRepliesCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/HelloWorldEventSourcedEntityExampleTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/HelloWorldPersistentEntityExample.java
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#26929 Java interop via for FlowWithContext
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowWithContextTest.java
  akka-stream/src/main/mima-filters/2.5.22.backwards.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContext.scala
Labels: backport, tested

#26893 act: remove shaded fork join pool implementation
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/RoutingLogic.scala
  akka-actor/src/main/java/akka/dispatch/forkjoin/ForkJoinPool.java
  akka-actor/src/main/java/akka/dispatch/forkjoin/ForkJoinTask.java
  akka-actor/src/main/java/akka/dispatch/forkjoin/ForkJoinWorkerThread.java
  akka-actor/src/main/java/akka/dispatch/forkjoin/LinkedTransferQueue.java
  akka-actor/src/main/java/akka/dispatch/forkjoin/RecursiveAction.java
  akka-actor/src/main/java/akka/dispatch/forkjoin/RecursiveTask.java
  akka-actor/src/main/java/akka/dispatch/forkjoin/ThreadLocalRandom.java
  akka-actor/src/main/java/akka/dispatch/forkjoin/TransferQueue.java
  akka-actor/src/main/java/akka/dispatch/forkjoin/package-info.java
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/dispatch/ForkJoinExecutorConfigurator.scala
  akka-actor/src/main/scala/akka/dispatch/Mailbox.scala
  akka-actor/src/main/scala/akka/dispatch/ThreadPoolBuilder.scala
  akka-docs/src/main/paradox/guide/tutorial_1.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#26700 Gracefully handle exception throw in SnapshotOffer
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotDecodeFailureSpec.scala
Labels: tested, to-be-backported

#26952 Gracefully handle exception throw in SnapshotOffer, #26699
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotDecodeFailureSpec.scala
Labels: backport, tested

#26961 Add setup operator
  akka-docs/src/main/paradox/stream/operators/Sink/setup.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/setup.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/SetupTest.java
  akka-stream-tests/src/test/scala/akka/stream/DslFactoriesConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SetupSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/SetupStage.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: backport, tested

#26950 add InternalStableApi annotation, for validation
  akka-actor/src/main/java/akka/annotation/InternalStableApi.java
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
Labels: backport, tested

#26944 Rewrite some code for Scala 2.13
  akka-actor-tests/src/test/scala/akka/dispatch/PriorityDispatcherSpec.scala
  akka-actor-tests/src/test/scala/akka/dispatch/StablePriorityDispatcherSpec.scala
  akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala
  akka-actor/src/main/scala/akka/actor/FSM.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala
  akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala
  akka-stream/src/main/scala/akka/stream/Materializer.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Queue.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Queue.scala
  akka-testkit/src/test/scala/akka/testkit/TestActorRefSpec.scala
  akka-testkit/src/test/scala/akka/testkit/TestProbeSpec.scala
Labels: tested

#26962 Deliver buffered messages after passivation, #26957
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
Labels: 2 - pick next, tested, to-be-backported

#26959 akka.build.version property, #26958
  build.sbt
  project/AkkaBuild.scala
  project/TimeStampede.scala
Labels: 2 - pick next, tested, to-be-backported

#26960 akka.build.version property, #26958, for validation
  build.sbt
  project/AkkaBuild.scala
  project/TimeStampede.scala
Labels: 2 - pick next, backport, tested

#26633 Implements actorRef source variant with backpressure #17610
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRefWithAck.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRefWithAck.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/SourceOperators.scala
  akka-stream-tests/src/test/scala/akka/stream/DslFactoriesConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefBackpressureSourceSpec.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorSource.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorSource.scala
  akka-stream-typed/src/test/scala/akka/stream/typed/scaladsl/ActorSourceSinkSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefBackpressureSource.scala
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#26810 Wrap the system event stream with a typed ActorRef
  akka-actor-typed-tests/src/test/java/akka/actor/typed/eventstream/EventStreamTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/eventstream/EventStreamSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/eventstream/EventStream.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/EventStreamExtension.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/EventStreamAdapter.scala
Labels: tested

#26968 Deliver buffered messages after passivation, #26957
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
Labels: backport, tested

#26908 Snapshot when stages stopped incorrect and can cause crash
  akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala
Labels: tested, to-be-backported

#26969 fix ByteStringSpec for Scala 2.13, #26956
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/PrimitivesSerializationSpec.scala
Labels: tested, to-be-backported

#26976 Snapshot when stages stopped incorrect and can cause crash #26902
  akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala
Labels: backport, tested

#26978 fix ByteStringSpec for Scala 2.13, #26956
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/PrimitivesSerializationSpec.scala
Labels: backport, tested

#26979 actorRef source variant with backpressure #17610
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRefWithAck.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRefWithAck.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/SourceOperators.scala
  akka-stream-tests/src/test/scala/akka/stream/DslFactoriesConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefBackpressureSourceSpec.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorSource.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorSource.scala
  akka-stream-typed/src/test/scala/akka/stream/typed/scaladsl/ActorSourceSinkSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefBackpressureSource.scala
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: backport, tested

#26965 Unicode arrows
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/EventSourcedEntity.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/QueueSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SetupSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/SetupStage.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#26937 Update cluster-metrics.md
  akka-docs/src/main/paradox/cluster-metrics.md
Labels: tested

#26939 Remove extra cherrypick step from contributing
  CONTRIBUTING.md
Labels: tested

#26949 add InternalStableApi annotation
  akka-actor/src/main/java/akka/annotation/InternalStableApi.java
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
Labels: tested

#26945 Use Def.settings
  project/AkkaBuild.scala
Labels: tested

#26984 Discovery: clarify what versions migration applies to
  akka-docs/src/main/paradox/discovery/index.md
Labels: t:discovery, t:docs, tested

#26981 Deprecate Serialization.deserialize that takes parameter #25945
  akka-actor/src/main/scala/akka/serialization/Serialization.scala
Labels: tested

#26980 Deprecate akka.actor.TypedActor #25516
  akka-actor-tests/src/test/scala/akka/actor/TypedActorSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/supervision/SupervisionCompileOnly.scala
  akka-actor/src/main/scala/akka/actor/TypedActor.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-remote/src/test/scala/akka/remote/TypedActorRemoteDeploySpec.scala
Labels: tested

#26943 add missing unapply for response types in DData Typed, #26942
  akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/scaladsl/Replicator.scala
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
Labels: 2 - pick next, tested

#26918 More specific test timing expectations
  akka-actor-tests/src/test/scala/akka/pattern/BackoffOnRestartSupervisorSpec.scala
Labels: tested

#26995 update latestPatchOf25 to 2.5.23
  RELEASING.md
  akka-cluster-sharding/src/main/mima-filters/2.5.22.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.22.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  project/MiMa.scala
Labels: tested

#26986 update latestPatchOf25 and releasing.md
  RELEASING.md
  akka-stream/src/main/mima-filters/2.5.22.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  project/MiMa.scala
Labels: tested

#26997 specify travis safelist for branches
  .travis.yml
Labels: tested

#26890 Typed testing docs: imports and scalatest dependency
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/AsyncTestingExampleTest.java
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/AsyncTestingExampleSpec.scala
  akka-docs/src/main/paradox/typed/testing.md
  build.sbt
Labels: 2 - pick next, tested

#26922 fix a race condition in ClusterReadView #24710
  akka-cluster/src/main/mima-filters/2.5.x.backwards.excludes
  akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MinMembersBeforeUpSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiNodeClusterSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/TransitionSpec.scala
Labels: 2 - pick next, tested

#26990 Stash before getting first listing in group router
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/GroupRouterImpl.scala
Labels: 2 - pick next, tested

#26999 Hooks for Akka Persistence Typed lifecycle
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
Labels: 2 - pick next, tested

#26966 Don't branch while releasing
  project/scripts/release
Labels: 2 - pick next, tested

#26994 ClusterReceptionist using own ddata Replicator #26936
  akka-cluster-typed/src/main/resources/reference.conf
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSettings.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: 2 - pick next, tested

#26987 Routers.pool now takes a factory
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/RoutersTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/routers.md
Labels: 2 - pick next, tested

#26993 Add reason for deprecating TypedActor, #25516
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed-actors.md
  akka-docs/src/test/java/jdocs/actor/TypedActorDocTest.java
  akka-docs/src/test/scala/docs/actor/TypedActorDocSpec.scala
Labels: 2 - pick next, tested

#26972 Use function instead of scala partial function for java api #26970
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorSource.scala
  akka-stream-typed/src/test/java/akka/stream/typed/javadsl/ActorSourceSinkCompileTest.java
  akka-stream-typed/src/test/java/docs/akka/stream/typed/ActorSourceExample.java
Labels: 2 - pick next, tested

#26870 Jackson serializer as replacement for Java serialization, #24155
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/ActorRefModule.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/ActorSystemAccess.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/AddressModule.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/AkkaJacksonModule.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/FiniteDurationModule.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonMigration.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonModule.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestEventMigration.java
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestMessages.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/MySerializable.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v1/Customer.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v1/ItemAdded.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v1/OrderAdded.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/Address.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/Customer.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/CustomerMigration.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/ItemAdded.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/OrderPlaced.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/OrderPlacedMigration.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2b/ItemAdded.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2b/ItemAddedMigration.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2c/ItemAdded.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2c/ItemAddedMigration.java
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
  build.sbt
  project/Dependencies.scala
  project/OSGi.scala
Labels: 2 - pick next, tested

#27013 Specific minimal scheduler API for typed #26971
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/ManualTime.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestKitJunitResource.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitBase.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ManualTime.scala
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/AsyncTestingExampleTest.java
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/AsyncTestingExampleSpec.scala
  akka-actor-typed-tests/src/test/java/akka/actor/typed/SchedulerTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SchedulerSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/SpawnProtocolDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Scheduler.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/SchedulerAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AskPattern.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
Labels: 2 - pick next, tested

#27016 remove upload of whitesource report from release script, #26866
  project/scripts/release
Labels: 2 - pick next, tested

#27021 workaround in release script for missing Jackson dependency for Scala 2.13.0-RC2
  build.sbt
  project/scripts/release
Labels: 2 - pick next, validating

#27003 specify travis safelist for branches
  .travis.yml
Labels: tested

#26996 act: TcpConnection: ignore late signals from SelectionHandler while shutting down
  akka-actor/src/main/scala/akka/io/TcpConnection.scala
Labels: tested, to-be-backported

#26998 Fix typo in expanded SRV query
  akka-docs/src/main/paradox/discovery/index.md
Labels: tested

#27004 Various internal stable markers
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-remote/src/main/scala/akka/remote/RemoteTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/RemoteInstrument.scala
Labels: tested

#27023 Remove various features deprecated since 2.5.0
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-actor/src/main/scala/akka/actor/Extension.scala
  akka-actor/src/main/scala/akka/actor/UntypedActor.scala
  akka-actor/src/main/scala/akka/actor/UntypedActorWithStash.scala
  akka-actor/src/main/scala/akka/event/Logging.scala
  akka-actor/src/main/scala/akka/event/LoggingReceive.scala
  akka-bench-jmh/src/main/scala/akka/stream/FusedGraphsBenchmark.scala
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/java/jdocs/persistence/PersistenceMultiDocTest.java
  akka-persistence/src/main/mima-filters/2.5.x.backwards.excludes
  akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala
  akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
  akka-stream/src/main/mima-filters/2.5.x.backwards.excludes
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
Labels: tested

#27010 Delegate stop method on TestKitJunitResource
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestKitJunitResource.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/BehaviorTestKitTest.java
Labels: tested

#26796 Complete ZipLatest when upstream completes without emitting
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipLatestSpec.scala
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/ZipLatestWithApply.scala.template
Labels: tested, to-be-backported

#27036 Fix some documentation whitespace
  akka-discovery/src/test/scala/akka/discovery/dns/DnsDiscoverySpec.scala
Labels: tested

#27032 Use travis stages
  .travis.yml
Labels: tested

#27017 Make netty and aeron dependencies optional
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  build.sbt
  project/Dependencies.scala
Labels: tested

#27041 Complete ZipLatest when upstream completes without emitting
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipLatestSpec.scala
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/ZipLatestWithApply.scala.template
Labels: backport, tested

#27046 No printlns on my guard
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterSingletonImpl.scala
Labels: tested

#27045 Upgrade scalafmt to 2.0.0-RC7
  .scalafmt.conf
  akka-actor-tests/src/test/scala/akka/actor/LocalActorRefProviderSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/SchedulerSpec.scala
  akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerMTSpec.scala
  akka-cluster-metrics/src/main/scala/akka/cluster/metrics/Metric.scala
  akka-persistence/src/test/scala/akka/persistence/PersistenceSpec.scala
Labels: tested

#27027 Remove API may change from akka typed
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Props.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/TypedActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/guide/actors-intro.md
  akka-docs/src/main/paradox/typed/guide/actors-motivation.md
  akka-docs/src/main/paradox/typed/guide/index.md
  akka-docs/src/main/paradox/typed/guide/introduction.md
  akka-docs/src/main/paradox/typed/guide/modules.md
  akka-docs/src/main/paradox/typed/guide/tutorial.md
  akka-docs/src/main/paradox/typed/guide/tutorial_1.md
  akka-docs/src/main/paradox/typed/guide/tutorial_2.md
  akka-docs/src/main/paradox/typed/guide/tutorial_3.md
  akka-docs/src/main/paradox/typed/guide/tutorial_4.md
  akka-docs/src/main/paradox/typed/guide/tutorial_5.md
  akka-docs/src/main/paradox/typed/index.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/stream.md
  akka-docs/src/main/paradox/typed/testing.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  build.sbt
  project/MiMa.scala
Labels: tested

#27026 Remove ApiMayChange from coordination module
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-coordination/src/main/mima-filters/2.5.x.backwards.excludes
  akka-coordination/src/main/scala/akka/coordination/lease/LeaseException.scala
  akka-coordination/src/main/scala/akka/coordination/lease/LeaseSettings.scala
  akka-coordination/src/main/scala/akka/coordination/lease/LeaseUsageSettings.scala
  akka-coordination/src/main/scala/akka/coordination/lease/TimeoutSettings.scala
  akka-coordination/src/main/scala/akka/coordination/lease/javadsl/Lease.scala
  akka-coordination/src/main/scala/akka/coordination/lease/javadsl/LeaseProvider.scala
  akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/Lease.scala
  akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/LeaseProvider.scala
  akka-docs/src/main/paradox/coordination.md
  build.sbt
Labels: tested

#27022 Remove JavaTestkit
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-testkit/src/main/java/akka/testkit/JavaTestKit.java
  akka-testkit/src/main/mima-filters/2.5.x.backwards.excludes
  akka-testkit/src/main/scala/akka/testkit/TestKit.scala
  akka-testkit/src/test/scala/akka/testkit/JavaTestKitSpec.scala
Labels: tested

#27014 Don't log internal messages as an event
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
Labels: tested

#27012 Better indicator of ActorRefProvider implementation selection
  akka-actor-tests/src/test/scala/akka/actor/ProviderSelectionSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-testkit/src/test/scala/akka/testkit/AbstractSpec.scala
Labels: tested

#26795 Harden RemotingSpec: Retry if address is taken
  akka-remote/src/test/scala/akka/remote/classic/RemotingSpec.scala
Labels: tested

#27035 FJP starvation spec
  akka-actor-tests/src/test/scala/akka/dispatch/ForkJoinPoolStarvationSpec.scala
Labels: tested

#27028 Include fan-out operators in the operator index
  akka-docs/src/main/categories/fan-out-operators.md
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/stream/operators/Balance.md
  akka-docs/src/main/paradox/stream/operators/Broadcast.md
  akka-docs/src/main/paradox/stream/operators/Partition.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/alsoTo.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/divertTo.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/wireTap.md
  akka-docs/src/main/paradox/stream/operators/Unzip.md
  akka-docs/src/main/paradox/stream/operators/UnzipWith.md
  akka-docs/src/main/paradox/stream/operators/index.md
  project/StreamOperatorsIndexGenerator.scala
Labels: tested

#27058 Update links of moved modules to doc.akka.io
  akka-docs/src/main/paradox/additional/deploy.md
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-dc.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/common/other-modules.md
  akka-docs/src/main/paradox/coordination.md
  akka-docs/src/main/paradox/discovery/index.md
  akka-docs/src/main/paradox/guide/modules.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/typed/guide/modules.md
Labels: t:docs, tested
