Repository akka/akka, pull requests merged in 2019-02, with the labels that each got.

#26316 Typo in futures.md
  akka-docs/src/main/paradox/futures.md
Labels: tested

#26328 Fix log message
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
Labels: tested

#26333 Log ActorRef rather than just path for watch/unwatch
  akka-actor/src/main/scala/akka/io/dns/RecordType.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
Labels: tested

#26334 Make cluster logging even more standard
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterHeartbeat.scala
  akka-cluster/src/main/scala/akka/cluster/CrossDcClusterHeartbeat.scala
Labels: tested

#26312 Create stateful function only once in FlowWithContextOps.statefulMapConcat()
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
Labels: tested

#26317 Clarify Javadoc now needs jdk9+
  CONTRIBUTING.md
Labels: tested

#26268 Upgrade Aeron to 1.14.0
  project/Dependencies.scala
Labels: tested

#26315 Make copyUSAsciiStrToBytes more robust w.r.t. JDK for Java9+ #26286
  akka-actor/src/main/scala/akka/util/Unsafe.java
Labels: tested

#26337 build: detect adoptopenjdk java homes
  project/CrossJava.scala
Labels: tested

#26297 move "#start-stop"'s start line
  akka-docs/src/test/scala/tutorial_1/ActorHierarchyExperiments.scala
Labels: tested

#26254 Subtypes of state in typed persistence runThen Java API
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/Effect.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
Labels: tested

#26246 Add asJava/asScala to RunnableGraph
  akka-stream-tests/src/test/java/akka/stream/actor/ActorSubscriberTest.java
  akka-stream-tests/src/test/java/akka/stream/io/OutputStreamSourceTest.java
  akka-stream-tests/src/test/java/akka/stream/io/SinkAsJavaSourceTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/KillSwitchTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/RunnableGraphTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SinkTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/java/akka/stream/stage/StageTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RunnableGraphSpec.scala
  akka-stream/src/main/mima-filters/2.5.20.backward.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#26136 Fix race condition in StreamConverters.asOutputStream()
  akka-bench-jmh/src/main/scala/akka/stream/impl/OutputStreamSourceStageBenchmark.scala
  akka-stream-tests/src/test/scala/akka/stream/io/OutputStreamSourceSpec.scala
  akka-stream/src/main/mima-filters/2.5.20.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala
Labels: tested

#26343 Cover the unsafe string access optimizations with direct tests
  akka-actor-tests/src/test/scala/akka/util/AsciiStringCopySpec.scala
Labels: tested

#25831 Extract the layouts of the running streams as an AST
  akka-bench-jmh/src/main/scala/akka/stream/FlatMapConcatBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/MapAsyncBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/PartitionHubBenchmark.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/StreamTestKit.scala
  akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala
  akka-stream/src/main/mima-filters/2.5.20.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala
Labels: tested

#26363 fix format of verbose logging of cluster events
  akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterLogSpec.scala
Labels: 2 - pick next, tested

#26200 Logger class for typed actors
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorLoggingTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Logger.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/LoggerClass.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-bench-jmh/src/main/scala/akka/util/StackBench.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
Labels: tested

#26351 fix wrong log level of cluster debug logging
  akka-cluster/src/main/scala/akka/cluster/Cluster.scala
Labels: tested

#26352 fix typo: excpetion -> exception
  akka-actor-tests/src/test/scala/akka/actor/TypedActorSpec.scala
  akka-actor/src/main/mima-filters/2.5.21.backwards.excludes
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
Labels: tested

#26339 Stop singleton and shards when self MemberDowned, #26336
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerDownedSpec.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested

#26309 Make the AbstractBehavior builder mutable
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/BehaviorBuilderTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ReceiveBuilderTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/OOIntroTest.java
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AbstractBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/BehaviorBuilder.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ReceiveBuilder.scala
  akka-actor/src/main/scala/akka/japi/function/Function.scala
  akka-cluster-typed/src/test/java/akka/cluster/ddata/typed/javadsl/ReplicatorTest.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExampleTest.java
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
  akka-docs/src/test/java/jdocs/typed/tutorial_2/IotSupervisor.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/inprogress2/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceGroup.java
  akka-docs/src/test/java/jdocs/typed/tutorial_4/DeviceManager.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/Device.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceGroup.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceGroupQuery.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceManager.java
Labels: tested

#26346 Fix deadlock in FunctionRef, #26326
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
Labels: 2 - pick next, tested

#26366 Clean up old docker containers at start of a docker test
  akka-actor-tests/src/test/scala/akka/io/dns/DockerBindDnsService.scala
Labels: tested

#26357 Fix new compiler warning #26239, before adding automated fix for all new
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala
Labels: t:build, tested

#26342 Remove remoting deployment from artery docs
  akka-docs/src/main/paradox/remoting-artery.md
Labels: tested

#26369 Fix ActorLoggingSpec for Scala 2.11, #26368
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
Labels: tested

#26359 Trivial typo fix in Streams docs
  akka-docs/src/main/paradox/general/stream/stream-design.md
Labels: tested

#26374 Update mima version to 2.5.21
  project/MiMa.scala
Labels: tested

#26378 Kill/Stop container if still running from previous
  akka-actor-tests/src/test/scala/akka/io/dns/DockerBindDnsService.scala
Labels: 2 - pick next, tested

#26379 Fix test expectation for JDK 11, refs #26030
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
Labels: 2 - pick next, tested

#26391 fix 2.13 compilation error, SortedSet, #26382
  .travis.yml
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerDownedSpec.scala
Labels: tested

#26388 Create one SBT general task to run locally before pushing a PR #26157
  build.sbt
Labels: tested

#26394 second fix 2.13 compilation error, SortedSet, #26382
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerDownedSpec.scala
Labels: tested

#26350 Redefine the Factory type alias in ccompat
  akka-actor/src/main/mima-filters/2.5.20.backwards.excludes
  akka-actor/src/main/scala-2.13-/akka/util/ccompat/package.scala
Labels: tested

#26386 Adds log operator to Source/FlowWithContext
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextLogSpec.scala
  akka-stream/src/main/mima-filters/2.5.21.backwards.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
Labels: tested

#26398 fix more with reply types in persistence-typed examples
  akka-actor/src/main/mima-filters/2.5.20.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.21.backwards.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/CommandHandlerWithReply.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/AccountExampleWithCommandHandlersInState.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/AccountExampleWithEventHandlersInState.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/AccountExampleWithMutableState.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/AccountExampleWithNullState.java
Labels: tested

#26405 harden ClusterShardingPersistenceSpec by using onPostStop, #26230
  akka-actor/src/main/scala/akka/util/ConstantFun.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
Labels: 2 - pick next, tested

#26419 Reorder Source/FlowWithContext type parameters (#26345)
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextLogSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/WithContextUsageSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SourceWithContext.scala
Labels: tested

#26403 Small tweaks to all command aliases
  CONTRIBUTING.md
  build.sbt
Labels: tested

#26416 Harden RateTransformationDocSpec: Use test patience rather than hadcode
  akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala
Labels: 2 - pick next, tested

#26402 release flag 11 instead of 9, #26381
  project/Jdk9.scala
Labels: tested

#26407 Make the OO example use classes for all the behaviors for Java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/OOIntroTest.java
  akka-docs/src/main/paradox/typed/actors.md
Labels: tested

#26415 Harden PrimitiveStateSpec: Expect termination before starting next actor
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala
Labels: 2 - pick next, tested

#26414 Increase timeout for AsyncDnsResovlerSpec + dont use ImplicitSender
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsResolverSpec.scala
Labels: 2 - pick next, tested

#26413 Warn if serializers for Akka internal messages are replaced, #26373
  akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala
  akka-actor-tests/src/test/scala/other/SerializerOutsideAkkaPackage.scala
  akka-actor/src/main/scala/akka/serialization/Serialization.scala
Labels: tested

#26274 Support mutable state by stashing commands while storing snapshot, #25740
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/JournalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotMutableStateSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: tested

#26430 Cluster Sharding Steps
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: tested

#26376 WIP: Add more code discipline to the build #26206
  akka-actor-tests/src/test/scala/akka/actor/ExtensionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
  project/AkkaDisciplinePlugin.scala
  project/plugins.sbt
Labels: tested

#26380 Fix excludes for docs publish in release script
  project/scripts/release
Labels: tested

#26399 Cleanup various warnings in akka-stream
  akka-stream-tests/src/test/scala/akka/stream/impl/TraversalBuilderSpec.scala
  akka-stream/src/main/mima-filters/2.5.21.backwards.excludes
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/extra/Timed.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorProcessor.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorPublisher.scala
  akka-stream/src/main/scala/akka/stream/impl/Buffers.scala
  akka-stream/src/main/scala/akka/stream/impl/JsonObjectParser.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
  akka-stream/src/main/scala/akka/stream/impl/StreamLayout.scala
  akka-stream/src/main/scala/akka/stream/impl/TraversalBuilder.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphStages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
  akka-stream/src/main/scala/akka/stream/impl/io/FileSubscriber.scala
  akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#26444 Add html reports for Scoverage #26443
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26417 Use latest java 8 and automatically upgrade in future
  .travis.yml
Labels: tested
