Repository akka/akka, pull requests merged in 2019-04, with the labels that each got.

#26632 Add title and version to Scaladoc pages
  project/Doc.scala
Labels: t:docs, tested

#26645 remove State >: Null constraint in javadsl
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/EventSourcedEntity.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventHandler.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
Labels: 2 - pick next, tested

#26644 Change typed whenTerminated sig to Future[Done], #25647
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitSpec.scala
  akka-actor-typed-tests/src/test/java/akka/actor/typed/ActorSystemTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ExtensionsSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-cluster-typed/src/test/java/akka/cluster/typed/ClusterApiTest.java
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorSystemSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
Labels: 2 - pick next, tested

#26631 Fix links to Delta State Replicated Data Types paper
  akka-distributed-data/src/main/scala/akka/cluster/ddata/ReplicatedData.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
Labels: tested

#26641 Fix minor text omissions in actor docs
  akka-docs/src/main/paradox/actors.md
Labels: 2 - pick next, tested

#26643 include state in EventSourcedBehavior.receiveSignal, #26574
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/EventSourcedSignal.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RequestingRecoveryPermit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/SignalHandler.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/EventSourcedActorFailureTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/LoggerSourceTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/NullEmptyStateTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PrimitiveStateTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RecoveryPermitterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRecoveryTimeoutSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotMutableStateSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: 2 - pick next, tested

#26646 fix rolling update for ddata change, #26284
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializer.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializerSpec.scala
Labels: 2 - pick next, tested

#26649 Fix typo of DispatcherSelector's Scaladoc
  akka-actor-typed/src/main/scala/akka/actor/typed/Props.scala
Labels: tested

#26620 Link to SO answer on scaladoc link disambiguation
  CONTRIBUTING.md
Labels: tested

#26612 Typed docs: include the import in the code snippet where it is used
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/coexistence/UntypedWatchingTypedSpec.scala
  akka-docs/src/main/paradox/typed/coexisting.md
Labels: t:docs, t:typed, tested

#26500 Harden InactiveEntityPassivationSpec
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/InactiveEntityPassivationSpec.scala
Labels: tested

#26406 Use logger in typed intro docs examples
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/OOIntroTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/OOIntroSpec.scala
Labels: 2 - pick next, tested

#26608 unstashAll as terminal Effect, #26489
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EffectImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/Effect.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
Labels: 2 - pick next, tested

#26657 Fix coordination test 2.13.0-M5 #26636
  akka-actor-tests/src/test/scala/akka/actor/DynamicAccessSpec.scala
  akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/LeaseProvider.scala
Labels: tested

#26656 Remove Scala 2.11 from crossScalaVersions
  .travis.yml
  build.sbt
  project/AkkaBuild.scala
  project/Dependencies.scala
  project/scripts/release
Labels: 2 - pick next, tested

#26663 Declare Akka Typed ready for production, #26640
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/guide/actors-intro.md
  akka-docs/src/main/paradox/typed/guide/actors-motivation.md
  akka-docs/src/main/paradox/typed/guide/index.md
  akka-docs/src/main/paradox/typed/guide/introduction.md
  akka-docs/src/main/paradox/typed/guide/modules.md
  akka-docs/src/main/paradox/typed/guide/tutorial.md
  akka-docs/src/main/paradox/typed/guide/tutorial_1.md
  akka-docs/src/main/paradox/typed/guide/tutorial_2.md
  akka-docs/src/main/paradox/typed/guide/tutorial_3.md
  akka-docs/src/main/paradox/typed/guide/tutorial_4.md
  akka-docs/src/main/paradox/typed/guide/tutorial_5.md
  akka-docs/src/main/paradox/typed/index.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/stream.md
  akka-docs/src/main/paradox/typed/testing.md
Labels: 2 - pick next, tested

#26627 Make RetentionCritera evolvable, #26545
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/Retention.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedSettings.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RetentionCriteriaImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/RetentionCriteria.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/RetentionCriteria.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/RetentionCriteriaSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRetentionSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: 2 - pick next, tested

#26650 Always intercept TimerMsg, also when restarted, #26556
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/InterceptSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
Labels: 2 - pick next, tested

#26653 Untyped/Typed supervision
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/AdapterTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/coexistence/TypedSupervisingUntypedSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/coexistence/UntypedSupervisingTypedSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/adapter/AdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/coexistence/TypedWatchingUntypedSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorRefFactoryAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/PropsAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Adapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/adapter/package.scala
  akka-docs/src/main/paradox/typed/coexisting.md
Labels: 2 - pick next, tested

#26665 Declare Artery TCP ready for production, #26664
  akka-docs/src/main/paradox/remoting-artery.md
Labels: 2 - pick next, tested

#26660 Use sbt-paradox-apidoc plugin
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/stream/operators/RestartFlow/onFailuresWithBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartFlow/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSink/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSource/onFailuresWithBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSource/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/ask.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/main/paradox/stream/stream-customize.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  build.sbt
  project/ParadoxSupport.scala
  project/plugins.sbt
Labels: tested

#26642 Allow build to run on JDK 8
  project/AkkaBuild.scala
  project/Doc.scala
Labels: tested

#26670 addition about rolling update in Artery migration guide
  akka-docs/src/main/paradox/project/rolling-update.md
  akka-docs/src/main/paradox/remoting-artery.md
Labels: tested

#26565 Make compilation options for akka typed modules strict
  akka-cluster-typed/src/main/scala/akka/cluster/typed/ClusterSingleton.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/test/scala/akka/cluster/ddata/typed/scaladsl/ReplicatorSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorSystemSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/RemoteDeployNotAllowedSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExample.scala
  akka-stream-typed/src/test/scala/akka/stream/typed/scaladsl/ActorFlowSpec.scala
  akka-stream-typed/src/test/scala/akka/stream/typed/scaladsl/ActorSourceSinkSpec.scala
  akka-stream-typed/src/test/scala/akka/stream/typed/scaladsl/CustomGuardianAndMaterializerSpec.scala
  akka-stream-typed/src/test/scala/docs/akka/stream/typed/ActorSourceSinkExample.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26672 update latestPatchOf25 to 2.5.22
  project/MiMa.scala
Labels: tested

#26669 Correctly parse stream signatures
  project/ParadoxSupport.scala
Labels: 2 - pick next, tested

#26647 akka-cluster-tools compiler warnings as fatal errors
  akka-cluster-tools/src/main/scala/akka/cluster/client/ClusterClient.scala
  akka-cluster-tools/src/main/scala/akka/cluster/client/protobuf/ClusterClientMessageSerializer.scala
  akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala
  akka-cluster-tools/src/main/scala/akka/cluster/pubsub/protobuf/DistributedPubSubMessageSerializer.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonProxy.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/protobuf/ClusterSingletonMessageSerializer.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/TestLeaseActor.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/client/ClusterClientSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/pubsub/DistributedPubSubMediatorSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/pubsub/DistributedPubSubRestartSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerDownedSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerLeaseSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerStartupSpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/pubsub/DistributedPubSubMediatorDeadLettersSpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonLeavingSpeedSpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonProxySpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonRestart2Spec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonRestartSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26674 Guide for using artery udp inside a container
  akka-docs/src/main/paradox/remoting-artery.md
Labels: tested

#26680 Fix ByteIterator for 2.11 and 2.13
  akka-actor/src/main/scala-2.11/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.13+/akka/util/ByteIterator.scala
Labels: tested

#26682 update instructions for how to use Scalafmt in IntelliJ
  CONTRIBUTING.md
Labels: tested

#26686 remove obsolete Java serialization compat tests, #26677
  akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala
Labels: tested

#26683 Use ExecutionContext.parasitic for Scala 2.13, #26655
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: t:scala-2.13, tested

#26598 Use BenchTestSource in streams JMH benchmarks
  akka-bench-jmh/src/main/scala/akka/remote/artery/BenchTestSource.scala
  akka-bench-jmh/src/main/scala/akka/stream/FlatMapMergeBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/FlowMapBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/FramingBenchmark.scala
  akka-bench-jmh/src/main/scala/akka/stream/SourceRefBenchmark.scala
Labels: tested

#26668 Review follow ups for PR #26653
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/coexistence/UntypedSupervisingTypedSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorRefFactoryAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Adapter.scala
  akka-actor/src/main/scala/akka/util/ErrorMessages.scala
  akka-docs/src/main/paradox/typed/coexisting.md
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
Labels: tested

#26673 akka-stream compiler warnings as fatal errors
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowTakeSpec.scala
  akka-stream/src/main/mima-filters/2.5.22.backwards.excludes
  akka-stream/src/main/scala/akka/stream/Materializer.scala
  akka-stream/src/main/scala/akka/stream/StreamTcpException.scala
  akka-stream/src/main/scala/akka/stream/Transformer.scala
  akka-stream/src/main/scala/akka/stream/actor/ActorPublisher.scala
  akka-stream/src/main/scala/akka/stream/extra/Implicits.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorProcessor.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSinkActor.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/impl/FanIn.scala
  akka-stream/src/main/scala/akka/stream/impl/FanOut.scala
  akka-stream/src/main/scala/akka/stream/impl/Messages.scala
  akka-stream/src/main/scala/akka/stream/impl/Modules.scala
  akka-stream/src/main/scala/akka/stream/impl/ReactiveStreamsCompliance.scala
  akka-stream/src/main/scala/akka/stream/impl/TraversalBuilder.scala
  akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/impl/io/FileSubscriber.scala
  akka-stream/src/main/scala/akka/stream/impl/io/IOSources.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamPublisher.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSubscriber.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
  akka-stream/src/main/scala/akka/stream/impl/io/compression/GzipDecompressor.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SinkRefImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/StreamRefsMaster.scala
  akka-stream/src/main/scala/akka/stream/javadsl/BidiFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/javadsl/RestartFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/RestartSink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/RestartSource.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/StreamConverters.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Tcp.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Framing.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Materialization.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
  akka-stream/src/main/scala/com/typesafe/sslconfig/akka/AkkaSSLConfig.scala
  akka-stream/src/main/scala/com/typesafe/sslconfig/akka/SSLEngineConfigurator.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26654 akka-persistence compiler warnings as fatal errors
  akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/main/scala/akka/persistence/Persistence.scala
  akka-persistence/src/main/scala/akka/persistence/PersistencePlugin.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSMBase.scala
  akka-persistence/src/main/scala/akka/persistence/journal/EventAdapters.scala
  akka-persistence/src/main/scala/akka/persistence/journal/PersistencePluginProxy.scala
  akka-persistence/src/main/scala/akka/persistence/journal/ReplayFilter.scala
  akka-persistence/src/main/scala/akka/persistence/journal/japi/AsyncWriteJournal.scala
  akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbIdMapping.scala
  akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbJournal.scala
  akka-persistence/src/main/scala/akka/persistence/journal/leveldb/SharedLeveldbStore.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/MessageSerializer.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/SnapshotSerializer.scala
  akka-persistence/src/main/scala/akka/persistence/snapshot/local/LocalSnapshotStore.scala
  akka-persistence/src/test/scala/akka/persistence/AtLeastOnceDeliveryCrashSpec.scala
  akka-persistence/src/test/scala/akka/persistence/AtLeastOnceDeliveryFailureSpec.scala
  akka-persistence/src/test/scala/akka/persistence/AtLeastOnceDeliverySpec.scala
  akka-persistence/src/test/scala/akka/persistence/EndToEndEventAdapterSpec.scala
  akka-persistence/src/test/scala/akka/persistence/EventAdapterSpec.scala
  akka-persistence/src/test/scala/akka/persistence/EventSourcedActorDeleteFailureSpec.scala
  akka-persistence/src/test/scala/akka/persistence/EventSourcedActorFailureSpec.scala
  akka-persistence/src/test/scala/akka/persistence/ManyRecoveriesSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PerformanceSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorBoundedStashingSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorJournalProtocolSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorRecoveryTimeoutSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorStashingSpec.scala
  akka-persistence/src/test/scala/akka/persistence/RecoveryPermitterSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotRecoveryLocalStoreSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotSerializationSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotSpec.scala
  akka-persistence/src/test/scala/akka/persistence/TimerPersistentActorSpec.scala
  akka-persistence/src/test/scala/akka/persistence/fsm/PersistentFSMSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26648 akka-cluster-sharding compiler warnings as fatal errors
  akka-cluster-sharding/src/main/mima-filters/2.5.21.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.5.22.backwards.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/RemoveInternalClusterShardingData.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingMinMembersSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiDcClusterShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/AllAtOnceEntityRecoveryStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/CoordinatedShutdownShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RemoveInternalClusterShardingDataSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/SupervisionSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26678 Enable fatal warnings for cluster metrics and slf4j
  akka-cluster-metrics/src/main/scala/akka/cluster/metrics/Provision.scala
  akka-cluster-metrics/src/main/scala/akka/cluster/metrics/protobuf/MessageSerializer.scala
  akka-cluster-metrics/src/multi-jvm/scala/akka/cluster/metrics/ClusterMetricsExtensionSpec.scala
  akka-cluster-metrics/src/multi-jvm/scala/akka/cluster/metrics/ClusterMetricsRoutingSpec.scala
  akka-cluster-metrics/src/test/scala/akka/cluster/metrics/ClusterMetricsExtensionSpec.scala
  akka-cluster-metrics/src/test/scala/akka/cluster/metrics/EWMASpec.scala
  akka-cluster-metrics/src/test/scala/akka/cluster/metrics/MetricSpec.scala
  akka-cluster-metrics/src/test/scala/akka/cluster/metrics/MetricsCollectorSpec.scala
  akka-cluster-metrics/src/test/scala/akka/cluster/metrics/TestUtil.scala
  akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala
  akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggingFilterSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26702 Fix typo in documentation
  akka-docs/src/main/paradox/typed/testing.md
Labels: tested

#26695 Replace deprecated expectNoMsg with expectNoMessage
  akka-docs/src/test/scala/tutorial_4/DeviceGroupSpec.scala
Labels: tested

#26705 revert Shard constructor signature changes
  akka-cluster-sharding/src/main/mima-filters/2.5.22.backwards.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardSpec.scala
Labels: tested

#26472 Update Shape.scala
  akka-stream/src/main/scala/akka/stream/Shape.scala
Labels: tested

#26687 Replace WrappingBehavior with directly access of InterceptorImpl
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WrappingBehavior.scala
Labels: tested

#26715 Fix a typo in PoisonPill warning
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
Labels: tested

#26716 Compiler warnings for actor-testkit #26708
  akka-testkit/src/main/scala/akka/testkit/TestKit.scala
  akka-testkit/src/main/scala/akka/testkit/javadsl/TestKit.scala
Labels: tested

#26693 Fix akka-stream javadoc errors
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#26628 Remove ancient streams migration guide
  akka-docs/src/main/paradox/project/migration-guide-stream-1.0-2.x.md
  akka-docs/src/main/paradox/project/migration-guides.md
Labels: tested

#26707 Document interceptor instance sharing in typed
  akka-actor-typed/src/main/scala/akka/actor/typed/BehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
Labels: tested

#26726 Enable fatal warnings by default (with excludes)
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26732 replace unicode arrows again
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/LogMessagesSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/OOIntroSpec.scala
  akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingPersistenceSpec.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardSpec.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/TestLeaseActor.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerLeaseSpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/TestLease.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonLeaseSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorSystemSpec.scala
  akka-coordination/src/main/scala/akka/coordination/lease/TimeoutSettings.scala
  akka-coordination/src/main/scala/akka/coordination/lease/internal/LeaseAdapter.scala
  akka-coordination/src/main/scala/akka/coordination/lease/javadsl/LeaseProvider.scala
  akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/Lease.scala
  akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/LeaseProvider.scala
  akka-coordination/src/test/scala/akka/coordination/lease/scaladsl/LeaseProviderSpec.scala
  akka-discovery/src/main/scala/akka/discovery/Discovery.scala
  akka-discovery/src/test/scala/akka/discovery/LookupSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/DeltaPropagationSelectorSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializerSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/SignalHandler.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRetentionSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/FanoutProcessorSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySinkSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: tested

#26742 Long is not an Int, #26733
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteRestartedQuarantinedSpec.scala
Labels: tested

#26740 fix wrong BackoffOpts in ClusterSharding, #26724
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
Labels: tested

#26743 Support disable of join compat config check, #26719
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/ClusterSettings.scala
  akka-cluster/src/test/scala/akka/cluster/JoinConfigCompatCheckerSpec.scala
Labels: tested

#26741 Fix akka-actor-testkit-typed warnings
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestInboxImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestKitUtils.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/BehaviorTestKitTest.java
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitSpec.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/TestProbeSpec.scala
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/ScalaTestIntegrationExampleSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26721 - Support for null is mapAsync and fromCompletionStage was added. #25475
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapAsync.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapAsyncUnordered.md
  akka-docs/src/main/paradox/stream/operators/Source/fromCompletionStage.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapAsyncSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapAsyncUnorderedSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphStages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: tested

#26736 Fix warnings in akka-osgi
  akka-osgi/src/main/scala/akka/osgi/ActorSystemActivator.scala
  akka-osgi/src/main/scala/akka/osgi/OsgiActorSystemFactory.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26725 Remove future from discipline settings
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26717 Compartmentalize java version related properties into existing JavaVersion #26662
  project/AkkaBuild.scala
  project/AkkaDisciplinePlugin.scala
  project/CrossJava.scala
  project/Doc.scala
  project/Jdk9.scala
Labels: tested

#26746 fix SupervisorHierarchySpec failure (changed in warnings cleanup), #26734
  akka-actor-tests/src/test/scala/akka/actor/SupervisorHierarchySpec.scala
Labels: tested

#26749 Remove warnings in persistence query module
  akka-persistence-query/src/main/scala/akka/persistence/query/PersistenceQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/AllPersistenceIdsPublisher.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/DeliveryBuffer.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdPublisher.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagPublisher.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/scaladsl/LeveldbReadJournal.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/DummyReadJournal.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdSpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByTagSpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/TestActor.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26751 Remove warnings in akka stream testkit module
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/StreamTestKit.scala
  akka-stream-testkit/src/test/scala/akka/stream/testkit/TwoStreamsSetup.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphConcatSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergeLatestSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergePreferredSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergePrioritizedSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergeSortedSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergeSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipLatestWithSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipNSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipWithNSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipWithSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26738 Fix warnings in akka-actor-typed
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26747 Remove warnings in akka-cluster-sharding-typed
  akka-bench-jmh-typed/src/main/scala/akka/actor/typed/TypedBenchmarkActors.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingMessageExtractor.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardingSerializer.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/EventSourcedEntity.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingStateSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26748 Remove warnings in persistence typed module
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26758 Fix 'unmoored scaladoc comment' error
  akka-osgi/src/main/scala/akka/osgi/DefaultOSGiLogger.scala
Labels: tested

#26752 Fix remaining akka-testkit warnings
  akka-multi-node-testkit/src/main/mima-filters/2.5.22.backwards.excludes
  akka-testkit/src/main/scala/akka/testkit/TestActorRef.scala
  akka-testkit/src/main/scala/akka/testkit/TestEventListener.scala
  akka-testkit/src/main/scala/akka/testkit/TestKit.scala
  akka-testkit/src/main/scala/akka/testkit/package.scala
  akka-testkit/src/test/scala/akka/testkit/AkkaSpecSpec.scala
  akka-testkit/src/test/scala/akka/testkit/Coroner.scala
  akka-testkit/src/test/scala/akka/testkit/JavaTestKitSpec.scala
  akka-testkit/src/test/scala/akka/testkit/TestFSMRefSpec.scala
  akka-testkit/src/test/scala/akka/testkit/metrics/MemoryUsageSnapshotting.scala
  akka-testkit/src/test/scala/akka/testkit/metrics/MetricsKit.scala
  akka-testkit/src/test/scala/akka/testkit/metrics/MetricsKitSpec.scala
  akka-testkit/src/test/scala/akka/testkit/metrics/reporter/AkkaConsoleReporter.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26739 Remove warnings in akka-cluster
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/actor/dungeon/Dispatch.scala
  akka-cluster/src/main/mima-filters/2.5.22.backwards.excludes
  akka-cluster/src/main/scala/akka/cluster/AutoDown.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterActorRefProvider.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterHeartbeat.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala
  akka-cluster/src/main/scala/akka/cluster/CrossDcClusterHeartbeat.scala
  akka-cluster/src/main/scala/akka/cluster/DowningProvider.scala
  akka-cluster/src/main/scala/akka/cluster/JoinConfigCompatChecker.scala
  akka-cluster/src/main/scala/akka/cluster/Member.scala
  akka-cluster/src/main/scala/akka/cluster/MembershipState.scala
  akka-cluster/src/main/scala/akka/cluster/Reachability.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/main/scala/akka/cluster/routing/ClusterRouterConfig.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterDeathWatchSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/ConvergenceSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/LargeMessageClusterSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/LeaderElectionSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MinMembersBeforeUpSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcHeartbeatTakingOverSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSunnyWeatherSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiNodeClusterSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/NodeChurnSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/NodeMembershipSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/NodeUpSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RestartFirstSeedNodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RestartNode2Spec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RestartNode3Spec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RestartNodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/UnreachableNodeJoinsAgainSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/routing/ClusterConsistentHashingGroupSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/routing/ClusterRoundRobinSpec.scala
  akka-cluster/src/test/scala/akka/cluster/AutoDownSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterConfigSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDomainEventPublisherSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterHeartbeatSenderStateSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
  akka-cluster/src/test/scala/akka/cluster/DowningProviderSpec.scala
  akka-cluster/src/test/scala/akka/cluster/FailureDetectorPuppet.scala
  akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala
  akka-cluster/src/test/scala/akka/cluster/HeartbeatNodeRingPerfSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ReachabilityPerfSpec.scala
  akka-cluster/src/test/scala/akka/cluster/StartupWithOneThreadSpec.scala
  akka-cluster/src/test/scala/akka/cluster/VectorClockPerfSpec.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
  akka-cluster/src/test/scala/akka/cluster/routing/ClusterRouterSupervisorSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: tested

#26762 Fix regression in ClusterRoundRobinSpec
  akka-cluster/src/multi-jvm/scala/akka/cluster/routing/ClusterRoundRobinSpec.scala
Labels: tested

#26763 Fix akka-actor-typed scaladoc
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ExtensionsImpl.scala
Labels: tested

#26766 Fix expected serialized bytes for 2.13
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
Labels: tested

#26771 Allow TCP unbind to be invoked multiple times
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
Labels: tested

#26777 Update to sbt-scalafmt 2.0.0
  project/plugins.sbt
Labels: tested

#26760 Remove Scala 2.11 for Akka 2.6
  .travis.yml
  CONTRIBUTING.md
  RELEASING.md
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
  akka-actor-tests/src/test/scala/akka/util/LineNumberSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor/src/main/scala-2.11/akka/compat/Future.scala
  akka-actor/src/main/scala-2.11/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.12/akka/compat/Future.scala
  akka-actor/src/main/scala-2.13/akka/compat/Future.scala
  akka-docs/src/main/paradox/java8-compat.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-remote/src/main/scala/akka/remote/serialization/DaemonMsgCreateSerializer.scala
  build.sbt
  project/AkkaBuild.scala
  project/AkkaDisciplinePlugin.scala
  project/Dependencies.scala
  project/Jdk9.scala
  project/MiMa.scala
  project/scripts/release
  scripts/authors.scala
Labels: tested

#26778 Minor typo
  akka-docs/src/main/paradox/serialization.md
Labels: t:docs, tested

#26783 Add Travis build status badge and fix Scaladex latest version badge #26782
  README.md
Labels: tested

#26781 Drop MiMa filters for 2.4.x
  akka-actor/src/main/mima-filters/2.4.1.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.10.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.11.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.12.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.14.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.2.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.8.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.9.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.x.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.4.0.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.4.11.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.4.17.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.4.4.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.4.x.backwards.excludes
  akka-cluster-tools/src/main/mima-filters/2.4.17.backwards.excludes
  akka-cluster-tools/src/main/mima-filters/2.4.4.backwards.excludes
  akka-cluster-tools/src/main/mima-filters/2.4.7.backwards.excludes
  akka-cluster-tools/src/main/mima-filters/2.4.8.backwards.excludes
  akka-cluster/src/main/mima-filters/2.4.10.backwards.excludes
  akka-cluster/src/main/mima-filters/2.4.14.backwards.excludes
  akka-cluster/src/main/mima-filters/2.4.x.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.4.0.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.4.10.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.4.14.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.4.x.backwards.excludes
  akka-persistence/src/main/mima-filters/2.4.1.backwards.excludes
  akka-persistence/src/main/mima-filters/2.4.11.backwards.excludes
  akka-persistence/src/main/mima-filters/2.4.14.backwards.excludes
  akka-persistence/src/main/mima-filters/2.4.2.backwards.excludes
  akka-persistence/src/main/mima-filters/2.4.4.backwards.excludes
  akka-persistence/src/main/mima-filters/2.4.x.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.0.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.1.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.10.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.11.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.13.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.14.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.16.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.17.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.6.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.x.backwards.excludes
  akka-stream-testkit/src/main/mima-filters/2.4.14.backwards.excludes
  akka-stream-testkit/src/main/mima-filters/2.4.x.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.10.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.11.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.12.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.14.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.17.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.2.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.4.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.6.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.7.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.8.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.9.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.x.backwards.excludes
  akka-testkit/src/main/mima-filters/2.4.16.backwards.excludes
  akka-testkit/src/main/mima-filters/2.4.9.backwards.excludes
  akka-testkit/src/main/mima-filters/2.4.x.backwards.excludes
Labels: tested

#26792 Fix race in ActorModelSpec
  akka-actor-tests/src/test/scala/akka/actor/dispatch/ActorModelSpec.scala
Labels: tested

#26794 Discards HandOverToMe in state End to avoid unhandled message warning
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
Labels: tested

#26798 Discards HandOverToMe in state End to avoid unhandled message warning #26793
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
Labels: backport, tested

#26727 Clarify scaladoc for restarting an infinite number of times
  akka-actor/src/main/scala/akka/actor/FaultHandling.scala
Labels: tested

#26661 Fixed documentation typos in DeviceGroup sample class
  akka-docs/src/test/java/jdocs/tutorial_4/DeviceGroup.java
Labels: tested

#26780 Attempt to fix multi-jvm failure when untyped system is adapted from typed system
  akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Conductor.scala
  akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala
Labels: tested, to-be-backported

#26803 Fix multi-jvm failure when untyped system is adapted from typed system
  akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Conductor.scala
  akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala
Labels: backport, tested

#26797 Speed up of framing spec
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FramingSpec.scala
Labels: tested

#26801 Fix typo in ShardingCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
Labels: tested

#26790 NoSerializationVerification for local discovery messages
  akka-discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
  akka-discovery/src/test/resources/reference.conf
Labels: tested, to-be-backported

#26804 update other modules page
  akka-docs/src/main/paradox/common/other-modules.md
Labels: tested, to-be-backported

#26791 Harden TestProbeSpec: increase short timeouts
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/TestProbeSpec.scala
Labels: tested

#26806 NoSerializationVerification for local discovery messages
  akka-discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
  akka-discovery/src/test/resources/reference.conf
Labels: backport, tested

#26807 update other modules page
  akka-docs/src/main/paradox/common/other-modules.md
Labels: backport, tested

#26767 Setup previousVersions for akka-coordination
  build.sbt
  project/MiMa.scala
Labels: tested

#26809 Setup previousVersions for akka-coordination
  build.sbt
  project/MiMa.scala
Labels: backport, tested

#26784 Remove actor dsl
  akka-actor-tests/src/test/java/akka/actor/InboxJavaAPITest.java
  akka-actor-tests/src/test/scala/akka/actor/ActorDSLSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ActorWithStashSpec.scala
  akka-actor/src/main/mima-filters/2.5.x.backwards.excludes
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/ActorDSL.scala
  akka-actor/src/main/scala/akka/actor/dsl/Creators.scala
  akka-actor/src/main/scala/akka/actor/dsl/Inbox.scala
  akka-contrib/src/test/scala/akka/contrib/circuitbreaker/CircuitBreakerProxySpec.scala
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/java/jdocs/actor/InboxDocTest.java
  akka-docs/src/test/scala/docs/actor/ActorDocSpec.scala
  akka-docs/src/test/scala/docs/io/EchoServer.scala
  project/AkkaBuild.scala
Labels: tested

#26808 Harden TestProbeSpec: increase short timeouts
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/TestProbeSpec.scala
Labels: backport, tested

#26805 cleanup migration guides toc
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/project/migration-guide-1.3.x-2.0.x.md
  akka-docs/src/main/paradox/project/migration-guide-2.0.x-2.1.x.md
  akka-docs/src/main/paradox/project/migration-guide-2.1.x-2.2.x.md
  akka-docs/src/main/paradox/project/migration-guide-2.2.x-2.3.x.md
  akka-docs/src/main/paradox/project/migration-guide-2.3.x-2.4.x.md
  akka-docs/src/main/paradox/project/migration-guide-2.4.x-2.5.x.md
  akka-docs/src/main/paradox/project/migration-guide-eventsourced-2.3.x.md
  akka-docs/src/main/paradox/project/migration-guide-old.md
  akka-docs/src/main/paradox/project/migration-guide-persistence-experimental-2.3.x-2.4.x.md
  akka-docs/src/main/paradox/project/migration-guide-stream-2.0-2.4.md
  akka-docs/src/main/paradox/project/migration-guides.md
Labels: tested

#26729 =str #25045 adding Java/Scala interop to SourceQueue and SinkQueue
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/QueueSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/QueueSourceSpec.scala
  akka-stream/src/main/mima-filters/2.5.22.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Queue.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Queue.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#26776 Remove akka-agent
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-agent/src/main/resources/reference.conf
  akka-agent/src/main/scala/akka/agent/Agent.scala
  akka-agent/src/test/scala/akka/agent/AgentSpec.scala
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/agents.md
  akka-docs/src/main/paradox/general/configuration.md
  akka-docs/src/main/paradox/index-futures.md
  akka-docs/src/main/paradox/index-utilities.md
  akka-docs/src/main/paradox/index.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/test/java/jdocs/agent/AgentDocTest.java
  akka-docs/src/test/scala/docs/agent/AgentDocSpec.scala
  build.sbt
  project/Dependencies.scala
  project/OSGi.scala
Labels: tested

#26820 Update r-b plugin
  project/plugins.sbt
Labels: tested

#26774 Move 'Remoting' under 'Clustering' in the docs
  akka-cluster/src/main/scala/akka/cluster/ClusterActorRefProvider.scala
  akka-cluster/src/test/scala/akka/cluster/AutoDownSpec.scala
  akka-docs/src/main/paradox/index-cluster.md
  akka-docs/src/main/paradox/index-network.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteSettings.scala
  akka-remote/src/test/scala/akka/remote/UntrustedSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/ArterySpecSupport.scala
Labels: tested

#26731 [#24220] Supports Supervision in Partition stage
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphPartitionSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: tested

#26756 ClusterSharding: increasing retry interval for registration call, #25191
  akka-cluster-sharding/src/main/mima-filters/2.5.22.backwards.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#26829 Show how to run plugin tck from java
  akka-docs/src/test/java/jdocs/persistence/LambdaPersistencePluginDocTest.java
Labels: tested

#26833 harden ClusterShardingPersistenceTest
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ClusterShardingPersistenceTest.java
Labels: tested

#26824 Wrong link in doc, also directs to bad URL #26823
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-docs/src/main/paradox/cluster-routing.md
  akka-docs/src/main/paradox/cluster-usage.md
Labels: tested

#26819 Enable passivate-idle-entity-after by default #25782
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/InactiveEntityPassivationSpec.scala
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested
