Repository akka/akka, pull requests merged in 2020-03, with the labels that each got.

#28660 Update mima to 0.7.0
  project/MiMa.scala
  project/plugins.sbt
Labels: tested

#28656 Update metrics-core, metrics-jvm to 4.1.4
  project/Dependencies.scala
Labels: dependency-change, tested

#28633 Clarify 'bug' gh tag is for potential prod issues
  CONTRIBUTING.md
Labels: tested

#28671 A missing rememberEntities in one test re-added
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
Labels: tested

#28598 Don't start journal when accessing event adapters, #28597
  akka-persistence/src/main/mima-filters/2.6.3.backwards.excludes/28597-lazy-journal.excludes
  akka-persistence/src/main/scala/akka/persistence/Persistence.scala
  akka-persistence/src/test/scala/akka/persistence/EndToEndEventAdapterSpec.scala
  akka-persistence/src/test/scala/akka/persistence/LoadPluginSpec.scala
Labels: tested

#28672 Race condition in typed AskSpec
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
Labels: tested

#28669 Add some nesting samples and clarifications to the docs
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/StyleGuideDocExamples.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#28356 Doc onFailureWithBackoff
  akka-docs/src/main/paradox/stream/operators/RestartSource/onFailuresWithBackoff.md
  akka-docs/src/test/java/jdocs/stream/operators/source/Restart.java
  akka-docs/src/test/scala/docs/stream/operators/source/Restart.scala
Labels: 2 - pick next, tested

#28643 Incorrect assumption in FlowFlatMapPrefixSpec
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
Labels: t:stream, tested

#28675 Eliminate logging race condition in ActorSystemSpec
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala
Labels: tested

#28662 Update to scalatest 3.1.1
  project/Dependencies.scala
  project/Paradox.scala
Labels: dependency-change, tested

#28680 Avoid SL4J noise by triggering logger init from single thread
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
Labels: tested

#28667 MapAsync wouldn't complete when upstream does in all scenarios
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapAsyncSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapAsyncUnorderedSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: t:stream, tested

#28686 stream: don't create AbruptTerminationException in happy case
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
Labels: t:stream, tested

#28682 Issue with the documentation for Partition
  akka-docs/src/test/scala/docs/stream/operators/PartitionDocExample.scala
Labels: tested

#28681 Allow closing StreamConverter InputStream twice
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamConvertersSpec.scala
  akka-stream/src/main/mima-filters/2.6.3.backwards.excludes/28681-allow-closing-inputstream-twice
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala
Labels: t:stream, tested

#28668 External sharding client handle empty DData key
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/internal/ExternalShardAllocationClientImpl.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/external/ExternalShardAllocationStrategySpec.scala
Labels: tested

#28690 Update aeron-client, aeron-driver to 1.26.0
  project/Dependencies.scala
Labels: dependency-change, tested

#28663 Improving the performance of ByteString.decodeString, and adding Byte…
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
  akka-actor/src/main/mima-filters/2.6.3.backwards.excludes/pr-28663-wip-bytestring-improvements-√.excludes
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13-/akka/util/ByteString.scala
Labels: tested, to-be-backported

#28704 Fix ambiguous reference to position in ByteBuffer/Buffer
  akka-actor/src/main/scala-2.13-/akka/util/ByteString.scala
Labels: tested

#28698 Improving the performance of ByteString.decodeString, and adding base64
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
  akka-actor/src/main/mima-filters/2.5.29.backwards.excludes/issue-28697-bytestring-improvements.excludes
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13-/akka/util/ByteString.scala
Labels: backport, tested

#28677 Reserve UPD or TPC ports according to artery config
  akka-remote-tests/src/test/scala/akka/remote/artery/ArteryFailedToBindSpec.scala
Labels: tested

#28705 Add CQRS page to docs
  akka-docs/src/main/paradox/typed/cqrs.md
  akka-docs/src/main/paradox/typed/index-persistence.md
Labels: tested

#28703 Fix takeWhile description
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/takeWhile.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/TakeWhile.scala
Labels: tested

#28678 Update jackson-databind to 2.10.3
  project/Dependencies.scala
Labels: 2 - pick next, dependency-change, tested

#28693 Docs: Sink.foreach
  akka-docs/src/main/paradox/stream/operators/Sink/foreach.md
  akka-docs/src/main/paradox/stream/operators/Sink/foreachAsync.md
  akka-docs/src/main/paradox/stream/operators/Sink/foreachParallel.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/SinkTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala
Labels: t:stream, tested

#28611 statefulMapConcat examples
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapConcat.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMapConcat.md
  akka-docs/src/test/java/jdocs/stream/operators/flow/StatefulMapConcat.java
  akka-docs/src/test/scala/docs/stream/operators/flow/StatefulMapConcat.scala
Labels: t:stream, tested

#28709 Fix ambiguous reference to position in ByteBuffer/Buffer
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
Labels: tested

#28688 Fix java leases usage from java and scala
  akka-coordination/src/main/mima-filters/2.6.4.backwards.excludes
  akka-coordination/src/main/scala/akka/coordination/lease/internal/LeaseAdapter.scala
  akka-coordination/src/main/scala/akka/coordination/lease/javadsl/LeaseProvider.scala
  akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/LeaseProvider.scala
  akka-coordination/src/test/java/jdocs/akka/coordination/lease/LeaseDocTest.java
  akka-coordination/src/test/scala/docs/akka/coordination/LeaseDocSpec.scala
Labels: 2 - pick next, tested

#28625 Distributed pubsub for typed
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/pubsub/PubSubExample.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/pubsub/LocalPubSubSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/pubsub/PubSubExample.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/pubsub/TopicImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/pubsub/Topic.scala
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ClusterMessages.java
  akka-cluster-typed/src/main/protobuf/ClusterMessages.proto
  akka-cluster-typed/src/main/resources/reference.conf
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AkkaClusterTypedSerializer.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiNodeTypedClusterSpec.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/PubSubSpec.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/internal/ClusterReceptionistUnreachabilitySpec.scala
  akka-docs/src/main/paradox/includes/cluster.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/distributed-pub-sub.md
  akka-docs/src/main/paradox/typed/persistence-testing.md
  build.sbt
Labels: 2 - pick next, tested

#28515 Clean up same thread execution contexts
  akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/CoordinatedShutdownSpec.scala
  akka-actor-tests/src/test/scala/akka/dispatch/ExecutionContextSpec.scala
  akka-actor-tests/src/test/scala/akka/dispatch/SameThreadExecutionContextSpec.scala
  akka-actor-tests/src/test/scala/akka/io/TcpIntegrationSpecSupport.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor/src/main/mima-filters/2.6.3.backwards.excludes/issue-26690-same-thread-execution-context.excludes
  akka-actor/src/main/scala-2.13+/akka/dispatch/internal/SameThreadExecutionContext.scala
  akka-actor/src/main/scala-2.13-/akka/dispatch/internal/SameThreadExecutionContext.scala
  akka-actor/src/main/scala/akka/actor/ActorSelection.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala
  akka-actor/src/main/scala/akka/dispatch/Future.scala
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
  akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
  akka-actor/src/main/scala/akka/pattern/GracefulStopSupport.scala
  akka-actor/src/main/scala/akka/routing/ScatterGatherFirstCompleted.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-remote/src/main/scala/akka/remote/artery/Handshake.scala
  akka-remote/src/main/scala/akka/remote/artery/SystemMessageDelivery.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/main/scala/akka/remote/transport/ThrottlerTransportAdapter.scala
  akka-remote/src/test/scala/akka/remote/artery/TestContext.scala
  akka-stream-tests/src/test/scala/akka/stream/io/FileSinkSpec.scala
  akka-stream/src/main/scala/akka/stream/KillSwitch.scala
  akka-stream/src/main/scala/akka/stream/impl/MaybeSource.scala
  akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/Unfold.scala
  akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphStages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Queue.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Tcp.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Queue.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-testkit/src/test/scala/akka/testkit/AkkaSpec.scala
Labels: 2 - pick next, tested

#28651 ShardedDaemonProcess
  akka-cluster-sharding-typed/src/main/resources/reference.conf
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardedDaemonProcessSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ShardedDaemonProcess.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ShardedDaemonProcess.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/ShardedDaemonProcessSpec.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ShardedDaemonProcessCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/resources/logback-test.xml
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ShardedDaemonProcessSpec.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-docs/src/main/paradox/common/may-change.md
  akka-docs/src/main/paradox/typed/cluster-sharded-daemon-process.md
  akka-docs/src/main/paradox/typed/index-cluster.md
  build.sbt
Labels: 2 - pick next, tested

#28714 doc: add link to video in CQRS page
  akka-docs/src/main/paradox/typed/cqrs.md
Labels: 2 - pick next, tested

#28713 Docs: use https links
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/stream/stream-io.md
Labels: tested

#28614 Fix ExplicitlyTriggeredScheduler cancellation
  akka-testkit/src/main/mima-filters/2.6.3.backwards.excludes/28604-fix-ExplicitlyTriggeredScheduler-cancellation.excludes
  akka-testkit/src/main/scala/akka/testkit/ExplicitlyTriggeredScheduler.scala
  akka-testkit/src/test/scala/akka/testkit/ExplicitlyTriggeredSchedulerSpec.scala
Labels: tested, to-be-backported

#28636 Cover adaptation failures with supervision
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/javadsl/AdaptationFailureSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/AdaptationFailureSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/MessageAndSignals.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ReceiveBuilder.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AbstractBehavior.scala
Labels: 2 - pick next, tested

#28715 Backport of sameThreadExecutionContext replacement method
  akka-actor/src/main/scala/akka/dispatch/Future.scala
Labels: 2 - pick next, tested

#28630 Adds ActorRef.ignore
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorRefIgnoreSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.3.backwards.excludes/28630-ActorRef-ignore.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorRef.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorRefResolver.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor/src/main/mima-filters/2.6.3.backwards.excludes/28630-ActorRef-ignore.excludes
  akka-actor/src/main/scala/akka/actor/ActorPath.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorRefIgnoreSerializationSpec.scala
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  build.sbt
Labels: tested

#28683 Update Source.actorRef sample to not use deprecated method
  akka-docs/src/main/paradox/stream/operators/Source/actorRef.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/SourceOperators.scala
Labels: tested

#28728 Always use the internal same thread execution context impl on Scala 2.12
  akka-actor/src/main/scala-2.13-/akka/dispatch/internal/SameThreadExecutionContext.scala
Labels: tested

#28731 SameThread ec test fix
  akka-actor-tests/src/test/scala/akka/dispatch/SameThreadExecutionContextSpec.scala
Labels: 2 - pick next, tested

#28730 fix unmoored doc comment in SequencedMessage
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/ConsumerController.scala
Labels: 2 - pick next, tested

#28733 Don't set -Yrangepos by default
  project/AkkaDisciplinePlugin.scala
Labels: tested

#28706 Update metrics-core, metrics-jvm to 4.1.5
  project/Dependencies.scala
Labels: dependency-change, tested

#28716 Mark journalFor and OptionVal InternalStableApi
  akka-actor/src/main/scala/akka/util/OptionVal.scala
  akka-persistence/src/main/scala/akka/persistence/Persistence.scala
Labels: tested

#28740 Avoid a duplicate link text.
  akka-docs/src/main/paradox/persistence.md
Labels: tested

#28737 fix format of RELEASING.md
  RELEASING.md
Labels: tested

#28727 add missing full stop
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
Labels: tested

#28750 Don't include event in PersistentRepr.toString
  akka-persistence/src/main/scala/akka/persistence/Persistent.scala
Labels: tested

#28692 Silencing multi-jvm shutdown error
  akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/Player.scala
Labels: tested

#28753 Doc example of Sink.ignore, #25468
  akka-docs/src/main/paradox/stream/operators/Sink/ignore.md
  akka-docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/sink/Ignore.scala
Labels: tested

#28745 Docs: Example on the as/fromJavaStream operators
  akka-docs/src/main/paradox/stream/operators/StreamConverters/asJavaStream.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/fromJavaStream.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/converters/StreamConvertersToJava.java
  akka-docs/src/test/scala/docs/stream/operators/converters/StreamConvertersToJava.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
Labels: t:stream, tested

#28760 Make running mima in PrValidation optional (default enabled)
  project/ValidatePullRequest.scala
Labels: backport, tested

#28749 Fix Mima in release-2.5
  project/MiMa.scala
  project/plugins.sbt
Labels: tested

#28726 Test jackson support for scala enumerations
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
Labels: tested

#28766 Too many demons
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ShardedDaemonProcessSpec.scala
Labels: tested

#28763 doc: Vector instead of List in daemon processes example
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ShardedDaemonProcessSpec.scala
Labels: tested

#28642 persistence: fix premature reset of the 'writeInProgress' flag in cas…
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence/src/main/mima-filters/2.6.4.backwards.excludes/28629-writeInProgress-race.excludes
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/main/scala/akka/persistence/JournalProtocol.scala
  akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala
  akka-persistence/src/main/scala/akka/persistence/journal/PersistencePluginProxy.scala
Labels: tested

#28754 Use Scala 2.12.11
  .travis.yml
  project/Dependencies.scala
Labels: dependency-change, tested

#28759 Allow a read of length 0 in InputStreamAdapter #28751
  akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSinkSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala
Labels: t:stream, tested

#26825 Persistence testkit implementation #15571
  akka-docs/src/main/paradox/general/configuration-reference.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/typed/persistence-testing.md
  akka-docs/src/test/java/jdocs/persistence/testkit/Configuration.java
  akka-docs/src/test/java/jdocs/persistence/testkit/TestKitExamples.java
  akka-docs/src/test/scala/docs/persistence/testkit/Configuration.scala
  akka-docs/src/test/scala/docs/persistence/testkit/TestKitExamples.scala
  akka-persistence-testkit/src/main/resources/reference.conf
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/EventStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/PersistenceTestKitPlugin.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/ProcessingPolicy.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/SnapshotStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/InMemStorageExtension.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SerializedEventStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SerializedSnapshotStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SimpleEventStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SimpleSnapshotStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SnapshotStorageEmulatorExtension.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/TestKitStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/SnapshotTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/TestOps.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/CommonUtils.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/CommonSnapshotTests.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/CommonTestKitTests.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/JavaDslUtils.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/SnapshotNotSerializeSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/SnapshotSerializeSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/TestKitNotSerializeSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/TestKitSerializeSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/CommonSnapshotTests.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/CommonTestKitTests.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/PersistenceTestKitJournalCompatSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/ScalaDslUtils.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/SnapshotNotSerializeSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/SnapshotSerializeSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/TestKitNotSerializeSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/TestKitSerializeSpec.scala
  akka-testkit/src/main/scala/akka/testkit/TestKit.scala
  akka-testkit/src/main/scala/akka/testkit/javadsl/TestKit.scala
  build.sbt
  project/Dependencies.scala
Labels: tested

#28770 Fix compiler error in project/Dependencies.scala
  project/Dependencies.scala
Labels: dependency-change, tested

#28578 Stream: Sugar for Sink.ignore
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowCompileSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: t:stream, tested

#28782 add example for Sink.head
  akka-docs/src/main/paradox/stream/operators/Sink/head.md
  akka-docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/HeadSinkSpec.scala
Labels: t:stream, tested

#28767 Remove FIXME and link to docs for typed pub sub
  akka-docs/src/main/paradox/distributed-pub-sub.md
Labels: tested

#27290 +act Add retry with new delay calculation support.
  akka-actor-tests/src/test/java/akka/pattern/PatternsTest.java
  akka-actor-tests/src/test/scala/akka/pattern/RetrySpec.scala
  akka-actor/src/main/scala/akka/pattern/Patterns.scala
  akka-actor/src/main/scala/akka/pattern/RetrySupport.scala
Labels: t:stream, tested

#28741 JMH bench and flight recorder for reliable delivery, #28725
  akka-actor-typed/src/main/scala-jdk-9/akka/actor/typed/internal/jfr/Events.scala
  akka-actor-typed/src/main/scala-jdk-9/akka/actor/typed/internal/jfr/JFRActorFlightRecorder.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ConsumerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ProducerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorFlightRecorder.scala
  akka-bench-jmh/src/main/resources/logback.xml
  akka-bench-jmh/src/main/scala/akka/actor/typed/delivery/ReliableDeliveryBenchmark.scala
  build.sbt
  project/Dependencies.scala
Labels: dependency-change, tested

#28791 Update to genjavadoc 0.16
  project/Doc.scala
Labels: tested

#28788 Minor conflate improvements
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/conflate.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/conflateWithSeed.md
  akka-docs/src/main/paradox/stream/stream-rate.md
Labels: tested

#28800 remove test config of old flight recorder
  akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterWatcherNoClusterWatcheeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiNodeClusterSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/RemoteFeaturesWithClusterSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemoteFeaturesSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/RemotingMultiNodeSpec.scala
  akka-remote/src/test/scala/akka/remote/RemoteFeaturesSpec.scala
Labels: tested

#28273 allow Source.queue concurrent pushing
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/QueueSourceSpec.scala
  akka-stream/src/main/mima-filters/2.6.3.backwards.excludes/28272-queue-source-concurrency.excludes
  akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: t:stream, tested

#28752 Doc example of Streams watch operator, #25468
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/watch.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Watch.scala
Labels: tested

#28814 Avoid jar cross-contamination by doing 3 separate buildRelease invocations
  project/Dependencies.scala
  project/scripts/release
Labels: dependency-change, tested

#28811 Update remoting.md
  akka-docs/src/main/paradox/remoting.md
Labels: tested

#28817 Remove last crossPaths occurrence
  build.sbt
  project/Protobuf.scala
Labels: tested

#28746 Docs: examples for io streams with StreamConverters
  akka-docs/src/main/paradox/stream/operators/StreamConverters/fromInputStream.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/fromJavaStream.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/fromOutputStream.md
  akka-docs/src/test/java/jdocs/stream/operators/converters/ToFromJavaIOStreams.java
  akka-docs/src/test/scala/docs/stream/operators/converters/ToFromJavaIOStreams.scala
  akka-stream/src/main/scala/akka/stream/javadsl/StreamConverters.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
Labels: t:stream, tested

#28793 Docs: TestKit leaking into Java getting started guide
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
Labels: tested

#28815 Publish snapshots to gustav with 'publish'
  project/Publish.scala
  project/scripts/release
Labels: validating

#28820 Create the git tag before releasing rather than during
  RELEASING.md
  project/scripts/release
Labels: tested

#28825 Updated incorrect comment
  akka-remote/src/main/scala/akka/remote/serialization/DaemonMsgCreateSerializer.scala
Labels: tested

#28827 mima: check against 2.6.4, and missing filters
  akka-actor-typed/src/main/mima-filters/2.6.4.backwards.excludes/reliable-delivery.excludes
  akka-stream/src/main/mima-filters/2.6.4.backwards.excludes/28272-source-queue.excludes
  project/MiMa.scala
Labels: t:stream, tested

#28823 [#28822] Don't advertise temporary references in the compression table
  akka-remote/src/main/scala/akka/remote/artery/compress/InboundCompressions.scala
Labels: tested

#28830 [DOC] Fix a GraphDSL example code to compile
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphOpsIntegrationSpec.scala
Labels: t:stream, tested

#28838 =act Add @inline Annotation.
  akka-actor/src/main/scala/akka/actor/package.scala
Labels: tested

#28813 =act Validate Actor class in Props.
  akka-actor/src/main/scala/akka/actor/AbstractProps.scala
Labels: tested

#28785 =str Don't create closure
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
Labels: t:stream, tested

#28832 Unstash to correct Beahviors.same when unstash in progress, #28831
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
Labels: tested

#28833 clear StashBuffer, #28786
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashBufferSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.4.backwards.excludes/issue-28786-stash-clear.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/StashBuffer.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/StashBuffer.scala
Labels: tested

#28828 Publish paradox/japi/api (snapshot) docs via sbt
  build.sbt
  project/AkkaBuild.scala
  project/Doc.scala
  project/Paradox.scala
  project/Publish.scala
  project/Release.scala
  project/scripts/release
Labels: tested

#28826 Operator docs: list watch as Actor interop
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/watch.md
  akka-docs/src/main/paradox/stream/operators/index.md
Labels: t:docs, t:stream, tested

#28821 #28810 Ensure no SubscriptionTimeout schedule leak in FanoutProcessorImpl
  akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala
Labels: t:stream, tested

#28847 Make ClassicActorSystemProvider.classicSystem public API
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/adapter/package.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/ClassicActorSystemProvider.scala
Labels: t:core, tested, to-be-backported

#28851 [Backport] Make ClassicActorSystemProvider.classicSystem public API
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/adapter/package.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/ClassicActorSystemProvider.scala
Labels: backport, t:core, tested
