Repository akka/akka, pull requests merged in 2020-05, with the labels that each got.

#28997 update latestPatchOf26 to 2.6.5
  akka-actor-typed/src/main/mima-filters/2.6.x.backwards.excludes/jfr.excludes
  project/MiMa.scala
Labels: 2 - pick next, tested

#28977 Don't generate JavaDoc noise, #28732
  project/Doc.scala
Labels: tested

#29011 Typo in "Basics and working with Flows"
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
Labels: tested

#28987 A stash that should have been buffer in shard
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
Labels: tested

#29004 Comment improvements on SSLConfigProvider reference.conf
  akka-remote/src/main/resources/reference.conf
Labels: tested

#29016 Update jackson-databind to 2.10.4
  project/Dependencies.scala
Labels: dependency-change, tested

#29017 Update metrics-core, metrics-jvm to 4.1.7
  project/Dependencies.scala
Labels: dependency-change, tested

#28580 Add necessary telemetry interceptors for Akka 2.6 AskPattern
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
Labels: tested

#28699 Bulk update of external shard allocation
  akka-cluster-sharding/src/main/mima-filters/2.6.5.backwards.excludes/shard-allocation-client.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/internal/ExternalShardAllocationClientImpl.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/javadsl/ExternalShardAllocationClient.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/scaladsl/ExternalShardAllocationClient.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ExternalShardAllocationSpec.scala
Labels: tested

#28637 Add necessary telemetry interceptors for Akka 2.5 AskPattern
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
Labels: tested

#29008 add Source.never
  akka-docs/src/main/paradox/stream/operators/Source/empty.md
  akka-docs/src/main/paradox/stream/operators/Source/never.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/NeverSourceSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: t:stream, tested

#29021 Final signature to apidoc review
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRef.md
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRef.md
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/Sink/actorRef.md
  akka-docs/src/main/paradox/stream/operators/Sink/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/Sink/fromMaterializer.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/ask.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/fromMaterializer.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/map.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/Source/from.md
Labels: tested

#29030 Update link-to-classic paragraph
  akka-docs/src/main/paradox/typed/actor-discovery.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/cluster-dc.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/cluster-singleton.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/distributed-pub-sub.md
  akka-docs/src/main/paradox/typed/fault-tolerance.md
  akka-docs/src/main/paradox/typed/fsm.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-docs/src/main/paradox/typed/mailboxes.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/reliable-delivery.md
  akka-docs/src/main/paradox/typed/routers.md
  akka-docs/src/main/paradox/typed/stash.md
  akka-docs/src/main/paradox/typed/testing-async.md
  akka-docs/src/main/paradox/typed/testing-sync.md
  akka-docs/src/main/paradox/typed/testing.md
Labels: tested

#28989 Log demand and nr of messages sent in delivery throughput sharding test
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/delivery/DeliveryThroughputSpec.scala
Labels: tested

#29027 Docs: sort out links
  akka-docs/src/main/paradox/actors.md
  akka-docs/src/main/paradox/additional/books.md
  akka-docs/src/main/paradox/additional/faq.md
  akka-docs/src/main/paradox/additional/operations.md
  akka-docs/src/main/paradox/additional/osgi.md
  akka-docs/src/main/paradox/additional/packaging.md
  akka-docs/src/main/paradox/cluster-client.md
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-docs/src/main/paradox/cluster-singleton.md
  akka-docs/src/main/paradox/cluster-usage.md
  akka-docs/src/main/paradox/common/other-modules.md
  akka-docs/src/main/paradox/distributed-data.md
  akka-docs/src/main/paradox/fsm.md
  akka-docs/src/main/paradox/general/actors.md
  akka-docs/src/main/paradox/general/message-delivery-reliability.md
  akka-docs/src/main/paradox/general/stream/stream-design.md
  akka-docs/src/main/paradox/io.md
  akka-docs/src/main/paradox/persistence-journals.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/project/examples.md
  akka-docs/src/main/paradox/project/immutable.md
  akka-docs/src/main/paradox/project/licenses.md
  akka-docs/src/main/paradox/project/links.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/project/migration-guide-old.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/routing.md
  akka-docs/src/main/paradox/security/2017-02-10-java-serialization.md
  akka-docs/src/main/paradox/serialization.md
  akka-docs/src/main/paradox/stream/operators/Flow/fromSinkAndSource.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/ask.md
  akka-docs/src/main/paradox/stream/reactive-streams-interop.md
  akka-docs/src/main/paradox/stream/stream-customize.md
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
  akka-docs/src/main/paradox/stream/stream-introduction.md
  akka-docs/src/main/paradox/stream/stream-refs.md
  akka-docs/src/main/paradox/testing.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/choosing-cluster.md
  akka-docs/src/main/paradox/typed/cluster-concepts.md
  akka-docs/src/main/paradox/typed/cluster-membership.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/distributed-data.md
  akka-docs/src/main/paradox/typed/guide/introduction.md
  akka-docs/src/main/paradox/typed/guide/modules.md
  akka-docs/src/main/paradox/typed/guide/tutorial_5.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/reliable-delivery.md
  akka-docs/src/main/paradox/typed/routers.md
  akka-docs/src/main/paradox/typed/style-guide.md
  project/project-info.conf
Labels: t:docs, tested

#29007 Improve grammar
  akka-docs/src/main/paradox/stream/stream-customize.md
Labels: t:docs, tested

#28990 Fix race condition in InputStreamSinkSpec
  akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSinkSpec.scala
Labels: t:stream, tested

#29019 Extra details around consistent hashing.
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#29002 Fix publishing credentials instructions
  project/scripts/release
Labels: tested

#29026 free memory when FunctionRef is stopped, #28959
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
Labels: tested

#29015 clarify ClusterSingletonProxy role docs
  akka-cluster-tools/src/main/resources/reference.conf
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonProxy.scala
Labels: tested

#28928 Step two of the CBOR serialization issue, #28927
  akka-serialization-jackson/src/main/resources/reference.conf
Labels: 2 - pick next, tested

#29020 Possibility to disable Artery ActorRef and manifest compression, #28967
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-remote/src/main/scala/akka/remote/artery/compress/TopHeavyHitters.scala
  akka-remote/src/test/scala/akka/remote/artery/compress/CompressionIntegrationSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/compress/HeavyHittersSpec.scala
Labels: tested

#29040 Improve grammar
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: t:docs, tested

#29042 Fix grammar
  CONTRIBUTING.md
Labels: tested

#29045 fix race condition in MessageAdapterSpec, #29044
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
Labels: tested

#29014 update protobuf 3.11.4
  akka-cluster-metrics/src/main/java/akka/cluster/metrics/protobuf/msg/ClusterMetricsMessages.java
  akka-cluster-sharding-typed/src/main/java/akka/cluster/sharding/typed/internal/protobuf/ShardingMessages.java
  akka-cluster-tools/src/main/java/akka/cluster/client/protobuf/msg/ClusterClientMessages.java
  akka-cluster-tools/src/main/java/akka/cluster/pubsub/protobuf/msg/DistributedPubSubMessages.java
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-multi-node-testkit/src/main/java/akka/remote/testconductor/TestConductorProtocol.java
  akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java
  akka-remote-tests/src/test/java/akka/remote/artery/protobuf/TestMessages.java
  akka-remote/src/main/java/akka/remote/ArteryControlFormats.java
  akka-remote/src/main/java/akka/remote/ContainerFormats.java
  akka-remote/src/main/java/akka/remote/SystemMessageFormats.java
  akka-remote/src/main/java/akka/remote/WireFormats.java
  akka-remote/src/test/java/akka/remote/ProtobufProtocol.java
  akka-remote/src/test/java/akka/remote/protobuf/v3/ProtobufProtocolV3.java
  akka-stream/src/main/java/akka/stream/StreamRefMessages.java
  project/Dependencies.scala
  project/Protobuf.scala
Labels: dependency-change, t:stream, tested

#29046 Clarification about receptionist subscription
  akka-docs/src/main/paradox/typed/actor-discovery.md
Labels: tested

#29032 Remove signature directive
  build.sbt
  project/ParadoxSupport.scala
Labels: tested

#29048 Cleanup reference to TLS1.3
  akka-remote/src/main/resources/reference.conf
Labels: tested

#29041 cancellable var -> private val
  akka-distributed-data/src/main/mima-filters/2.6.5.backwards.excludes/pr-29041-immutable-cancellable.excludes
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
Labels: tested

#28984 =build Fix commandAlias for fixall and sortImports
  .scalafix.conf
  akka-actor/src/main/scala-2.13/akka/compat/Future.scala
  akka-actor/src/main/scala-2.13/akka/dispatch/internal/SameThreadExecutionContext.scala
  akka-actor/src/main/scala-2.13/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.13/akka/util/ByteString.scala
  akka-actor/src/main/scala/akka/dispatch/affinity/AffinityPool.scala
  akka-actor/src/main/scala/akka/io/dns/DnsSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/internal/ExternalShardAllocationClientImpl.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterJmx.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/EventSourcedBehaviorTestKit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala
  akka-remote/src/main/scala/akka/remote/transport/netty/SSLEngineProvider.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteSendConsistencySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/DeprecatedTlsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/NeverSourceSpec.scala
  akka-stream/src/main/scala/akka/stream/SslTlsOptions.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TlsModule.scala
  akka-stream/src/main/scala/akka/stream/javadsl/TLS.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Tcp.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala
  akka-stream/src/main/scala/com/typesafe/sslconfig/akka/AkkaSSLConfig.scala
  akka-stream/src/main/scala/com/typesafe/sslconfig/akka/SSLEngineConfigurator.scala
  build.sbt
  project/ProjectFileIgnoreSupport.scala
  project/ScalaFixExtraRulesPlugin.scala
  project/ScalaFixForJdk9Plugin.scala
  project/ScalafixForMultiNodePlugin.scala
Labels: t:stream, tested

#29043 Coordinator ddata state store with persistent remember entities
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/CustomStateStoreModeProvider.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntities.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberShards.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingCustomShardAllocationSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGracefulShutdownSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingLeavingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingMinMembersSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesNewExtractorSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingConfig.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentStartEntitySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
Labels: tested

#29013 Additional testing of duplicated extensions
  akka-actor-tests/src/test/scala/akka/actor/ExtensionSpec.scala
  akka-actor-typed/src/main/resources/reference.conf
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-stream/src/main/resources/reference.conf
Labels: t:stream, tested

#29049 Review defaults for TLS algorithms defaults
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/test/scala/akka/remote/RemoteConfigSpec.scala
  akka-remote/src/test/scala/akka/remote/Ticket1978ConfigSpec.scala
Labels: tested

#29047 Allow taking a stream snapshot of a stream that uses TLS
  akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala
  akka-stream/src/main/mima-filters/2.6.5.backwards.excludes/change-StreamSnapshotImpl-toString.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala
Labels: t:stream, tested

#29058 Migration from persistent shard coordinator to ddata with eventsource…
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/javadsl/ClusterShardingSettingsCompileOnly.java
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-sharding/src/main/protobuf/ClusterShardingMessages.proto
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntities.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberShards.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardingMigrationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/external/ExternalShardAllocationStrategySpec.scala
  akka-docs/src/main/paradox/includes/cluster.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#28729 Replace LazyFlow with FutureFlow (and implement other lazy flows on top of it)
  akka-docs/src/main/paradox/stream/operators/Flow/futureFlow.md
  akka-docs/src/main/paradox/stream/operators/Flow/lazyFlow.md
  akka-docs/src/main/paradox/stream/operators/Flow/lazyFutureFlow.md
  akka-docs/src/main/paradox/stream/operators/Flow/lazyInitAsync.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFutureFlowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala
  akka-stream/src/main/mima-filters/2.6.5.backwards.excludes/28729-future-flow.backwards.excludes
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/FlatMapPrefix.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/FutureFlow.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: t:stream, tested

#29064 Batch entitiy start updates for remembered entities
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-sharding/src/main/protobuf/ClusterShardingMessages.proto
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntities.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntitiesStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesPerfSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializerSpec.scala
Labels: tested

#29070 Typed testkit: log capture logger initalisation
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/LogbackUtil.scala
Labels: tested

#28897 Docs for lazy stream operators
  akka-docs/src/main/paradox/stream/operators/Flow/lazyFlow.md
  akka-docs/src/main/paradox/stream/operators/Sink/lazySink.md
  akka-docs/src/main/paradox/stream/operators/Source/lazySource.md
  akka-docs/src/test/java/jdocs/stream/operators/flow/Lazy.java
  akka-docs/src/test/java/jdocs/stream/operators/sink/Lazy.java
  akka-docs/src/test/java/jdocs/stream/operators/source/Lazy.java
  akka-docs/src/test/scala/docs/stream/operators/flow/Lazy.scala
  akka-docs/src/test/scala/docs/stream/operators/sink/Lazy.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Lazy.scala
Labels: tested

#29039 Adds support to read PEM keys
  akka-pki/src/main/scala/akka/pki/pem/DERPrivateKeyLoader.scala
  akka-pki/src/main/scala/akka/pki/pem/PEMDecoder.scala
  akka-pki/src/test/resources/certificate.pem
  akka-pki/src/test/resources/multi-prime-pkcs1.pem
  akka-pki/src/test/resources/pkcs1.pem
  akka-pki/src/test/resources/pkcs8.pem
  akka-pki/src/test/scala/akka/pki/pem/DERPrivateKeyLoaderSpec.scala
  akka-pki/src/test/scala/akka/pki/pem/PEMDecoderSpec.scala
  build.sbt
  project/Dependencies.scala
Labels: dependency-change, tested

#29071 Reafactor shard to have a state for each entity
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntities.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/EntitiesSpec.scala
Labels: tested

#29074 Use new TLS algorithm defaults in remoting tests
  akka-remote/src/test/scala/akka/remote/Ticket1978CommunicationSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemotingSpec.scala
Labels: tested

#27614 Don't set fields of actor / actorcell using reflection
  akka-actor-tests/src/test/scala/akka/actor/ActorLifeCycleSpec.scala
  akka-actor/src/main/mima-filters/2.6.5.backwards.excludes/27614-no-reflection-in-actorcell.excludes
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-actor/src/main/scala/akka/actor/dungeon/FaultHandling.scala
  akka-actor/src/main/scala/akka/util/Reflect.scala
Labels: tested

#29089 Fix grammer error in cluster-concepts
  akka-docs/src/main/paradox/typed/cluster-concepts.md
Labels: tested

#29057 Docs: revise Coordinated Shutdown with new actors APIs
  akka-docs/src/main/paradox/coordinated-shutdown.md
  akka-docs/src/test/java/jdocs/actor/ActorDocTest.java
  akka-docs/src/test/java/jdocs/actor/typed/CoordinatedActorShutdownTest.java
  akka-docs/src/test/scala/docs/actor/ActorDocSpec.scala
  akka-docs/src/test/scala/docs/actor/typed/CoordinatedActorShutdownSpec.scala
Labels: t:docs, tested

#29094 Cherry pick of ShardCoordinator state replication, #28856
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingLeavingSpec.scala
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatedDataMessages.java
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatorMessages.java
  akka-distributed-data/src/main/mima-filters/2.6.4.backwards.excludes/issue-28856-coordinator-state.excludes
  akka-distributed-data/src/main/protobuf/ReplicatorMessages.proto
  akka-distributed-data/src/main/resources/reference.conf
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializer.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/WriteAggregatorSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializerSpec.scala
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: tested

#29098 actor: need to keep signature of `clearActorFields` for now
  akka-actor/src/main/mima-filters/2.6.5.backwards.excludes/27614-no-reflection-in-actorcell.excludes
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-actor/src/main/scala/akka/actor/dungeon/Children.scala
  akka-actor/src/main/scala/akka/actor/dungeon/FaultHandling.scala
Labels: tested

#29012 add lz4 compression for jackson
  akka-bench-jmh/src/main/scala/akka/serialization/jackson/JacksonSerializationBench.scala
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  project/Dependencies.scala
Labels: dependency-change, tested

#29069 Ignore possible state change in start #28979
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
Labels: tested

#28577 more useful JavaDoc for javadsl Flow
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
Labels: tested

#29105 Fixed Deploy productElement implementation #29104
  akka-actor/src/main/scala/akka/actor/Deployer.scala
Labels: tested

#29065 Don't stall coordinator init on slow remember shard store
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
Labels: tested

#27112 Detect illegal access to ActorContext from the outside
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorThreadSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.5.backwards.excludes/current-actor-thread.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AbstractBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AbstractBehavior.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
Labels: discuss-design, t:typed, tested

#29099 Add Lightbend's SBR to Akka Cluster, #29085
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/GlobalRegistry.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/GremlinController.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/RandomizedBrainResolverIntegrationSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/SbrTestLeaseActor.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/SplitBrainResolverIntegrationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingLeaseSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerLeaseSpec.scala
  akka-cluster-tools/src/test/scala/akka/cluster/singleton/ClusterSingletonLeaseSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/DowningProvider.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/DowningStrategy.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolverProvider.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolverSettings.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/SunnyWeatherSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/sbr/DownAllIndirectlyConnected5NodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/sbr/DownAllUnstable5NodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/sbr/IndirectlyConnected3NodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/sbr/IndirectlyConnected5NodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/sbr/LeaseMajority5NodeSpec.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/SplitBrainResolverSpec.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/TestAddresses.scala
  akka-coordination/src/test/scala/akka/coordination/lease/TestLease.scala
  akka-coordination/src/test/scala/akka/coordination/lease/TestLeaseActor.scala
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/common/other-modules.md
  akka-docs/src/main/paradox/coordination.md
  akka-docs/src/main/paradox/split-brain-resolver.md
  akka-docs/src/main/paradox/typed/cluster-membership.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/guide/modules.md
  akka-docs/src/main/paradox/typed/index-cluster.md
  akka-docs/src/test/java/jdocs/coordination/LeaseDocTest.java
  akka-docs/src/test/scala/docs/coordination/LeaseDocSpec.scala
  build.sbt
Labels: tested

#29116 change email in pom.xml
  project/Publish.scala
Labels: tested

#29123 Scala Steward once per month
  .scala-steward.conf
Labels: tested

#29122 remove reply type parameter from Command in Account example
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithMutableState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithNullState.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleDocSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithOptionState.scala
Labels: tested

#29124 Multiple remember entities fixes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStore.scala
Labels: tested

#29118 InternalStableApi on JavaDurationConverters
  akka-actor/src/main/scala/akka/dispatch/Future.scala
  akka-actor/src/main/scala/akka/util/JavaDurationConverters.scala
Labels: tested

#29108 Update metrics-core, metrics-jvm to 4.1.9
  project/Dependencies.scala
Labels: dependency-change, tested

#29129 Don not crash coordinator on old remember entities store responses
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested

#29130 Fix race in ActorThreadSpec
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorThreadSpec.scala
Labels: tested

#29079 Publish Dropped to eventstream when serialized payload too large
  akka-remote/src/main/scala/akka/remote/Endpoint.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteMessageSerializationSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemotingSpec.scala
Labels: tested

#29117 doc: add routers to Higher level Cluster tools
  akka-docs/src/main/paradox/includes/cluster.md
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#29112 Detect duplicate serializer identifiers, #29100
  akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala
  akka-actor/src/main/scala/akka/serialization/Serialization.scala
  akka-docs/src/main/paradox/serialization.md
  akka-docs/src/test/scala/docs/serialization/SerializationDocSpec.scala
Labels: tested

#29113 Stash the custom termination message for watchWith
  akka-actor-tests/src/test/scala/akka/actor/DeathWatchSpec.scala
  akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala
Labels: tested

#29128 fix wrong lastSequenceNumber, #28976
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
Labels: tested

#29092 Allow ShardCoordinator to watch old region ActorRef that is not in cluster, #29034
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardCoordinatorDowningSpec.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
Labels: tested

#29136 Improve remember entities docs
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29119 handle thrown exceptions in Retry pattern in same way as failed Future
  akka-actor-tests/src/test/scala/akka/pattern/RetrySpec.scala
  akka-actor/src/main/scala/akka/pattern/RetrySupport.scala
Labels: tested

#29140 Log markers for SBR, #29085
  akka-cluster/src/main/scala/akka/cluster/ClusterLogMarker.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/DowningStrategy.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/SplitBrainResolverSpec.scala
Labels: validating

#29103 Latency benchmarks for rememered entities + JFR events
  akka-actor-typed/src/main/scala-jdk-9/akka/actor/typed/internal/jfr/JFRActorFlightRecorder.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorFlightRecorder.scala
  akka-actor/src/main/scala/akka/util/FlightRecorderLoader.scala
  akka-cluster-sharding-typed/src/multi-jvm/resources/logback-test.xml
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesPerfSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/FlightRecording.scala
  akka-cluster-sharding/src/main/scala-jdk-9/akka/cluster/sharding/internal/jfr/Events.scala
  akka-cluster-sharding/src/main/scala-jdk-9/akka/cluster/sharding/internal/jfr/JFRShardingFlightRecorder.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardingFlightRecorder.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesPerfSpec.scala
  akka-remote/src/main/scala-jdk-9/akka/remote/artery/jfr/JFRRemotingFlightRecorder.scala
  akka-remote/src/main/scala/akka/remote/artery/RemotingFlightRecorder.scala
  build.sbt
  project/AkkaDisciplinePlugin.scala
Labels: tested

#29083 Extend backoff supervision with custom message handling #29082
  akka-actor-tests/src/test/scala/akka/pattern/BackoffOnRestartSupervisorSpec.scala
  akka-actor-tests/src/test/scala/akka/pattern/BackoffSupervisorSpec.scala
  akka-actor/src/main/mima-filters/2.6.5.backwards.excludes/29082-backoff-reply.excludes
  akka-actor/src/main/scala/akka/pattern/Backoff.scala
  akka-actor/src/main/scala/akka/pattern/BackoffOptions.scala
  akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnRestartSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnStopSupervisor.scala
Labels: tested

#29121 Fix TLS 1.3 issues on JDKs which support it
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/javadsl/TLS.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala
Labels: t:stream, tested, to-be-backported

#29091 stream: make keepAlive/IdleInject more reliable against flukes
  akka-stream/src/main/scala/akka/stream/impl/Timers.scala
Labels: t:stream, tested

#29068 stream: cosmetic improvements to FutureFlow
  akka-stream/src/main/scala/akka/stream/impl/fusing/FutureFlow.scala
Labels: t:stream, tested

#29028 LocalActorRefProvider: added dedicated logger for deserialization failures
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/LocalActorRefProviderLogMessagesSpec.scala
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
Labels: tested

#29148 [2.5 backport] Fix TLS 1.3 issues on JDKs which support it #29121
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/javadsl/TLS.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala
Labels: backport, t:stream, tested
