Repository akka/akka, pull requests merged in 2020-06, with the labels that each got.

#29144 Telemetry SPI hooks for SBR decision, #29085
  akka-cluster/src/main/scala/akka/cluster/sbr/DowningStrategy.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
Labels: tested

#29149 Batch remember entity stops
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesPerfSpec.scala
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-sharding/src/main/protobuf/ClusterShardingMessages.proto
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntities.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntitiesStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesPerfSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/EntitiesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesBatchedUpdatesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStoreSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializerSpec.scala
Labels: tested

#29158 Merge Master into Remember Entities again
  akka-actor-tests/src/test/scala/akka/actor/DeathWatchSpec.scala
  akka-actor-tests/src/test/scala/akka/pattern/BackoffOnRestartSupervisorSpec.scala
  akka-actor-tests/src/test/scala/akka/pattern/BackoffSupervisorSpec.scala
  akka-actor-tests/src/test/scala/akka/pattern/RetrySpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/LocalActorRefProviderLogMessagesSpec.scala
  akka-actor/src/main/mima-filters/2.6.5.backwards.excludes/29082-backoff-reply.excludes
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala
  akka-actor/src/main/scala/akka/pattern/Backoff.scala
  akka-actor/src/main/scala/akka/pattern/BackoffOptions.scala
  akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/RetrySupport.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnRestartSupervisor.scala
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnStopSupervisor.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardCoordinatorDowning2Spec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardCoordinatorDowningSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingLeaseSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ConstantRateEntityRecoveryStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/JoinConfigCompatCheckShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ProxyShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardRegionSpec.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterLogMarker.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/DowningStrategy.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/SplitBrainResolverSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/main/scala/akka/remote/artery/RemotingFlightRecorder.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/Timers.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/FutureFlow.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/javadsl/TLS.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala
Labels: tested

#29160 Link to akka cluster video
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#29163 Publish akka.actor.Dropped when dropping buffered in sharding
  akka-actor/src/main/scala/akka/util/MessageBuffer.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#29161 Rewritten remember entity shard bugfixes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
Labels: tested

#29165 Accumulate and ack all requests to start entity
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
Labels: tested

#29157 Small fix in Buffer's doc
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/buffer.md
Labels: tested

#29166 DData shard store improvements
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStoreSpec.scala
Labels: tested

#29168 Turn verbose sharding logging into a config flag
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingLeaseSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ConcurrentStartupShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/CoordinatedShutdownShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/EntitiesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/InactiveEntityPassivationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/JoinConfigCompatCheckShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardingMigrationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentStartEntitySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ProxyShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesBatchedUpdatesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RemoveInternalClusterShardingDataSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardRegionSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardWithLeaseSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/SupervisionSpec.scala
Labels: tested

#29164 Start entity ack not needed in shard
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntitiesStarter.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/EntitiesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesShardIdExtractorChangeSpec.scala
Labels: tested

#29173 Move coordinator state and remembered entities next to each other
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29169 Remove mention of materializer from streams quickstart
  akka-docs/src/main/paradox/stream/stream-quickstart.md
Labels: tested

#29177 Tests for EventSourced remember entities shard store
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/OldCoordinatorStateMigrationEventAdapter.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntitiesCoordinatorStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntitiesProvider.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardingMigrationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/internal/RememberEntitiesShardStoreSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializerSpec.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29175 Restore termination behavior for non-remember entities
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/EntityTerminationSpec.scala
Labels: tested

#29174 Remember entities starting separation of concerns
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EntityRecoveryStrategy.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntitiesStarter.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntityStarter.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/AllAtOnceEntityRecoveryStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ConstantRateEntityRecoveryStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/internal/RememberEntitiesStarterSpec.scala
Labels: tested

#29176 Handle some corner case states when receiving StartEntity
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/StartEntitySpec.scala
Labels: tested

#29180 DEBUG logging for cluster sahrding leaving spec (remember entities branch)
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingLeavingSpec.scala
Labels: tested

#29184 Add type annotation for public method
  akka-distributed-data/src/main/scala/akka/cluster/ddata/DurableStore.scala
Labels: tested

#29088 Docs: WithContext
  akka-docs/src/main/paradox/stream/index.md
  akka-docs/src/main/paradox/stream/operators/Flow/asFlowWithContext.md
  akka-docs/src/main/paradox/stream/operators/Source/asSourceWithContext.md
  akka-docs/src/main/paradox/stream/stream-context.md
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
Labels: t:stream, tested

#29097 Docs: Fix a small typo in sharded daemon process docs
  akka-docs/src/main/paradox/typed/cluster-sharded-daemon-process.md
Labels: tested

#29181 Provide one more init overload for Sharded Daemon Process
  akka-cluster-sharding-typed/src/main/mima-filters/2.6.5.backwards.excludes/daemon-process-init-overloads.excludes
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ShardedDaemonProcess.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ShardedDaemonProcess.scala
Labels: tested

#29187 Link to new Kubernetes deployment guide
  akka-docs/src/main/paradox/additional/deploying.md
Labels: 2 - pick next, tested

#29152 k8s-friendly SSLEngine provider (simplified)
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/artery/tcp/ConfigSSLEngineProvider.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/SecureRandomFactory.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ssl/PemManagersProvider.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ssl/RotatingKeysSSLEngineProvider.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ssl/SSLEngineConfig.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ssl/SessionVerifier.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ssl/X509Readers.scala
  akka-remote/src/test/resources/Makefile
  akka-remote/src/test/resources/domain.crt
  akka-remote/src/test/resources/keystore
  akka-remote/src/test/resources/ssl/README.md
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node001.example.com.crt
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node001.example.com.p12
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node001.example.com.pem
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node002.example.com.crt
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node002.example.com.p12
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node002.example.com.pem
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node003.example.com.crt
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node003.example.com.p12
  akka-remote/src/test/resources/ssl/artery-nodes/artery-node003.example.com.pem
  akka-remote/src/test/resources/ssl/client.example.com.crt
  akka-remote/src/test/resources/ssl/client.example.com.p12
  akka-remote/src/test/resources/ssl/exampleca.crt
  akka-remote/src/test/resources/ssl/exampleca.p12
  akka-remote/src/test/resources/ssl/gen-artery-nodes.example.com.sh
  akka-remote/src/test/resources/ssl/gen-functions.sh
  akka-remote/src/test/resources/ssl/genca.sh
  akka-remote/src/test/resources/ssl/gencerts.sh
  akka-remote/src/test/resources/ssl/island.example.com.crt
  akka-remote/src/test/resources/ssl/island.example.com.p12
  akka-remote/src/test/resources/ssl/node.example.com.crt
  akka-remote/src/test/resources/ssl/node.example.com.p12
  akka-remote/src/test/resources/ssl/node.example.com.pem
  akka-remote/src/test/resources/ssl/one.example.com.crt
  akka-remote/src/test/resources/ssl/one.example.com.p12
  akka-remote/src/test/resources/ssl/password
  akka-remote/src/test/resources/ssl/pem/README.md
  akka-remote/src/test/resources/ssl/pem/pkcs1.pem
  akka-remote/src/test/resources/ssl/pem/selfsigned-certificate.pem
  akka-remote/src/test/resources/ssl/rsa-client.example.com.crt
  akka-remote/src/test/resources/ssl/rsa-client.example.com.p12
  akka-remote/src/test/resources/ssl/rsa-client.example.com.pem
  akka-remote/src/test/resources/ssl/two.example.com.crt
  akka-remote/src/test/resources/ssl/two.example.com.p12
  akka-remote/src/test/resources/truststore
  akka-remote/src/test/scala/akka/remote/artery/ArterySpecSupport.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/SecureRandomFactorySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/CipherSuiteSupportCheck.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/PeerSubjectVerifierSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/PemManagersProviderSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/RotatingKeysSSLEngineProviderSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/TlsResourcesSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/X509ReadersSpec.scala
  build.sbt
  project/Dependencies.scala
Labels: 2 - pick next, tested

#29193 Persistence testkit response bugfix
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/EventSourcedBehaviorTestKitImpl.scala
Labels: tested

#29107 Implement throttle for Source(Flow)WithContext
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowWithContextThrottleTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceWithContextThrottleTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowWithContextThrottleSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FlowWithContext.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SourceWithContext.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
Labels: t:stream, tested

#29200 latestPatchOf 2.6.6
  project/MiMa.scala
Labels: tested

#29204 minor typo in akka-remote reference.conf
  akka-remote/src/main/resources/reference.conf
Labels: tested

#29201 Updates to releasing steps
  RELEASING.md
Labels: tested

#29202 Minor apidocs fixes
  akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala
Labels: t:stream, tested

#29153 Docs: Discovery via DNS
  akka-discovery/src/test/scala/akka/discovery/dns/DnsDiscoverySpec.scala
  akka-docs/src/main/paradox/discovery/index.md
  akka-docs/src/main/paradox/io-dns.md
  akka-docs/src/test/java/jdocs/discovery/DnsDiscoveryDocTest.java
  akka-docs/src/test/scala/docs/discovery/DnsDiscoveryDocSpec.scala
  build.sbt
Labels: t:discovery, t:docs, tested

#29214 Adds skeleton pages for gunzip and inflate.
  akka-docs/src/main/paradox/stream/operators/Compression/gunzip.md
  akka-docs/src/main/paradox/stream/operators/Compression/inflate.md
  akka-docs/src/main/paradox/stream/operators/index.md
  project/StreamOperatorsIndexGenerator.scala
Labels: t:docs, t:stream, tested

#29211 doc: add link to SBR video
  akka-docs/src/main/paradox/split-brain-resolver.md
  akka-docs/src/main/paradox/typed/choosing-cluster.md
Labels: tested

#29210 LocalPubSubSpec: Stop log being captured from creation
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/pubsub/LocalPubSubSpec.scala
Labels: tested

#29209 Allow update from Lightbend SBR in ClusterReceptionistConfigCompatChecker
  akka-cluster/src/main/scala/akka/cluster/JoinConfigCompatCheckCluster.scala
  akka-cluster/src/main/scala/akka/cluster/JoinConfigCompatChecker.scala
  akka-cluster/src/test/scala/akka/cluster/JoinConfigCompatCheckClusterSpec.scala
Labels: tested

#29225 Remove 'dry run' feature
  project/scripts/release
Labels: tested

#29220 Add imports to discovery scala snippets
  akka-discovery/src/test/scala/doc/akka/discovery/CompileOnlySpec.scala
Labels: tested

#29227 RE rework smaller end review feedback fixes
  akka-cluster-sharding-typed/src/multi-jvm/resources/logback-test.xml
  akka-cluster-sharding/src/main/mima-filters/2.6.6.backwards.excludes/remember-entities-refactor.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/OldCoordinatorStateMigrationEventAdapter.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/CustomStateStoreModeProvider.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntityStarter.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#28955 stream: Unencoded attribute name
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
Labels: t:stream, tested

#29237 Never use durable store for the cluster receptionist replicator
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSettings.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
Labels: tested

#29172 Protobuf v3 osgi
  build.sbt
  project/OSGi.scala
Labels: tested

#29178 Docs: Actor source stream operators
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRef.md
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRef.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/SourceOperators.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorSource.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorSource.scala
  akka-stream-typed/src/test/java/docs/akka/stream/typed/ActorSourceExample.java
  akka-stream-typed/src/test/java/docs/akka/stream/typed/ActorSourceWithBackpressureExample.java
  akka-stream-typed/src/test/scala/docs/akka/stream/typed/ActorSourceSinkExample.scala
Labels: t:docs, t:stream, tested

#29242 Avoid triggering IntelliJ's dead code detection
  akka-remote/src/test/scala/akka/remote/Ticket1978CommunicationSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteDeploymentSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/CipherSuiteSupportCheck.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowIntersperseSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapErrorSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowRecoverSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/UnfoldResourceAsyncSourceSpec.scala
Labels: t:stream, tested

#29232 Store clear out set of shards when not needed
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesCoordinatorStore.scala
Labels: tested

#29230 Use watchWith for entity terminated
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#29233 Split up large writes in the EventSourcedRememberEntitiesShardStore
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/internal/RememberEntitiesShardStoreSpec.scala
Labels: tested

#29240 Harden PersistentShardingMigrationSpec
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardingMigrationSpec.scala
Labels: tested

#29253 Missing wildcard port for netty in some sharding tests
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardingMigrationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesShardIdExtractorChangeSpec.scala
Labels: tested

#29252 Remove or replace master/slave terminology from tests and API docs
  akka-actor-tests/src/test/scala/akka/actor/ActorWithStashSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/RestartStrategySpec.scala
  akka-actor/src/main/scala/akka/io/Inet.scala
  akka-docs/src/main/paradox/stream/stream-substream.md
  akka-remote-tests/src/multi-jvm/scala/akka/remote/LookupRemoteActorSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/NewRemoteActorSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/testconductor/TestConductorSpec.scala
Labels: tested

#29254 Removing, deprecating and replacing usage of black/whitelist
  CONTRIBUTING.md
  akka-actor/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/security/index.md
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMapConcat.md
  akka-docs/src/test/java/jdocs/stream/operators/flow/StatefulMapConcat.java
  akka-docs/src/test/scala/docs/stream/operators/flow/StatefulMapConcat.scala
  akka-remote/src/main/mima-filters/2.6.6.backwards.excludes/terminology-cleanup.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteDaemon.scala
  akka-remote/src/main/scala/akka/remote/serialization/ProtobufSerializer.scala
  akka-remote/src/test/scala/akka/remote/artery/UntrustedSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemoteDeploymentAllowListSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/UntrustedSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/ProtobufSerializerSpec.scala
  akka-serialization-jackson/src/main/mima-filters/2.6.6.backwards.excludes/terminology-cleanup.excludes
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
Labels: tested

#29235 ShardedDaemonProcess: Use Interger in javadsl function
  akka-cluster-sharding-typed/src/main/mima-filters/2.6.6.backwards.excludes/daemon-process-init-overloads.excludes
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ShardedDaemonProcess.scala
Labels: tested

#28986 Improved utilities/logging documentation
  akka-docs/src/main/paradox/typed/logging.md
Labels: tested

#29222 Improve RotatingKeysSSLEngineProviderSpec
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/RotatingKeysSSLEngineProviderSpec.scala
Labels: tested

#29265 Initial prototype of active active event sourcing
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PersistenceId.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ActiveActiveEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/test/resources/logback-test.xml
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorWatchSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/aa/AAAuctionExampleSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/aa/AABlogExampleSpec.scala
  build.sbt
  project/Dependencies.scala
Labels: dependency-change, tested

#29213 Akka 29194 errors via async boundary
  akka-stream-tests/src/test/scala/akka/stream/FusingSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
Labels: t:stream, tested

#29278 Avoid 'dead code after this construct' warnings in jackson-databind example
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2a/CustomerMigration.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2c/ItemAddedMigration.scala
Labels: tested

#29288 Validate leveldb write plugin is enabled for leveldb read plugin
  akka-docs/src/test/scala/docs/persistence/query/LeveldbPersistenceQueryDocSpec.scala
  akka-persistence-query/src/main/mima-filters/2.6.7.backwards.excludes/29288-leveldb-cleanups.excludes
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/AllPersistenceIdsStage.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdStage.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagStage.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/javadsl/LeveldbReadJournal.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/scaladsl/LeveldbReadJournal.scala
Labels: tested

#29287 ActiveActive: Events with metadata and events by persistence id for
  akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdStage.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagStage.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/TestActor.scala
  akka-persistence-testkit/src/main/resources/reference.conf
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/EventStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/PersistenceTestKitPlugin.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SerializedEventStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SimpleEventStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/PersistenceTestKitReadJournalProvider.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/internal/EventsByPersistenceIdStage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/javadsl/PersistenceTestKitReadJournal.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/scaladsl/PersistenceTestKitReadJournal.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/query/EventsByPersistenceIdSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/EventSourcedBehaviorTestKitSpec.scala
  akka-persistence-typed-tests/src/test/resources/logback-test.xml
  akka-persistence-typed-tests/src/test/scala/docs.akka.persistence.typed/AAAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs.akka.persistence.typed/AABlogExampleSpec.scala
  akka-persistence-typed/src/main/mima-filters/2.6.7.backwards.excludes/29217-active-active-event-sourcing.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence/src/main/mima-filters/2.6.7.backwards.excludes/29217-active-active-event-sourcing.excludes
  akka-persistence/src/main/scala/akka/persistence/journal/EventWithMetaData.scala
  akka-persistence/src/main/scala/akka/persistence/journal/inmem/InmemJournal.scala
  akka-persistence/src/test/scala/akka/persistence/EventSourcedActorFailureSpec.scala
  akka-persistence/src/test/scala/akka/persistence/journal/chaos/ChaosJournal.scala
  build.sbt
  project/Dependencies.scala
Labels: dependency-change, tested

#29246 Allowing arbitrary random number generators
  akka-remote/src/main/mima-filters/2.6.x.backwards.excludes/pr-29246-remove-prng-constans.excludes
  akka-remote/src/main/scala/akka/remote/artery/tcp/SecureRandomFactory.scala
Labels: tested

#29139 dotty phase 3: Some required syntax changes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/SupervisorHierarchySpec.scala
  akka-actor-tests/src/test/scala/akka/actor/dispatch/ActorModelSpec.scala
  akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala
  akka-actor-tests/src/test/scala/akka/io/TcpIntegrationSpecSupport.scala
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorRefIgnoreSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/receptionist/ReceptionistApiSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/FSMDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ExtensionsImpl.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/dispatch/CachingConfig.scala
  akka-actor/src/main/scala/akka/japi/JavaAPI.scala
  akka-actor/src/main/scala/akka/util/Index.scala
  akka-remote-tests/src/test/scala/akka/remote/testkit/LogRoleReplace.scala
  akka-remote/src/main/scala/akka/remote/PhiAccrualFailureDetector.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/TlsTcpSpec.scala
  akka-slf4j/src/test/scala/akka/event/slf4j/Slf4jLoggerSpec.scala
  akka-testkit/src/test/scala/akka/testkit/WithLogCapturing.scala
  akka-testkit/src/test/scala/akka/testkit/metrics/reporter/AkkaConsoleReporter.scala
Labels: tested

#29274 Docs: Document reference.conf appending on gradle+kotlin
  akka-docs/src/main/paradox/additional/packaging.md
Labels: t:docs, tested

#29309 Alternative approach for storing metadata
  akka-actor/src/main/scala/akka/util/AlwaysIncreasingClock.scala
  akka-actor/src/main/scala/akka/util/WallClock.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/TestActor.scala
  akka-persistence-tck/src/main/scala/akka/persistence/CapabilityFlags.scala
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/EventStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/PersistenceTestKitPlugin.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SerializedEventStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SimpleEventStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/internal/EventsByPersistenceIdStage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/scaladsl/PersistenceTestKitReadJournal.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/test/resources/application.conf
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/query/EventsByPersistenceIdSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/PersistenceTestKitJournalCompatSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs.akka.persistence.typed/AABlogExampleSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ActiveActiveEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence/src/main/scala/akka/persistence/Persistent.scala
  akka-persistence/src/main/scala/akka/persistence/journal/EventWithMetaData.scala
  akka-persistence/src/main/scala/akka/persistence/journal/inmem/InmemJournal.scala
Labels: tested

#29307 Update sbt to 1.3.12
  project/build.properties
Labels: tested

#29195 Docs: link to object API docs
  akka-docs/src/main/paradox/stream/operators/RestartFlow/onFailuresWithBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartFlow/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSink/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSource/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/Source/fromJavaStream.md
  akka-docs/src/main/paradox/typed/persistence-testing.md
Labels: tested

#29329 better timestamp format for active-active
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested

#29323 wrong serializer config in ActorSystemSpec
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorSystemSpec.scala
Labels: tested

#29328 message adapter in ActiveActiveShardingDirectReplication
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ActiveActiveShardingDirectReplicationSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/EventPublishingSpec.scala
Labels: tested

#29326 Fix doc typo
  akka-docs/src/test/java/jdocs/stream/operators/PartitionDocExample.java
Labels: tested
