Repository akka/akka, pull requests merged in 2020-01, with the labels that each got.

#28438 Fixing typo - "timej" to "time"
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
Labels: tested

#28433 Update sbt to 1.3.6
  project/build.properties
Labels: tested

#28435 Update junit to 4.13
  project/Dependencies.scala
Labels: tested

#28443 Fix RetryFlow not stopping after maxRetries
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RetryFlowSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/RetryFlowCoordinator.scala
Labels: tested

#28159 Add stream name to buffer overflow log message
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: tested

#28447 Update jackson-databind to 2.10.2
  project/Dependencies.scala
Labels: tested

#28415 Clean up akka.build.version #26675
  project/AkkaBuild.scala
Labels: tested

#28424 doc: fix ScalaFiddle integration for Akka 2.6
  akka-docs/src/main/paradox/assets/js/scalafiddle.js
  akka-docs/src/main/paradox/stream/stream-quickstart.md
Labels: 2 - pick next, tested

#28444 Report UDP connection error for negatively-cached hostnames
  akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala
  akka-actor/src/main/scala/akka/io/InetAddressDnsResolver.scala
  akka-actor/src/main/scala/akka/io/UdpConnection.scala
Labels: tested

#28442 Update sbt-paradox-akka to 0.29
  project/plugins.sbt
Labels: tested

#28446 Update jctools-core to 3.0.0
  project/Dependencies.scala
Labels: tested

#28445 Update commons-codec to 1.14
  project/Dependencies.scala
Labels: tested

#28383 Timestamp in EventEnvelope, #28331
  akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdStage.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagStage.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdSpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByTagSpec.scala
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala
  akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java
  akka-persistence/src/main/mima-filters/2.6.1.backwards.excludes/28331-timestamp-PersistentRepr.excludes
  akka-persistence/src/main/protobuf/MessageFormats.proto
  akka-persistence/src/main/scala/akka/persistence/Persistent.scala
  akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbStore.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/MessageSerializer.scala
Labels: tested, to-be-backported

#28429 Keeps live stream open for empty persistence ids #28428
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdStage.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdSpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByTagSpec.scala
Labels: tested

#28455 doc: change link text to Event Sourcing
  akka-docs/src/main/paradox/persistence.md
Labels: tested

#28452 Fix typos, add some punctuation, and rephrase some text
  akka-docs/src/main/paradox/typed/from-classic.md
Labels: tested

#28411 Update sbt-java-formatter to 0.5.0
  project/plugins.sbt
Labels: tested

#28419 ByteString performance regression toArray on 2.13
  akka-actor/src/main/mima-filters/2.6.1.backwards.excludes/pr-28419-byte-string-perf-2.13.excludes
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
  akka-bench-jmh/src/main/scala/akka/util/ByteString_toArray_Benchmark.scala
Labels: 2 - pick next, tested

#28418 Use MessageBuffer in RecoveryPermitter, #28417
  akka-actor-tests/src/test/scala/akka/util/MessageBufferSpec.scala
  akka-actor/src/main/scala/akka/util/MessageBuffer.scala
  akka-persistence/src/main/scala/akka/persistence/RecoveryPermitter.scala
Labels: tested, to-be-backported

#28456 Re enable stress spec artery
  akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala
  akka-remote/src/main/scala/akka/remote/artery/RemotingFlightRecorder.scala
Labels: tested

#28394 Limit and LimitWeighted operator docs
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/limit.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/limitWeighted.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/Limit.java
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/LimitWeighted.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Limit.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/LimitWeighted.scala
Labels: tested

#28458 Update sbt-header to 5.4.0
  project/plugins.sbt
Labels: tested

#28457 Document update strategy for sattelite projects
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
  akka-docs/src/main/paradox/project/downstream-upgrade-strategy.md
  akka-docs/src/main/paradox/project/index.md
Labels: tested

#28406 Typed receptionist deregistration
  akka-actor-typed-tests/src/test/resources/logback-test.xml
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/receptionist/LocalReceptionistSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.1.backwards.excludes/issue-28123-typed-receptionist-unregistration.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistMessages.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-actor/src/main/scala-2.13+/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13+/akka/util/ccompat/ccompatUsedUntil213.scala
  akka-actor/src/main/scala-2.13+/akka/util/ccompat/package.scala
  akka-actor/src/main/scala-2.13/akka/compat/Future.scala
  akka-cluster-typed/src/main/mima-filters/2.6.1.backwards.excludes/issue-28123-typed-receptionist-unregistration.excludes
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/Registry.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/ReceptionistExample.java
  akka-cluster-typed/src/test/resources/logback-test.xml
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistStateSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/ReceptionistExample.scala
  akka-docs/src/main/paradox/typed/actor-discovery.md
Labels: tested

#28332 Publish operations from InmemJournal
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleDocTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithMutableState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithNullState.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleDocSpec.scala
  akka-docs/src/main/paradox/typed/persistence-testing.md
  akka-persistence/src/main/scala/akka/persistence/journal/inmem/InmemJournal.scala
  akka-persistence/src/test/scala/akka/persistence/journal/inmem/InmemJournalSpec.scala
Labels: tested

#28407 Fix memory leak of restarting Artery outbound stream, #28390
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/HandshakeRestartReceiverSpec.scala
  akka-remote/src/main/mima-filters/2.5.27.backwards.excludes
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/Handshake.scala
  akka-remote/src/main/scala/akka/remote/artery/SystemMessageDelivery.scala
  akka-remote/src/test/scala/akka/remote/artery/InboundHandshakeSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/OutboundIdleShutdownSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/TestContext.scala
Labels: tested

#28472 Add missing word Map to tutorial_4.md
  akka-docs/src/main/paradox/typed/guide/tutorial_4.md
Labels: tested

#28453 Timestamp in EventEnvelope, #28331
  akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdPublisher.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/EventsByTagPublisher.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdSpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByTagSpec.scala
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala
  akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java
  akka-persistence/src/main/mima-filters/2.5.27.backwards.excludes
  akka-persistence/src/main/protobuf/MessageFormats.proto
  akka-persistence/src/main/scala/akka/persistence/Persistent.scala
  akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbStore.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/MessageSerializer.scala
Labels: backport, tested

#28469 Rename Start message in HelloWorld
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-docs/src/main/paradox/typed/actors.md
  akka-persistence/src/test/scala/akka/persistence/journal/inmem/InmemJournalSpec.scala
Labels: tested

#28484 Minor doc and scaladoc cleanup.
  akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
  akka-docs/src/main/paradox/common/circuitbreaker.md
  akka-docs/src/main/paradox/dispatchers.md
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/typed/dispatchers.md
Labels: tested

#28481 doc: links to videos
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/typed/actors.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#28480 doc: example for splitWhen and splitAfter, #25468
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/splitAfter.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/splitWhen.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/Split.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Split.scala
Labels: tested

#28454 Deprecate EventEnvelope ctor without timestamp
  akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByTagSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedEventAdapterSpec.scala
Labels: tested

#28414 Logging of UnhandledMessage, #28260
  akka-actor-tests/src/test/scala/akka/actor/DeadLetterSuspensionSpec.scala
  akka-actor-tests/src/test/scala/akka/event/EventStreamSpec.scala
  akka-actor/src/main/resources/reference.conf
  akka-actor/src/main/scala/akka/actor/Actor.scala
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-actor/src/main/scala/akka/event/DeadLetterListener.scala
  akka-actor/src/main/scala/akka/event/Logging.scala
Labels: tested

#28378 Update scalacheck to 1.14.3
  project/Dependencies.scala
Labels: tested

#28375 Update metrics-core, metrics-jvm to 4.1.2
  project/Dependencies.scala
Labels: tested

#28398 Update jul-to-slf4j, log4j-over-slf4j, ... to 1.7.30
  project/Dependencies.scala
Labels: tested

#28396 Update sbt-pgp to 2.0.1
  project/plugins.sbt
Labels: tested

#28475 Update aeron-client, aeron-driver to 1.25.0
  project/Dependencies.scala
Labels: tested

#28486 Update sbt-reproducible-builds to 0.23
  project/plugins.sbt
Labels: tested

#28479 Incorrect assumptions in LazyAndFutureSourcesTest
  akka-stream-tests/src/test/java/akka/stream/javadsl/LazyAndFutureSourcesTest.java
Labels: tested

#28482 Examples for the sliding operator
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/sliding.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/Sliding.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Sliding.scala
Labels: tested

#28489 Increase logger startup timeout in cluster metric tests
  akka-cluster-metrics/src/multi-jvm/scala/akka/cluster/metrics/ClusterMetricsExtensionSpec.scala
Labels: tested

#28488 Operator doc for flatmap merge
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/flatMapMerge.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/FlatMapMerge.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/FlatMapMerge.scala
Labels: tested

#28460 Backport: ByteString performance regression toArray on 2.13
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
  akka-actor/src/main/mima-filters/2.5.27.backwards.excludes
  akka-actor/src/main/scala-2.12/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.13+/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.13+/akka/util/ByteString.scala
  akka-bench-jmh/src/main/scala/akka/util/ByteString_toArray_Benchmark.scala
  project/AkkaDisciplinePlugin.scala
Labels: backport, tested

#28338 Add source.completionStage example #25468
  akka-docs/src/main/paradox/stream/operators/Source/completionStage.md
  akka-docs/src/main/paradox/stream/operators/Source/future.md
  akka-docs/src/test/java/jdocs/stream/operators/source/FromCompletionStage.java
Labels: tested

#28337 Remove deprecated actorRefWithAck from 'pending' lists
  project/StreamOperatorsIndexGenerator.scala
Labels: tested

#28493 Missing Java getters for optional fields on akka.actor.Address
  akka-actor-tests/src/test/java/akka/actor/AddressTest.java
  akka-actor/src/main/scala/akka/actor/Address.scala
Labels: tested

#28346 Support cancellation propagation in StreamRefs
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SinkRefImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/StreamRefsProtocol.scala
  akka-stream/src/main/scala/akka/stream/serialization/StreamRefSerializer.scala
Labels: 2 - pick next, tested

#28495 Update sbt to 1.3.7
  project/build.properties
Labels: tested

#28502 Rename RecoveryPermitter.pending for telemetry
  akka-persistence/src/main/scala/akka/persistence/RecoveryPermitter.scala
Labels: tested

#28503 Rename RecoveryPermitter.pending for telemetry
  akka-persistence/src/main/scala/akka/persistence/RecoveryPermitter.scala
Labels: tested

#28496 Update 'managing blocking' examples
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/test/java/jdocs/actor/typed/BlockingDispatcherTest.java
  akka-docs/src/test/scala/docs/actor/typed/BlockingDispatcherSample.scala
Labels: tested

#28494 Backport SystemMaterializer API
  akka-actor/src/main/scala/akka/actor/ClassicActorSystemProvider.scala
  akka-stream-tests/src/test/scala/akka/stream/SystemMaterializerSpec.scala
  akka-stream/src/main/scala/akka/stream/Materializer.scala
  akka-stream/src/main/scala/akka/stream/SystemMaterializer.scala
Labels: tested

#28211 External shard allocation strategy
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/Murmur2MessageExtractor.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/Murmur2.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ExternalShardAllocationCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ExternalShardAllocationCompileOnlySpec.scala
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/ClientTimeoutException.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/ExternalShardAllocation.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/ExternalShardAllocationStrategy.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/ShardLocations.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/internal/ExternalShardAllocationClientImpl.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/javadsl/ExternalShardAllocationClient.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/external/scaladsl/ExternalShardAllocationClient.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ExternalShardAllocationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/external/ExternalShardAllocationStrategySpec.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: 2 - pick next, tested

#28483 Failed: JoinConfigCompatCheckerClusterShardingSpec #28477
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/JoinConfigCompatCheckerClusterShardingSpec.scala
Labels: 2 - pick next, tested

#28462 Use MessageBuffer in RecoveryPermitter, #28417
  akka-actor-tests/src/test/scala/akka/util/MessageBufferSpec.scala
  akka-actor/src/main/scala/akka/util/MessageBuffer.scala
  akka-persistence/src/main/scala/akka/persistence/RecoveryPermitter.scala
Labels: tested

#28403 Don't warn about discarded return values
  project/AkkaDisciplinePlugin.scala
Labels: tested

#28470 Shard region registration to more potential oldest, #28416
  akka-cluster-sharding/src/main/mima-filters/2.6.1.backwards.excludes/issue-28416-region-registration.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRegistrationCoordinatedShutdownSpec.scala
Labels: tested

#28506 Add distributed workers to examples
  akka-docs/src/main/paradox/project/examples.md
Labels: 2 - pick next, tested

#28507 backport: apply ByteIterator fix from #28460 also to Scala 2.11
  akka-actor/src/main/scala-2.11/akka/util/ByteIterator.scala
Labels: backport, tested

#28467 stream: filter out elements without demand
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFilterSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: 2 - pick next, tested

#28306 docs: fix leader action transition descriptions
  akka-docs/src/main/paradox/typed/cluster-membership.md
Labels: 2 - pick next, tested

#28518 Add kafka to sharding example project
  akka-docs/src/main/paradox/project/examples.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: 2 - pick next, tested

#28516 Update aeron-client, aeron-driver to 1.25.1 and Agrona to 1.3.0
  project/Dependencies.scala
Labels: 2 - pick next, tested

#28512 Cut sample stashing in an EventSourcedBehavior
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
Labels: 2 - pick next, tested

#27352 allow Sink.queue concurrent pulling
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/QueueSinkSpec.scala
  akka-stream/src/main/mima-filters/2.6.1.backwards.excludes/27361-queue-sink-concurrency.excludes
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
Labels: 2 - pick next, tested

#28510 Examples for Source.zipN and Source.zipWithN
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zip.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zipAll.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zipWith.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zipWithIndex.md
  akka-docs/src/main/paradox/stream/operators/Source/zipN.md
  akka-docs/src/main/paradox/stream/operators/Source/zipWithN.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/source/Zip.java
  akka-docs/src/test/scala/docs/stream/operators/source/Zip.scala
Labels: 2 - pick next, tested

#28514 First step of rolling update cluster serlializer no classmanifests
  akka-cluster/src/main/mima-filters/2.6.1.backwards.excludes/issue-13654-no-class-manifests-for-cluster-serializer-step1.excludes
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
  akka-docs/src/main/paradox/project/rolling-update.md
Labels: 2 - pick next, tested

#28527 doc: Mention dispatcher shutdown timeouts
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/test/scala/docs/dispatcher/DispatcherDocSpec.scala
Labels: tested

#28533 Fixes EventEnvelope unapply
  akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala
Labels: backport, tested

#28536 Fixes EventEnvelope unapply
  akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala
Labels: backport, tested

#28537 clarify ExecutionContext for whenTerminated operations
  akka-actor-typed/src/main/scala/akka/actor/typed/ActorSystem.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: tested

#28531 Improve akka logging docs
  akka-docs/src/main/paradox/logging.md
Labels: tested

#28535 update MiMa latestPatch for 2.5
  project/MiMa.scala
Labels: tested

#28547 Config option of Artery hostname for client side of TCP connection, #28546
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
Labels: tested

#28540 Add paramater documentation for event sourced entities
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
Labels: tested
