Repository akka/akka, pull requests merged in 2020-07, with the labels that each got.

#29301 Update sbt-assembly to 0.15.0
  build.sbt
  project/plugins.sbt
Labels: tested

#29325 ClusterShardingSpec: Enable log capturing
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
Labels: tested, validating

#29337 Support persistAll for active active
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested

#29171 Docs: Actor sink stream operators
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRef.md
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/Sink/actorRef.md
  akka-docs/src/main/paradox/stream/operators/Sink/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorSink.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorSink.scala
  akka-stream-typed/src/test/java/docs/akka/stream/typed/ActorSinkWithAckExample.java
  akka-stream-typed/src/test/scala/docs/akka/stream/typed/ActorSourceSinkExample.scala
Labels: t:stream, tested

#29341 Partial revert of #29268 to preserve source compatibility
  akka-actor/src/main/scala-2.13/akka/util/ByteString.scala
Labels: tested

#29024 Docs: re-add akka.patterns page
  akka-actor/src/main/scala/akka/pattern/FutureTimeoutSupport.scala
  akka-actor/src/main/scala/akka/pattern/Patterns.scala
  akka-docs/src/main/paradox/.htaccess
  akka-docs/src/main/paradox/futures.md
  akka-docs/src/main/paradox/index-utilities.md
  akka-docs/src/test/java/jdocs/future/FutureDocTest.java
  akka-docs/src/test/scala/docs/future/FutureDocSpec.scala
Labels: tested

#29333 update the log message in docs for mixed versions
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
Labels: tested

#28940 Flush messages before DeathWatchNotification, #28695
  akka-actor/src/main/mima-filters/2.6.6.backwards.excludes/28695-isTerminating.excludes
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDeathWatchNotificationSpec.scala
  akka-remote/src/main/mima-filters/2.6.6.backwards.excludes/28695-watch-flush.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/Control.scala
  akka-remote/src/main/scala/akka/remote/artery/FlushBeforeDeathWatchNotification.scala
  akka-remote/src/main/scala/akka/remote/artery/FlushOnShutdown.scala
  akka-remote/src/main/scala/akka/remote/serialization/ArteryMessageSerializer.scala
  akka-remote/src/test/scala/akka/remote/artery/DeathWatchNotificationSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/ArteryMessageSerializerSpec.scala
Labels: tested

#29345 Change JsonFraming to fail stage if completing within an object #29228
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/JsonFramingSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/JsonObjectParser.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/JsonFraming.scala
Labels: t:stream, tested

#29335 Test coverage for active active published events after replay
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveEventPublishingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
Labels: tested

#29352 making explicit the posible configurations in typed of the akka.actor.provider
  akka-docs/src/main/paradox/typed/actor-discovery.md
Labels: tested

#29342 clear captured logs after successful tests #29339
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/LogCapturing.scala
Labels: tested

#29244 Reproduce and fix ByteString initialization issue
  akka-actor-tests/src/test/scala/akka/util/ByteStringInitializationSpec.scala
  akka-actor/src/main/scala-2.13/akka/util/ByteString.scala
Labels: tested, to-be-backported

#29302 Update sort-imports to 0.5.4
  project/ScalaFixExtraRulesPlugin.scala
Labels: tested

#29303 Update commons-io to 2.7
  project/Dependencies.scala
Labels: dependency-change, tested

#29296 Reduce assert time and increase poll freq PersistentTestKit
  akka-persistence-testkit/src/test/resources/application.conf
Labels: tested

#29294 BehaviourTestKit: Add receptionist inbox
  akka-actor-testkit-typed/src/main/mima-filters/2.6.6.backwards.excludes/29294-receptionist-inbox.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/ActorSystemStub.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/BehaviorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKit.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: tested

#29009 use datagram channel creator for udp sender
  akka-actor/src/main/scala/akka/io/UdpSender.scala
Labels: tested

#29332 Introduce version vectors for replicated events
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ActiveActiveShardingDirectReplicationSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveEventPublishingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PublishedEvent.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/VersionVector.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ActiveActiveEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
Labels: tested

#28618 [2.5] Fix ExplicitlyTriggeredScheduler cancellation
  akka-testkit/src/main/mima-filters/2.5.29.backwards.excludes
  akka-testkit/src/main/scala/akka/testkit/ExplicitlyTriggeredScheduler.scala
  akka-testkit/src/test/scala/akka/testkit/ExplicitlyTriggeredSchedulerSpec.scala
Labels: tested

#29358 Bytestring bits
  akka-actor/src/main/scala-2.12/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13/akka/util/ByteString.scala
Labels: tested

#29357 Revert "Flush messages before DeathWatchNotification, #28695 (#28940)"
  akka-actor/src/main/mima-filters/2.6.6.backwards.excludes/28695-isTerminating.excludes
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDeathWatchNotificationSpec.scala
  akka-remote/src/main/mima-filters/2.6.6.backwards.excludes/28695-watch-flush.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/Control.scala
  akka-remote/src/main/scala/akka/remote/artery/FlushBeforeDeathWatchNotification.scala
  akka-remote/src/main/scala/akka/remote/artery/FlushOnShutdown.scala
  akka-remote/src/main/scala/akka/remote/serialization/ArteryMessageSerializer.scala
  akka-remote/src/test/scala/akka/remote/artery/DeathWatchNotificationSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/ArteryMessageSerializerSpec.scala
Labels: tested

#29336 Sharding EntityRef for testing, #29267
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/testkit/TestEntityRefImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/testkit/javadsl/EntityRef.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/testkit/scaladsl/EntityRef.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/testkit/scaladsl/TestEntityRefSpec.scala
Labels: 2 - pick next, tested

#29245 Use the target actor name in the temporary ask actor name
  akka-actor-tests/src/test/scala/akka/pattern/AskSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.6.backwards.excludes/actor-path-in-ask-temp-name.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InternalRecipientRef.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorRefAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-actor/src/main/mima-filters/2.6.6.backwards.excludes/actor-path-in-ask-temp-name.excludes
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
  akka-actor/src/main/scala/akka/pattern/GracefulStopSupport.scala
  akka-actor/src/main/scala/akka/pattern/PromiseRef.scala
  akka-cluster-sharding-typed/src/main/mima-filters/2.6.6.backwards.excludes/actor-path-in-ask-temp-name.excludes
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/transport/ThrottlerTransportAdapter.scala
Labels: 2 - pick next, tested

#29361 Fix SBR lease-implementation config example
  akka-docs/src/main/paradox/split-brain-resolver.md
Labels: tested

#29190 Ok/error protocol and failable ask
  akka-actor-tests/src/test/java/akka/pattern/StatusReplyTest.java
  akka-actor-tests/src/test/scala/akka/pattern/StatusReplySpec.scala
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorContextAskTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsAskWithStatusTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.6.backwards.excludes/ask-with-status.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/AskPattern.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-actor/src/main/scala/akka/actor/Actor.scala
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
  akka-actor/src/main/scala/akka/pattern/Patterns.scala
  akka-actor/src/main/scala/akka/pattern/StatusReply.scala
  akka-cluster-sharding-typed/src/main/mima-filters/2.6.6.backwards.excludes/ask-with-status.excludes
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/testkit/TestEntityRefImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleDocTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithMutableState.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithNullState.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleDocSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithEventHandlersInState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithOptionState.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AkkaClusterTypedSerializer.scala
  akka-docs/src/main/paradox/typed/interaction-patterns.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/style-guide.md
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BlogPostEntity.scala
  akka-remote/src/main/java/akka/remote/ContainerFormats.java
  akka-remote/src/main/protobuf/ContainerFormats.proto
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/serialization/MiscMessageSerializer.scala
  akka-remote/src/test/scala/akka/remote/serialization/MiscMessageSerializerSpec.scala
Labels: 2 - pick next, tested

#29363 Allow 2.5 snapshot requirement in version check
  akka-actor-tests/src/test/scala/akka/AkkaVersionSpec.scala
  akka-actor/src/main/scala/akka/AkkaVersion.scala
Labels: tested

#29247 Added MergeSequence graph stage
  akka-docs/src/main/paradox/stream/operators/MergeSequence.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/main/paradox/stream/stream-graphs.md
  akka-docs/src/test/java/jdocs/stream/operators/MergeSequenceDocExample.java
  akka-docs/src/test/scala/docs/stream/operators/MergeSequenceDocExample.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergeSequenceSpec.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
  project/StreamOperatorsIndexGenerator.scala
Labels: 2 - pick next, t:stream, tested

#29366 Update sbt 1.3.13
  project/build.properties
Labels: tested

#29369 No dry run in release instructions
  RELEASING.md
Labels: tested

#29375 typo on release-drafter's template
  .github/release-drafter.yml
Labels: tested

#29376 actor: remove stack trace from AskTimeoutException
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
Labels: tested

#29370 Post 2.6.7 updates
  akka-cluster-sharding/src/main/mima-filters/2.6.x.backwards.excludes/jdk-11-specific-classes.excludes
  project/MiMa.scala
Labels: tested

#29356 Adds sample code for the monitor operator
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/monitor.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/Monitor.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Monitor.scala
Labels: t:docs, tested

#29381 Replace reference to deprecated API
  akka-docs/src/main/paradox/stream/stream-composition.md
Labels: tested

#29384 Allow entities to stop by terminating without remember entities
  akka-cluster-sharding/src/main/mima-filters/2.6.7.backwards.excludes/shard-state-transition-regression.excludes
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingConfig.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingLeaseSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/EntitiesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/EntityTerminationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/GetShardTypeNamesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/InactiveEntityPassivationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardingMigrationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentStartEntitySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ProxyShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesBatchedUpdatesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesShardIdExtractorChangeSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardRegionSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardWithLeaseSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/StartEntitySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/SupervisionSpec.scala
Labels: tested

#29380 Durable pruning fail fix
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/DurablePruningSpec.scala
Labels: tested

#29391 Update actor-lifecycle.md
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
Labels: tested

#29386 Initial docs for active active
  akka-docs/src/main/paradox/typed/images/causality.png
  akka-docs/src/main/paradox/typed/images/lww.png
  akka-docs/src/main/paradox/typed/images/replicated-events1.png
  akka-docs/src/main/paradox/typed/images/replicated-events2.png
  akka-docs/src/main/paradox/typed/index-persistence.md
  akka-docs/src/main/paradox/typed/persistence-active-active.md
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/AAAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/AABlogExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ActiveActiveCompileOnlySpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ActiveActiveEventSourcing.scala
Labels: tested

#29392 remove not needed curly braces
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
Labels: tested

#29362 Metadata for snapshots for active active
  akka-docs/src/main/paradox/persistence.md
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveSnapshotSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence/src/main/mima-filters/2.6.7.backwards.excludes/29217-active-active-event-sourcing.excludes
  akka-persistence/src/main/scala/akka/persistence/SnapshotProtocol.scala
Labels: tested

#29390 2.6.8 post release changes
  project/MiMa.scala
Labels: tested

#29379 addActorTerminationTask fix
  akka-actor-tests/src/test/scala/akka/actor/CoordinatedShutdownSpec.scala
  akka-actor/src/main/mima-filters/2.6.7.backwards.excludes/actor-termination-task.excludes
  akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala
Labels: tested

#29372 Port CRDTs from multi dc
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveBaseSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/CounterSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/LwwSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/ORSetSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/AABlogExampleSpec.scala
  akka-persistence-typed/src/main/java/akka/persistence/typed/serialization/Crdts.java
  akka-persistence-typed/src/main/protobuf/Crdts.proto
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/Counter.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/LwwTime.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/ORSet.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/OpCrdt.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ActiveActiveEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/serialization/CrdtSerializer.scala
  build.sbt
Labels: tested

#29394 Fix mima excludes for actor termination task
  akka-actor/src/main/mima-filters/2.6.8.backwards.excludes/actor-termination-task.excludes
Labels: tested

#29385 Avoid stuck rebalances during coordinator leaving
  akka-cluster-sharding/src/main/mima-filters/2.6.8.backwards.excludes/29385-sharding-leaving-fix.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: 2 - pick next, tested

#29396 Docs an example for triggers
  akka-docs/src/main/paradox/typed/index-persistence.md
  akka-docs/src/main/paradox/typed/persistence-active-active-examples.md
  akka-docs/src/main/paradox/typed/persistence-active-active.md
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/AAAuctionExampleSpec.scala
Labels: tested

#29403 typo
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29399 Fix logic in TestKitUtils.scrubActorSystemName() Resolves #28994
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitSpec.scala
  akka-testkit/src/main/scala/akka/testkit/TestKitUtils.scala
Labels: tested

#29364 Active active sharding
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingExtension.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ActiveActiveShardingExtensionImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/ActiveActiveShardingTest.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ActiveActiveShardingSpec.scala
  akka-docs/src/main/paradox/typed/persistence-active-active.md
Labels: tested

#29412 fix typo
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#29408 Make sure to gracefully stop replication streams when aa actor stops
  akka-docs/src/main/paradox/typed/persistence-active-active.md
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ActiveActiveCompileOnlyTest.java
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/AABlogExampleSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/LwwTime.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested

#29411 Incorrect assumption about event ordering in test fixed
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveSpec.scala
Labels: tested

#29413 EventPublishing API for Java
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingSettings.scala
  akka-docs/src/main/paradox/typed/persistence-active-active.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ActiveActiveEventSourcedBehavior.scala
Labels: tested

#29416 Don't log user event toString in active active
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested

#29417 ActiveActiveSharding make it possible to use with custom envelope
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingExtension.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ActiveActiveShardingExtensionImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/ActiveActiveShardingTest.java
Labels: tested

#29418 Active active docs mention plugin support
  akka-docs/src/main/paradox/typed/persistence-active-active.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence/src/main/scala/akka/persistence/SnapshotProtocol.scala
Labels: tested

#29378 Add verifyCodeStyle #29377
  CONTRIBUTING.md
  build.sbt
Labels: t:build, tested

#29431 Detect illegal access to context
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ActiveActiveIllegalAccessSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ActiveActiveEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
Labels: tested

#29421 Active active journal support changes
  akka-docs/src/main/paradox/typed/persistence-active-active.md
  akka-persistence-tck/src/main/scala/akka/persistence/CapabilityFlags.scala
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala
  akka-persistence-tck/src/main/scala/akka/persistence/snapshot/SnapshotStoreSpec.scala
  akka-persistence-typed/src/main/java/akka/persistence/typed/serialization/ActiveActive.java
  akka-persistence-typed/src/main/protobuf/ActiveActive.proto
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/serialization/ActiveActiveSerializer.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/ActiveActiveSerializationSpec.scala
  akka-persistence/src/main/scala/akka/persistence/SnapshotProtocol.scala
  project/OSGi.scala
Labels: tested

#29229 doc(RetryFlow): explain with more details
  akka-stream/src/main/scala/akka/stream/scaladsl/RetryFlow.scala
Labels: t:stream, tested

#29434 PersistentRepr serializer support for metadata
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ActiveActiveShardingSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ActiveActiveShardingExtensionImpl.scala
  akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/ORSet.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ActiveActiveEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ActiveActiveEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/serialization/ActiveActiveSerializer.scala
  akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java
  akka-persistence/src/main/protobuf/MessageFormats.proto
  akka-persistence/src/main/scala/akka/persistence/Persistent.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/MessageSerializer.scala
  akka-persistence/src/test/scala/akka/persistence/serialization/MessageSerializerSpec.scala
Labels: tested

#29435 Rename active active to replicated event sourcing
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedShardingExtension.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedShardingSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ReplicatedShardingExtensionImpl.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/ReplicatedShardingTest.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingDirectReplicationSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-docs/src/main/paradox/project/examples.md
  akka-docs/src/main/paradox/typed/cluster-dc.md
  akka-docs/src/main/paradox/typed/index-persistence.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-examples.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-tck/src/main/scala/akka/persistence/CapabilityFlags.scala
  akka-persistence-typed-tests/src/test/java/akka/persistence/typed/ReplicatedEventSourcingTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedEventSourcingCompileOnlyTest.java
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/MultiJournalReplicationSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventPublishingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationBaseSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationIllegalAccessSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationSnapshotSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/CounterSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/LwwSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/ORSetSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedBlogExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedEventSourcingCompileOnlySpec.scala
  akka-persistence-typed/src/main/java/akka/persistence/typed/serialization/ReplicatedEventSourcing.java
  akka-persistence-typed/src/main/mima-filters/2.6.7.backwards.excludes/29217-replicated-event-sourcing.excludes
  akka-persistence-typed/src/main/protobuf/ReplicatedEventSourcing.proto
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PublishedEvent.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/ReplicaId.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplicationSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ReplicatedEventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ReplicatedEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ReplicatedEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/serialization/ReplicatedEventSourcingSerializer.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingSerializationSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorWatchSpec.scala
  akka-persistence/src/main/scala/akka/persistence/SnapshotProtocol.scala
Labels: tested

#29438 Test case for three replicated event sourced entities
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingSpec.scala
Labels: tested

#29439 Document hot standby for replicated event sourcing
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
Labels: tested

#29404 Avoid warning for NoState to RememberingStart
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
Labels: tested

#29436 Restart replication stream from correct seen seqNr
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested

#29419 Clarify pool router routees are always local
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#29443 Replicated event sourcing auction example for Java
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-examples.md
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedAuctionExampleTest.java
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
  build.sbt
Labels: tested

#29442 Tagging for replicated event sourcing
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/EventStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/PersistenceTestKitPlugin.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SerializedEventStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/TestKitStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/internal/EventsByPersistenceIdStage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/javadsl/PersistenceTestKitReadJournal.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/scaladsl/PersistenceTestKitReadJournal.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/query/CurrentEventsByTagSpec.scala
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/MyReplicatedBehavior.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedEventSourcingCompileOnlyTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedStringSet.java
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingTaggingSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested
