Repository akka/akka, pull requests merged in 2020-12, with the labels that each got.

#29831 Stream Testkit: new-API-friendly
  akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala
  akka-docs/src/test/scala/docs/stream/GraphStageDocSpec.scala
  akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala
  akka-docs/src/test/scala/docs/stream/StreamTestKitDocSpec.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeAdhocSource.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeDroppyBroadcast.scala
  akka-stream-testkit/src/main/mima-filters/2.5.x.backwards.excludes/2.6.0.excludes
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/javadsl/TestSink.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/javadsl/TestSource.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/TestSink.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/TestSource.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphDSLCompileSpec.scala
  build.sbt
Labels: t:stream, tested

#29848 Ignore gossip desrialization failures
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested

#29834 Don't cache temp actors in ActorRefResolveCache, #29828
  akka-actor/src/main/scala/akka/actor/ActorRef.scala
  akka-remote/src/main/mima-filters/2.6.10.backwards.excludes/issue-29828-resolve-cache.excludes
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-remote/src/main/scala/akka/remote/artery/compress/InboundCompressions.scala
  akka-remote/src/main/scala/akka/remote/serialization/ActorRefResolveCache.scala
  akka-remote/src/test/scala/akka/remote/artery/ActorRefResolveCacheQuarantineSpec.scala
Labels: tested

#29857 Fixed a formatting issue
  akka-docs/src/main/paradox/typed/fsm.md
Labels: tested

#29856 Normalize Event Sourcing wording #29577
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedShardingExtension.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingDirectReplicationSpec.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-docs/src/main/paradox/cluster-sharding.md
  akka-docs/src/main/paradox/general/message-delivery-reliability.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/typed/from-classic.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/delivery/EventSourcedProducerQueue.scala
  akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
Labels: tested

#29862 docs: Link project info to snapshots
  project/project-info.conf
Labels: tested

#29860 Refactor example to make it easier to copy-paste #29578
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#29853 Add how to compose Partial Behaviors #29832
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-docs/src/main/paradox/typed/style-guide.md
Labels: tested

#29367 Use scalafix to update scala 2.13.3, silencer 1.7.0
  .scalafix.conf
  akka-actor-tests/src/test/scala/akka/actor/ActorLifeCycleSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ActorWithStashSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/FSMActorSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/RestartStrategySpec.scala
  akka-actor-tests/src/test/scala/akka/io/dns/internal/DnsClientSpec.scala
  akka-actor-tests/src/test/scala/akka/routing/ScatterGatherFirstCompletedSpec.scala
  akka-bench-jmh/src/main/scala/akka/BenchRunner.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/SbrTestLeaseActor.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ActorSystemSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/ddata/typed/scaladsl/ReplicatorDocSpec.scala
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
  akka-docs/src/test/scala/docs/actor/ActorDocSpec.scala
  akka-docs/src/test/scala/docs/actor/FaultHandlingDocSample.scala
  akka-docs/src/test/scala/docs/actor/io/dns/DnsCompileOnlyDocSpec.scala
  akka-docs/src/test/scala/docs/ddata/DistributedDataDocSpec.scala
  akka-docs/src/test/scala/docs/ddata/ShoppingCart.scala
  akka-docs/src/test/scala/docs/future/FutureDocSpec.scala
  akka-docs/src/test/scala/docs/io/EchoServer.scala
  akka-docs/src/test/scala/docs/persistence/PersistenceEventAdapterDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/query/PersistenceQueryDocSpec.scala
  akka-docs/src/test/scala/docs/stream/CompositionDocSpec.scala
  akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala
  akka-docs/src/test/scala/docs/stream/GraphDSLDocSpec.scala
  akka-docs/src/test/scala/docs/stream/GraphStageLoggingDocSpec.scala
  akka-docs/src/test/scala/docs/stream/QuickStartDocSpec.scala
  akka-docs/src/test/scala/docs/stream/StreamPartialGraphDSLDocSpec.scala
  akka-docs/src/test/scala/docs/stream/TwitterStreamQuickstartDocSpec.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeMultiGroupBy.scala
  akka-docs/src/test/scala/docs/stream/io/StreamFileDocSpec.scala
  akka-docs/src/test/scala/docs/stream/io/StreamTcpDocSpec.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Restart.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Tick.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Zip.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/ExtrapolateAndExpand.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Fold.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/MergeLatest.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Throttle.scala
  akka-docs/src/test/scala/docs/testkit/ParentChildSpec.scala
  akka-docs/src/test/scala/docs/testkit/TestkitDocSpec.scala
  akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala
  akka-stream-tests/src/test/scala/akka/stream/io/InputStreamSourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowZipWithIndexSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachAsyncSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StageActorRefSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamConvertersSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/UnfoldResourceSourceAsync.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala
  build.sbt
  project/AkkaDisciplinePlugin.scala
  project/ScalaFixExtraRulesPlugin.scala
  project/ScalaFixForJdk9Plugin.scala
  project/ScalafixForMultiNodePlugin.scala
  project/ScalafixIgnoreFilePlugin.scala
  project/ScalafixSupport.scala
Labels: tested

#29866 Better logging when no seed nodes found
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested

#29875 Operators: Add example for groupBy
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/groupBy.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/GroupBy.scala
Labels: t:docs, t:stream, tested

#29876 [Docs] Fix wrong syntax using paradox directives
  akka-docs/src/main/paradox/project/immutable.md
  akka-docs/src/main/paradox/stream/operators/Sink/collection.md
  akka-docs/src/main/paradox/stream/operators/Source/never.md
Labels: t:docs, tested

#29877 Include name attribute in GraphStageLogic toString
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: t:stream, tested

#29870 Adds 'exists' and 'contains' method to StashBuffer
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/StashBufferTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashBufferSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.10.backwards.excludes/stash-buffer-exists-contains.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/StashBuffer.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/StashBuffer.scala
Labels: tested

#29885 Update spray-json to 1.3.6
  project/Dependencies.scala
Labels: dependency-change, tested

#29884 Update sbt-bill-of-materials to 1.0.1
  project/plugins.sbt
Labels: tested

#29882 Update sbt-pgp to 2.0.2
  project/plugins.sbt
Labels: tested

#29880 Update sbt-scalafix to 0.9.24
  project/plugins.sbt
Labels: tested

#29883 Update paradox-theme-akka, ... to 0.36
  project/plugins.sbt
Labels: tested

#29890 =str Remove outHandler of FlattenMerge
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
Labels: t:stream, tested

#29888 Operators: Add example for watchTermination
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/watchTermination.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/WatchTermination.scala
Labels: tested

#29906 CI: run license checks from Travis
  .travis.yml
Labels: validating

#29907 [2.5.x] CI: check policies with environment key
  .travis.yml
Labels: tested

#29898 Akka 29891 testkit msg adaptors
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: tested

#29903 Akka 29900 stubbed timer
  akka-actor-testkit-typed/src/main/mima-filters/2.6.10.backwards.excludes/29903-actor-testkit-typed-timer-support
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/Effect.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/EffectfulActorContext.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/Effects.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/BehaviorTestKitTest.java
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.10.backwards.excludes/behavior-testkit-timer-support.backwards.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/TimerScheduler.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/TimerScheduler.scala
  akka-docs/src/main/paradox/typed/testing-sync.md
Labels: tested

#29910 Adds variant accepting any ack message (#29586)
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/Sink/actorRefWithBackpressure.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefBackpressureSinkSpec.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorSink.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorSink.scala
  akka-stream-typed/src/test/scala/akka/stream/typed/scaladsl/ActorSourceSinkSpec.scala
  akka-stream/src/main/mima-filters/2.6.x.backwards.excludes/29586-sink-internal-api.excludes
  akka-stream/src/main/scala/akka/stream/impl/ActorRefBackpressureSinkStage.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  build.sbt
Labels: t:stream, tested

#29918 Change wording on a sentence
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested
