Repository akka/akka, pull requests merged in 2020-09, with the labels that each got.

#29529 Fix tck persistence provider in jdocs
  akka-docs/src/test/java/jdocs/persistence/LambdaPersistencePluginDocTest.java
Labels: tested

#29533 Fix grammar in exception message
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
Labels: tested

#29541 Fix acceptable-heartbeat-pause in cluster.StressSpec, #29512
  akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala
Labels: tested

#29545 Sharding request-to-start but already started logging
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
Labels: tested

#29531 Document workaround for jackson serialiaztion of scala case objects
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
Labels: tested

#29522 Improve Shard#entityCreated API performance (#29520)
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
Labels: tested

#28915 Chunked messages in reliable delivery, #24276
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ConsumerControllerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/DurableProducerControllerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/DurableProducerQueueSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/DurableWorkPullingSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ProducerControllerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ReliableDeliveryRandomSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ReliableDeliverySpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/TestConsumer.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/TestDurableProducerQueue.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/TestProducerWithAsk.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/WorkPullingSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.8.backwards.excludes/issue-24276-reliable-chunks.excludes
  akka-actor-typed/src/main/resources/reference.conf
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/ConsumerController.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/DurableProducerQueue.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/ProducerController.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/WorkPullingProducerController.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ChunkedMessage.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ConsumerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ProducerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/WorkPullingProducerControllerImpl.scala
  akka-cluster-sharding-typed/src/main/resources/reference.conf
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/delivery/ShardingProducerController.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/delivery/internal/ShardingProducerControllerImpl.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/delivery/ReliableDeliveryShardingSpec.scala
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ReliableDelivery.java
  akka-cluster-typed/src/main/mima-filters/2.6.8.backwards.excludes/issue-24276-reliable-chunks.excludes
  akka-cluster-typed/src/main/protobuf/ReliableDelivery.proto
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/delivery/ReliableDeliverySerializer.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/ChunkLargeMessageSpec.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiNodeTypedClusterSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/delivery/ReliableDeliverySerializerSpec.scala
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/typed/reliable-delivery.md
  akka-docs/src/test/scala/docs/persistence/PersistenceSchemaEvolutionDocSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/delivery/EventSourcedProducerQueue.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/delivery/ReliableDeliveryWithEventSourcedProducerQueueSpec.scala
Labels: 2 - pick next, tested

#29547 Add links to how to deal with blocking APIs #29544
  akka-docs/src/main/paradox/general/actor-systems.md
  akka-docs/src/main/paradox/general/terminology.md
  akka-docs/src/main/paradox/typed/dispatchers.md
Labels: 2 - pick next, tested

#29539 Fix time in AtLeastOnce.setDeliverySnapshot, #27786
  akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala
Labels: 2 - pick next, tested

#29566 testkit: do not try to use 127.x.y.255 as a test localhost address
  akka-testkit/src/main/scala/akka/testkit/SocketUtil.scala
Labels: tested, to-be-backported

#29567 [2.5 backport] testkit: do not try to use 127.x.y.255 as a test localhost address
  akka-testkit/src/main/scala/akka/testkit/SocketUtil.scala
Labels: tested

#29561 minor doc updates for replicated event sourcing
  akka-docs/src/main/paradox/common/may-change.md
  akka-docs/src/main/paradox/common/other-modules.md
  akka-docs/src/main/paradox/project/examples.md
  akka-docs/src/main/paradox/typed/cqrs.md
Labels: 2 - pick next, tested

#29525 Reduce sharding warnings when there are no buffered messages
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: 2 - pick next, tested

#29572 Publish releases as 'github release' as well
  RELEASING.md
Labels: tested

#29569 Fix calculating backoff delay in order to prevent IllegalArgumentExce…
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
Labels: tested

#29570 Enable fatal errors for docs
  akka-docs/src/test/scala/docs/actor/ActorDocSpec.scala
  akka-docs/src/test/scala/docs/actor/FSMDocSpec.scala
  akka-docs/src/test/scala/docs/actor/FaultHandlingDocSample.scala
  akka-docs/src/test/scala/docs/actor/FaultHandlingDocSpec.scala
  akka-docs/src/test/scala/docs/actor/InitializationDocSpec.scala
  akka-docs/src/test/scala/docs/actor/PropsEdgeCaseSpec.scala
  akka-docs/src/test/scala/docs/actor/UnnestedReceives.scala
  akka-docs/src/test/scala/docs/actor/typed/CoordinatedActorShutdownSpec.scala
  akka-docs/src/test/scala/docs/cluster/FactorialBackend.scala
  akka-docs/src/test/scala/docs/cluster/FactorialFrontend.scala
  akka-docs/src/test/scala/docs/cluster/TransformationBackend.scala
  akka-docs/src/test/scala/docs/cluster/TransformationFrontend.scala
  akka-docs/src/test/scala/docs/coordination/LeaseDocSpec.scala
  akka-docs/src/test/scala/docs/dispatcher/DispatcherDocSpec.scala
  akka-docs/src/test/scala/docs/event/EventBusDocSpec.scala
  akka-docs/src/test/scala/docs/event/LoggingDocSpec.scala
  akka-docs/src/test/scala/docs/extension/ExtensionDocSpec.scala
  akka-docs/src/test/scala/docs/extension/SettingsExtensionDocSpec.scala
  akka-docs/src/test/scala/docs/future/FutureDocSpec.scala
  akka-docs/src/test/scala/docs/io/IODocSpec.scala
  akka-docs/src/test/scala/docs/io/ReadBackPressure.scala
  akka-docs/src/test/scala/docs/io/UdpDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/PersistenceEventAdapterDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/PersistencePluginDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/PersistentActorExample.scala
  akka-docs/src/test/scala/docs/persistence/query/LeveldbPersistenceQueryDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/query/MyEventsByTagSource.scala
  akka-docs/src/test/scala/docs/persistence/query/PersistenceQueryDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/testkit/PersistenceInitSpec.scala
  akka-docs/src/test/scala/docs/remoting/RemoteDeploymentDocSpec.scala
  akka-docs/src/test/scala/docs/routing/ConsistentHashingRouterDocSpec.scala
  akka-docs/src/test/scala/docs/routing/CustomRouterDocSpec.scala
  akka-docs/src/test/scala/docs/routing/RouterDocSpec.scala
  akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala
  akka-docs/src/test/scala/docs/stream/FlowStreamRefsDocSpec.scala
  akka-docs/src/test/scala/docs/stream/GraphStageDocSpec.scala
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
  akka-docs/src/test/scala/docs/stream/RateTransformationDocSpec.scala
  akka-docs/src/test/scala/docs/stream/ReactiveStreamsDocSpec.scala
  akka-docs/src/test/scala/docs/stream/RestartDocSpec.scala
  akka-docs/src/test/scala/docs/stream/StreamPartialGraphDSLDocSpec.scala
  akka-docs/src/test/scala/docs/stream/StreamTestKitDocSpec.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeAdhocSource.scala
  akka-docs/src/test/scala/docs/stream/operators/SourceOperators.scala
  akka-docs/src/test/scala/docs/stream/operators/converters/StreamConvertersToJava.scala
  akka-docs/src/test/scala/docs/stream/operators/flow/FromSinkAndSource.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Restart.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Tick.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Zip.scala
  akka-docs/src/test/scala/docs/testkit/ParentChildSpec.scala
  akka-docs/src/test/scala/docs/testkit/PlainWordSpec.scala
  akka-docs/src/test/scala/docs/testkit/TestKitUsageSpec.scala
  akka-docs/src/test/scala/docs/testkit/TestkitDocSpec.scala
  build.sbt
  project/AkkaDisciplinePlugin.scala
Labels: tested

#29576 Fix markdown syntax for link that uses parens
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#29551 Allocate rebalanced shards immediately, #29543
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested

#29580 Update latest patch version
  project/MiMa.scala
Labels: tested

#29546 Add app-version to the Member information, #27300
  akka-actor-tests/src/test/scala/akka/util/ManifestInfoSpec.scala
  akka-actor-tests/src/test/scala/akka/util/ManifestInfoVersionSpec.scala
  akka-actor-tests/src/test/scala/akka/util/VersionSpec.scala
  akka-actor/src/main/scala/akka/util/ManifestInfo.scala
  akka-actor/src/main/scala/akka/util/Version.scala
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/mima-filters/2.6.8.backwards.excludes/issue-27300-appVersion.excludes
  akka-cluster/src/main/protobuf/ClusterMessages.proto
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterJmx.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterSettings.scala
  akka-cluster/src/main/scala/akka/cluster/Member.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/JoinSeedNodeSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MBeanSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterConfigSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterHeartbeatSenderSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
  akka-cluster/src/test/scala/akka/cluster/CrossDcHeartbeatSenderSpec.scala
  akka-cluster/src/test/scala/akka/cluster/MemberOrderingSpec.scala
  akka-cluster/src/test/scala/akka/cluster/TestMember.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/TestAddresses.scala
Labels: tested

#29584 move mima filter to right version
  akka-cluster/src/main/mima-filters/2.6.9.backwards.excludes/issue-27300-appVersion.excludes
Labels: tested

#29555 Holistic shard allocation strategy, #29543
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/testkit/scaladsl/TestEntityRefSpec.scala
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/LeastShardAllocationStrategy.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGracefulShutdownSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingMinMembersSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/DeprecatedLeastShardAllocationStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/LeastShardAllocationStrategyRandomizedSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/LeastShardAllocationStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29583 Link to Replicated Event Sourcing video
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
Labels: tested

#29582 Adding missing word to Split Brain Resolver documentation
  akka-docs/src/main/paradox/split-brain-resolver.md
Labels: tested

#29593 Fix grammar
  akka-docs/src/main/paradox/typed/guide/actors-intro.md
Labels: tested

#29594 docs: Fix markdown link with brackets
  akka-docs/src/main/paradox/typed/guide/modules.md
Labels: tested

#29590 reduce too verbose logging sharding, #27276
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#29603 Increase stable-after in StressSpec, #29512
  akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala
Labels: tested

#29607 testkit: more resilient check for available loopback addresses in SocketUtil on MacOS
  akka-testkit/src/main/scala/akka/testkit/SocketUtil.scala
Labels: tested, to-be-backported

#29608 [2.5 backport] testkit: more resilient check for available loopback addresses in SocketUtil on MacOS
  akka-testkit/src/main/scala/akka/testkit/SocketUtil.scala
Labels: backport, tested

#29600 Adds mapAsync(Unordered) operator samples
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapAsync.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapAsyncUnordered.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/MapAsyncs.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/MapAsyncs.scala
Labels: tested

#29606 Terminates actor systems in parallel
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/RotatingKeysSSLEngineProviderSpec.scala
Labels: tested

#29605 Handle SubSource already timed out on failure or completion
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
Labels: t:stream, tested

#29610 remove redundant final in object private def
  akka-cluster/src/main/scala/akka/cluster/VectorClock.scala
Labels: tested

#29621 Remove unreferenced private method
  akka-cluster/src/main/scala/akka/cluster/Gossip.scala
Labels: tested

#29618 Tiny style fix
  akka-cluster/src/main/scala/akka/cluster/Reachability.scala
Labels: tested

#29622 Remove redundant brackets
  akka-cluster/src/main/scala/akka/cluster/VectorClock.scala
Labels: tested

#29617 Fix comment index
  akka-cluster/src/main/scala/akka/cluster/Gossip.scala
Labels: tested

#29548 Cluster aware shard allocation and rolling updates
  akka-actor/src/main/scala/akka/util/ConstantFun.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/AbstractLeastShardAllocationStrategy.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/LeastShardAllocationStrategy.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/RollingUpdateShardAllocationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/DeprecatedLeastShardAllocationStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/LeastShardAllocationStrategyRandomizedSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/LeastShardAllocationStrategySpec.scala
Labels: tested

#29634 clearAll when creating new EventSourcedBehaviorTestKit, #29609
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/EventSourcedBehaviorTestKitImpl.scala
Labels: 2 - pick next, tested

#29625 simplify the SBR instability check
  akka-cluster/src/main/mima-filters/2.6.9.backwards.excludes/sbr-setReachability.excludes
  akka-cluster/src/main/scala/akka/cluster/sbr/DowningStrategy.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/SplitBrainResolverSpec.scala
Labels: tested

#29611 support async reply and noReply in EventSourcedBehaviorTestKit, #29602 #29581
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/EventSourcedBehaviorTestKitImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/EventSourcedBehaviorTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/EventSourcedBehaviorTestKit.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/EventSourcedBehaviorTestKitSpec.scala
Labels: 2 - pick next, tested

#29624 another merge test for GCounter, #29616
  akka-distributed-data/src/test/scala/akka/cluster/ddata/GCounterSpec.scala
Labels: tested

#29613 Adding example of fold for sink
  akka-docs/src/main/paradox/stream/operators/Sink/fold.md
  akka-docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/sink/Fold.scala
Labels: tested

#29642 Docs for which versions support RES
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
Labels: tested

#29644 log transport flush timeout
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
Labels: tested

#29645 Include quarantine reason when ignored because unknown UID
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
Labels: tested

#29641 Docs: Reduce operator
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/reduce.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Reduce.scala
Labels: tested

#29646 Fix cross-dc heartbeat interval config, #29614
  akka-cluster/src/main/scala/akka/cluster/CrossDcClusterHeartbeat.scala
  akka-cluster/src/test/scala/akka/cluster/CrossDcHeartbeatSenderSpec.scala
Labels: tested

#29647 Fix documentation version warning for 'series' page
  akka-docs/src/main/paradox/assets/js/warnOldDocs.js
Labels: tested

#29619 Replace to with toSet
  akka-cluster/src/main/scala/akka/cluster/Reachability.scala
Labels: tested

#29657 Update sbt-jmh to 0.4.0
  project/plugins.sbt
Labels: tested

#29656 Update jctools-core to 3.1.0
  project/Dependencies.scala
Labels: dependency-change, tested

#29654 Update commons-io to 2.8.0
  project/Dependencies.scala
Labels: dependency-change, tested

#29643 harden ReliableDeliverySpec, #29340
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ReliableDeliverySpec.scala
Labels: tested

#29655 Update aeron-client, aeron-driver to 1.30.0
  project/Dependencies.scala
Labels: dependency-change, tested

#29653 Update commons-codec to 1.15
  project/Dependencies.scala
Labels: dependency-change, tested

#29650 use PersistenceTestKitReadJournal in EventSourcedBehaviorTestKit
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/EventSourcedBehaviorTestKitImpl.scala
Labels: tested

#29620 Remove weird char NBSP
  akka-cluster/src/main/scala/akka/cluster/Member.scala
Labels: tested

#29595 Fix grammar
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#29661 adjust default minimum for down-all-when-unstable
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolverSettings.scala
Labels: tested

#29664 Swap args when initializing *MajorityPlus classes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested

#29638 Cluster sharding health check
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingHealthCheck.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingHealthCheckSpec.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29502 Reintroduce flush on terminate
  akka-actor/src/main/mima-filters/2.6.9.backwards.excludes/28695-isTerminating.excludes
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDeathWatchNotificationSpec.scala
  akka-remote/src/main/mima-filters/2.6.9.backwards.excludes/28695-watch-flush.excludes
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/Control.scala
  akka-remote/src/main/scala/akka/remote/artery/FlushBeforeDeathWatchNotification.scala
  akka-remote/src/main/scala/akka/remote/artery/FlushOnShutdown.scala
  akka-remote/src/main/scala/akka/remote/serialization/ArteryMessageSerializer.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/RotatingKeysSSLEngineProviderSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/ArteryMessageSerializerSpec.scala
Labels: tested

#29658 Filter out messages from other replicated entities
  akka-cluster-sharding-typed/src/main/mima-filters/2.6.9.backwards.excludes/issue-29658-fix-direct-replication.excludes
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ReplicatedShardingExtensionImpl.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingDirectReplicationSpec.scala
  akka-persistence-typed/src/main/mima-filters/2.6.9.backwards.excludes/issue-26949-fix-direct-replication.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/ReplicationId.scala
Labels: tested

#29675 Fix for ReplicatedShardingSpec failing
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ReplicatedShardingExtensionImpl.scala
Labels: tested

#29637 Watching an actor ref on a member that left should give terminated
  akka-cluster/src/main/mima-filters/2.6.9.backwards.excludes/issue-29628-watch-and-tombstones.excludes
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterDeathWatchSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDomainEventSpec.scala
  akka-remote/src/main/scala/akka/remote/RemoteWatcher.scala
Labels: tested

#29639 Proper threadsafe collection of stream snapshots
  akka-stream/src/main/mima-filters/2.6.9.backwards.excludes/28960-stream-snapshots.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala
Labels: t:stream, tested

#29596 Fix links to Microsoft CQRS and ES reference
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/typed/guide/modules.md
Labels: tested

#29579 Make a distinction between hand-offs for rebalance and region shutdown
  akka-cluster-sharding/src/main/mima-filters/2.6.9.backwards.excludes/29549-distinct-shutdown-and-rebalance.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
Labels: tested

#29673 Add completion timeout example
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/completionTimeout.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/CompletionTimeout.scala
Labels: tested

#29665 Config for when to move to WeaklyUp
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterSettings.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MemberWeaklyUpSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MinMembersBeforeUpSpec.scala
Labels: tested

#29666 Documentation for Sharding rolling update
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/JoinSeedNodeSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterSpec.scala
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/typed/cluster-sharding-concepts.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29678 [Docs] Make Rejected extend OperationResult
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
Labels: tested
