Repository akka/akka, pull requests merged in 2020-04, with the labels that each got.

#28738 Add punctuation and fix some typo's
  akka-docs/src/main/paradox/typed/reliable-delivery.md
Labels: tested

#28834 change %mdc examples, and tests
  akka-actor-testkit-typed/src/test/resources/logback-test.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-dev.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-prod.xml
  akka-actor-typed-tests/src/test/resources/logback-doc-test.xml
  akka-actor-typed-tests/src/test/resources/logback-test.xml
  akka-bench-jmh/src/main/resources/logback.xml
  akka-cluster-metrics/src/test/resources/logback-test.xml
  akka-cluster-sharding-typed/src/multi-jvm/resources/logback-test.xml
  akka-cluster-sharding-typed/src/test/resources/logback-test.xml
  akka-cluster-typed/src/multi-jvm/resources/logback-test.xml
  akka-cluster-typed/src/test/resources/logback-test.xml
  akka-docs/src/main/paradox/logging.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-docs/src/test/resources/logback-test.xml
  akka-osgi/src/test/resources/logback-test.xml
  akka-persistence-typed/src/test/resources/logback-test.xml
Labels: tested

#28843 fix DispatcherSameAsParent when using ClusterActorRefProvider, #28842
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestKitUtils.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/DispatcherSelectorSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/ClusterDispatcherSelectorSpec.scala
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
Labels: tested

#28777 [DOC] Fix example package names in `Learning Akka Typed from Classic `
  akka-docs/src/main/paradox/typed/from-classic.md
Labels: tested

#28855 Update sbt to 1.3.9
  project/build.properties
Labels: tested

#28858 Fix compiling javadoc jar
  project/Doc.scala
Labels: tested

#28809 Persistence initialization utility #28808
  akka-docs/src/main/paradox/typed/persistence-testing.md
  akka-docs/src/test/java/jdocs/persistence/testkit/PersistenceInitTest.java
  akka-docs/src/test/scala/docs/persistence/testkit/PersistenceInitSpec.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/PersistenceInitImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/PersistenceInit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/PersistenceInit.scala
Labels: tested

#28854 Update sbt-paradox-akka to 0.32
  project/plugins.sbt
Labels: tested

#28845 Update sbt-reproducible-builds to 0.24
  project/plugins.sbt
Labels: tested

#28739 Expose capacity property on StashBuffer
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashBufferSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.3.backwards.excludes/pr-28739-expose-stashbuffer-capacity.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/StashBuffer.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/StashBuffer.scala
Labels: tested

#28860 Document how to publish updated documentation
  RELEASING.md
Labels: tested

#28864 Move StashBuffer.capacity to 2.6.4 excludes
  akka-actor-typed/src/main/mima-filters/2.6.4.backwards.excludes/pr-28739-expose-stashbuffer-capacity.excludes
Labels: validating

#28795 Notify Receptionist subscribers when node added and removed, #28792
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ClusterMessages.java
  akka-cluster-typed/src/main/mima-filters/2.6.4.backwards.excludes/issue-28792-ClusterReceptionist.excludes
  akka-cluster-typed/src/main/protobuf/ClusterMessages.proto
  akka-cluster-typed/src/main/resources/reference.conf
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AkkaClusterTypedSerializer.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionist.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSettings.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/AkkaClusterTypedSerializerSpec.scala
  akka-cluster-typed/src/test/scala/akka/cluster/typed/internal/receptionist/ClusterReceptionistSpec.scala
Labels: tested

#28865 Update interaction-patterns.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#28775 Unstash one instead of all in ConsumerController, #28718
  akka-actor-typed-tests/src/test/resources/logback-test.xml
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ConsumerControllerSpec.scala
  akka-actor-typed/src/main/scala-jdk-9/akka/actor/typed/internal/jfr/Events.scala
  akka-actor-typed/src/main/scala-jdk-9/akka/actor/typed/internal/jfr/JFRActorFlightRecorder.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ConsumerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorFlightRecorder.scala
Labels: dependency-change, t:stream, tested

#28805 improvements of the PersistenceTestKit doc samples
  akka-docs/src/main/paradox/typed/persistence-testing.md
  akka-docs/src/test/java/jdocs/persistence/testkit/PersistenceTestKitSampleTest.java
  akka-docs/src/test/java/jdocs/persistence/testkit/TestKitExamples.java
  akka-docs/src/test/scala/docs/persistence/testkit/TestKitExamples.scala
  build.sbt
Labels: tested

#28735 Step two in the cluster message manifest change
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
Labels: tested

#28717 The parasitic marked internal stable and further docs on the annotation
  akka-actor/src/main/java/akka/annotation/InternalStableApi.java
  akka-actor/src/main/scala/akka/dispatch/Future.scala
Labels: tested

#28779 Typed: Configurable resend interval for ProducerController
  akka-actor-typed/src/main/resources/reference.conf
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/ProducerController.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ProducerControllerImpl.scala
Labels: tested

#28776 Refactor remember entitites in shards
  akka-actor/src/main/scala/akka/pattern/internal/BackoffOnStopSupervisor.scala
  akka-cluster-sharding/src/main/mima-filters/2.6.4.backwards.excludes/remember-entities-refactor.excludes
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/CustomStateStoreModeProvider.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EntityRecoveryStrategy.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntities.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntitiesStarter.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntitiesStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/AllAtOnceEntityRecoveryStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingLeaseSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ConcurrentStartupShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ConstantRateEntityRecoveryStrategySpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/CoordinatedShutdownShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/GetShardTypeNamesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/InactiveEntityPassivationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/JoinConfigCompatCheckShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ProxyShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RemoveInternalClusterShardingDataSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardRegionSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardWithLeaseSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/SupervisionSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializerSpec.scala
Labels: tested

#28877 mima filter for ProducerController.Settings constructor, #28747
  akka-actor-typed/src/main/mima-filters/2.6.4.backwards.excludes/issue-28747-ProducerController.excludes
Labels: 2 - pick next, tested

#28866 Update aeron-client, aeron-driver to 1.27.0
  project/Dependencies.scala
Labels: dependency-change, tested

#28873 clarify the implicit parameters of AskPattern, #28836
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#28799 possibility to select dispatcher for delivery actors
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/ProducerController.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/WorkPullingProducerController.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ProducerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/WorkPullingProducerControllerImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/delivery/ShardingProducerController.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/delivery/internal/ShardingConsumerControllerImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/delivery/internal/ShardingProducerControllerImpl.scala
Labels: tested

#28891 Clarify 'inconsistent classpath' error
  akka-actor-tests/src/test/scala/akka/util/ManifestInfoSpec.scala
  akka-actor/src/main/scala/akka/util/ManifestInfo.scala
Labels: tested

#28892 Fix ReliableDeliveryBenchmark on JDK8, #28889
  akka-bench-jmh/src/main/scala/akka/actor/typed/delivery/ReliableDeliveryBenchmark.scala
Labels: tested

#28886 Don't rely on logs in pubsub spec
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/pubsub/LocalPubSubSpec.scala
Labels: tested

#28893 Minor improvement in Artery logging
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
Labels: tested

#28888 actor: streamline cross source directory usage
  akka-actor/src/main/scala-2.12/akka/dispatch/internal/SameThreadExecutionContext.scala
  akka-actor/src/main/scala-2.12/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.12/akka/util/ccompat/CompatImpl.scala
  akka-actor/src/main/scala-2.12/akka/util/ccompat/ccompatUsedUntil213.scala
  akka-actor/src/main/scala-2.12/akka/util/ccompat/package.scala
  akka-actor/src/main/scala-2.13/akka/dispatch/internal/SameThreadExecutionContext.scala
  akka-actor/src/main/scala-2.13/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.13/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13/akka/util/ccompat/ccompatUsedUntil213.scala
  akka-actor/src/main/scala-2.13/akka/util/ccompat/package.scala
Labels: tested

#28894 build: remove scala-2.13+ / scala-2.13- directories for now
  project/AkkaBuild.scala
Labels: tested

#28896 Silence another close error in multi-jvm tests
  akka-multi-node-testkit/src/main/mima-filters/2.6.4.backwards.excludes/RemoteConnection-shutdown.excludes
  akka-multi-node-testkit/src/main/scala/akka/remote/testconductor/RemoteConnection.scala
Labels: tested

#28871 Fix 27338 - Allow passing an actor system to the typed.ActorTestKit
  akka-actor-testkit-typed/src/main/mima-filters/2.6.4.backwards.excludes/27338-ActorTestKit-system.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestKitJunitResource.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ScalaTestWithActorTestKit.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitSpec.scala
Labels: 2 - pick next, tested

#28890 #28869 - example for setting policies in docs (persistence testkit)
  akka-docs/src/main/paradox/typed/persistence-testing.md
  akka-docs/src/test/java/jdocs/persistence/testkit/PersistenceTestKitPolicySampleTest.java
  akka-docs/src/test/scala/docs/persistence/testkit/TestKitExamples.scala
Labels: tested

#28887 Make sure subscription completed before testing
  akka-actor-testkit-typed/src/main/mima-filters/2.6.4.backwards.excludes/28885-event-bus-testkit-addons.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestKitJunitResource.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitBase.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/TestProbe.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/TimerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
Labels: tested

#28758 OSGi: register ActorSystem under ActorFactoryRef interface
  akka-osgi/src/main/scala/akka/osgi/ActorSystemActivator.scala
Labels: t:osgi, tested

#28911 Update metrics-core, metrics-jvm to 4.1.6
  project/Dependencies.scala
Labels: dependency-change, tested

#28912 Update sbt-header to 5.5.0
  project/plugins.sbt
Labels: tested

#28790 avoid filling ConsumerController stash with resent messages
  akka-actor-typed/src/main/scala-jdk-9/akka/actor/typed/internal/jfr/Events.scala
  akka-actor-typed/src/main/scala-jdk-9/akka/actor/typed/internal/jfr/JFRActorFlightRecorder.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ConsumerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ProducerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorFlightRecorder.scala
Labels: tested

#28783 multi-node throughput test for reliable delivery, #28725
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/delivery/DeliveryThroughputSpec.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/BenchmarkFileReporter.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/TestRateReporter.scala
  build.sbt
Labels: tested

#28874 JMH bench for work pulling, 28725
  akka-bench-jmh/src/main/scala/akka/actor/typed/delivery/ReliableDeliveryBenchmark.scala
Labels: tested

#28921 Update sbt to 1.3.10
  project/build.properties
Labels: tested

#28924 Doc statement no longer true with new Actor APIs
  akka-docs/src/main/paradox/stream/stream-introduction.md
Labels: tested

#28902 =clu Not allow `null` messages to be sent to Shard
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingMessageExtractor.scala
Labels: tested

#28933 Remove microkernel leftovers in ActorSystem
  akka-actor/src/main/mima-filters/2.6.4.backwards.excludes/kernel-legacy.excludes
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: tested

#28929 Doc correction of ClusterMessageSerializer manifests change
  akka-docs/src/main/paradox/project/rolling-update.md
Labels: tested

#28930 Update the schema evolution doc to also mention Jackson, #28916
  akka-docs/src/main/paradox/persistence-schema-evolution.md
Labels: tested

#28878 avoid touching MDC for context.log.trace in reliable delivery
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ConsumerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ProducerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/WorkPullingProducerControllerImpl.scala
  akka-bench-jmh/src/main/scala/akka/actor/typed/delivery/ReliableDeliveryBenchmark.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/delivery/internal/ShardingProducerControllerImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/delivery/EventSourcedProducerQueue.scala
Labels: tested

#28920 JacksonCborSerializer should use CBOR ofc, #28918
  akka-docs/src/main/paradox/project/rolling-update.md
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
Labels: tested

#28941 #28908 - rename returnDefaultPolicy to resetPolicy
  akka-docs/src/test/java/jdocs/persistence/testkit/PersistenceTestKitPolicySampleTest.java
  akka-docs/src/test/scala/docs/persistence/testkit/TestKitExamples.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/TestKitStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/SnapshotTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/TestOps.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/CommonSnapshotTests.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/javadsl/CommonTestKitTests.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/CommonSnapshotTests.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/CommonTestKitTests.scala
Labels: tested

#28958 Fix grammatical error
  akka-docs/src/main/paradox/typed/from-classic.md
Labels: tested

#28954 fix wrong ActorSystem name when using MultiNodeClusterShardingSpec #28953
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestKitUtils.scala
  akka-multi-node-testkit/src/main/scala/akka/remote/testkit/MultiNodeSpec.scala
  akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamSpec.scala
  akka-testkit/src/main/scala/akka/testkit/TestKitUtils.scala
  akka-testkit/src/test/scala/akka/testkit/AkkaSpec.scala
Labels: t:stream, tested

#28969 Fix typo in ClusterMetricsDisabledSpec
  akka-cluster-metrics/src/multi-jvm/scala/akka/cluster/metrics/ClusterMetricsExtensionSpec.scala
Labels: tested

#28962 Update sbt-java-formatter to 0.5.1 and disable javafmt on compile
  project/JavaFormatter.scala
  project/plugins.sbt
Labels: tested

#28895 Harden ShardCoordinator state replication, #28856
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingLeavingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatedDataMessages.java
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatorMessages.java
  akka-distributed-data/src/main/mima-filters/2.6.4.backwards.excludes/issue-28856-coordinator-state.excludes
  akka-distributed-data/src/main/protobuf/ReplicatorMessages.proto
  akka-distributed-data/src/main/resources/reference.conf
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializer.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/WriteAggregatorSpec.scala
  akka-distributed-data/src/test/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializerSpec.scala
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: 2 - pick next, tested

#28975 Docs: list persistence plugins
  akka-docs/src/main/paradox/persistence-plugins.md
Labels: 2 - pick next, t:docs, tested

#28857 Check mima against 2.5.31
  project/MiMa.scala
Labels: 2 - pick next, tested

#28950 Docs: API docs for asSourceWithContext
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: t:stream, tested

#28584 Docs: flatMapConcat
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/flatMapConcat.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/FlatMapConcat.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/FlatMapConcat.scala
Labels: tested

#28687 Minor typo in documentation.
  akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala
Labels: tested

#28974 remove visible protobuf-java dependency from akka-protobuf-v3, #28939
  build.sbt
  project/Dependencies.scala
Labels: 2 - pick next, dependency-change, tested

#28586 Docs: mergeLatest
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mergeLatest.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/MergeLatest.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/MergeLatest.scala
Labels: tested

#28981 actor: use simple comparison in LightArrayRevolverScheduler
  akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala
Labels: tested, to-be-backported

#28944 Update sbt-header to 5.6.0
  project/plugins.sbt
Labels: tested

#28932 Allow changing the recovery strategy in a typed persistence actor #25216
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/mima-filters/2.6.4.backwards.excludes/issue-25216-typed-persistence-recovery-strategies.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RecoveryImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/Recovery.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/Recovery.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorWatchSpec.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: 2 - pick next, tested

#28983 Update sbt-paradox-akka to 0.33
  project/plugins.sbt
Labels: tested

#28909 Shard coordinator remember entities refactor
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/CustomStateStoreModeProvider.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesCoordinatorStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesProvider.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntities.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/RememberEntitiesStore.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesFailureSpec.scala
Labels: tested

#28881 Add Source.fromJavaStream as convenient method alias
  akka-docs/src/main/paradox/stream/operators/Source/fromJavaStream.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/source/From.java
  akka-docs/src/test/scala/docs/stream/operators/source/From.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: t:stream, tested

#28868 Use sbt-publish-rsync rather than our own
  RELEASING.md
  build.sbt
  project/Doc.scala
  project/Paradox.scala
  project/Publish.scala
  project/plugins.sbt
  project/scripts/release
Labels: tested

#28762 Docs: sync and refresh ask stream operators
  akka-docs/src/main/paradox/stream/operators/ActorFlow/ask.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/ask.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-typed/src/test/java/akka/stream/typed/javadsl/ActorFlowCompileTest.java
  akka-stream-typed/src/test/java/docs/javadsl/ActorFlowCompileTest.java
  akka-stream-typed/src/test/scala/docs/scaladsl/ActorFlowSpec.scala
Labels: 2 - pick next, t:docs, t:stream, tested

#28900 Docs: sort all operators by method name in left-hand menu
  akka-docs/src/main/paradox/stream/operators/Sink/actorRef.md
  akka-docs/src/main/paradox/stream/operators/Sink/asPublisher.md
  akka-docs/src/main/paradox/stream/operators/Sink/cancelled.md
  akka-docs/src/main/paradox/stream/operators/Sink/combine.md
  akka-docs/src/main/paradox/stream/operators/Sink/fold.md
  akka-docs/src/main/paradox/stream/operators/Sink/foreach.md
  akka-docs/src/main/paradox/stream/operators/Sink/foreachAsync.md
  akka-docs/src/main/paradox/stream/operators/Sink/foreachParallel.md
  akka-docs/src/main/paradox/stream/operators/Sink/fromSubscriber.md
  akka-docs/src/main/paradox/stream/operators/Sink/head.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/ask.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/fromMaterializer.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/setup.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRef.md
  akka-docs/src/main/paradox/stream/operators/Source/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/Source/asSubscriber.md
  akka-docs/src/main/paradox/stream/operators/Source/combine.md
  akka-docs/src/main/paradox/stream/operators/Source/completionStage.md
  akka-docs/src/main/paradox/stream/operators/Source/completionStageSource.md
  akka-docs/src/main/paradox/stream/operators/Source/cycle.md
  akka-docs/src/main/paradox/stream/operators/Source/empty.md
  akka-docs/src/main/paradox/stream/operators/Source/failed.md
  akka-docs/src/main/paradox/stream/operators/Source/from.md
  akka-docs/src/main/paradox/stream/operators/Source/fromCompletionStage.md
  akka-docs/src/main/paradox/stream/operators/Source/fromFuture.md
  akka-docs/src/main/paradox/stream/operators/Source/fromFutureSource.md
  akka-docs/src/main/paradox/stream/operators/Source/fromIterator.md
  akka-docs/src/main/paradox/stream/operators/Source/fromPublisher.md
  akka-docs/src/main/paradox/stream/operators/Source/fromSourceCompletionStage.md
  akka-docs/src/main/paradox/stream/operators/Source/future.md
  akka-docs/src/main/paradox/stream/operators/Source/futureSource.md
  akka-docs/src/main/paradox/stream/operators/Source/lazily.md
  akka-docs/src/main/paradox/stream/operators/Source/lazilyAsync.md
  akka-docs/src/main/paradox/stream/operators/Source/lazyCompletionStage.md
  akka-docs/src/main/paradox/stream/operators/Source/lazyCompletionStageSource.md
  akka-docs/src/main/paradox/stream/operators/Source/lazyFuture.md
  akka-docs/src/main/paradox/stream/operators/Source/lazyFutureSource.md
  akka-docs/src/main/paradox/stream/operators/Source/lazySingle.md
  akka-docs/src/main/paradox/stream/operators/Source/lazySource.md
  akka-docs/src/main/paradox/stream/operators/Source/maybe.md
  akka-docs/src/main/paradox/stream/operators/index.md
  project/StreamOperatorsIndexGenerator.scala
Labels: 2 - pick next, needs-attention, t:docs, t:stream

#28844 Dynamically adjust the ConsumerController's resend interval for Request, #28720
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ConsumerControllerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/DurableProducerControllerSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ReliableDeliveryRandomSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.4.backwards.excludes/reliable-delivery.excludes
  akka-actor-typed/src/main/resources/reference.conf
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/ConsumerController.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ConsumerControllerImpl.scala
Labels: 2 - pick next, tested

#28797 Examples for extrapolate
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/expand.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/extrapolate.md
  akka-docs/src/main/paradox/stream/stream-rate.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/ExtrapolateAndExpand.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/ExtrapolateAndExpand.scala
Labels: tested

#28988 Check that ActorIdentity is from the expected ActorPath
  akka-remote/src/test/scala/akka/remote/artery/RemoteSendConsistencySpec.scala
Labels: tested

#28946 Handling of onSpinWait and its absence in AffinityPool
  akka-actor/src/main/java/akka/dispatch/affinity/OnSpinWait.java
  akka-actor/src/main/scala/akka/dispatch/affinity/AffinityPool.scala
Labels: 2 - pick next, tested

#28945 Handling of onSpinWait and its absence in AffinityPool
  akka-actor/src/main/java/akka/dispatch/affinity/OnSpinWait.java
  akka-actor/src/main/scala/akka/dispatch/affinity/AffinityPool.scala
Labels: 2 - pick next, tested

#28952 Synchronous TestKit for EventSourcedBehavior, #23712
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ActorTestKit.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleDocTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleDocSpec.scala
  akka-docs/src/main/paradox/typed/persistence-testing.md
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/EventSourcedBehaviorTestKitImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/EventSourcedBehaviorTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/javadsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/EventSourcedBehaviorTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/test/resources/logback-test.xml
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/EventSourcedBehaviorTestKitSpec.scala
  akka-persistence-typed/src/main/mima-filters/2.6.4.backwards.excludes/issue-23712-testkit.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RequestingRecoveryPermit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/StashManagement.scala
  build.sbt
  project/Dependencies.scala
  project/project-info.conf
Labels: 2 - pick next, dependency-change, tested

#28995 A few more apidoc directives
  akka-docs/src/main/paradox/stream/operators/RestartFlow/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSink/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSource/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RetryFlow/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/Sink/collection.md
  akka-docs/src/main/paradox/stream/operators/Sink/combine.md
  akka-docs/src/main/paradox/stream/operators/Sink/queue.md
  akka-docs/src/main/paradox/stream/operators/Sink/setup.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/alsoTo.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/batchWeighted.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/buffer.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/collect.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/completionTimeout.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/concat.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/idleTimeout.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/log.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/merge.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/setup.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/throttle.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/watch.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zip.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/zipWith.md
  akka-docs/src/main/paradox/stream/operators/Source/combine.md
  akka-docs/src/main/paradox/stream/operators/Source/queue.md
Labels: tested

#28992 Support GetClusterShardingStats query in Typed #24466
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingQuery.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardingState.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/ClusterShardingStatsSpec.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ShardingCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingStateSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingStatsSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ShardingCompileOnlySpec.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGetStatsSpec.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#28998 Docs: Javadoc links in project info
  project/project-info.conf
Labels: tested

#29003 fix publishRsync in release script
  project/scripts/release
Labels: tested
