Repository akka/akka, pull requests merged in 2020-02, with the labels that each got.

#28543 Update sbt-unidoc to 0.4.3
  project/plugins.sbt
Labels: tested

#28492 stream: fail eagerly during SubSink/SubSource materialization
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowPrefixAndTailSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSplitWhenSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
Labels: tested, to-be-backported

#28564 stream: remove extra printStackTrace
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSplitWhenSpec.scala
Labels: tested

#28560 Fix filter operator example output
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Filter.scala
Labels: tested

#28565 harden ClusterSingletonManagerLeave2Spec, #27555 (#27565)
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerLeave2Spec.scala
Labels: backport, tested

#28551 Improved error message when loading ServiceDiscovery impl
  akka-discovery/src/main/scala/akka/discovery/Discovery.scala
Labels: tested

#28549 Getting started referred to a package name not present in quickstart
  akka-docs/src/main/paradox/typed/guide/tutorial_1.md
  akka-docs/src/main/paradox/typed/guide/tutorial_2.md
  akka-docs/src/main/paradox/typed/guide/tutorial_3.md
  akka-docs/src/test/scala/typed/tutorial_3/DeviceInProgress.scala
Labels: tested

#28563 [2.5 backport] stream: fail eagerly during SubSink/SubSource material…ization
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowPrefixAndTailSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSplitWhenSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
Labels: backport, tested

#28526 add GPG_TTY instruction
  project/scripts/release
Labels: tested

#28561 Update sbt to 1.3.8
  project/build.properties
Labels: tested

#28534 update MiMa latestPatch
  akka-remote/src/main/mima-filters/2.6.x.backwards.excludes/jdk11-specific-classes.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.29.backwards.excludes
  akka-stream/src/main/mima-filters/2.6.x.backwards.excludes/28324-jdk9-specific-classes.backwards.excludes
  project/MiMa.scala
Labels: tested

#28570 test Jackson serialization of UUID
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
Labels: tested

#28572 Fix typo depredated, change to deprecated
  akka-actor/src/main/resources/reference.conf
Labels: tested

#28380 stream: add flatMapPrefix operator
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/flatMapPrefix.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests-tck/src/test/scala/akka/stream/tck/FlatMapPrefixTest.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/FlatMapPrefix.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: 2 - pick next, tested

#28573 Change link from google groups to discuss
  akka-docs/src/main/paradox/project/links.md
Labels: tested

#28562 Execute post stop for guardian behaviors
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/OnSignalSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/GuardianStartupBehavior.scala
Labels: tested

#28522 Use unique name for typed and untyped testprobes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/ActorTestKitSpec.scala
  akka-testkit/src/main/scala/akka/testkit/TestKit.scala
Labels: tested

#28554 Configure Autolabler
  .github/autolabeler.yml
Labels: tested

#28575 doc: links to latest videos
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/typed/dispatchers.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#28569 doc: header level of Polymorphic types in Jackson docs
  akka-docs/src/main/paradox/serialization-jackson.md
Labels: tested

#28576 Improve error message when coordinator not found
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#28528 Do not cache PromiseActorRef
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
Labels: tested

#28530 Make the ScalaFiddle example copy-pastable, and runnable
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
Labels: tested

#28585 Some improvements to Java tutorial
  akka-docs/src/main/paradox/typed/guide/tutorial_1.md
Labels: tested

#28459 update to sbt-java-formatter to 0.5.0, and sbt 1.3.6
  akka-actor/src/main/mima-filters/2.4.8.backwards.excludes
  akka-actor/src/main/mima-filters/2.4.x.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.12.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.17.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.24.backwards.excludes
  akka-actor/src/main/mima-filters/2.5.25.backwards.excludes
  akka-camel/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster-metrics/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster-metrics/src/main/mima-filters/2.5.24.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.4.x.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster-sharding/src/main/mima-filters/2.5.24.backwards.excludes
  akka-cluster-tools/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster-tools/src/main/mima-filters/2.5.24.backwards.excludes
  akka-cluster/src/main/mima-filters/2.5.17.backwards.excludes
  akka-cluster/src/main/mima-filters/2.5.24.backwards.excludes
  akka-coordination/src/main/mima-filters/2.5.24.backwards.excludes
  akka-discovery/src/main/mima-filters/2.5.19.backwards.excludes
  akka-discovery/src/main/mima-filters/2.5.24.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.4.x.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.5.17.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.5.21.backwards.excludes
  akka-distributed-data/src/main/mima-filters/2.5.24.backwards.excludes
  akka-docs/src/test/java/jdocs/stream/TwitterStreamQuickstartDocTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeGlobalRateLimit.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeMultiGroupByTest.java
  akka-multi-node-testkit/src/main/mima-filters/2.5.17.backwards.excludes
  akka-multi-node-testkit/src/main/mima-filters/2.5.24.backwards.excludes
  akka-persistence-query/src/main/mima-filters/2.5.17.backwards.excludes
  akka-persistence-query/src/main/mima-filters/2.5.24.backwards.excludes
  akka-persistence/src/main/mima-filters/2.4.x.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.17.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.24.backwards.excludes
  akka-persistence/src/main/mima-filters/2.5.25.backwards.excludes
  akka-remote/src/main/mima-filters/2.4.x.backwards.excludes
  akka-remote/src/main/mima-filters/2.5.17.backwards.excludes
  akka-remote/src/main/mima-filters/2.5.24.backwards.excludes
  akka-remote/src/main/mima-filters/2.5.25.backwards.excludes
  akka-stream/src/main/mima-filters/2.4.11.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.11.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.17.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.21.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.22.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.24.backwards.excludes
  akka-stream/src/main/mima-filters/2.5.4.backwards.excludes
  akka-testkit/src/main/mima-filters/2.5.17.backwards.excludes
  akka-testkit/src/main/mima-filters/2.5.24.backwards.excludes
  project/Dependencies.scala
  project/JavaFormatter.scala
  project/MiMa.scala
  project/build.properties
  project/plugins.sbt
Labels: tested

#28579 doc: minor typo fix
  akka-docs/src/main/paradox/general/stream/stream-design.md
Labels: tested

#28539 Issue#26072:Added lombok usage documentation
  akka-docs/src/main/paradox/project/immutable.md
  akka-docs/src/main/paradox/project/index.md
Labels: tested

#28525 Avoid 'dead code' errors when compiling in IntelliJ
  akka-actor-tests/src/test/scala/akka/actor/ActorRefSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ExtensionSpec.scala
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: tested

#28568 Don't initialize Lmdb when rememberEntities not used, #28567
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
Labels: tested

#28582 Example for Source.fromIterator #25468
  akka-docs/src/main/paradox/stream/operators/Source/fromIterator.md
  akka-docs/src/test/java/jdocs/stream/operators/source/From.java
  akka-docs/src/test/scala/docs/stream/operators/source/From.scala
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
Labels: t:stream, tested

#28553 Unwrap tagged events on addition (#28552)
  akka-persistence/src/main/scala/akka/persistence/journal/inmem/InmemJournal.scala
Labels: tested

#28594 remove obsolete PersistenceSettings.view
  akka-persistence/src/main/mima-filters/2.6.3.backwards.excludes/28331-timestamp-PersistentRepr.excludes
  akka-persistence/src/main/scala/akka/persistence/JournalProtocol.scala
  akka-persistence/src/main/scala/akka/persistence/Persistence.scala
  akka-persistence/src/main/scala/akka/persistence/Protocol.scala
Labels: tested

#28593 Host name verification off is not necessarily bad
  akka-docs/src/main/paradox/remoting-artery.md
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala
Labels: tested

#28600 Remove not needed ReplicatedDataSerializer
  akka-docs/src/test/scala/docs/ddata/protobuf/TwoPhaseSetSerializer2.scala
Labels: tested

#28595 note about rolling update when changing transport
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/remoting-artery.md
Labels: tested

#28591 Push that DeprecatedTlsSpec timeout a bit up
  akka-stream-tests/src/test/scala/akka/stream/io/DeprecatedTlsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
Labels: t:stream, tested

#28542 Shield unsafe journal plugins from corner case, #28541
  akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala
Labels: tested

#28607 Recommend config checker when migrating to 2.6
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#28588 Allow opt out of code discipline
  .sbt-java-formatter.conf
  CONTRIBUTING.md
  project/AkkaDisciplinePlugin.scala
Labels: tested

#28613 Docs #25468 : add code examples for drop and dropWhile Operators
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/drop.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/dropWhile.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Drop.scala
Labels: t:stream, tested

#28616 Docs: sink seq operator examples
  akka-docs/src/main/paradox/stream/operators/Sink/seq.md
  akka-docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala
Labels: t:stream, tested

#28619 Update silencer-lib, silencer-plugin to 1.5.0
  project/AkkaDisciplinePlugin.scala
Labels: tested

#28622 Fix incorrect link in 2.6 migration guide
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#28615 Docs: Source.repeat (and friends)
  akka-docs/src/main/paradox/stream/operators/Source/repeat.md
  akka-docs/src/main/paradox/stream/operators/Source/single.md
  akka-docs/src/main/paradox/stream/operators/Source/tick.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
Labels: t:stream, tested

#28624 Improve support for half-closing outgoing TCP connections
  akka-actor/src/main/scala/akka/io/TcpConnection.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
Labels: t:stream, tested

#28610 stream: provide mapMaterializedValue for Graph
  akka-stream-tests/src/test/java/akka/stream/javadsl/GraphDslTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphDSLCompileSpec.scala
  akka-stream/src/main/scala/akka/stream/Graph.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: t:stream, tested

#28558 UdpConnectedIntegrationSpec dns fail fix
  akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala
  akka-actor/src/main/scala/akka/io/TcpOutgoingConnection.scala
  akka-actor/src/main/scala/akka/io/UdpConnection.scala
  akka-actor/src/main/scala/akka/io/dns/DnsProtocol.scala
Labels: tested

#28628 Clarify 'failed' tag meaning more
  CONTRIBUTING.md
Labels: tested

#28581 Update sbt-mima-plugin to 0.6.4
  project/plugins.sbt
Labels: tested

#28646 Introduce the onReceiveTimeout hook for SeedNodeProcess
  akka-cluster/src/main/scala/akka/cluster/SeedNodeProcess.scala
Labels: tested

#28635 Update silencer-lib, silencer-plugin to 1.6.0
  project/AkkaDisciplinePlugin.scala
Labels: tested

#28623 Update sbt-paradox-akka to 0.31
  project/plugins.sbt
Labels: tested

#28647 Introduce the onReceiveTimeout hook for SeedNodeProcess
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
Labels: tested

#28644 Adds gzip and deflate to the operator list
  akka-docs/src/main/categories/compression-operators.md
  akka-docs/src/main/paradox/stream/operators/Compression/deflate.md
  akka-docs/src/main/paradox/stream/operators/Compression/gzip.md
  akka-docs/src/main/paradox/stream/operators/index.md
  project/StreamOperatorsIndexGenerator.scala
Labels: tested

#28645 Productionize CurrentShardRegionState #27406
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-sharding/src/main/protobuf/ClusterShardingMessages.proto
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGetStateSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingQueriesSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardRegionSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardingQueriesSpec.scala
  akka-docs/src/main/paradox/cluster-sharding.md
Labels: 2 - pick next, tested

#28639 Adds example to Source.completionStageSource
  akka-docs/src/main/paradox/stream/operators/Source/completionStage.md
  akka-docs/src/main/paradox/stream/operators/Source/completionStageSource.md
  akka-docs/src/main/paradox/stream/operators/Source/futureSource.md
  akka-docs/src/test/java/jdocs/stream/operators/source/CompletionStageSource.java
  akka-docs/src/test/scala/docs/stream/operators/source/FutureSource.scala
Labels: t:stream, tested

#28631 Multi node test hardening for Sharding #27749
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingCustomShardAllocationSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingFailureSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGetStateSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGetStatsSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGracefulShutdownSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingIncorrectSetupSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingLeavingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingMinMembersSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingQueriesSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRegistrationCoordinatedShutdownSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesNewExtractorSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesPerfSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRememberEntitiesSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingRolePartitioningSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSingleShardPerEntitySpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ExternalShardAllocationSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiDcClusterShardingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingConfig.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiNodeClusterSpec.scala
Labels: 2 - pick next, tested

#28590 Log warning when typed message adapters return null
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorContextPipeToSelfTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextPipeToSelfSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
Labels: tested

#28498 Update scalacheck-1-14 to 3.1.0.1
  project/Dependencies.scala
Labels: dependency-change, tested
