Repository akka/akka, pull requests merged in 2020-08, with the labels that each got.

#29432 fix StreamRefs IllegalStateException
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SinkRefImpl.scala
Labels: t:stream, tested

#29450 Minor adjustments to replicated es docs
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/ReplicatedShardingTest.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-docs/src/main/paradox/typed/index-persistence.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/MultiJournalReplicationSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventPublishingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationIllegalAccessSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationSnapshotSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/LwwSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/ORSetSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedBlogExampleSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplicationSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
Labels: tested

#28402 Make warnings in Java code fatal
  akka-actor-tests/src/test/java/akka/actor/ActorCreationTest.java
  akka-actor-tests/src/test/java/akka/actor/ActorSelectionTest.java
  akka-actor-tests/src/test/java/akka/actor/JavaAPI.java
  akka-actor-tests/src/test/java/akka/actor/StashJavaAPITestActors.java
  akka-actor-tests/src/test/java/akka/event/LoggingAdapterTest.java
  akka-actor-tests/src/test/java/akka/japi/MatchBuilderTest.java
  akka-actor-tests/src/test/java/akka/japi/pf/ReceiveBuilderTest.java
  akka-actor-tests/src/test/scala/akka/actor/ActorWithStashSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/ExtensionSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/JavaAPISpec.scala
  akka-actor-tests/src/test/scala/akka/japi/JavaAPITest.scala
  akka-actor-tests/src/test/scala/akka/util/JavaDurationSpec.scala
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/Aggregator.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/TailChopping.java
  akka-actor/src/main/java/akka/actor/AbstractScheduler.java
  akka-cluster-tools/src/test/java/akka/cluster/client/ClusterClientTest.java
  akka-docs/src/test/java/jdocs/actor/ActorDocTest.java
  akka-docs/src/test/java/jdocs/actor/io/dns/DnsCompileOnlyDocTest.java
  akka-docs/src/test/java/jdocs/ddata/DataBot.java
  akka-docs/src/test/java/jdocs/ddata/DistributedDataDocTest.java
  akka-docs/src/test/java/jdocs/persistence/query/MyEventsByTagSource.java
  akka-docs/src/test/java/jdocs/stream/FlowDocTest.java
  akka-docs/src/test/java/jdocs/stream/FlowErrorDocTest.java
  akka-docs/src/test/java/jdocs/stream/GraphStageDocTest.java
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-docs/src/test/java/jdocs/stream/RestartDocTest.java
  akka-docs/src/test/java/jdocs/stream/StreamPartialGraphDSLDocTest.java
  akka-docs/src/test/java/jdocs/stream/StreamTestKitDocTest.java
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeAdhocSourceTest.java
  akka-docs/src/test/java/jdocs/stream/operators/flow/StatefulMapConcat.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/PersistentFsmToTypedMigrationCompileOnlyTest.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/WebStoreCustomerFSM.java
  akka-persistence/src/main/java/akka/persistence/fsm/japi/pf/FSMStateFunctionBuilder.java
  akka-persistence/src/main/java/akka/persistence/fsm/japi/pf/FSMStopBuilder.java
  akka-persistence/src/test/java/akka/persistence/fsm/AbstractPersistentFSMTest.java
  akka-stream-tests/src/test/java-jdk9-only/akka/stream/javadsl/JavaFlowSupportCompileTest.java
  akka-stream-tests/src/test/java/akka/stream/io/InputStreamSinkTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/AttributesTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/GraphDslTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SetupTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-typed/src/test/java/akka/stream/typed/javadsl/ActorSourceSinkCompileTest.java
  akka-stream-typed/src/test/java/docs/akka/stream/typed/ActorSinkExample.java
  akka-stream/src/main/scala/akka/stream/UniformFanInShape.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  project/AkkaDisciplinePlugin.scala
  project/TestExtras.scala
Labels: tested

#29437 Avoid non-tail recursion when stashed no-effect messages are processed
  akka-persistence-typed/src/main/mima-filters/2.6.8.backwards.excludes/issue-29401-stack-overflow.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedStashOverflowSpec.scala
Labels: tested

#29405 Bump jackson to 2.10.5
  project/Dependencies.scala
Labels: dependency-change, tested

#29446 docs: add newish modules in listing
  akka-docs/src/main/paradox/common/other-modules.md
Labels: tested

#29454 DRY ReplicatedEventSourcedBehavior.apply
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedShardingSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingDirectReplication.scala
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedAuctionExampleTest.java
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/EventPublishingSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ReplicatedEventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
Labels: tested

#29459 javacOptions in Compile configuration (not compile task)
  project/AkkaBuild.scala
  project/AkkaDisciplinePlugin.scala
  project/JdkOptions.scala
Labels: tested

#29460 Rename replicated settings
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedEntityProvider.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedShardingExtension.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ReplicatedShardingExtensionImpl.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/ReplicatedShardingTest.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
Labels: tested

#29461 a few more things when reviewing replicated event sourcing
  akka-actor/src/main/scala/akka/util/AlwaysIncreasingClock.scala
  akka-actor/src/main/scala/akka/util/WallClock.scala
  akka-docs/src/main/paradox/typed/guide/modules.md
  akka-docs/src/main/paradox/typed/persistence.md
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/ORSet.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplicationSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/VersionVector.scala
Labels: tested

#29462 Add entity type name for replicated entity
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/ReplicatedShardingTest.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingDirectReplicationSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-persistence-typed-tests/src/test/java/akka/persistence/typed/ReplicatedEventSourcingTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/MyReplicatedBehavior.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedAuctionExampleTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedStringSet.java
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/MultiJournalReplicationSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventPublishingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingTaggingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationIllegalAccessSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationSnapshotSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/CounterSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/LwwSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/ORSetSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedBlogExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedEventSourcingCompileOnlySpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PersistenceId.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplicationSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ReplicatedEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ReplicatedEventSourcing.scala
Labels: tested

#29346 Harden multi-dc joining, #29280
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/mima-filters/2.6.8.backwards.excludes/issue-29280-GossipStatus.excludes
  akka-cluster/src/main/protobuf/ClusterMessages.proto
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/Gossip.scala
  akka-cluster/src/main/scala/akka/cluster/MembershipState.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcJoin2Spec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcJoinSpec.scala
  akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala
  akka-cluster/src/test/scala/akka/cluster/protobuf/ClusterMessageSerializerSpec.scala
Labels: tested

#29470 add akka-docs to nonFatalJavaWarningsFor
  project/AkkaDisciplinePlugin.scala
Labels: tested

#29469 docs: redirect to deploying from old URL
  akka-docs/src/main/paradox/.htaccess
Labels: tested

#29444 Update to paradox akka theme 0.35 to get new LB.com links
  project/plugins.sbt
Labels: tested

#29429 Update metrics-core, metrics-jvm to 4.1.11
  project/Dependencies.scala
Labels: dependency-change, tested

#29425 Update sbt-dynver to 4.1.1
  project/plugins.sbt
Labels: tested

#29382 Add mergePreferred, mergePrioritized docs (#25468)
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mergePreferred.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mergePrioritized.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMergeSpec.scala
Labels: t:stream, tested

#29468 Fix documentation about the way to enable the akka async dns resolver
  akka-actor/src/main/scala/akka/io/dns/DnsProtocol.scala
Labels: tested

#29477 Polish Auction example
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-auction.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-examples.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed-tests/src/test/java/akka/persistence/typed/ReplicatedEventSourcingTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/MyReplicatedBehavior.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedAuctionExampleTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedStringSet.java
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
Labels: tested

#29482 Counter example, shopping cart
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-cart.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-examples.md
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedBlogExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedShoppingCartExample.java
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedBlogExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedShoppingCartExampleSpec.scala
Labels: tested

#29481 ORSet example, MovieWatchList
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-cart.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-examples.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedBlogExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedMovieExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedShoppingCartExample.java
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedBlogExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedMovieWatchListExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedShoppingCartExampleSpec.scala
Labels: tested

#29479 LwwTime example
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-cart.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing-examples.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedBlogExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedMovieExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedShoppingCartExample.java
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedBlogExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedMovieWatchListExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedShoppingCartExampleSpec.scala
Labels: tested

#29476 Remove doclint from javac for docs
  project/AkkaDisciplinePlugin.scala
Labels: tested

#29487 actor: sync allModules with current set of published modules
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
Labels: tested

#29488 Remove val from case class
  akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala
Labels: tested

#29485 Handle dispatcher aliases for stash config
  akka-actor-tests/src/test/scala/akka/actor/ActorWithBoundedStashSpec.scala
  akka-actor-tests/src/test/scala/akka/actor/dispatch/DispatchersSpec.scala
  akka-actor/src/main/scala/akka/dispatch/Dispatchers.scala
  akka-actor/src/main/scala/akka/dispatch/Mailboxes.scala
Labels: tested

#29483 Replicated Sharding improvements
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedEntityProvider.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ReplicatedShardingExtensionImpl.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/ReplicatedShardingTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ReplicatedShardingCompileOnlySpec.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingDirectReplicationSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ReplicatedShardingCompileOnlySpec.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala
  akka-cluster/src/main/scala/akka/cluster/Member.scala
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed-tests/src/test/java/akka/persistence/typed/ReplicatedEventSourcingTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/MyReplicatedBehavior.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedAuctionExampleTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedBlogExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedMovieExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedShoppingCartExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedStringSet.java
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/MultiJournalReplicationSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventPublishingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingTaggingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationIllegalAccessSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationSnapshotSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/CounterSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/LwwSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/ORSetSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedBlogExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedEventSourcingCompileOnlySpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedMovieWatchListExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedShoppingCartExampleSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PersistenceId.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/ReplicationId.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplicationSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ReplicatedEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ReplicatedEventSourcing.scala
Labels: tested

#29489 Correctly check Java test has ran
  project/TestExtras.scala
Labels: tested

#29478 Add random factor for CircuitBreaker
  akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerSpec.scala
  akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
Labels: tested

#29493 Turn on direct replication by default
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedEntityProvider.scala
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ReplicatedEventSourcedBehavior.scala
Labels: tested

#29492 Make ShardingDirectReplication private
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedShardingExtension.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ReplicatedShardingExtensionImpl.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingDirectReplicationSpec.scala
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
Labels: tested

#29491 Test coverage and fixes for direct replication
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingDirectReplication.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-persistence-typed/src/main/java/akka/persistence/typed/serialization/ReplicatedEventSourcing.java
  akka-persistence-typed/src/main/protobuf/ReplicatedEventSourcing.proto
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/ReplicationId.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/serialization/ReplicatedEventSourcingSerializer.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/serialization/ReplicatedEventSourcingSerializerSpec.scala
Labels: tested

#29497 debug logging of ArteryUpdSendConsistencyWithThreeLanesSpec, #29465
  akka-remote/src/test/scala/akka/remote/artery/RemoteSendConsistencySpec.scala
Labels: tested

#29472 Reduce scope of cluster.StressSpec, #23511
  akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala
Labels: tested

#29463 Forward terminated from ShardCoordinator to RebalanceWorker
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingLeavingSpec.scala
Labels: tested

#29499 full convergence also for joining nodes for first multi-dc join, #29486
  akka-cluster/src/main/scala/akka/cluster/MembershipState.scala
  akka-cluster/src/test/scala/akka/cluster/GossipSpec.scala
Labels: tested

#29500 Fix patch versin for scala when overriding
  project/Dependencies.scala
Labels: dependency-change, tested

#29498 convenience for ShardedDaemonProcess role, #29490
  akka-cluster-sharding-typed/src/main/mima-filters/2.6.8.backwards.excludes/issue-29490-ShardedDaemonProcess-role.excludes
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardedDaemonProcessSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/ShardedDaemonProcessSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ShardedDaemonProcessSpec.scala
Labels: tested

#29496 reduce combinations in RandomizedBrainResolverIntegrationSpec, #29185
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/RandomizedBrainResolverIntegrationSpec.scala
Labels: tested

#29473 Harden BackoffSupervisorSpec, #29467
  akka-actor-tests/src/test/scala/akka/pattern/BackoffSupervisorSpec.scala
Labels: tested

#29474 harden ClusterSingletonManagerLeaseSpec, #29423
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ExternalShardAllocationSpec.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerLeaseSpec.scala
Labels: tested

#29471 fix write consistency timeout in Sharding, #29344
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/DDataRememberEntitiesShardStore.scala
Labels: tested

#29371 Make akka-protobuf-v3_2.12-2.6.x reproducible again
  build.sbt
Labels: tested

#29501 doc: rolling update from 2.5.x to 2.6.2
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#29516 Update silencer-lib, silencer-plugin to 1.7.1
  project/AkkaDisciplinePlugin.scala
Labels: tested

#29518 Update metrics-core, metrics-jvm to 4.1.12.1
  project/Dependencies.scala
Labels: dependency-change, tested

#29521 Pin jackson to 2.10.
  .scala-steward.conf
Labels: tested

#29519 Update jctools-core to 3.0.1
  project/Dependencies.scala
Labels: dependency-change, tested

#29513 docs: render depenency on Futures page correctly
  akka-docs/src/main/paradox/futures.md
Labels: tested

#29510 Feedback from creating replicated entity sample
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedEntityProvider.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedShardingExtension.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ReplicatedShardingExtensionImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/testkit/TestEntityRefImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-cluster-sharding-typed/src/test/java/akka/cluster/sharding/typed/ReplicatedShardingTest.java
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/ReplicatedShardingCompileOnlySpec.java
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/ReplicatedShardingSpec.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/ReplicatedShardingCompileOnlySpec.scala
  akka-persistence-typed-tests/src/test/java/akka/persistence/typed/ReplicatedEventSourcingTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/MyReplicatedBehavior.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedAuctionExampleTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedBlogExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedMovieExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedShoppingCartExample.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedStringSet.java
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventPublishingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicatedEventSourcingTaggingSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationIllegalAccessSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/ReplicationSnapshotSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/CounterSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/LwwSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/crdt/ORSetSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedAuctionExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedBlogExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedEventSourcingCompileOnlySpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedMovieWatchListExampleSpec.scala
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedShoppingCartExampleSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ReplicatedEventSourcing.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/ReplicatedEventSourcing.scala
Labels: tested

#29305 Update sbt-reproducible-builds to 0.25
  project/plugins.sbt
Labels: tested

#29517 Update sbt-java-formatter to 0.6.0
  project/plugins.sbt
Labels: tested

#29514 Event migration improvements
  akka-docs/src/main/paradox/persistence-schema-evolution.md
  akka-docs/src/main/paradox/serialization-jackson.md
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonMigration.scala
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestEventMigrationV2.java
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestEventMigrationV2WithV3.java
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestEventMigrationV3.java
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestMessages.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v1/ItemAdded.java
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v1withv2/ItemAddedMigration.java
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/ScalaTestEventMigration.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v1/ItemAdded.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v1withv2/ItemAddedMigration.scala
Labels: tested

#29523 Prefer "update" over "upgrade" when rolling
  akka-docs/src/main/paradox/additional/rolling-updates.md
  akka-docs/src/main/paradox/project/rolling-update.md
  akka-docs/src/main/paradox/serialization.md
  akka-docs/src/main/paradox/typed/cluster-dc.md
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29527 Use the correct name for Akka HTTP
  akka-docs/src/main/paradox/typed/dispatchers.md
Labels: tested

#29526 Start ShardedDaemon pinging once member is up
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
Labels: tested
