Repository akka/akka, pull requests merged in 2020-10, with the labels that each got.

#29688 upgrade ScalaTest and scalatestplus-junit
  project/Dependencies.scala
Labels: dependency-change, tested

#29623 Making docs better
  akka-docs/src/main/paradox/stream/operators/ActorFlow/ask.md
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRef.md
  akka-docs/src/main/paradox/stream/operators/ActorSink/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/ActorSource/actorRefWithBackpressure.md
  akka-docs/src/main/paradox/stream/operators/index.md
Labels: tested

#29591 Restart(Source|Flow|Sink): Configurable stream restart deadline
  akka-docs/src/main/paradox/stream/operators/RestartFlow/onFailuresWithBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartFlow/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSink/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSource/onFailuresWithBackoff.md
  akka-docs/src/main/paradox/stream/operators/RestartSource/withBackoff.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/main/paradox/stream/stream-error.md
  akka-docs/src/test/java/jdocs/stream/RestartDocTest.java
  akka-docs/src/test/java/jdocs/stream/operators/source/Restart.java
  akka-docs/src/test/scala/docs/stream/RestartDocSpec.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Restart.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RestartSpec.scala
  akka-stream/src/main/mima-filters/2.6.9.backwards.excludes/29591-restart-deadline.backwards.excludes
  akka-stream/src/main/scala/akka/stream/RestartSettings.scala
  akka-stream/src/main/scala/akka/stream/javadsl/RestartFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/RestartSink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/RestartSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartSink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartSource.scala
Labels: t:stream, tested

#29687 Support throwing exception in Java TestProbe.awaitAssert
  akka-actor-testkit-typed/src/main/mima-filters/2.6.9.backwards.excludes/29687-java-TestProbe-awaitAssert-support-checked-exception.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestProbe.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/TestProbeTest.java
Labels: tested

#29686 Fix grammar error in streams cookbook
  akka-docs/src/main/paradox/stream/stream-cookbook.md
Labels: tested

#29640 disseminate downing decisions faster, #29612
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/TransitionSpec.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
Labels: tested

#29682 consistently prefix sharding log messages with typeName
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ShardWithLeaseSpec.scala
Labels: 2 - pick next, tested

#29692 Fix Welcome/Gossip deserialization of app-version
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
Labels: tested

#29699 Update sbt-osgi to 0.9.6
  project/plugins.sbt
Labels: tested

#29712 Handle when there are no known regions yet
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/AbstractLeastShardAllocationStrategy.scala
Labels: 2 - pick next, tested

#29707 ShardRegion ignores HostShard when shutting down
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
Labels: tested

#29719 Fix population of akka-protobuf-v3
  .scala-steward.conf
  project/plugins.sbt
Labels: tested

#29691 log-frame-size-exceeding for Artery, #29683
  akka-actor/src/main/scala/akka/routing/Router.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/NodeChurnSpec.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/PerformanceSpec.scala
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/typed/logging.md
  akka-remote/src/main/resources/reference.conf
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
  akka-remote/src/main/scala/akka/remote/artery/RemoteInstrument.scala
  akka-remote/src/test/scala/akka/remote/MessageLoggingSpec.scala
Labels: tested

#29721 mima latestPatchOf 2.6.10
  project/MiMa.scala
Labels: tested

#29715 Typo / grammatical fixes
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
  akka-docs/src/main/paradox/extending-akka.md
  akka-docs/src/main/paradox/io.md
  akka-docs/src/main/paradox/persistence-schema-evolution.md
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
Labels: tested

#29724 Add Metals output to .gitignore
  .gitignore
Labels: tested

#29723 Grammar fix
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#29722 exit-jvm config in docs
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#29717 Adding example of headOption operator
  akka-docs/src/main/paradox/stream/operators/Sink/headOption.md
  akka-docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/sink/HeadOption.scala
Labels: tested

#29729 Simplify code: replace exists with contains
  akka-distributed-data/src/main/scala/akka/cluster/ddata/ORSet.scala
Labels: tested

#29716 Adding example for collection operator
  akka-docs/src/main/paradox/stream/operators/Sink/collection.md
  akka-docs/src/test/scala/docs/stream/operators/sink/Collection.scala
Labels: tested

#29693 Fix for PersistentShardingMigrationSpec failing
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/PersistentShardingMigrationSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/RememberEntitiesShardIdExtractorChangeSpec.scala
Labels: tested

#29728 Update junit to 4.13.1
  project/Dependencies.scala
Labels: tested

#29733 Fix typo
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapAsync.md
Labels: tested

#29734 Fix .scala-steward.conf syntax
  .scala-steward.conf
Labels: tested

#29741 Fix typo
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#29740 Log distributed data size, #29736
  akka-distributed-data/src/main/mima-filters/2.6.10.backwards.excludes/issue-29736-log-data-size.excludes
  akka-distributed-data/src/main/resources/reference.conf
  akka-distributed-data/src/main/scala/akka/cluster/ddata/PayloadSizeAggregator.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
Labels: tested

#29747 improve logging of shard region shutdown timeout, #29711
  akka-cluster-sharding/src/main/mima-filters/2.6.10.backwards.excludes/issue-29711-log-region-shutdown.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/ClusterShardingInternalsSpec.scala
Labels: tested

#29754 Update mima to check against 2.5.32
  project/MiMa.scala
Labels: tested

#29752 Link FAQ to community and support pages
  akka-docs/src/main/paradox/additional/faq.md
Labels: tested

#29758 Update cluster.md
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#29748 Unstash GetShardHome requests one-by-one, #29742
  akka-cluster-sharding/src/main/mima-filters/2.6.10.backwards.excludes/issue-29742-unstash-GetShardHome.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested

#29757 show package name in getting started examples, #28432
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
  akka-docs/src/test/java/jdocs/typed/tutorial_2/IotMain.java
  akka-docs/src/test/java/jdocs/typed/tutorial_2/IotSupervisor.java
  akka-docs/src/test/java/jdocs/typed/tutorial_3/inprogress1/Device.java
  akka-docs/src/test/scala/typed/tutorial_1/ActorHierarchyExperiments.scala
  akka-docs/src/test/scala/typed/tutorial_2/IotApp.scala
  akka-docs/src/test/scala/typed/tutorial_2/IotSupervisor.scala
  akka-docs/src/test/scala/typed/tutorial_3/DeviceInProgress.scala
Labels: tested

#29749 Adding example of cancelled operator
  akka-docs/src/main/paradox/stream/operators/Sink/cancelled.md
  akka-docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/sink/Cancelled.scala
Labels: tested

#29744 Improving docs- removing redundant phrases
  akka-docs/src/main/paradox/stream/operators/Flow/completionStageFlow.md
  akka-docs/src/main/paradox/supervision-classic.md
  akka-docs/src/main/paradox/testing.md
Labels: tested

#29762 Dont rely on DNS for a doc spec
  akka-docs/src/test/java/jdocs/discovery/DnsDiscoveryDocTest.java
Labels: tested

#29766 Fixes the wording of the Scaladoc on the `unwatched` method
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/Effect.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/Effects.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/Effects.scala
Labels: tested

#29771 Fix typo in docs for cluster sharding rolling updates
  akka-docs/src/main/paradox/additional/rolling-updates.md
Labels: tested

#29761 DEBUG logging for BasicClusterManualSpec
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
Labels: tested

#29731 stream: register newshells with no active interpreters
  akka-actor-tests/src/test/scala/akka/util/ByteStringInitializationSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/PeerSubjectVerifierSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
Labels: tested, to-be-backported

#29764 Update mima to 0.8.1
  project/plugins.sbt
Labels: tested

#29755 Update mima to 2.5.32 (backport)
  project/MiMa.scala
Labels: tested

#29701 Update sbt-scalafmt to 2.4.2
  project/plugins.sbt
Labels: tested

#29759 Isolate shard init logic to own method
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
Labels: tested

#29760 simplify the stopping example, #28144
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/GracefulStopDocTest.java
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/GracefulStopDocSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Behaviors.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
  akka-docs/src/main/paradox/typed/actor-lifecycle.md
Labels: tested

#29725 Update metrics-core, metrics-jvm to 4.1.13
  project/Dependencies.scala
Labels: tested
