Repository akka/akka, pull requests merged in 2020-11, with the labels that each got.

#29774 cleanup test comment
  akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/PeerSubjectVerifierSpec.scala
Labels: tested

#29778 Add limitation about supervision in sync Testkit #29767
  akka-docs/src/main/paradox/typed/testing-sync.md
Labels: tested

#29783 Fix BehaviorTestKit.signal false alarm in thread check #29779
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: tested

#29348 More debug logging for Artery transport shutdown
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/FlushOnShutdown.scala
Labels: tested

#29773 Fix cluster sharding with remember entities test
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
Labels: tested

#29672 Add snapshot saving after replaying events if retention criteria indicates missing snapshot
  akka-persistence-typed/src/main/mima-filters/2.6.10.backwards.excludes/pr-29672-snapshot-after-event-replay.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRetentionSpec.scala
Labels: tested

#29770 BoundedSourceQueue API
  akka-docs/src/main/paradox/stream/operators/Source/queue.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/BoundedSourceQueueSpec.scala
  akka-stream/src/main/scala/akka/stream/BoundedSourceQueue.scala
  akka-stream/src/main/scala/akka/stream/OverflowStrategy.scala
  akka-stream/src/main/scala/akka/stream/QueueOfferResult.scala
  akka-stream/src/main/scala/akka/stream/impl/BoundedSourceQueue.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: tested

#29796 Review writeup for RES direct deplication in docs
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
Labels: tested

#29792 Akka 29784 stateful map concat relax f ret type
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapConcatSpec.scala
  akka-stream/src/main/mima-filters/2.6.10.backwards.excludes/akka-29784-statefulMapConcat-relax-types.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/FlowWithContextOps.scala
Labels: tested

#29798 Add type annotation for public method
  akka-cluster/src/main/scala/akka/cluster/Gossip.scala
Labels: tested

#29793 Harden lease majority spec
  akka-cluster/src/multi-jvm/scala/akka/cluster/sbr/LeaseMajority5NodeSpec.scala
Labels: tested

#29799 Docs: link to videos
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
Labels: t:docs, tested

#29763 cleanup associations when handshake didn't complete, #29615
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
Labels: tested

#29789 Increase timeout to make room for leveldb disk access slow
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRetentionSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
Labels: tested

#29802 tests: shorten probabilitic test in BoundedSourceQueueSpec
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/BoundedSourceQueueSpec.scala
Labels: tested

#29769 Reset index if it gets out of sync with the snapshot storage
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/TestKitStorage.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/PersistenceTestKit.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/TestOps.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/CommonUtils.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/CommonSnapshotTests.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/ScalaDslUtils.scala
Labels: 2 - pick next, tested

#29797 Configure visibility
  akka-serialization-jackson/src/main/resources/reference.conf
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala
  akka-serialization-jackson/src/test/java/akka/serialization/jackson/JavaTestMessages.java
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
Labels: tested

#29817 not isEmpty => nonEmpty
  akka-actor/src/main/scala/akka/actor/ActorSelection.scala
Labels: tested

#29788 Docs: use RestartSettings in Java DSL example
  akka-docs/src/test/java/jdocs/stream/operators/source/Restart.java
Labels: tested

#29815 Stream Testkit: new-API-friendly
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/javadsl/TestSink.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/javadsl/TestSource.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/TestSink.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/TestSource.scala
Labels: t:stream, tested

#29671 Fix passing of lease settings in typed cluster sharding.
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ShardedDaemonProcessImpl.scala
Labels: tested

#29814 Stream Testkit: use assertAllStagesStopped with system in the Java DSL
  akka-stream-testkit/src/main/scala/akka/stream/testkit/javadsl/StreamTestKit.scala
Labels: t:stream, tested

#29806 Update aeron-client, aeron-driver to 1.31.1
  project/Dependencies.scala
Labels: tested

#29751 Include entries DData Gossip message dynamically based on size, #28421
  akka-distributed-data/src/main/mima-filters/2.6.10.backwards.excludes/issue-28421-dynamic-gossip.excludes
  akka-distributed-data/src/main/resources/reference.conf
  akka-distributed-data/src/main/scala/akka/cluster/ddata/EstimatedSize.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/PayloadSizeAggregator.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/PruningState.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/VersionVector.scala
  akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorGossipSpec.scala
Labels: tested

#29805 Update sort-imports to 0.5.5
  project/ScalaFixExtraRulesPlugin.scala
Labels: tested

#29809 Update scalacheck to 1.15.1
  project/Dependencies.scala
Labels: tested

#29807 Update metrics-core, metrics-jvm to 4.1.14
  project/Dependencies.scala
Labels: tested

#29804 Update sbt-scalafix to 0.9.23
  project/plugins.sbt
Labels: tested

#29819 Fix deprecated versin is cluster sharding settings
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
Labels: tested

#29821 move identify to /MultiNodeTypedClusterSpec
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/delivery/DeliveryThroughputSpec.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/ChunkLargeMessageSpec.scala
  akka-cluster-typed/src/multi-jvm/scala/akka/cluster/typed/MultiNodeTypedClusterSpec.scala
Labels: tested

#29824 Move to travis-ci.com
  .travis.yml
  CONTRIBUTING.md
  README.md
Labels: tested

#29826 Revert "Stream Testkit: new-API-friendly"
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/javadsl/TestSink.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/javadsl/TestSource.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/TestSink.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/TestSource.scala
Labels: t:stream, tested

#29827 Fix logging: expectTerminated instead
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala
Labels: tested

#29823 Automatic closing of sub inlets/outlets
  akka-stream-tests/src/test/scala/akka/stream/impl/SubInletOutletSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: t:stream, tested

#29822 Operator docs: examples for asSource/FlowWithContext
  .scalafmt.conf
  akka-docs/src/main/paradox/stream/operators/Flow/asFlowWithContext.md
  akka-docs/src/main/paradox/stream/operators/Source/asSourceWithContext.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/WithContextTest.java
  akka-docs/src/test/scala/docs/stream/operators/WithContextSpec.scala
Labels: t:docs, t:stream, tested

#29840 Fix typo: wort -> worth
  akka-docs/src/main/paradox/split-brain-resolver.md
Labels: tested

#29844 Update persistence.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#29836 Fix port configuration for basic cluster example spec
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
Labels: tested

#29830 Add examples for asInputStream and asOutputStream
  akka-docs/src/main/paradox/stream/operators/StreamConverters/asInputStream.md
  akka-docs/src/main/paradox/stream/operators/StreamConverters/asOutputStream.md
  akka-docs/src/test/java/jdocs/stream/operators/converters/ToFromJavaIOStreams.java
  akka-docs/src/test/scala/docs/stream/operators/converters/ToFromJavaIOStreams.scala
Labels: t:stream, tested

#29845 Fix for stream ref test fail
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala
Labels: t:stream, tested

#29839 Produce a BOM for Akka libraries
  build.sbt
  project/Publish.scala
  project/plugins.sbt
Labels: dependency-change, tested

#29846 links to platform guide
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/project/examples.md
  akka-docs/src/main/paradox/typed/choosing-cluster.md
  akka-docs/src/main/paradox/typed/cqrs.md
  akka-docs/src/main/paradox/typed/guide/tutorial_5.md
  akka-docs/src/main/paradox/typed/persistence.md
  project/Paradox.scala
Labels: tested
