Repository akka/akka, pull requests merged in 2021-02, with the labels that each got.

#29987 MiMa for 2.6.12 take 2
  akka-cluster/src/main/mima-filters/2.6.12.backwards.excludes/down-when-quarantined.excludes
  project/MiMa.scala
Labels: tested

#29959 Ensure little endian ordering when copying envelope buffer
  akka-remote/src/main/scala/akka/remote/artery/EnvelopeBufferPool.scala
  akka-remote/src/test/scala/akka/remote/artery/EnvelopeBufferSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteInstrumentsSerializationSpec.scala
Labels: 2 - pick next, tested

#29999 docs: put 'recover' and 'mapError' under 'error handling'
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapError.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/recover.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/recoverWith.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/recoverWithRetries.md
  akka-docs/src/main/paradox/stream/operators/index.md
Labels: tested

#29869 Align BoundedSourceQueue test expectations with reality
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/BoundedSourceQueueSpec.scala
Labels: t:stream, tested

#29962 Remove support for PoisonPill in ActorRefSource (#26622)
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefSourceSpec.scala
  akka-stream/src/main/mima-filters/2.6.10.backwards.excludes/29586-sink-internal-api.excludes
  akka-stream/src/main/mima-filters/2.6.12.backwards.excludes/26622-stagelogic-internal-api.excludes
  akka-stream/src/main/scala/akka/stream/impl/ActorRefBackpressureSource.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorRefSource.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SinkRefImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: t:stream, tested

#30010 Removes obsolete authors.pl
  scripts/authors.pl
Labels: tested

#30011 Update sbt-dotty to 0.5.2
  project/plugins.sbt
Labels: tested

#30015 Update sbt to 1.4.7
  project/build.properties
Labels: tested

#29838 Full cluster shutdown
  akka-cluster-sharding-typed/src/multi-jvm/resources/logback-test.xml
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/ClusterShardingPreparingForShutdownSpec.scala
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/ClusterShardingStatsSpec.scala
  akka-cluster-sharding/src/main/mima-filters/2.6.12.backwards.excludes/full-cluster-shutdown.excludes
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerPreparingForShutdownSpec.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/Cluster.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterImpl.scala
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/BasicClusterExampleTest.java
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/protobuf/ClusterMessages.proto
  akka-cluster/src/main/scala/akka/cluster/Cluster.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/main/scala/akka/cluster/Member.scala
  akka-cluster/src/main/scala/akka/cluster/MembershipState.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterShutdownSpec.scala
  akka-docs/src/main/paradox/typed/cluster-membership.md
Labels: 2 - pick next, tested

#29992 Compile akka-actor and akka-actor-tests with Scala 3 in PR validation
  .travis.yml
Labels: tested

#29988 Don't add MemberExited as unreachable in SBR, #2995
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
Labels: tested

#30032 lack of semicolon in ActorHierarchyExperiments package
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
Labels: tested

#30030 docs: Fix Java code to check cookiesReply for ask
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/InteractionPatternsTest.java
Labels: tested

#30023 Don't use GraphStage toString when materializing Source.fromPublisher, #30022
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
Labels: t:stream, tested

#30014 Update metrics-core, metrics-jvm to 4.1.17
  project/Dependencies.scala
Labels: dependency-change, tested

#30007 Adds internal logger for EventSourcedBehavior
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/EventSourcedBehaviorLoggingSpec.scala
  akka-persistence-typed/src/main/mima-filters/2.6.12.backwards.excludes/pr-30007-internal-logger-for-es-behavior.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EffectImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RequestingRecoveryPermit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/StashManagement.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorWatchSpec.scala
Labels: tested

#30034 Fix for broken cluster shutdown
  akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/ClusterShutdownSpec.scala
Labels: tested

#29960 Allow introspection on typed EntityRefs to support serialization
  akka-cluster-sharding-typed/src/main/mima-filters/2.6.12.backwards.excludes/pr-29960-entityref-introspection.excludes
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/testkit/TestEntityRefImpl.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/javadsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/testkit/javadsl/EntityRef.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/testkit/scaladsl/EntityRef.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
  akka-docs/src/main/paradox/typed/interaction-patterns.md
Labels: tested

#30035 Adds scala/java tabs #30019
  akka-docs/src/main/paradox/fault-tolerance.md
Labels: tested

#30013 Update aeron-client, aeron-driver to 1.32.0
  project/Dependencies.scala
Labels: dependency-change, tested

#30038 Unmoored doc comment fixed
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
Labels: 2 - pick next, tested

#30041 Fail fix in ClusterShardingPreparingForShutdownSpec
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/ClusterShardingPreparingForShutdownSpec.scala
Labels: tested

#30029 remove object name because it doesn't work if you write it as documented
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/OOIntroSpec.scala
Labels: tested

#30046 Nicer ManifestInfo check
  akka-actor-tests/src/test/scala/akka/util/ManifestInfoSpec.scala
  akka-actor/src/main/scala/akka/util/ManifestInfo.scala
Labels: tested

#30049 Makes the SBR lease name configurable
  akka-cluster/src/main/mima-filters/2.6.12.backwards.excludes/sbr-lease-name.excludes
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolverProvider.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolverSettings.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/LeaseMajoritySpec.scala
Labels: 2 - pick next, tested

#30039 Source location in a few more stages
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/FlatMapPrefix.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/FutureFlow.scala
Labels: 2 - pick next, t:stream, tested

#29902 Short circuit bidi flow identity
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/BidiFlowSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/BidiFlow.scala
Labels: 2 - pick next, t:stream, tested

#30056 Update manifestInfo docs
  akka-docs/src/main/paradox/common/binary-compatibility-rules.md
Labels: 2 - pick next, tested

#30052 Update to sbt-paradox-akka 0.38 with copy-snippet support for the docs
  project/plugins.sbt
Labels: 2 - pick next, tested

#30033 Doubly dilated timeouts in typed test probe
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala
Labels: 2 - pick next, tested

#30061 Post 2.6.13 release changes
  project/MiMa.scala
Labels: tested
