Repository akka/akka, pull requests merged in 2021-12, with the labels that each got.

#30963 Update logback-classic to 1.2.7
  project/Dependencies.scala
Labels: dependency-change

#30966 Update aeron-client, aeron-driver to 1.37.0
  project/Dependencies.scala
Labels: dependency-change

#30991 Update to logback 1.2.8
  project/Dependencies.scala
Labels: dependency-change

#30999 Mark the new passivation strategies as may change
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EntityPassivationStrategy.scala
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: 2 - pick next

#31004 Add adjustable active entity limit per shard region
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EntityPassivationStrategy.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/passivation/LeastFrequentlyUsedSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/passivation/LeastRecentlyUsedSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/passivation/MostRecentlyUsedSpec.scala
Labels: 2 - pick next

#31007 Fix for build failure on Scala 2.12
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/scaladsl/PersistenceTestKitReadJournal.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStore.scala
Labels: 2 - pick next

#31006 Update to logback 1.2.9, and Paradox 0.41
  project/Dependencies.scala
  project/plugins.sbt
Labels: 2 - pick next, dependency-change

#30993 Add @deprecated to akka.stream.OverflowStrategy#dropNew (#30977)
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefSourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowBufferSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/QueueSourceSpec.scala
  akka-stream/src/main/scala/akka/stream/OverflowStrategy.scala
Labels: t:stream

#31009 docs: update persistence plugin listings
  akka-docs/src/main/paradox/common/other-modules.md
  akka-docs/src/main/paradox/persistence-plugins.md
Labels: t:docs

#30974 scala3: show scala3-compatible code in most of akka-docs
  akka-docs/src/test/scala/docs/actor/ActorDocSpec.scala
  akka-docs/src/test/scala/docs/actor/SharedMutableStateDocSpec.scala
  akka-docs/src/test/scala/docs/actor/typed/CoordinatedActorShutdownSpec.scala
  akka-docs/src/test/scala/docs/actor/typed/SharedMutableStateDocSpec.scala
  akka-docs/src/test/scala/docs/cluster/TransformationFrontend.scala
  akka-docs/src/test/scala/docs/ddata/DistributedDataDocSpec.scala
  akka-docs/src/test/scala/docs/future/FutureDocSpec.scala
  akka-docs/src/test/scala/docs/persistence/PersistencePluginDocSpec.scala
  akka-docs/src/test/scala/docs/stream/BidiFlowDocSpec.scala
  akka-docs/src/test/scala/docs/stream/CompositionDocSpec.scala
  akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala
  akka-docs/src/test/scala/docs/stream/GraphDSLDocSpec.scala
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
  akka-docs/src/test/scala/docs/stream/ReactiveStreamsDocSpec.scala
  akka-docs/src/test/scala/docs/stream/StreamPartialGraphDSLDocSpec.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeDroppyBroadcast.scala
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeLoggingElements.scala
  akka-docs/src/test/scala/docs/stream/io/StreamTcpDocSpec.scala
  akka-docs/src/test/scala/docs/stream/operators/BroadcastDocExample.scala
  akka-docs/src/test/scala/docs/stream/operators/flow/FromSinkAndSource.scala
  akka-docs/src/test/scala/docs/stream/operators/flow/FutureFlow.scala
  akka-docs/src/test/scala/docs/stream/operators/source/Tick.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/Monitor.scala
  akka-docs/src/test/scala/docs/testkit/TestkitDocSpec.scala
  project/AkkaDisciplinePlugin.scala
Labels: dependency-change

#31014 migrate-SBT-Dependencies
  project/Dependencies.scala
Labels: dependency-change
