Repository akka/akka, pull requests merged in 2021-06, with the labels that each got.

#30276 Wip optimize allocations optionval √
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-remote/src/main/scala/akka/remote/artery/Codecs.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/impl/TraversalBuilder.scala
Labels: 2 - pick next, t:stream, tested

#30195 Source.fromPublisher does not pick up attributes fix #30076
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceFromPublisherSpec.scala
  akka-stream/src/main/mima-filters/2.6.14.backwards.excludes/issue-30076-added-extra-parameter.excludes
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
Labels: t:stream, tested

#30265 Remove unused imports
  akka-actor-tests/src/test/java/akka/event/ActorWithMDC.java
  akka-actor-tests/src/test/java/akka/japi/ThrowablesTest.java
  akka-actor-tests/src/test/java/akka/japi/pf/ReceiveBuilderTest.java
  akka-actor-tests/src/test/java/akka/pattern/PatternsTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorContextPipeToSelfTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ReceiveBuilderTest.java
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/RoutersTest.java
  akka-actor/src/main/java/akka/dispatch/AbstractBoundedNodeQueue.java
  akka-actor/src/main/java/akka/dispatch/affinity/OnSpinWait.java
  akka-bench-jmh/src/main/java/akka/serialization/jackson/JavaMessages.java
  akka-cluster-tools/src/test/java/akka/cluster/singleton/ClusterSingletonManagerTest.java
  akka-cluster-typed/src/test/java/jdocs/akka/cluster/typed/PingSerializerExampleTest.java
  akka-distributed-data/src/test/java/akka/cluster/ddata/JavaImplOfDeltaReplicatedData2.java
  akka-docs/src/test/java/jdocs/actor/ActorDocTest.java
  akka-docs/src/test/java/jdocs/actor/typed/DispatcherDocTest.java
  akka-docs/src/test/java/jdocs/cluster/FactorialFrontendMain.java
  akka-docs/src/test/java/jdocs/ddata/DistributedDataDocTest.java
  akka-docs/src/test/java/jdocs/dispatcher/DispatcherDocTest.java
  akka-docs/src/test/java/jdocs/pattern/BackoffSupervisorDocTest.java
  akka-docs/src/test/java/jdocs/pattern/SupervisedAskSpec.java
  akka-docs/src/test/java/jdocs/persistence/PersistenceQueryDocTest.java
  akka-docs/src/test/java/jdocs/persistence/query/MyEventsByTagSource.java
  akka-docs/src/test/java/jdocs/stream/FlowErrorDocTest.java
  akka-docs/src/test/java/jdocs/stream/FlowParallelismDocTest.java
  akka-docs/src/test/java/jdocs/stream/FlowStreamRefsDocTest.java
  akka-docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/java/jdocs/stream/operators/flow/FromSinkAndSource.java
  akka-docs/src/test/java/jdocs/stream/operators/source/Lazy.java
  akka-docs/src/test/java/jdocs/stream/operators/source/UnfoldAsync.java
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/Monitor.java
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/Sliding.java
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/Split.java
  akka-docs/src/test/java/jdocs/typed/tutorial_5/DeviceTest.java
  akka-persistence-query/src/test/java/akka/persistence/query/PersistenceQueryTest.java
  akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorJavaDslTest.java
  akka-stream-tests/src/test/java/akka/stream/io/InputStreamSinkTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/LazyAndFutureFlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/RetryFlowTest.java
  akka-stream-typed/src/test/java/akka/stream/typed/javadsl/ActorSourceSinkCompileTest.java
  akka-testkit/src/test/java/akka/testkit/javadsl/TestKitApiTest.java
Labels: tested

#30279 Introduce onDeadLetterMailboxEnqueue hook for telemetry
  akka-actor/src/main/scala/akka/dispatch/Mailboxes.scala
Labels: 2 - pick next, tested

#30232 Update metrics-core, metrics-jvm to 4.1.21
  project/Dependencies.scala
Labels: dependency-change, tested

#30219 Artery test transport blackhole only let HandshakeReq pass
  akka-remote/src/main/scala/akka/remote/artery/TestStage.scala
Labels: tested

#30262 ByteString.toArrayUnsafe method for zero copy transformation of bytestrings
  akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala
  akka-actor/src/main/scala-2.12/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13/akka/util/ByteString.scala
  akka-actor/src/main/scala-3/akka/util/ByteString.scala
Labels: 2 - pick next, tested

#30161 Inner stages of lazy/future stages should inherit attributes
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/FlatMapPrefix.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/FutureFlow.scala
Labels: 2 - pick next, t:stream, tested

#30237 fix(docs): java snippet showing how to tag events
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
Labels: tested

#30213 Deprecate LevelDB
  akka-bench-jmh/src/main/scala/akka/persistence/LevelDbBatchingBenchmark.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/RemoveInternalClusterShardingData.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/MultiNodeClusterShardingSpec.scala
  akka-docs/src/main/paradox/persistence-plugins.md
  akka-docs/src/main/paradox/persistence-query-leveldb.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/persistence.md
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/LeveldbReadJournalProvider.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/javadsl/LeveldbReadJournal.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/scaladsl/LeveldbReadJournal.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/AllPersistenceIdsSpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByPersistenceIdSpec.scala
  akka-persistence-query/src/test/scala/akka/persistence/query/journal/leveldb/EventsByTagSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedEventAdapterSpec.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSnapshotAdapterSpec.scala
  akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbJournal.scala
  akka-persistence/src/main/scala/akka/persistence/journal/leveldb/SharedLeveldbStore.scala
  akka-persistence/src/test/scala/akka/persistence/AtLeastOnceDeliverySpec.scala
  akka-persistence/src/test/scala/akka/persistence/EndToEndEventAdapterSpec.scala
  akka-persistence/src/test/scala/akka/persistence/EventAdapterSpec.scala
  akka-persistence/src/test/scala/akka/persistence/OptionalSnapshotStoreSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PerformanceSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistenceSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
  akka-persistence/src/test/scala/akka/persistence/PersistentActorStashingSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotDirectoryFailureSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotRecoveryWithEmptyJournalSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotSerializationSpec.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotSpec.scala
  akka-persistence/src/test/scala/akka/persistence/fsm/PersistentFSMSpec.scala
Labels: 2 - pick next, tested

#30214 Don't put temporary actor refs in the heavy hitters table
  akka-remote/src/main/scala/akka/remote/artery/compress/InboundCompressions.scala
Labels: 2 - pick next, tested

#30177 Incorrect API:doc on RestartSource.onFailuresWithBackoff
  akka-stream/src/main/scala/akka/stream/javadsl/RestartSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartSource.scala
Labels: t:stream, tested

#30258 Compile typed actors with Scala 3
  .travis.yml
  akka-actor-typed/src/main/mima-filters/2.6.14.backwards.excludes/pr-30258.excludes
  akka-actor-typed/src/main/scala-2.12/akka/actor/typed/internal/receptionist/Platform.scala
  akka-actor-typed/src/main/scala-2.13/akka/actor/typed/internal/receptionist/Platform.scala
  akka-actor-typed/src/main/scala-3/akka/actor/typed/internal/receptionist/Platform.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/SpawnProtocol.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ConsumerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ProducerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/WorkPullingProducerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/InterceptorImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorContextAdapter.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/LocalReceptionist.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Behaviors.scala
Labels: 2 - pick next, tested

#30171 Fix specificity of inherited attributes for {Source,Flow,Sink}.fromMaterializer
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FromMaterializationSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SetupSpec.scala
  akka-stream/src/main/mima-filters/2.6.14.backwards.excludes/30171-setup-stage.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/SetupStage.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
Labels: 2 - pick next, t:stream, tested

#30224 Move typed persistence tests away from LevelDB
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/SerializedEventStorageImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/query/scaladsl/PersistenceTestKitReadJournal.scala
  akka-persistence-typed-tests/src/test/java/akka/persistence/typed/javadsl/EventSourcedActorFailureTest.java
  akka-persistence-typed-tests/src/test/java/akka/persistence/typed/javadsl/EventSourcedBehaviorJavaDslTest.java
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorFailureSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorInterceptorSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRecoveryTimeoutSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorReplySpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorRetentionSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorStashSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorTimersSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorWatchSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedEventAdapterSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSequenceNumberSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedSnapshotAdapterSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedStashOverflowSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/LoggerSourceSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/OptionalSnapshotStoreSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/PerformanceSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/PrimitiveStateSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/SlowInMemorySnapshotStore.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/SnapshotMutableStateSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/SnapshotRecoveryWithEmptyJournalSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingEvents.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/PersistentFsmToTypedMigrationSpec.scala
  build.sbt
Labels: 2 - pick next, tested

#30266 Byte array allocation/copy hunt
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ConsumerControllerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/ProducerControllerImpl.scala
  akka-actor/src/main/scala-2.12/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.13/akka/util/ByteString.scala
  akka-actor/src/main/scala-3/akka/util/ByteString.scala
  akka-actor/src/main/scala/akka/serialization/AsyncSerializer.scala
  akka-actor/src/main/scala/akka/serialization/Serializer.scala
  akka-cluster-metrics/src/main/scala/akka/cluster/metrics/protobuf/MessageSerializer.scala
  akka-cluster-tools/src/main/scala/akka/cluster/pubsub/protobuf/DistributedPubSubMessageSerializer.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/delivery/ReliableDeliverySerializer.scala
  akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatorMessageSerializer.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/SerializationSupport.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/serialization/ReplicatedEventSourcingSerializer.scala
  akka-persistence/src/main/scala/akka/persistence/serialization/MessageSerializer.scala
  akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/MaxThroughputSpec.scala
  akka-remote/src/main/scala/akka/remote/ByteStringUtils.scala
  akka-remote/src/main/scala/akka/remote/MessageSerializer.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/TcpFraming.scala
  akka-remote/src/main/scala/akka/remote/serialization/DaemonMsgCreateSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/MessageContainerSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/WrappedPayloadSupport.scala
  akka-remote/src/main/scala/akka/remote/transport/AkkaPduCodec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamGraphStage.scala
  akka-stream/src/main/scala/akka/stream/impl/io/compression/DeflateCompressor.scala
  akka-stream/src/main/scala/akka/stream/impl/io/compression/DeflateDecompressorBase.scala
  akka-stream/src/main/scala/akka/stream/impl/io/compression/GzipCompressor.scala
  akka-stream/src/main/scala/akka/stream/impl/io/compression/GzipDecompressor.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Framing.scala
  akka-stream/src/main/scala/akka/stream/serialization/StreamRefSerializer.scala
Labels: 2 - pick next, t:stream, tested

#30280 First implementation of DurableStateBehavior, #30277
  .travis.yml
  akka-persistence-query/src/main/scala/akka/persistence/query/DurableStateChange.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/javadsl/DurableStateStoreQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/DurableStateStoreQuery.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/DurableStateBehaviorReplySpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/DurableStateSignal.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/DurableStateBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/DurableStateSettings.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/DurableStateStoreException.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/DurableStateStoreInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/EffectImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/NoOpSnapshotAdapter.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/Recovering.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/RequestingRecoveryPermit.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/SideEffect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/StashManagement.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/javadsl/CommandHandler.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/javadsl/CommandHandlerWithReply.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/javadsl/DurableStateBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/javadsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/javadsl/SignalHandler.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/scaladsl/DurableStateBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/scaladsl/Effect.scala
  akka-persistence/src/main/resources/reference.conf
  akka-persistence/src/main/scala/akka/persistence/state/DurableStateStoreProvider.scala
  akka-persistence/src/main/scala/akka/persistence/state/DurableStateStoreRegistry.scala
  akka-persistence/src/main/scala/akka/persistence/state/inmem/InmemDurableStateStoreProvider.scala
  akka-persistence/src/main/scala/akka/persistence/state/inmem/javadsl/InmemDurableStateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/inmem/scaladsl/InmemDurableStateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/javadsl/DurableStateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/javadsl/DurableStateUpdateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/scaladsl/DurableStateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/scaladsl/DurableStateUpdateStore.scala
Labels: tested

#30226 Resolve snapshot check skipped for some events (#30225)
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntitiesShardStore.scala
Labels: 2 - pick next, tested

#30221 Fix context propagation
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/ZipLatestWithApply.scala.template
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/ZipWithApply.scala.template
  akka-stream/src/main/scala/akka/stream/impl/Buffers.scala
  akka-stream/src/main/scala/akka/stream/impl/ContextPropagation.scala
  akka-stream/src/main/scala/akka/stream/impl/Timers.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphStages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: 2 - pick next, t:stream, tested

#30190 support ipv6 in artery
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala
  akka-remote/src/main/scala/akka/remote/artery/ArterySettings.scala
Labels: 2 - pick next, tested

#30097 Update sbt-pgp to 2.1.2
  project/plugins.sbt
Labels: tested

#30285 More tests on DurableStateBehavior
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/DurableStateBehaviorInterceptorSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/DurableStateBehaviorTimersSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/PrimitiveStateSpec.scala
Labels: validating

#30286 fix default DurableStateStore pluginId and config, #30277
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/DurableStateBehaviorInterceptorSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/DurableStateBehaviorReplySpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/DurableStateBehaviorTimersSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/PrimitiveStateSpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/DurableStateSettings.scala
  akka-persistence/src/main/resources/reference.conf
  akka-persistence/src/main/scala/akka/persistence/Persistence.scala
  akka-persistence/src/main/scala/akka/persistence/state/DurableStateStoreRegistry.scala
Labels: tested

#30288 Publish from GitHub Actions
  .github/workflows/publish.yml
  README.md
  RELEASING.md
  project/plugins.sbt
  project/scripts/release
  scripts/create-release-issue.sh
  scripts/release-train-issue-template.md
Labels: tested

#30100 Update jctools-core to 3.3.0
  project/Dependencies.scala
Labels: dependency-change, tested

#30289 Fix mapConcat context propagation
  akka-stream/src/main/scala/akka/stream/impl/ContextPropagation.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: 2 - pick next, t:stream, tested

#29216 Handles handover done message in state oldest
  akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonManager.scala
Labels: tested

#30291 Use whitesource credential when publishing from GH Actions
  .github/workflows/publish.yml
Labels: tested

#30293 Install graphviz for publishing
  .github/workflows/publish.yml
Labels: tested

#30301 Update scala-library to 2.12.14
  project/Dependencies.scala
Labels: dependency-change, tested

#30306 set sonatype profile name for publishing
  project/Publish.scala
Labels: tested

#30304 Update sbt-jmh to 0.4.3
  project/plugins.sbt
Labels: tested

#30314 Amend release script to update milestones
  scripts/release-train-issue-template.md
Labels: tested

#30316 Fixed typo - replaced scaladsl with javadsl
  akka-persistence-query/src/main/scala/akka/persistence/query/javadsl/DurableStateStoreQuery.scala
Labels: validating

#30318 Fix word wrap in Stream Sink.combine docs
  akka-docs/src/main/paradox/stream/operators/Sink/combine.md
Labels: tested

#30305 Fix Akka Persistence Docs Java Example
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/StashingExample.java
Labels: tested

#30340 Move more release instructions to the template
  RELEASING.md
  akka-docs/src/main/paradox/project/links.md
  project/MiMa.scala
  scripts/release-train-issue-template.md
Labels: tested

#30344 Changed seqNr to 'revision' for all durable state APIs and implementations
  akka-persistence-query/src/main/scala/akka/persistence/query/DurableStateChange.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/DurableStateStoreInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/Recovering.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/scaladsl/DurableStateBehavior.scala
  akka-persistence/src/main/scala/akka/persistence/state/javadsl/DurableStateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/javadsl/DurableStateUpdateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/scaladsl/DurableStateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/scaladsl/DurableStateUpdateStore.scala
Labels: tested

#30347 Remove ApiMayChange for Replicated Event Sourcing, #30346
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedEntityProvider.scala
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ReplicatedShardingExtension.scala
  akka-docs/src/main/paradox/common/may-change.md
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
  akka-persistence-typed-tests/src/test/scala/docs/akka/persistence/typed/ReplicatedEventSourcingCompileOnlySpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/Counter.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/LwwTime.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/ORSet.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/crdt/OpCrdt.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/Running.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/ReplicatedEventSourcedBehavior.scala
Labels: tested
