Repository akka/akka, pull requests merged in 2021-05, with the labels that each got.

#30210 avoiding the superposing of the buttons and the code
  akka-docs/src/test/scala/docs/stream/StreamTestKitDocSpec.scala
Labels: tested

#30175 Documentation: Adding section for Projections to the Modules summary…
  akka-docs/src/main/paradox/common/other-modules.md
  akka-docs/src/main/paradox/typed/guide/modules.md
Labels: tested

#30180 Update sbt-dotty to 0.5.4
  project/plugins.sbt
Labels: tested

#30206 build: more reliable reference to protobuf jar
  project/Protobuf.scala
Labels: tested

#30203 avoiding fixed persistenceId on example
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BasicPersistentBehaviorCompileOnly.scala
Labels: tested

#30160 Refactor GraphDslTest and TcpTest
  akka-stream-tests/src/test/java/akka/stream/javadsl/GraphDslTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/TcpTest.java
Labels: t:stream, tested

#30181 Update sbt-scalafix to 0.9.27
  project/plugins.sbt
Labels: tested

#30183 Update sbt-bill-of-materials to 1.0.2
  project/plugins.sbt
Labels: tested

#30217 Resolve missing internal state update in EventSourcedRememberEntities…
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntitiesShardStore.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/internal/RememberEntitiesShardStoreSpec.scala
Labels: tested

#30165 Use assertThrows in classes ActorCreationTest and OutputStreamSinkTest
  akka-actor-tests/src/test/java/akka/actor/ActorCreationTest.java
  akka-stream-tests/src/test/java/akka/stream/io/OutputStreamSinkTest.java
Labels: t:stream, tested

#30218 Fixed typo: statefulMapConcat example corrected typo
  akka-docs/src/test/java/jdocs/stream/operators/flow/StatefulMapConcat.java
  akka-docs/src/test/scala/docs/stream/operators/flow/StatefulMapConcat.scala
Labels: tested

#30227 Remove usage of Java assert in tests (#30220)
  akka-actor-tests/src/test/java/akka/util/JavaDuration.java
  akka-docs/src/test/java/jdocs/actor/FaultHandlingTest.java
  akka-docs/src/test/java/jdocs/duration/Java.java
  akka-docs/src/test/java/jdocs/io/japi/EchoHandler.java
  akka-docs/src/test/java/jdocs/io/japi/IODocTest.java
  akka-docs/src/test/java/jdocs/stream/StreamTestKitDocTest.java
  akka-persistence-typed-tests/src/test/java/jdocs/akka/persistence/typed/ReplicatedAuctionExampleTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SinkTest.java
Labels: t:stream, tested

#30235 Fix Broadcast examples, as they currently fail.
  akka-docs/src/test/scala/docs/stream/operators/BroadcastDocExample.scala
Labels: tested

#30233 Use StandardCharsets.UTF-8 in SerializationDocTest
  akka-docs/src/test/java/jdocs/serialization/SerializationDocTest.java
Labels: tested

#30105 Add Sink.asPublisher example and update doc
  akka-docs/src/main/paradox/stream/operators/Sink/asPublisher.md
  akka-docs/src/test/java/jdocs/stream/operators/SinkDocExamples.java
  akka-docs/src/test/scala/docs/stream/operators/sink/AsPublisher.scala
Labels: tested

#30216 Fixed race condition in MergeHub draining test: 30207
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala
Labels: t:stream, tested

#30211 Delete CI-sensitive LevelDB perf spec
  akka-persistence-tck/src/test/scala/akka/persistence/journal/leveldb/LeveldbJournalNativePerfSpec.scala
Labels: tested

#30239 stream: reuse `maxBytesPerChunk` buffer for inflate / gunzip
  akka-stream/src/main/scala/akka/stream/impl/io/compression/DeflateDecompressorBase.scala
Labels: t:stream, tested

#30209 fix lease support missing for typed cluster singleton
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ClusterShardingSettings.scala
  akka-cluster-typed/src/main/scala/akka/cluster/typed/ClusterSingleton.scala
Labels: tested

#30244 Remove SourceModule/SinkModule newInstance
  akka-stream-testkit/src/main/mima-filters/2.6.14.backwards.excludes/stream-module-newInstance.excludes
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala
  akka-stream/src/main/mima-filters/2.6.14.backwards.excludes/stream-module-newInstance.excludes
  akka-stream/src/main/scala/akka/stream/impl/Modules.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
Labels: t:stream, tested

#30236 Fix test ActorCreationTest.testWrongAnonymousInPlaceCreator
  akka-actor-tests/src/test/java/akka/actor/ActorCreationTest.java
  akka-actor-tests/src/test/scala/akka/actor/PropsCreationSpec.scala
  akka-actor/src/main/scala/akka/actor/AbstractProps.scala
Labels: tested

#30246 Add BoundaryEvent cancellation hook for telemetry
  akka-stream/src/main/mima-filters/2.6.14.backwards.excludes/30246-boundary-event-cancellation-hook.excludes
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
Labels: t:stream, tested

#30248 Update Scala to 3.0.0 final, sbt to 1.5.2
  build.sbt
  project/AkkaBuild.scala
  project/AkkaDisciplinePlugin.scala
  project/AutomaticModuleName.scala
  project/CopyrightHeader.scala
  project/CopyrightHeaderForBoilerplate.scala
  project/CopyrightHeaderForBuild.scala
  project/CopyrightHeaderForJdk9.scala
  project/CopyrightHeaderForProtobuf.scala
  project/Dependencies.scala
  project/Doc.scala
  project/JavaFormatter.scala
  project/Jdk9.scala
  project/JdkOptions.scala
  project/MultiNode.scala
  project/Paradox.scala
  project/ParadoxBrowse.scala
  project/Protobuf.scala
  project/Publish.scala
  project/ScalaFixExtraRulesPlugin.scala
  project/ScalafixSupport.scala
  project/SigarLoader.scala
  project/TestExtras.scala
  project/ValidatePullRequest.scala
  project/Whitesource.scala
  project/build.properties
  project/plugins.sbt
Labels: dependency-change, tested

#29921 Add more explicit annotations of top level coexistence
  akka-docs/src/main/paradox/typed/coexisting.md
  akka-docs/src/main/paradox/typed/from-classic.md
Labels: tested

#30070 Change tests to use new Source.queue api, #29801
  akka-bench-jmh/src/main/scala/akka/remote/artery/SendQueueBenchmark.scala
  akka-docs/src/test/java/jdocs/stream/IntegrationDocTest.java
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupBySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream-typed/src/test/java/akka/stream/typed/javadsl/ActorSourceSinkCompileTest.java
  akka-stream-typed/src/test/scala/akka/stream/typed/scaladsl/ActorSourceSinkSpec.scala
Labels: t:stream, tested

#30259 Call BoundaryEvent cancellation hook for telemetry when ActorGraphInterpreter stops
  akka-actor/src/main/scala/akka/actor/ActorCell.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
Labels: 2 - pick next, t:stream, tested

#30252 Lazy and fast concat and prepend
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/concat.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/concatLazy.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/prepend.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/prependLazy.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowConcatSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowPrependSpec.scala
  akka-stream/src/main/mima-filters/2.6.14.backwards.excludes/23044-concat-prepend-improvements.excludes
  akka-stream/src/main/scala/akka/stream/impl/SingleConcat.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
Labels: 2 - pick next, t:stream, tested

#30261 Fix LineNumberSpec failing in Scala 3
  akka-actor-tests/src/test/scala-3/akka/util/LineNumberSpec.scala
Labels: tested

#30268 Extends supervision strategy to define custom log levels #30267
  akka-actor/src/main/mima-filters/2.6.14.backwards.excludes/30267-supervision-loglevel.excludes
  akka-actor/src/main/scala/akka/actor/FaultHandling.scala
  akka-docs/src/main/paradox/fault-tolerance.md
Labels: tested

#30250 Unnecessary boxing was removed from tests
  akka-actor-tests/src/test/java/akka/actor/JavaAPI.java
  akka-actor-tests/src/test/java/akka/actor/StashJavaAPITestActors.java
  akka-actor-tests/src/test/java/akka/japi/MatchBuilderTest.java
Labels: tested

#30238 Possibility to make snapshot load failures non-fatal, #30234
  akka-docs/src/main/paradox/persistence.md
  akka-docs/src/main/paradox/typed/persistence-snapshot.md
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/PersistenceTestKitPlugin.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/BehaviorSetup.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ExternalInteractions.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/SnapshotIsOptionalSpec.scala
  akka-persistence/src/main/resources/reference.conf
  akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala
  akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
Labels: 2 - pick next, tested
