Repository akka/akka, pull requests merged in 2021-07, with the labels that each got.

#30334 Smart batching of writes in TcpStages
  akka-stream/src/main/resources/reference.conf
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
Labels: t:stream, tested

#30353 stream: actually read coalesce-writes setting from config
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
Labels: t:stream, tested

#30356 Hide private members in documentation (#20185)
  project/Doc.scala
Labels: tested

#30357 Revert "Hide private members in documentation (#20185)"
  project/Doc.scala
Labels: tested

#30364 A few ByteString.size switched to ByteString.length
  akka-remote/src/main/scala/akka/remote/Endpoint.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/TcpFraming.scala
  akka-stream/src/main/scala/akka/stream/impl/io/ByteStringParser.scala
  akka-stream/src/main/scala/akka/stream/impl/io/compression/DeflateCompressor.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Framing.scala
Labels: t:stream, tested

#30351 Clarify sharding stop message being local
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#30352 Update cluster.md
  akka-docs/src/main/paradox/typed/cluster.md
Labels: tested

#30281 Remove unchecked cast from SourceTest and FlowTest
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
Labels: t:stream, tested

#30324 akka-stream compiling on Scala 3
  .travis.yml
  akka-stream-tests/src/test/scala/akka/stream/DslFactoriesConsistencySpec.scala
  akka-stream/src/main/boilerplate/akka/stream/javadsl/GraphCreate.scala.template
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/GraphApply.scala.template
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/ZipLatestWithApply.scala.template
  akka-stream/src/main/mima-filters/2.6.15.backwards.excludes/compile-on-scala-3.backwards.excludes
  akka-stream/src/main/scala-2.12/akka/stream/impl/ImplicitExtensionIdApply.scala
  akka-stream/src/main/scala-2.13/akka/stream/impl/ImplicitExtensionIdApply.scala
  akka-stream/src/main/scala-3/akka/stream/impl/ImplicitExtensionIdApply.scala
  akka-stream/src/main/scala/akka/stream/MaterializerLoggingProvider.scala
  akka-stream/src/main/scala/akka/stream/impl/ActorProcessor.scala
  akka-stream/src/main/scala/akka/stream/impl/Buffers.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/ResizableMultiReaderRingBuffer.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/Throttle.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
  akka-stream/src/main/scala/akka/stream/impl/streamref/StreamRefSettingsImpl.scala
  akka-stream/src/main/scala/akka/stream/javadsl/BidiFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/FileIO.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Graph.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/StreamConverters.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/BidiFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
  akka-stream/src/main/scala/akka/stream/stage/StageLogging.scala
  akka-stream/src/main/scala/com/typesafe/sslconfig/akka/AkkaSSLConfig.scala
  project/Dependencies.scala
Labels: t:stream, tested

#30296 Update gson to 2.8.7
  project/Dependencies.scala
Labels: dependency-change, tested

#30337 doc: make it clear inputBuffer has no effect in sample
  akka-docs/src/main/paradox/stream/stream-composition.md
Labels: tested

#29534 stream: fix client-side mutual TLS bug
  akka-stream-tests/src/test/scala/akka/stream/impl/io/TLSUtilsSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
Labels: t:stream, tested

#30372 Reading until last global offset at time of calling currentChanges, a…
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStore.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStoreSpec.scala
Labels: tested

#30331 allow minor versions after Scala 3.0
  project/AkkaDisciplinePlugin.scala
  project/Dependencies.scala
Labels: dependency-change, tested

#30376 sprinkle ApiMayChange over durable state
  akka-docs/src/main/paradox/common/may-change.md
  akka-persistence-query/src/main/scala/akka/persistence/query/DurableStateChange.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/javadsl/DurableStateStoreQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/DurableStateStoreQuery.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/javadsl/DurableStateBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/javadsl/Effect.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/scaladsl/DurableStateBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/scaladsl/Effect.scala
  akka-persistence/src/main/scala/akka/persistence/state/DurableStateStoreProvider.scala
  akka-persistence/src/main/scala/akka/persistence/state/DurableStateStoreRegistry.scala
  akka-persistence/src/main/scala/akka/persistence/state/javadsl/DurableStateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/javadsl/DurableStateUpdateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/scaladsl/DurableStateStore.scala
  akka-persistence/src/main/scala/akka/persistence/state/scaladsl/DurableStateUpdateStore.scala
Labels: tested

#30382 Update sbt to 1.5.4
  project/build.properties
Labels: tested

#30380 Update sbt-reproducible-builds to 0.28
  project/plugins.sbt
Labels: tested

#30375 Update `scala-java8-compat` to `1.0.0`
  project/Dependencies.scala
Labels: dependency-change, tested

#30313 benchmark: ByteString append and builder
  akka-bench-jmh/src/main/scala/akka/util/ByteString_append_Benchmark.scala
Labels: tested

#30390 missing line
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/MapConcat.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/MapConcat.scala
Labels: tested

#30377 Update commons-io to 2.10.0
  project/Dependencies.scala
Labels: dependency-change, tested

#30383 Update jul-to-slf4j, log4j-over-slf4j, ... to 1.7.31
  project/Dependencies.scala
Labels: dependency-change, tested

#30388 Akka 30374 flat map prefix attributes propagation
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
Labels: t:stream, tested

#30385 Compile some more subprojects with scala3 on travis
  .travis.yml
Labels: tested

#30384 Share source directory between Scala 2.13 and Scala 3
  akka-actor/src/main/scala-2.13+/akka/compat/Future.scala
  akka-actor/src/main/scala-2.13+/akka/compat/PartialFunction.scala
  akka-actor/src/main/scala-2.13+/akka/dispatch/internal/SameThreadExecutionContext.scala
  akka-actor/src/main/scala-2.13+/akka/util/ccompat/ccompatUsedUntil213.scala
  akka-actor/src/main/scala-2.13+/akka/util/ccompat/package.scala
  akka-actor/src/main/scala-3/akka/compat/Future.scala
  akka-actor/src/main/scala-3/akka/compat/PartialFunction.scala
  akka-actor/src/main/scala-3/akka/dispatch/internal/SameThreadExecutionContext.scala
  akka-actor/src/main/scala-3/akka/util/ccompat/ccompatUsedUntil213.scala
  akka-actor/src/main/scala-3/akka/util/ccompat/package.scala
  project/AkkaBuild.scala
Labels: tested

#30295 Update sbt-assembly to 1.0.0
  project/plugins.sbt
Labels: tested

#30294 Update sbt-scalafix to 0.9.29
  project/plugins.sbt
Labels: tested

#30379 Update metrics-core, metrics-jvm to 4.1.24
  project/Dependencies.scala
Labels: dependency-change, tested

#30360 Akka Stream TCK tests on Scala 3.0
  .travis.yml
  akka-stream-testkit/src/main/scala/akka/stream/testkit/scaladsl/StreamTestKit.scala
  akka-stream-testkit/src/test/scala/akka/stream/impl/fusing/GraphInterpreterSpecKit.scala
Labels: t:stream, tested

#30397 Remove the extra bracket from testing documentation
  akka-docs/src/main/paradox/testing.md
Labels: tested

#30387 First draft of reference docs on durable state
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleWithNullDurableState.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithCommandHandlersInDurableState.scala
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleWithOptionDurableState.scala
  akka-docs/src/main/paradox/index.md
  akka-docs/src/main/paradox/typed/index-persistence-durable-state.md
  akka-docs/src/main/paradox/typed/index-persistence.md
  akka-docs/src/main/paradox/typed/persistence-durable-state.md
  akka-docs/src/main/paradox/typed/persistence-style-durable-state.md
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/DurableStateBehaviorReplySpec.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/scaladsl/Effect.scala
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BlogPostEntityDurableState.java
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/DurableStatePersistentBehaviorTest.java
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/BlogPostEntityDurableState.scala
  akka-persistence-typed/src/test/scala/docs/akka/persistence/typed/DurableStatePersistentBehaviorCompileOnly.scala
Labels: tested

#30381 Update lz4-java to 1.8.0
  project/Dependencies.scala
Labels: dependency-change, tested

#30405 Fix deprecated links in osgi.md
  akka-docs/src/main/paradox/additional/osgi.md
Labels: tested

#30404 fix: Actually set halfClosed in half closed sample
  akka-docs/src/test/java/jdocs/stream/operators/flow/FromSinkAndSource.java
  akka-docs/src/test/scala/docs/stream/operators/flow/FromSinkAndSource.scala
Labels: tested

#30338 fix: Defer coordinator stop until region graceful stop has completed …
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGracefulShutdownOldestSpec.scala
Labels: tested

#30395 Compile akka-actor-testkit with scala 3
  .travis.yml
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/TestKitSettings.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/StubbedActorContext.scala
Labels: tested

#30396 Compile akka-discovery with Scala 3
  .travis.yml
  akka-discovery/src/main/scala/akka/discovery/Discovery.scala
  akka-discovery/src/main/scala/akka/discovery/aggregate/AggregateServiceDiscovery.scala
  akka-discovery/src/main/scala/akka/discovery/config/ConfigServiceDiscovery.scala
  akka-discovery/src/main/scala/akka/discovery/dns/DnsServiceDiscovery.scala
Labels: tested

#30386 compile akka-coordination with scala3
  .travis.yml
  akka-coordination/src/main/scala/akka/coordination/lease/scaladsl/LeaseProvider.scala
  akka-coordination/src/test/scala/akka/coordination/lease/TestLease.scala
  akka-coordination/src/test/scala/akka/coordination/lease/TestLeaseActor.scala
Labels: tested

#30302 Update scala-library to 2.13.6
  project/Dependencies.scala
Labels: dependency-change, tested

#30411 Update genjavadoc
  project/Doc.scala
Labels: tested

#30409 Test akka-coordination on Scala 3
  .travis.yml
  project/Dependencies.scala
Labels: dependency-change, tested

#30402 sharding: actively signal 'region stopped' to the coordinator
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGracefulShutdownSpec.scala
Labels: tested

#30408 Compile akka-serialization-jackson with Scala 3
  .travis.yml
  akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala
  akka-serialization-jackson/src/test/scala/akka/serialization/jackson/JacksonSerializerSpec.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/CustomAdtSerializer.scala
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/SerializationDocSpec.scala
  project/Dependencies.scala
Labels: dependency-change, tested

#30407 Run akka-testkit tests on Scala 3
  .travis.yml
Labels: tested

#30410 Test Akka Discovery with Scala 3
  .travis.yml
  akka-actor-tests/src/test/scala/akka/io/dns/DockerBindDnsService.scala
Labels: dependency-change, tested

#30361 Akka Remote compiling on Scala 3.0
  .travis.yml
  akka-actor/src/main/scala/akka/actor/Address.scala
  akka-remote/src/main/mima-filters/2.6.15.backwards.excludes/compile-on-scala-3.backwards.excludes
  akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala
  akka-remote/src/main/scala/akka/remote/RemoteMetricsExtension.scala
  akka-remote/src/main/scala/akka/remote/Remoting.scala
  akka-remote/src/main/scala/akka/remote/RemotingLifecycleEvent.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/ImmutableLongMap.scala
  akka-remote/src/main/scala/akka/remote/artery/RemoteInstrument.scala
  akka-remote/src/main/scala/akka/remote/artery/aeron/TaskRunner.scala
  akka-remote/src/main/scala/akka/remote/artery/compress/DecompressionTable.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ArteryTcpTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/tcp/ssl/SessionVerifier.scala
  akka-remote/src/main/scala/akka/remote/serialization/ArteryMessageSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/DaemonMsgCreateSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/ProtobufSerializer.scala
  akka-remote/src/main/scala/akka/remote/serialization/ThrowableSupport.scala
  akka-remote/src/main/scala/akka/remote/serialization/WrappedPayloadSupport.scala
  akka-remote/src/main/scala/akka/remote/transport/FailureInjectorTransportAdapter.scala
  akka-remote/src/main/scala/akka/remote/transport/TestTransport.scala
  akka-remote/src/main/scala/akka/remote/transport/ThrottlerTransportAdapter.scala
  akka-remote/src/main/scala/akka/remote/transport/netty/NettyTransport.scala
  build.sbt
Labels: dependency-change, tested

#30354 io: probe TCP socket when reading before registering interest
  akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala
  akka-actor/src/main/mima-filters/2.6.15.backwards.excludes/30354-improve-TcpConnection.excludes
  akka-actor/src/main/scala/akka/io/TcpConnection.scala
Labels: tested

#30421 akka-paradox: update to 0.39 (backport)
  project/plugins.sbt
Labels: tested

#30420 akka-paradox: update to 0.39
  project/plugins.sbt
Labels: tested

#30283 Run tests for actors and typed actors on Scala 3
  .travis.yml
  akka-actor-tests/src/test/java/akka/actor/AbstractFSMActorTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/IntroTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorContextSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ActorRefIgnoreSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/BehaviorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/ExtensionsSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/MailboxSelectorSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/InteractionPatternsSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/OOIntroSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/BehaviorBuilder.scala
Labels: dependency-change, tested

#30423 enable all tests that are passing with scala 3
  .travis.yml
Labels: tested

#30427 use GH Actions to compile and tests with Scala 3
  .github/workflows/scala3-build.yml
  .jvmopts-ci
  .travis.yml
  akka-actor-tests/src/test/scala/akka/util/BoundedBlockingQueueSpec.scala
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/ActorContextPipeToSelfTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextPipeToSelfSpec.scala
Labels: tested

#30428 Fix race in RoutersTest
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/RoutersTest.java
Labels: tested

#30419 docs: addItem method in EventSourcedBehavior docs
  akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java
Labels: tested

#30415 Run akka-remote tests on Scala 3
  .github/workflows/scala3-build.yml
  akka-multi-node-testkit/src/main/scala/akka/remote/testkit/MultiNodeSpec.scala
  akka-multi-node-testkit/src/main/scala/akka/remote/testkit/PerfFlamesSupport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/test/scala/akka/remote/AckedDeliverySpec.scala
  akka-remote/src/test/scala/akka/remote/artery/ActorRefResolveCacheQuarantineSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/ImmutableLongMapSpec.scala
  akka-remote/src/test/scala/akka/remote/artery/SerializationErrorSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/RemotingSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/transport/AkkaProtocolSpec.scala
  akka-remote/src/test/scala/akka/remote/classic/transport/netty/NettyTransportSpec.scala
  akka-remote/src/test/scala/akka/remote/serialization/MiscMessageSerializerSpec.scala
Labels: tested

#30403 Add more docs on durable state
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/DurableStateStoreQueryUsageCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/DurableStateStoreQueryUsageCompileOnlySpec.scala
  akka-docs/src/main/paradox/persistence-query-durable-state.md
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/main/paradox/typed/cqrs-durable-state.md
  akka-docs/src/main/paradox/typed/cqrs.md
  akka-docs/src/main/paradox/typed/index-persistence-durable-state.md
  akka-docs/src/main/paradox/typed/persistence-durable-state.md
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#30440 Minor fixes in tests and documentation
  akka-docs/src/main/paradox/persistence-query-durable-state.md
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/DurableStateBehaviorReplySpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/NullEmptyStateSpec.scala
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/state/scaladsl/PrimitiveStateSpec.scala
Labels: tested

#30443 Remove dev-durable-state from travis safelist
  .travis.yml
Labels: validating

#30429 Fix MailboxSelectorSpec race
  akka-actor-testkit-typed/src/main/mima-filters/2.6.15.backwards.excludes/excess-checking.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/LoggingTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/LoggingTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/LoggingTestKit.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/MailboxSelectorSpec.scala
Labels: tested

#30433 [Docs] Fix scala snippet for Sink.combine #30431
  akka-docs/src/main/paradox/stream/operators/Sink/combine.md
Labels: tested
