Repository akka/akka, pull requests merged in 2021-08, with the labels that each got.

#30417 scala3: akka-cluster
  .github/workflows/scala3-build.yml
  akka-cluster-metrics/src/main/scala/akka/cluster/metrics/MetricsCollector.scala
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-cluster/src/main/scala/akka/cluster/ClusterEvent.scala
  akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala
  akka-cluster/src/main/scala/akka/cluster/Member.scala
  akka-cluster/src/main/scala/akka/cluster/routing/ClusterRouterConfig.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcHeartbeatTakingOverSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/MultiDcSunnyWeatherSpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDomainEventSpec.scala
  akka-cluster/src/test/scala/akka/cluster/JoinConfigCompatCheckerSpec.scala
Labels: tested

#30438 Diagnose BalancingSpec failure
  akka-actor-tests/src/test/scala/akka/routing/BalancingSpec.scala
Labels: tested

#30461 Don't run multi-jvm tests on GHA for Scala 3
  .github/workflows/scala3-build.yml
Labels: tested

#30453 Build Test Akka Cluster Metrics with sigar library.
  .github/workflows/nightly-cluster-metrics-sigar.yml
  .jvmopts-ci
  .sbtopts
Labels: tested

#30467 Fix LocalPubSubSpec instability
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/pubsub/LocalPubSubSpec.scala
Labels: tested

#30468 Exclude failing tests only on GHA
  .github/workflows/scala3-build.yml
  akka-actor-tests/src/test/scala/akka/event/EventStreamSpec.scala
  akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/pubsub/LocalPubSubSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala
  akka-testkit/src/test/scala/akka/testkit/TestTags.scala
Labels: t:stream, tested

#30472 Parallelize GH Action for Scala 3
  .github/workflows/scala3-build.yml
Labels: tested

#30470 Diagnose FlowFlatMapPrefixSpec
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
Labels: t:stream, tested

#30477 Exclude CircuitBreakerMTSpec from GH Action tests
  akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerMTSpec.scala
Labels: tested

#30463 Fix UdpConnectedIntegrationSpec instability
  akka-actor-tests/src/test/scala/akka/io/UdpConnectedIntegrationSpec.scala
Labels: tested

#30436 Enable logging for flaky EventStreamSpec
  akka-actor-tests/src/test/scala/akka/event/EventStreamSpec.scala
Labels: tested

#30471 BalancingSpec: log the sender of the expected messages
  akka-actor-tests/src/test/scala/akka/routing/BalancingSpec.scala
Labels: tested

#30475 fix EventStreamSpec instability
  akka-actor-tests/src/test/scala/akka/event/EventStreamSpec.scala
Labels: tested

#30473 Fix TlsSpec on AdoptOpenJdk 1.8.0-272+
  akka-stream-tests/src/test/scala/akka/stream/io/DeprecatedTlsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
Labels: t:stream, tested

#30484 Exclude failing test on GH Action
  akka-actor-tests/src/test/scala/akka/event/EventStreamSpec.scala
Labels: tested

#30456 Align scalaVersion in .travis
  .travis.yml
Labels: tested

#30485 Use latest Ubuntu and JDK latest LTS
  .github/workflows/scala3-build.yml
Labels: tested

#30422 Auto-publish backported docs
  .github/workflows/publish-docs.yml
  .github/workflows/publish.yml
  RELEASING.md
Labels: tested

#30494 Fix CoronerSpec instability
  akka-testkit/src/test/scala/akka/testkit/Coroner.scala
Labels: tested

#30491 Avoid lazySource cancellation race in test
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala
Labels: tested, t:stream

#30497 Exclude ConsumerControllerSpec on GH Actions
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ConsumerControllerSpec.scala
Labels: tested

#30500 Abort scala3 jobs when pushing new commits on the PR
  .github/workflows/scala3-build.yml
Labels: tested

#30499 Stabilise InmemPersistentActorSpec
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
Labels: tested

#30465 fix HubSpec 'MergeHub must immediately cancel' instability
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala
Labels: tested, t:stream

#30517 Minor doc adjustment for Durable State
  akka-docs/src/main/paradox/common/may-change.md
  akka-docs/src/main/paradox/typed/durable-state/persistence.md
Labels: tested

#30520 Combine some tests projects in Scala3 build
  .github/workflows/scala3-build.yml
Labels: tested

#30521 Add (some) GH Actions nightly jobs
  .github/workflows/build-test-prValidation.yml
  .github/workflows/nightly-jdk11.yml
  .github/workflows/nightly-jdk8-scala2.13.yml
  .github/workflows/nightly-jdk8.yml
  akka-actor-tests/src/test/scala/akka/routing/BalancingSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/delivery/ConsumerControllerSpec.scala
  akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/delivery/DurableShardingSpec.scala
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/StartEntitySpec.scala
  akka-cluster/src/test/scala/akka/cluster/ClusterDeathWatchNotificationSpec.scala
  akka-persistence/src/test/java/akka/persistence/fsm/AbstractPersistentFSMTest.java
  project/CopyrightHeaderForBoilerplate.scala
  project/Dependencies.scala
  project/Doc.scala
  project/MultiNode.scala
Labels: needs-attention, dependency-change

#30513 Fix TcpConnection error handling
  akka-actor/src/main/scala/akka/io/TcpConnection.scala
Labels: tested

#30506 Update metrics-core, metrics-jvm to 4.1.25
  project/Dependencies.scala
Labels: tested, dependency-change

#30514 ContextPropagation enhancement
  akka-stream/src/main/mima-filters/2.6.12.backwards.excludes/pr-29086-rename-grouped.excludes
  akka-stream/src/main/mima-filters/2.6.16.backwards.excludes/context-propagation.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/ContextPropagation.scala
Labels: tested, t:stream

#30526 Correction of adopt java version
  .github/workflows/nightly-jdk8.yml
Labels: tested

#30493 LazySourceSpec: improve 'no demand' test stability
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala
Labels: tested, t:stream

#30503 Improvements to documentation on Stream-Actor interop
  akka-docs/src/main/paradox/stream/actor-interop.md
  akka-docs/src/test/scala/docs/stream/IntegrationDocSpec.scala
Labels: tested

#30505 Update commons-io to 2.11.0
  project/Dependencies.scala
Labels: tested, dependency-change

#30490 Fix FlowFlatMapPrefixSpec instability
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
Labels: tested, t:stream

#30533 Fix running whitesource in nightly
  .github/workflows/nightly-jdk8.yml
Labels: tested

#30451 Run akka-stream-tests on Scala 3
  .github/workflows/scala3-build.yml
  akka-bench-jmh/src/main/scala/akka/stream/MaterializationBenchmark.scala
  akka-distributed-data/src/main/scala/akka/cluster/ddata/DistributedData.scala
  akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala
  akka-stream-tests/src/test/java/akka/stream/javadsl/GraphDslTest.java
  akka-stream-tests/src/test/scala/akka/stream/DslConsistencySpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/FixedBufferSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/TraversalTestUtils.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/ActorGraphInterpreterSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/AsyncCallbackSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/GraphInterpreterSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/LifecycleInterpreterSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/DeprecatedTlsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TcpHelper.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TcpSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/io/TlsSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/AttributesSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/BidiFlowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowAskSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowDispatcherSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowJoinSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowKillSwitchSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapAsyncSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapAsyncUnorderedSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowRecoverWithSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowScanAsyncSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBackedFlowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBalanceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphBroadcastSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphDSLCompileSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergeLatestSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergePreferredSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergePrioritizedSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMergeSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphOpsIntegrationSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphPartialSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphPartitionSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphUnzipWithSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipLatestSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipNSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/PublisherSinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RestartSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RetryFlowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ReverseArrowSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RunnableGraphSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkForeachAsyncSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamConvertersSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/snapshot/MaterializerStateSpec.scala
  akka-stream/src/main/boilerplate/akka/stream/scaladsl/GraphApply.scala.template
  project/AkkaBuild.scala
  project/Dependencies.scala
Labels: tested, t:stream

#30535 Mark ContextPropagation with InternalStableApi
  akka-stream/src/main/scala/akka/stream/impl/ContextPropagation.scala
Labels: tested, t:stream

#30536 Fix LazySourceSpec instability
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala
Labels: tested, t:stream

#30542 Improve InmemPersistentActorSpec stability
  akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala
Labels: tested

#30545 Remove WhiteSource plugin
  .github/workflows/nightly-jdk8.yml
  .github/workflows/publish.yml
  .travis.yml
  RELEASING.md
  build.sbt
  project/Publish.scala
  project/Whitesource.scala
  project/plugins.sbt
Labels: tested

#30537 Fix StartEntitySpec instability
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/StartEntitySpec.scala
Labels: tested

#30539 Avoid ActorsLeakSpec failure
  akka-remote/src/test/scala/akka/remote/classic/ActorsLeakSpec.scala
Labels: tested

#30538 Fix actor ref backpressure source spec instability
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/ActorRefBackpressureSourceSpec.scala
Labels: tested, t:stream

#30488 Quieter logging for ShardCoordinator initialization
  akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala
Labels: tested, 2 - pick next

#30321 fix: Race condition in LazySourceSpec
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala
Labels: tested, t:stream

#30522 Link mapConcat, flatMapConcat and flatMapMerge
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/flatMapConcat.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/flatMapMerge.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapConcat.md
Labels: tested, 2 - pick next

#30523 Backoff supervision with critical log level, #30445
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/StashSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.15.backwards.excludes/issue-30445.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/SupervisorStrategy.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
Labels: tested, 2 - pick next

#30525 Remove unused sample references from FlowDoc{Test|Spec} (#20450)
  akka-docs/src/test/java/jdocs/stream/FlowDocTest.java
  akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala
Labels: tested, 2 - pick next

#30328 Exclude exiting members in Read/Write MajorityPlus, #30327
  akka-cluster-sharding/src/main/resources/reference.conf
  akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala
  akka-docs/src/main/paradox/typed/distributed-data.md
Labels: tested, 2 - pick next

#30529 Log settings for restart stream stages, #30445
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RestartSpec.scala
  akka-stream/src/main/mima-filters/2.6.15.backwards.excludes/context-propagation.excludes
  akka-stream/src/main/mima-filters/2.6.15.backwards.excludes/issue-30445-RestartSettings.excludes
  akka-stream/src/main/scala/akka/stream/RestartSettings.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartFlow.scala
Labels: tested, 2 - pick next, t:stream

#30549 AST for DurableStateChange to support deletes
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/DurableStateStoreQueryUsageCompileOnlyTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/DurableStateStoreQueryUsageCompileOnlySpec.scala
  akka-docs/src/main/paradox/durable-state/persistence-query.md
  akka-persistence-query/src/main/scala/akka/persistence/query/DurableStateChange.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/javadsl/DurableStateStoreQuery.scala
  akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/DurableStateStoreQuery.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/state/javadsl/PersistenceTestKitDurableStateStore.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStore.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStoreSpec.scala
Labels: tested, 2 - pick next

#30554 MiMa latest patch 2.6.16
  project/MiMa.scala
Labels: tested

#30557 GH Actions: Run validatePullRequest and MiMa
  .github/workflows/binary-compatibility-checks.yml
  .github/workflows/build-test-prValidation.yml
  .travis.yml
Labels: tested

#30504 Update logback-classic to 1.2.5
  project/Dependencies.scala
Labels: tested, dependency-change

#30507 Update sbt to 1.5.5
  project/build.properties
Labels: tested

#30478 Use generic type inference and method references in FlowDocTest.java
  akka-docs/src/test/java/jdocs/stream/FlowDocTest.java
Labels: tested

#30560 Replace try/catch on assertThrows in FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
Labels: tested, t:stream

#30563 use internalLogger instead of context.log for recovery logging
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/ReplayingSnapshot.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/state/internal/Recovering.scala
Labels: tested

#30561 Also dilate the initial delay when testing timeouts in akka-stream-testkit
  .github/workflows/build-test-prValidation.yml
  akka-docs/src/main/paradox/cluster-metrics.md
  akka-stream-testkit/src/test/scala/akka/stream/testkit/StreamTestKitSpec.scala
  project/Paradox.scala
Labels: tested, t:stream

#30551 GH Actions: Nightly builds improvements
  .github/workflows/nightly-builds.yml
  .github/workflows/nightly-cluster-metrics-sigar.yml
  .github/workflows/nightly-jdk11.yml
  .github/workflows/nightly-jdk8-scala2.13.yml
  .github/workflows/nightly-jdk8.yml
  build.sbt
  project/AkkaBuild.scala
  project/MultiNode.scala
Labels: tested

#30562 Clearer error message when the test fails
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/MessageAdapterSpec.scala
Labels: tested

#30590 Fix broken links in CONTRIBUTING.MD
  CONTRIBUTING.md
Labels: tested

#30588 Replace broken links on RFC standarts
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-stream/src/main/scala/akka/stream/impl/io/compression/GzipDecompressor.scala
Labels: t:stream

#30571 GH Actions: Add nightly job to run Artery cluster tests
  .github/workflows/nightly-builds.yml
Labels: tested

#30572 GH Actions: Add nightly job to run Classic cluster tests
  .github/workflows/nightly-builds.yml
  akka-cluster/src/multi-jvm/scala/akka/cluster/StressSpec.scala
  project/SbtMultiJvm.scala
Labels: tested

#30573 GH Actions: Add nightly job to run Artery Aeron remote tests
  .github/workflows/nightly-builds.yml
Labels: tested

#30593 Fix broken links about java serialization (#30589)
  akka-docs/src/main/paradox/project/migration-guide-2.5.x-2.6.x.md
  akka-docs/src/main/paradox/remoting-artery.md
  akka-docs/src/main/paradox/remoting.md
  akka-docs/src/main/paradox/security/2017-02-10-java-serialization.md
  akka-docs/src/main/paradox/serialization.md
Labels: t:docs

#30595 Update contributing guide to remove Jenkins and add Github Actions
  .github/workflows/binary-compatibility-checks.yml
  .github/workflows/nightly-builds.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish.yml
  .github/workflows/scala3-build.yml
  CONTRIBUTING.md
Labels: t:docs
