Repository akka/akka, pull requests merged in 2021-03, with the labels that each got.

#30012 Update sbt-scalafix to 0.9.25
  project/plugins.sbt
Labels: tested

#29986 Use scala.concurrent.Batchable for Scala 2.13
  akka-actor/src/main/scala-2.12/akka/dispatch/internal/ScalaBatchable.scala
  akka-actor/src/main/scala-2.13/akka/dispatch/internal/ScalaBatchable.scala
  akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala
  akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala
Labels: tested

#30069 Add batchable sources also for Scala 3
  akka-actor/src/main/scala-3/akka/dispatch/internal/ScalaBatchable.scala
Labels: 2 - pick next, tested

#30066 Adds initial delay to Timers #30065
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/Effect.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/EffectfulActorContext.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.13.backwards.excludes/30065-timers-initialDelay.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/TimerSchedulerImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/TimerScheduler.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/TimerScheduler.scala
  akka-actor/src/main/mima-filters/2.6.13.backwards.excludes/30065-timers-initialDelay.excludes
  akka-actor/src/main/scala/akka/actor/Timers.scala
  akka-actor/src/main/scala/akka/actor/dungeon/TimerSchedulerImpl.scala
Labels: tested

#30043 stream: add assertion against JDK bug to avoid spin loop in TlsActor
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
Labels: t:stream, tested

#30083 typo
  akka-docs/src/main/paradox/stream/stream-refs.md
Labels: tested

#30092 configuration for SBR lease release #30090
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/RandomizedBrainResolverIntegrationSpec.scala
  akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sbr/SplitBrainResolverIntegrationSpec.scala
  akka-cluster/src/main/mima-filters/2.6.13.backwards.excludes/issue-30090-sbr-release-lease.excludes
  akka-cluster/src/main/resources/reference.conf
  akka-cluster/src/main/scala/akka/cluster/sbr/DowningStrategy.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolverProvider.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolverSettings.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/sbr/LeaseMajority5NodeSpec.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/LeaseMajoritySpec.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/SplitBrainResolverSpec.scala
Labels: tested

#30081 Refactor exception handling in StatusReplyTest
  akka-actor-tests/src/test/java/akka/pattern/StatusReplyTest.java
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerPreparingForShutdownSpec.scala
Labels: tested

#30042 Extend GroupedWeightedWithin to accept maxWeight and maxNumber simultaneously
  CONTRIBUTING.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/groupedWeightedWithin.md
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupedWithinSpec.scala
  akka-stream/src/main/mima-filters/2.6.13.backwards.excludes/pr-30042-extended-group-weighted-within.excludes
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  plugins/serialversion-remover-plugin/src/main/scala/akka/Plugin.scala
Labels: t:stream, tested

#30112 Link to Akka Cloud Platform
  akka-docs/src/main/paradox/additional/deploying.md
Labels: tested

#29973 Inherit attributes from Restart{Source,Flow,Sink}
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/RestartSpec.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartSink.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RestartSource.scala
Labels: t:stream, tested

#30075 Update ActorHierarchyExperiments.java
  akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java
Labels: tested

#30025 Clarify desugaring of IncomingConnection.handleWith
  akka-stream/src/main/scala/akka/stream/javadsl/Tcp.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala
Labels: t:stream, tested

#30117 Bump Scala 3 to RC1
  project/Dependencies.scala
Labels: dependency-change, tested

#30116 Allow custom mailbox for user guardian
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
  akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala
Labels: tested

#30121 genjavadoc: update 0.16 -> 0.17
  project/Doc.scala
Labels: tested

#30128 Commit api/japi docs when releasing
  project/scripts/release
Labels: tested

#30113 Replace Charset.forName("UTF-8") on StandartCharsets.UTF_8
  akka-docs/src/test/java/jdocs/persistence/PersistenceSchemaEvolutionDocTest.java
  akka-protobuf/src/main/java/akka/protobuf/ByteString.java
  akka-protobuf/src/main/java/akka/protobuf/CodedOutputStream.java
Labels: tested

#30107 minor corrections of remoting docs
  akka-docs/src/main/paradox/remoting-artery.md
Labels: tested

#30125 Added size() to BoundedSourceQueue #30124
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/BoundedSourceQueueSpec.scala
  akka-stream/src/main/mima-filters/2.6.13.backwards.excludes/pr-30125-added-size-to-bounded-source-queue.excludes
  akka-stream/src/main/scala/akka/stream/BoundedSourceQueue.scala
  akka-stream/src/main/scala/akka/stream/impl/BoundedSourceQueue.scala
Labels: t:stream, tested

#30095 Update sbt-dotty to 0.5.3
  project/plugins.sbt
Labels: tested

#30130 Upgrade jackson to 2.11.4
  .scala-steward.conf
  project/Dependencies.scala
Labels: dependency-change, tested

#30109 remove default-dispatcher from heartbeat delay message
  akka-cluster/src/main/scala/akka/cluster/ClusterHeartbeat.scala
Labels: tested

#30118 Drop the java supervision sample link
  akka-docs/src/main/paradox/general/supervision.md
Labels: tested

#30136 Unwrap tagged replicated events before publishing to other replicas
  akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingDirectReplication.scala
  akka-persistence-typed/src/main/mima-filters/2.6.13.backwards.excludes/pr-30080-replicated-publishing-tagged-events.excludes
  akka-persistence-typed/src/main/scala/akka/persistence/typed/PublishedEvent.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
Labels: tested

#30148 Add link to SBR lease documentation; fix minor syntax mistakes
  akka-docs/src/main/paradox/coordination.md
Labels: tested

#30137 Crosslink and extra sentence about top level spawn in from-classic
  akka-docs/src/main/paradox/typed/coexisting.md
  akka-docs/src/main/paradox/typed/from-classic.md
Labels: tested

#30078 Remove recursive call to Java withBroadcastPredicate
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/RoutersTest.java
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
Labels: 2 - pick next, tested

#30150 Renamed single letter parameter
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
Labels: t:stream, tested

#30110 Use type inference for collections in FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
Labels: t:stream, tested

#30144 Implement isTimerActive for BehaviorTestKit #30140
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/EffectfulActorContext.scala
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
Labels: tested

#30152 Refactor SourceTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
Labels: t:stream, tested

#30099 Update junit to 4.13.2
  project/Dependencies.scala
Labels: dependency-change, tested

#30127 ActorSinkWithAckExample Ack message
  akka-stream-typed/src/test/java/docs/akka/stream/typed/ActorSinkWithAckExample.java
Labels: t:stream, tested
