Repository akka/akka, pull requests merged in 2021-01, with the labels that each got.

#29914 Race condition in DeprecatedSupervisionSpec fixed
  akka-cluster-sharding/src/test/scala/akka/cluster/sharding/SupervisionSpec.scala
Labels: tested

#29896 Missing boundary for expectation to always hold
  akka-cluster-tools/src/multi-jvm/scala/akka/cluster/pubsub/DistributedPubSubMediatorSpec.scala
Labels: tested

#29886 Update jctools-core to 3.2.0
  project/Dependencies.scala
Labels: dependency-change, tested

#29905 No empty state serialization check when not enabled
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/EventSourcedBehaviorTestKitImpl.scala
Labels: 2 - pick next, tested

#29917 Default ScalaFutures timeout is too short for sharding req-res
  akka-cluster-sharding-typed/src/multi-jvm/scala/akka/cluster/sharding/typed/MultiDcClusterShardingSpec.scala
Labels: tested

#29894 Make sure static mdc from withMdc set during actor startup
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/WithMdcBehaviorInterceptor.scala
Labels: tested

#29931 tcp: clearer debug message when connection is closed successfully
  akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala
Labels: t:stream, tested

#29941 Typo in docs stateful for stateless
  akka-docs/src/main/paradox/typed/choosing-cluster.md
Labels: tested

#29928 Make typed TestProbe a RecipientRef
  akka-actor-testkit-typed/src/main/mima-filters/2.6.10.backwards.excludes/pr-29928-testprobe-is-recipientref.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestProbe.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/TestProbe.scala
  akka-docs/src/main/paradox/typed/testing-async.md
Labels: tested

#29934 Use java.util.function.Predicate for Stash Java API
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/StashBufferImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/StashBuffer.scala
Labels: tested

#29927 Akka29924 router pool bcast
  akka-actor-typed-tests/src/test/java/akka/actor/typed/javadsl/RoutersTest.java
  akka-actor-typed-tests/src/test/java/jdocs/akka/typed/RouterTest.java
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/RoutersSpec.scala
  akka-actor-typed-tests/src/test/scala/docs/akka/typed/RouterSpec.scala
  akka-actor-typed/src/main/mima-filters/2.6.10.backwards.excludes/routers-pool-bcast.backwards.excludes
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/routing/PoolRouterImpl.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/javadsl/Routers.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala
  akka-actor/src/main/scala/akka/util/ConstantFun.scala
  akka-docs/src/main/paradox/typed/routers.md
Labels: tested

#29935 Better operator string represenation (take 2)
  akka-stream-tests/src/test/scala/akka/stream/impl/GraphStageLogicSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FromMaterializationSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SetupSpec.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/impl/LazySource.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/SetupStage.scala
  akka-stream/src/main/scala/akka/stream/impl/Sinks.scala
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: t:stream, tested

#29738 Explain why Mailbox#cleanup uses recursion [ci skip]
  akka-actor/src/main/scala/akka/dispatch/Mailbox.scala
Labels: tested

#29833 Exhaustive comparison for cache policies
  akka-actor/src/main/scala/akka/io/dns/internal/package.scala
Labels: tested

#29727 Add askWithStatus
  akka-docs/src/main/paradox/stream/operators/ActorFlow/askWithStatus.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorFlow.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorFlow.scala
  akka-stream-typed/src/test/java/docs/javadsl/ActorFlowCompileTest.java
  akka-stream-typed/src/test/scala/docs/scaladsl/ActorFlowSpec.scala
Labels: 2 - pick next, tested

#29867 Longer DNS timeout to avoiding ci fail
  akka-docs/src/test/java/jdocs/discovery/DnsDiscoveryDocTest.java
  akka-docs/src/test/scala/docs/discovery/DnsDiscoveryDocSpec.scala
Labels: tested

#29912 Add example for foldAsync
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/foldAsync.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/FoldAsync.scala
Labels: tested

#29913 Add example for mapError
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/mapError.md
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/MapError.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/MapError.scala
Labels: tested

#29945 Update metrics-core, metrics-jvm to 4.1.16
  project/Dependencies.scala
Labels: dependency-change, tested

#29881 Update jackson-databind to 2.10.5.1
  .scala-steward.conf
  project/Dependencies.scala
Labels: 2 - pick next, dependency-change, help wanted, tested

#29899 Incorrect test expectations i FlowFutureFlowSpec fixed
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFutureFlowSpec.scala
Labels: t:stream, tested

#29926 EventSourcedBehaviorTestKit serialization improvements
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/internal/EventSourcedBehaviorTestKitImpl.scala
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/EventSourcedBehaviorTestKit.scala
Labels: 2 - pick next, tested

#29873 Fix duplicate RequestNext messages in durable WorkPullingProducerController, #29854
  akka-actor-typed/src/main/scala/akka/actor/typed/delivery/internal/WorkPullingProducerControllerImpl.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/delivery/WorkPullingWithEventSourcedProducerQueueSpec.scala
Labels: 2 - pick next, tested

#29847 Adapted message failure supervision bugfix
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorAdapter.scala
Labels: 2 - pick next, tested

#29953 more headers
  akka-docs/src/test/java/jdocs/stream/operators/sourceorflow/MapError.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/FoldAsync.scala
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/MapError.scala
Labels: tested

#29952 update latestPatchOf26 to 2.6.11
  project/MiMa.scala
Labels: tested

#29001 Add more comments about formatting.
  CONTRIBUTING.md
Labels: tested

#29954 Typo
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/LoggingTestKit.scala
Labels: tested

#29958 Race condition in WorkPullingWithEventSourcedProducerQueueSpec
  akka-persistence-typed/src/test/scala/akka/persistence/typed/delivery/WorkPullingWithEventSourcedProducerQueueSpec.scala
Labels: tested

#29944 Update sbt-pgp to 2.1.1
  project/plugins.sbt
Labels: tested

#29943 Update asn-one to 0.5.0
  project/Dependencies.scala
Labels: dependency-change, tested

#29974 broken link
  akka-actor/src/main/scala/akka/routing/ConsistentHash.scala
Labels: tested

#29968 Update replicated ES support for JDBC
  akka-docs/src/main/paradox/typed/replicated-eventsourcing.md
Labels: tested

#29967 SubSinkInlet/SubSourceOutlet memory leak fix
  akka-stream/src/main/mima-filters/2.6.11.backwards.excludes/29966-sub-inlet-outlet-memleak.backward.excludes
  akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala
Labels: t:stream, tested

#29086 Add GroupedWeighted FlowOp and Make Grouped use GroupedWeighted
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/grouped.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/groupedWeighted.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/groupedWeightedWithin.md
  akka-docs/src/main/paradox/stream/operators/Source-or-Flow/groupedWithin.md
  akka-docs/src/main/paradox/stream/operators/index.md
  akka-docs/src/test/java/jdocs/stream/operators/SourceOrFlow.java
  akka-docs/src/test/scala/docs/stream/operators/sourceorflow/GroupedWeighted.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterSupervisionSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowGroupedWeightedSpec.scala
  akka-stream/src/main/mima-filters/2.6.11.backwards.excludes/pr-29086-rename-grouped.excludes
  akka-stream/src/main/scala/akka/stream/impl/Stages.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: t:stream, tested

#29978 Update to paradox theme with new cookie banner
  project/plugins.sbt
Labels: 2 - pick next, tested

#29976 Race condition in prefixAndTailSpec
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowPrefixAndTailSpec.scala
Labels: t:stream, tested

#29970 Add a note about shard actor factory being local
  akka-docs/src/main/paradox/typed/cluster-sharding.md
Labels: tested

#29737 SBR downing when a node is quarantined from the other side
  akka-cluster/src/main/mima-filters/2.6.10.backwards.excludes/down-when-quarantined.excludes
  akka-cluster/src/main/scala/akka/cluster/sbr/DowningStrategy.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolverProvider.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/DowningWhenOtherHasQuarantinedThisActorSystemSpec.scala
  akka-cluster/src/multi-jvm/scala/akka/cluster/SplitBrainQuarantineSpec.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/SplitBrainResolverSpec.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/TestStage.scala
Labels: 2 - pick next, tested
