Repository akka/akka, pull requests merged in 2021-04, with the labels that each got.

#30119 Remove unnecessary modifiers from FI.java
  akka-actor/src/main/java/akka/japi/pf/FI.java
Labels: tested

#30157 Change Effects() to Effect()
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#30142 Preserve attributes of inner stages when using {Source,Flow,Sink}.fromMaterializer
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FromMaterializationSpec.scala
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SetupSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/SetupStage.scala
Labels: t:stream, tested

#30162 Remove async boundary note in `Source.actorRef` docs
  akka-stream-typed/src/main/scala/akka/stream/typed/javadsl/ActorSource.scala
  akka-stream-typed/src/main/scala/akka/stream/typed/scaladsl/ActorSource.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
Labels: t:stream

#30147 Avoid TaskQueue allocations in Scheduler #30093
  akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala
Labels: tested

#30063 Document persist failure supervision for ESBs
  akka-persistence-typed/src/main/scala/akka/persistence/typed/javadsl/EventSourcedBehavior.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala
Labels: 2 - pick next, tested

#30059 Add draining control support to MergeHub #30057
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/HubSpec.scala
  akka-stream/src/main/mima-filters/2.6.13.backwards.excludes/30059-mergehub-draining-support.excludes
  akka-stream/src/main/scala/akka/stream/javadsl/Hub.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Hub.scala
Labels: t:stream, tested

#30173 MiMa latest patch update to 2.6.14
  project/MiMa.scala
Labels: tested

#30139 Extra catch-ignore for source attributes in case not possible
  akka-stream-tests/src/test/scala/akka/stream/SourceLocationAttributeSpec.scala
  akka-stream/src/main/scala/akka/stream/Attributes.scala
Labels: t:stream, tested

#30155 Simplified reverse in lease majority
  akka-cluster/src/main/mima-filters/2.6.13.backwards.excludes/simplified-reverse-logic-in-lease-majority.excludes
  akka-cluster/src/main/scala/akka/cluster/sbr/DowningStrategy.scala
  akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala
  akka-cluster/src/test/scala/akka/cluster/sbr/SplitBrainResolverSpec.scala
Labels: tested

#30178 Merged a PR with mima excludes from before last release
  akka-cluster/src/main/mima-filters/2.6.14.backwards.excludes/simplified-reverse-logic-in-lease-majority.excludes
Labels: tested

#30185 Pin jackson-databind to 2.11
  .scala-steward.conf
Labels: tested

#30172 Unwatch before watch in typed Supervision
  akka-actor-typed-tests/src/test/scala/akka/actor/typed/SupervisionSpec.scala
  akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala
Labels: tested

#30169 Clarify documentation for persisting multiple events in the context o…
  akka-docs/src/main/paradox/typed/persistence.md
Labels: tested

#30187 Removes unnecessary postStop #30071
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphStages.scala
Labels: t:stream, tested

#30196 Change jdk version for javadoc generation in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: tested

#30197 #30191 - Actualization of docs for "Resumable projections"
  akka-docs/src/main/paradox/persistence-query.md
  akka-docs/src/test/java/jdocs/persistence/ResumableProjectionExample.java
  akka-docs/src/test/scala/docs/persistence/query/PersistenceQueryDocSpec.scala
Labels: tested

#30202 Add settings to use context.log for internal ESB logging
  akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/EventSourcedBehaviorLoggingSpec.scala
  akka-persistence-typed/src/main/mima-filters/2.6.14.backwards.excludes/settings-to-fallback-to-context-log.excludes
  akka-persistence-typed/src/main/resources/reference.conf
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala
  akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedSettings.scala
  akka-persistence-typed/src/test/scala/akka/persistence/typed/internal/StashStateSpec.scala
Labels: tested

#30194 add example to the doc of combine operator
  akka-docs/src/main/paradox/stream/operators/Sink/combine.md
Labels: tested
