Repository akka/akka, pull requests merged in 2022-10, with the labels that each got.

#31633 Slight optimization of SupervisedGraphStage
  akka-stream/src/main/mima-filters/2.7.0.backwards.excludes/31589-supervised-grapshtagelogic.backwards.excludes
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: t:stream

#31651 Change doc wording of oss
  akka-docs/src/main/paradox/additional/operations.md
  akka-docs/src/main/paradox/project/links.md
  akka-docs/src/main/paradox/split-brain-resolver.md
  akka-docs/src/main/paradox/typed/cluster.md
  akka-docs/src/main/paradox/typed/guide/introduction.md
  akka-docs/src/main/paradox/typed/guide/modules.md
Labels: 2 - pick next

#31648 =sbt Bump Scala version to 2.12.17 & 2.13.10, sbt to 1.7.2
  akka-actor/src/main/scala/akka/actor/dungeon/Children.scala
  akka-actor/src/main/scala/akka/pattern/AskSupport.scala
  akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
  project/AkkaDisciplinePlugin.scala
  project/Dependencies.scala
  project/JdkOptions.scala
  project/build.properties
Labels: 2 - pick next, dependency-change

#31620 =str Make SingleConsumerMultiProducer the default mailbox for stream.
  akka-stream/src/main/resources/reference.conf
  akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala
  akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
Labels: 2 - pick next, t:stream

#31630 fix: Don't double close on cancel in statefulMap
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowStatefulMapSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: 2 - pick next, t:stream

#31640 =str Add dedicated stream timeout exceptions for timeout related oper…
  akka-stream-tests/src/test/java/akka/stream/javadsl/FlowTest.java
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream/src/main/scala/akka/stream/StreamTimeoutException.scala
  akka-stream/src/main/scala/akka/stream/impl/Timers.scala
  akka-stream/src/main/scala/akka/stream/javadsl/BidiFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/Source.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala
  akka-stream/src/main/scala/akka/stream/javadsl/SubSource.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/BidiFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/SubFlow.scala
Labels: 2 - pick next, t:stream

#31642 =str Make use of `applyOrElse` in MapError operator.
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: t:stream

#31667 Revert "!str filter out elements without demands for Flow#collect operator"
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowCollectSpec.scala
  akka-stream/src/main/mima-filters/2.6.20.backwards.excludes/pr-31617-collect-filter-without-demands.excludes
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: t:stream

#31668 Jackson 2.13.4.2
  project/Dependencies.scala
Labels: dependency-change

#30050 Implement effectful ask in typed BehaviorTestKit
  akka-actor-testkit-typed/src/main/mima-filters/2.6.20.backwards.excludes/effectful-ask.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/Effect.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/EffectfulActorContext.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/Effects.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/Effects.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/BehaviorTestKitTest.java
  akka-actor-testkit-typed/src/test/java/jdocs/akka/actor/testkit/typed/javadsl/SyncTestingExampleTest.java
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
  akka-actor-testkit-typed/src/test/scala/docs/akka/actor/testkit/typed/scaladsl/SyncTestingExampleSpec.scala
  akka-docs/src/main/paradox/typed/testing-sync.md
  akka-persistence/src/main/scala-3/akka/persistence/TraitOrder.scala
Labels: tested, 2 - pick next

#31678 fix: emitting DeletedDurableState for deleted objects
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStore.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStoreSpec.scala
Labels: 2 - pick next

#31683 fix: Record timestamp should not be reused
  akka-persistence-testkit/src/main/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStore.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/state/scaladsl/PersistenceTestKitDurableStateStoreSpec.scala
Labels: 2 - pick next

#31056 Remove dotty serial version uid plugin second try
  build.sbt
  plugins/serialversion-remover-plugin/src/main/resources/plugin.properties
  plugins/serialversion-remover-plugin/src/main/scala/akka/Plugin.scala
  project/AkkaDisciplinePlugin.scala
Labels: 2 - pick next

#31673 Add support for asking the BehaviorTestKit
  akka-actor-testkit-typed/src/main/mima-filters/2.6.20.backwards.excludes/31673.ask-behaviortestkit.excludes
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/BehaviorTestKitImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestInboxImpl.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/BehaviorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/TestInbox.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKit.scala
  akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/TestInbox.scala
  akka-actor-testkit-typed/src/test/java/akka/actor/testkit/typed/javadsl/BehaviorTestKitTest.java
  akka-actor-testkit-typed/src/test/scala/akka/actor/testkit/typed/scaladsl/BehaviorTestKitSpec.scala
  akka-actor/src/main/scala/akka/util/OptionVal.scala
  akka-cluster-sharding-typed/src/test/java/jdocs/akka/cluster/sharding/typed/AccountExampleUnpersistentDocTest.java
  akka-cluster-sharding-typed/src/test/scala/docs/akka/cluster/sharding/typed/AccountExampleUnpersistentDocSpec.scala
Labels: 2 - pick next

#31675 =str Optimize concat for `javadsl.Source.empty`.
  akka-stream-tests/src/test/java/akka/stream/javadsl/SourceTest.java
  akka-stream/src/main/scala/akka/stream/impl/TraversalBuilder.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: t:stream

#31691 Compile persistence-testkit with Scala 2.12
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/UnpersistentDurableStateSpec.scala
  akka-persistence-testkit/src/test/scala/akka/persistence/testkit/scaladsl/UnpersistentEventSourcedSpec.scala
Labels: 2 - pick next

#31690 Fix RecipeAdhocSource test, #31674
  akka-docs/src/test/java/jdocs/stream/javadsl/cookbook/RecipeAdhocSourceTest.java
  akka-docs/src/test/scala/docs/stream/cookbook/RecipeAdhocSource.scala
Labels: 2 - pick next

#31669 =str Avoid subMaterialization when the provided recover source is empty.
  akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowRecoverWithSpec.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: t:stream
