Repository akka/akka, pull requests merged in 2023-10, with the labels that each got.

#32149 bump: Shaded protobuf-java 3.21.12
  build.sbt
  project/Dependencies.scala
  project/Protobuf.scala
Labels: dependency-change

#32151 test: harden BasicClusterConfigSpec
  akka-cluster-typed/src/test/scala/docs/akka/cluster/typed/BasicClusterExampleSpec.scala
Labels: failed

#32152 bump: commons-io 2.14.0 (was 2.13.0)
  project/Dependencies.scala
Labels: dependency-change

#32150 bump: Regenerate with protoc 3.21.12
  akka-cluster-metrics/src/main/java/akka/cluster/metrics/protobuf/msg/ClusterMetricsMessages.java
  akka-cluster-sharding-typed/src/main/java/akka/cluster/sharding/typed/internal/protobuf/ShardingMessages.java
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-tools/src/main/java/akka/cluster/pubsub/protobuf/msg/DistributedPubSubMessages.java
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ClusterMessages.java
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ReliableDelivery.java
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatedDataMessages.java
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatorMessages.java
  akka-multi-node-testkit/src/main/java/akka/remote/testconductor/TestConductorProtocol.java
  akka-persistence-query/src/main/java/akka/persistence/query/internal/protobuf/QueryMessages.java
  akka-persistence-typed/src/main/java/akka/persistence/typed/serialization/ReplicatedEventSourcing.java
  akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java
  akka-remote-tests/src/test/java/akka/remote/artery/protobuf/TestMessages.java
  akka-remote/src/main/java/akka/remote/ArteryControlFormats.java
  akka-remote/src/main/java/akka/remote/ContainerFormats.java
  akka-remote/src/main/java/akka/remote/SystemMessageFormats.java
  akka-remote/src/main/java/akka/remote/WireFormats.java
  akka-remote/src/test/java/akka/remote/ProtobufProtocol.java
  akka-remote/src/test/java/akka/remote/protobuf/v3/ProtobufProtocolV3.java
  akka-stream/src/main/java/akka/stream/StreamRefMessages.java
Labels: t:stream

#32132 =str Make decider a lazy val.
  akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
Labels: t:stream

#32161 fix: Handle uid collision in a more graceful way
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala
  akka-remote/src/main/scala/akka/remote/artery/Association.scala
  akka-remote/src/main/scala/akka/remote/artery/Handshake.scala
  akka-remote/src/test/scala/akka/remote/artery/RemoteConnectionSpec.scala
Labels: bug

#32179 Remove unnecessary todo in Flow and Sink
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala
Labels: t:stream

#32180 bump: Shaded protobuf-java 3.24.0
  akka-cluster-metrics/src/main/java/akka/cluster/metrics/protobuf/msg/ClusterMetricsMessages.java
  akka-cluster-sharding-typed/src/main/java/akka/cluster/sharding/typed/internal/protobuf/ShardingMessages.java
  akka-cluster-sharding/src/main/java/akka/cluster/sharding/protobuf/msg/ClusterShardingMessages.java
  akka-cluster-tools/src/main/java/akka/cluster/pubsub/protobuf/msg/DistributedPubSubMessages.java
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ClusterMessages.java
  akka-cluster-typed/src/main/java/akka/cluster/typed/internal/protobuf/ReliableDelivery.java
  akka-cluster/src/main/java/akka/cluster/protobuf/msg/ClusterMessages.java
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatedDataMessages.java
  akka-distributed-data/src/main/java/akka/cluster/ddata/protobuf/msg/ReplicatorMessages.java
  akka-multi-node-testkit/src/main/java/akka/remote/testconductor/TestConductorProtocol.java
  akka-persistence-query/src/main/java/akka/persistence/query/internal/protobuf/QueryMessages.java
  akka-persistence-typed/src/main/java/akka/persistence/typed/serialization/ReplicatedEventSourcing.java
  akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java
  akka-remote-tests/src/test/java/akka/remote/artery/protobuf/TestMessages.java
  akka-remote/src/main/java/akka/remote/ArteryControlFormats.java
  akka-remote/src/main/java/akka/remote/ContainerFormats.java
  akka-remote/src/main/java/akka/remote/SystemMessageFormats.java
  akka-remote/src/main/java/akka/remote/WireFormats.java
  akka-remote/src/test/java/akka/remote/ProtobufProtocol.java
  akka-remote/src/test/java/akka/remote/protobuf/v3/ProtobufProtocolV3.java
  akka-stream/src/main/java/akka/stream/StreamRefMessages.java
  project/Dependencies.scala
  project/Protobuf.scala
Labels: t:stream, dependency-change

#32200 fix: Don't log environment variable values
  akka-actor/src/main/scala/akka/actor/ActorSystem.scala
  project/Dependencies.scala
Labels: dependency-change
