Repository akka/akka, pull requests merged in 2023-09, with the labels that each got.

#32071 chore: Migration for dropped AkkaSSLConfig,
  akka-docs/src/main/paradox/project/migration-guide-2.8.x-2.9.x.md
  akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala
  akka-stream/src/main/scala/akka/stream/impl/io/TlsModule.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala
Labels: t:stream

#32061 =str Make use of `statefulMap` to implement `zipWithIndex`.
  akka-bench-jmh/src/main/scala/akka/stream/ZipWithIndexBenchmark.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
Labels: t:stream

#32074 bump: netty-handler, netty-transport 4.1.97.Final (was 4.1.96.Final)
  project/Dependencies.scala
Labels: dependency-change

#32091 [feat] str: Support for setting defaultAttributes on materializers
  akka-docs/src/main/paradox/stream/stream-flows-and-basics.md
  akka-stream-tests/src/test/scala/akka/stream/MaterializerWithAttributesSpec.scala
  akka-stream/src/main/mima-filters/2.9.0-M1.backwards.excludes/impl-start-materializer.excludes
  akka-stream/src/main/scala/akka/stream/ActorMaterializer.scala
  akka-stream/src/main/scala/akka/stream/Materializer.scala
  akka-stream/src/main/scala/akka/stream/SystemMaterializer.scala
  akka-stream/src/main/scala/akka/stream/impl/MaterializerGuardian.scala
Labels: t:stream

#32099 chore: Follow up to #32091 putting mima excludes in the right place
  akka-stream/src/main/mima-filters/2.8.4.backwards.excludes/impl-start-materializer.excludes
Labels: t:stream

#32086 bump: Jackson 2.15.2
  .scala-steward.conf
  akka-serialization-jackson/src/test/java/jdoc/akka/serialization/jackson/v2a/CustomerMigration.java
  akka-serialization-jackson/src/test/scala/doc/akka/serialization/jackson/v2a/CustomerMigration.scala
  project/Dependencies.scala
Labels: dependency-change

#32054 =str Remove unneeded `hasNext` checking in IterableSource.
  akka-stream/src/main/scala/akka/stream/impl/fusing/GraphStages.scala
Labels: t:stream

#32102 chore: Mark stream APIs stable
  akka-stream/src/main/scala/akka/stream/Attributes.scala
  akka-stream/src/main/scala/akka/stream/javadsl/RetryFlow.scala
  akka-stream/src/main/scala/akka/stream/scaladsl/RetryFlow.scala
  akka-stream/src/main/scala/akka/stream/snapshot/MaterializerState.scala
Labels: t:stream

#32110 fix: clear inflight DNS requests on failure to allow retries
  akka-actor-tests/src/test/scala/akka/io/dns/internal/AsyncDnsResolverSpec.scala
  akka-actor/src/main/scala/akka/io/dns/internal/AsyncDnsResolver.scala
Labels: 2 - pick next

#32120 chore: MiMa 2.8.5 (main)
  akka-actor/src/main/mima-filters/2.8.5.backwards.excludes/31933.remove.Main
  akka-actor/src/main/mima-filters/2.8.5.backwards.excludes/drop-typedactor.excludes
  akka-cluster-tools/src/main/mima-filters/2.8.5.backwards.excludes/drop-cluster-client.excludes
  akka-persistence-query/src/main/mima-filters/2.8.5.backwards.excludes/stabilize-timestamp-offset.excludes
  akka-persistence-typed/src/main/mima-filters/2.8.5.backwards.excludes/EventWriter-gaps.excludes
  akka-persistence/src/main/mima-filters/2.8.5.backwards.excludes/32068-SerializedEvent.excludes
  akka-remote/src/main/mima-filters/2.8.5.backwards.excludes/issue-31095-quarantine-harmless.excludes
  akka-stream/src/main/mima-filters/2.8.5.backwards.excludes/drop-ssl-config.excludes
  akka-stream/src/main/mima-filters/2.8.5.backwards.excludes/impl-start-materializer.excludes
  project/MiMa.scala
Labels: t:stream

#32118 bump: Aeron 1.42.1
  project/Dependencies.scala
Labels: dependency-change

#32060 =str Resort the `OnNext` extractor order.
  akka-stream/src/main/scala/akka/stream/impl/FanIn.scala
  akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala
Labels: t:stream

#32125 chore: Drop Scala 2.12
  .github/workflows/binary-compatibility-checks.yml
  .github/workflows/nightly-builds.yml
  akka-actor-tests/src/test/scala-2.12/akka/util/LineNumberSpec.scala
  akka-actor-tests/src/test/scala-2.12/akka/util/TypedMultiMapSpec.scala
  akka-actor-typed/src/main/scala-2.12/akka/actor/typed/internal/receptionist/Platform.scala
  akka-actor/src/main/scala-2.12/akka/compat/Future.scala
  akka-actor/src/main/scala-2.12/akka/compat/PartialFunction.scala
  akka-actor/src/main/scala-2.12/akka/dispatch/internal/SameThreadExecutionContext.scala
  akka-actor/src/main/scala-2.12/akka/dispatch/internal/ScalaBatchable.scala
  akka-actor/src/main/scala-2.12/akka/util/ByteIterator.scala
  akka-actor/src/main/scala-2.12/akka/util/ByteString.scala
  akka-actor/src/main/scala-2.12/akka/util/ccompat/CompatImpl.scala
  akka-actor/src/main/scala-2.12/akka/util/ccompat/ccompatUsedUntil213.scala
  akka-actor/src/main/scala-2.12/akka/util/ccompat/package.scala
  akka-cluster-typed/src/main/scala-2.12/akka/cluster/typed/internal/receptionist/ClusterReceptionistProtocol.scala
  project/Dependencies.scala
Labels: dependency-change

#32140 bump: netty-handler, netty-transport 4.1.99.Final (was 4.1.98.Final)
  project/Dependencies.scala
Labels: dependency-change

#32141 bump: scala-library 2.13.12 (was 2.13.11)
  project/Dependencies.scala
Labels: dependency-change

#32139 bump: metrics-core, metrics-jvm 4.2.20 (was 4.2.19)
  project/Dependencies.scala
Labels: dependency-change

#32142 bump: scala-java8-compat 1.0.2 (was 1.0.0)
  project/Dependencies.scala
Labels: dependency-change

#32144 bump: scalatest 3.2.17 (was 3.2.16)
  project/Dependencies.scala
Labels: dependency-change
